// Package ssh implements the "net.ssh.ping" namespaced Collection
// method. Generated by pleiades forge new-collection
// (internal/forge/collectionscaffold), then hand-completed: this is a
// method with Status: StatusImplemented and a real Invoke.
//
// This package's init registers "net.ssh.ping" into the shared
// pkg/collection registry via collection.MustRegister. A runbook task
// naming this FQCN reaches engine.NewCollectionActionExecutor's real
// dispatch path, which calls Ping below directly, since this Manifest's
// Status is StatusImplemented and Invoke is set.
//
// This is Phase 16 (Native Go Execution Adapter)'s own Release Gate
// fixture ("The Runner executes a mock Ping collection, captures the
// output, and pushes a task.completed event back to NATS"), built as a
// real, permanently useful method rather than a disposable test-only
// stub: it is the one artifact reachable only through the full chain that
// phase built (dispatch with a real JIT-delivered secret, the Runner's
// real DAG executor, the Collection registry, the per-task subprocess
// boundary, a real SSH connection, a real device), so it proves every
// remaining checklist item at once.
//
// Because this package lives under internal/, it is reachable only from
// code inside this module or a fork of it: Go's internal/ visibility rule
// blocks any other module from importing it at all. This generator is
// repo-contributor tooling, not end-user extensibility; a third-party
// Collection arriving from outside this binary needs a separate,
// not-yet-built distribution mechanism (Part X's OCI distribution work),
// not this one.
//
// Like every Collection package it imports only pkg/. What that used to
// cost is worth recording, because it is the reason pkg/remoteexec
// exists. This method could not import internal/transport/ssh, so it
// hand-rolled its own dial, its own authentication and its own
// known_hosts check, and inherited none of that package's circuit
// breaker or retry-with-backoff. This file's own doc comment said that
// tradeoff was "acceptable for a lightweight, read-only diagnostic
// method, and would need revisiting if this package grew a second,
// write-capable method." Phase 38's first tier is roughly twenty
// write-capable methods, so it was revisited: the mechanism moved to
// pkg/remoteexec, which both a Collection and internal/transport/ssh can
// reach, and this method now gets the breaker and the retry it never had
// while carrying no copy of the security-critical parts.
package ssh

import (
	"context"
	"fmt"

	"github.com/Subject-Void-LLC/the-pleiades/pkg/capability"
	"github.com/Subject-Void-LLC/the-pleiades/pkg/collection"
	"github.com/Subject-Void-LLC/the-pleiades/pkg/inventory"
	"github.com/Subject-Void-LLC/the-pleiades/pkg/remoteexec"
	"github.com/Subject-Void-LLC/the-pleiades/pkg/sdk"
)

// paramData is the optional string a runbook task can set to change what
// this method echoes back, mirroring Ansible's own ping module ("data"
// defaults to "pong"). paramInsecureSkipHostKeyVerify is the escape
// hatch for a target with no known_hosts entry yet, off by default:
// skipping host key verification is a real MITM exposure, so it must be
// set explicitly and loudly by the runbook author, never assumed.
const (
	paramData                      = "data"
	paramInsecureSkipHostKeyVerify = "insecure_skip_host_key_verify"
	defaultPingData                = "pong"
)

func init() {
	collection.MustRegister(collection.Descriptor{
		Name: "net.ssh.ping",
		Manifest: collection.Manifest{
			SupportedTransports: []string{
				"ssh",
			},
			RequiredCapabilities: []capability.Name{
				capability.Name("SSHTransportCapable"),
			},
			ExecutionContext: collection.ExecutionContext{
				RequiresElevation: false,
				Site:              collection.SiteTarget,
				Device:            collection.DeviceRequired,
			},
			PlatformTargets: nil,
			EngineVersion:   ">=0.2.0",
			Status:          collection.StatusImplemented,
			// Nothing to undo, which is the same fact that makes this
			// method report changed: false.
			Reversibility: collection.Reversibility{
				Reversible: false,
				Notes:      "This method opens a connection and echoes a value back. It changes nothing on the device, so there is nothing to undo; that is the same fact that makes it report changed: false.",
				ReadOnly:   true,
			},
			// Read-only (Ping), so a check runs it for real.
			SupportsCheck: true,
			Doc: collection.Doc{
				Summary:     "Opens a real SSH connection to the target and echoes a value back, to prove reachability.",
				Description: "Dials the device's SSHTransportCapable host and port, authenticates with the credential the Controller attached to this dispatch, and runs a trivial, read-only remote command that echoes params.data (default \"pong\") back. Never reports changed: a connectivity check does not alter device state.",
				Returns: []collection.ReturnField{
					{Name: "reply", Type: "string", Returned: "always", Description: "The trimmed value the remote command echoed back."},
				},
				Examples: []collection.Example{
					{Name: "Check a device is reachable over SSH", RunbookYAML: "- name: Ping the device\n  net.ssh.ping:\n  register: reachability\n"},
				},
			},
		},
		Invoke: Ping,
		// Ping itself, since it only reads: the one command it sends is
		// echo with a quoted argument, which cannot redirect, so a check
		// proves reachability exactly as a real run does.
		Check: Ping,
	})
}

// Ping implements the "net.ssh.ping" collection method: see this
// package's own doc comment for why it exists and what it proves.
func Ping(ctx context.Context, rc sdk.RunbookContext, device inventory.InventoryItem, params map[string]any) (collection.Result, error) {
	sshDev, ok := device.(capability.SSHTransportCapable)
	if !ok {
		return collection.Result{}, fmt.Errorf("net.ssh.ping requires a target device implementing SSHTransportCapable")
	}

	data := defaultPingData
	if v, ok := params[paramData].(string); ok && v != "" {
		data = v
	}

	// Credentials arrive through InjectSecrets rather than through
	// params, because params come from the runbook file and a runbook
	// file is committed to version control. AuthFromSecrets reads the
	// same wire.Secret* keys the Controller flattened the credential into,
	// so neither end of that map carries its own spelling of them.
	auth, err := remoteexec.AuthFromSecrets(rc.InjectSecrets())
	if err != nil {
		return collection.Result{}, fmt.Errorf("net.ssh.ping: %w", err)
	}

	// Shared rather than New: a Collection method is invoked once per task
	// with nowhere to keep a Runner in between, so a fresh one every time
	// would carry a circuit breaker that has never seen a failure and can
	// therefore never open. See remoteexec.Shared for the honest limit on
	// what that buys under the per-task subprocess boundary.
	runner := remoteexec.Shared(remoteexec.Options{
		InsecureSkipHostKeyVerify: boolParam(params, paramInsecureSkipHostKeyVerify),
	})
	target := remoteexec.Target{Host: sshDev.SSHHost(), Port: sshDev.SSHPort()}

	// QuoteArg is what makes params.data safe to interpolate: an
	// author-supplied value can contain any byte sequence, including shell
	// metacharacters, and must come back as one argument rather than as a
	// second command.
	result, err := runner.Run(ctx, nil, target, auth, "echo "+remoteexec.QuoteArg(data))
	if err != nil {
		return collection.Result{}, fmt.Errorf("net.ssh.ping: %w", err)
	}
	if result.ExitCode != 0 {
		return collection.Result{}, fmt.Errorf("net.ssh.ping: run command on %s exited %d: %s",
			target.Addr(), result.ExitCode, result.Stderr)
	}

	reply := trimTrailingNewline(result.Stdout)
	if err := rc.SetStat("reply", reply); err != nil {
		return collection.Result{}, fmt.Errorf("net.ssh.ping: %w", err)
	}

	return collection.Result{Changed: false}, nil
}

// boolParam reads a boolean task parameter, treating a missing or
// non-boolean value as false.
//
// It accepts a real bool only, not the string "true". YAML already
// decodes an unquoted true into a bool, and accepting the string form
// would mean silently honoring a quoted "false" as true-ish somewhere
// down the line. That matters more than usual here: the one parameter
// this reads turns off host key verification.
func boolParam(params map[string]any, key string) bool {
	v, ok := params[key].(bool)
	return ok && v
}

// trimTrailingNewline removes the single line terminator a remote echo
// appends, and nothing else.
//
// It is deliberately not strings.TrimSpace. The value being echoed is
// whatever the runbook author put in params.data, and trimming every
// leading and trailing space would quietly return something other than
// what they asked to be echoed back, which for a method whose entire
// output is "did this value survive the round trip" is the wrong answer.
func trimTrailingNewline(s string) string {
	if len(s) > 0 && s[len(s)-1] == '\n' {
		s = s[:len(s)-1]
	}
	if len(s) > 0 && s[len(s)-1] == '\r' {
		s = s[:len(s)-1]
	}
	return s
}
