package parity

import (
	"fmt"
	"sort"
	"strings"
)

// RenderReport produces the committed backlog: every field of every AWX
// object in the corpus, what we can do with it, and which phase owns what
// we cannot.
//
// Generated rather than hand-written, for the reason AWX_PARITY.md's own
// tables were wrong twice: a table maintained by hand is a claim, and a
// claim about compatibility is exactly the thing this package exists to
// replace with a measurement. It is committed and diffed so a change that
// silently drops a represented field fails a test rather than quietly
// regenerating.
func RenderReport(tables map[ObjectType]Classification, exports map[ObjectType]map[string]Export) string {
	var b strings.Builder

	b.WriteString("# AWX parity: what we can hold\n\n")
	b.WriteString("Generated by `go test ./tests/parity/ -update-gaps` from the real AWX exports\n")
	b.WriteString("committed under `testdata/`. Do not edit by hand.\n\n")
	b.WriteString("This is the backlog for `.SPECIFICATION/AWX_PARITY_ROADMAP.md`. Every phase there\n")
	b.WriteString("closes a named subset of the gaps below, and its release gate cites the rows it\n")
	b.WriteString("removes.\n\n")

	renderSummary(&b, tables, exports)
	renderPhaseBacklog(&b, tables)

	for _, object := range ObjectTypes() {
		table, ok := tables[object]
		if !ok {
			continue
		}
		renderObject(&b, object, table, exports[object])
	}

	return b.String()
}

// renderSummary is the whole report in one table, because the first
// question anybody asks is how much of AWX we can hold and it should not
// require scrolling.
func renderSummary(b *strings.Builder, tables map[ObjectType]Classification, exports map[ObjectType]map[string]Export) {
	b.WriteString("## Summary\n\n")
	b.WriteString("Metadata is excluded from these counts: it is AWX's REST envelope, and counting\n")
	b.WriteString("it either way would flatter or punish the number for something no import would\n")
	b.WriteString("ever carry.\n\n")
	b.WriteString("| Object | Carried | Direct | Converted | Gaps | Unsupported |\n")
	b.WriteString("|---|---|---|---|---|---|\n")

	var carriedAll, totalAll, directAll, convertedAll, gapsAll, unsupportedAll int
	for _, object := range ObjectTypes() {
		table, ok := tables[object]
		if !ok {
			continue
		}
		counts := table.Counts()
		carried := counts[Represented] + counts[Convertible]
		total := carried + counts[Gap] + counts[Unsupported]

		fmt.Fprintf(b, "| `%s` | %d/%d | %d | %d | %d | %d |\n",
			object, carried, total, counts[Represented], counts[Convertible],
			counts[Gap], counts[Unsupported])

		carriedAll += carried
		totalAll += total
		directAll += counts[Represented]
		convertedAll += counts[Convertible]
		gapsAll += counts[Gap]
		unsupportedAll += counts[Unsupported]
	}
	fmt.Fprintf(b, "| **total** | **%d/%d** | %d | %d | %d | %d |\n\n",
		carriedAll, totalAll, directAll, convertedAll, gapsAll, unsupportedAll)

	objects := 0
	for _, set := range exports {
		for _, export := range set {
			objects += len(export.Results)
		}
	}
	fmt.Fprintf(b, "Corpus: %d object(s) across %d resource types.\n\n---\n\n", objects, len(exports))
}

// renderPhaseBacklog inverts the tables: what does each roadmap phase
// actually have to deliver? This is the view somebody planning work reads,
// and it is generated from the same rows as everything else so it cannot
// disagree with them.
func renderPhaseBacklog(b *strings.Builder, tables map[ObjectType]Classification) {
	type owed struct{ object, field string }
	byPhase := map[string][]owed{}

	for _, object := range ObjectTypes() {
		table, ok := tables[object]
		if !ok {
			continue
		}
		for _, name := range table.Names() {
			f := table[name]
			if f.Status != Gap {
				continue
			}
			byPhase[f.Phase] = append(byPhase[f.Phase], owed{string(object), name})
		}
	}

	phases := make([]string, 0, len(byPhase))
	for phase := range byPhase {
		phases = append(phases, phase)
	}
	sort.Strings(phases)

	b.WriteString("## What each phase owes\n\n")
	b.WriteString("Every gap, grouped by the phase that closes it. A phase is done when its rows\n")
	b.WriteString("are gone from this list.\n\n")
	b.WriteString("| Phase | Fields | Owed |\n|---|---|---|\n")
	for _, phase := range phases {
		fields := byPhase[phase]
		sort.Slice(fields, func(i, j int) bool {
			if fields[i].object != fields[j].object {
				return fields[i].object < fields[j].object
			}
			return fields[i].field < fields[j].field
		})
		var rendered []string
		for _, f := range fields {
			rendered = append(rendered, fmt.Sprintf("`%s.%s`", f.object, f.field))
		}
		fmt.Fprintf(b, "| %s | %d | %s |\n", phase, len(fields), strings.Join(rendered, ", "))
	}
	b.WriteString("\n---\n\n")
}

// renderObject renders one resource's own table, grouped by status.
func renderObject(b *strings.Builder, object ObjectType, table Classification, exports map[string]Export) {
	counts := table.Counts()
	carried := counts[Represented] + counts[Convertible]
	total := carried + counts[Gap] + counts[Unsupported]

	fmt.Fprintf(b, "## `%s`\n\n", object)
	fmt.Fprintf(b, "%d of %d meaningful fields carried. ", carried, total)

	var files []string
	for name := range exports {
		files = append(files, name)
	}
	sort.Strings(files)
	if len(files) > 0 {
		fmt.Fprintf(b, "Corpus: %s.\n\n", strings.Join(files, ", "))
	} else {
		b.WriteString("Derived from another resource's corpus.\n\n")
	}

	section(b, table, Gap, "Gaps")
	section(b, table, Convertible, "Convertible")
	section(b, table, Represented, "Represented")
	section(b, table, Unsupported, "Deliberately unsupported")
	section(b, table, Metadata, "AWX REST envelope")
}

// section renders one status group, skipping it entirely when empty so a
// resource's table stays readable.
func section(b *strings.Builder, c Classification, status Status, heading string) {
	var fields []Field
	for _, name := range c.Names() {
		if c[name].Status == status {
			fields = append(fields, c[name])
		}
	}
	if len(fields) == 0 {
		return
	}

	fmt.Fprintf(b, "### %s (%d)\n\n", heading, len(fields))

	switch status {
	case Gap:
		b.WriteString("| Field | Owning phase | Notes |\n|---|---|---|\n")
		sort.Slice(fields, func(i, j int) bool {
			if fields[i].Phase != fields[j].Phase {
				return fields[i].Phase < fields[j].Phase
			}
			return fields[i].Name < fields[j].Name
		})
		for _, f := range fields {
			fmt.Fprintf(b, "| `%s` | %s | %s |\n", f.Name, f.Phase, cell(f.Note))
		}
	case Convertible:
		b.WriteString("| Field | Lands in | Conversion required |\n|---|---|---|\n")
		for _, f := range fields {
			fmt.Fprintf(b, "| `%s` | `%s` | %s |\n", f.Name, f.Ours, cell(f.Conversion))
		}
	case Represented:
		b.WriteString("| Field | Lands in | Notes |\n|---|---|---|\n")
		for _, f := range fields {
			fmt.Fprintf(b, "| `%s` | `%s` | %s |\n", f.Name, f.Ours, cell(f.Note))
		}
	default:
		b.WriteString("| Field | Reason |\n|---|---|\n")
		for _, f := range fields {
			fmt.Fprintf(b, "| `%s` | %s |\n", f.Name, cell(f.Note))
		}
	}
	b.WriteString("\n")
}

// cell makes a value safe for a Markdown table cell.
func cell(s string) string {
	if strings.TrimSpace(s) == "" {
		return "none"
	}
	s = strings.ReplaceAll(s, "|", "\\|")
	s = strings.ReplaceAll(s, "\n", " ")
	return strings.Join(strings.Fields(s), " ")
}
