package devicescaffold

// deviceTemplateSource is the vendor device-type source file template. It
// mirrors internal/inventory/devices/cisco/router.go's structure exactly
// (package doc, init self-registration, struct, constructor, HasCapability)
// with two additions the hand-written packages lack: the compile-time
// var _ inventory.InventoryItem assertion Phase 33's checklist calls for,
// and a generated-header honesty block covering the composition-root
// reachability gap, the internal/ visibility constraint, and the
// skeleton-only accessor scope.
const deviceTemplateSource = `// Package {{.Vendor}} holds the concrete device type implementation for
// {{.Vendor}} gear ("{{.TypeKey}}"). Generated by pleiades forge new-device
// (internal/inventory/devicescaffold); mirrors the hand-written
// internal/inventory/devices/cisco and devices/linux packages.
//
// This package's init registers {{.ConstructorName}} into the shared
// record.Types registry under "{{.TypeKey}}". internal/inventory/factory.go's
// NewItemFactory draws its batteries-included set from that registry
// rather than importing this package by name, so this package is NOT YET
// REACHABLE from the stock binary: internal/inventory/builtins.go's
// blank-import list is what actually triggers a device package's init(),
// and it still only names cisco and linux. Add a blank import of this
// package there (or to your own composition root) before this type is
// reachable through NewItemFactory(). This package itself never imports
// internal/inventory, only the leaf internal/inventory/record package plus
// pkg/inventory, pkg/capability, and pkg/policy, so internal/inventory can
// depend on it (via a future blank import) without a cycle back.
//
// Because this package lives under internal/, it is reachable only from
// code inside this module or a fork of it: Go's internal/ visibility rule
// blocks any other module from importing it at all. This generator is
// repo-contributor tooling, not end-user extensibility; a third-party
// device type arriving from outside this binary needs a separate,
// not-yet-built distribution mechanism, not this one.
//
// Scope: this file gives {{.StructName}} the structural skeleton every
// device type needs (a record.Base embed, a capability-baseline
// constructor, HasCapability, and the compile-time InventoryItem
// assertion below) but adds no capability-specific accessor methods,
// since pkg/capability.Descriptor's Assert is an opaque function with no
// reflectable method-set metadata this generator could read. Until a
// human adds real accessor methods matching each declared capability's
// interface, HasCapability correctly returns false for all of them: see
// the TODO on {{.StructName}} below.
package {{.Vendor}}

import (
	"github.com/SubjectVoidLLC/the-pleiades/internal/inventory/record"
	"github.com/SubjectVoidLLC/the-pleiades/pkg/capability"
	"github.com/SubjectVoidLLC/the-pleiades/pkg/inventory"
	"github.com/SubjectVoidLLC/the-pleiades/pkg/policy"
)

func init() {
	record.RegisterType({{quote .TypeKey}}, {{.ConstructorName}})
}

// {{.StructName}} implements inventory.InventoryItem.
//
// TODO(forge): {{.StructName}} does not yet structurally implement any of
// its declared capabilities. Add accessor methods matching each
// capability interface in pkg/capability (for example, a network device
// type typically needs a CLIPrompt() string method to satisfy
// NetworkCLICapable) so HasCapability returns true for a capability this
// type declares.
type {{.StructName}} struct {
	*record.Base
}

var _ inventory.InventoryItem = (*{{.StructName}})(nil)

// {{.ConstructorName}} builds a {{.StructName}} from rec. It matches the
// record.Constructor shape (func(record.Record) (inventory.InventoryItem,
// error)) record.RegisterType expects.
//
// The capability set is the vendor baseline given to
// "pleiades forge new-device" unioned with rec.Capabilities, per Phase
// 32's capability granularity decision: classification-derived data can
// only add to what this type already asserts about itself, never replace
// it.
func {{.ConstructorName}}(rec record.Record) (inventory.InventoryItem, error) {
	caps := policy.UnionSlices(
		[]capability.Name{
{{range .Capabilities}}			capability.Name({{quote .}}),
{{end}}		},
		rec.Capabilities,
	)
	base := record.NewBase(rec, caps)
	return &{{.StructName}}{Base: base}, nil
}

// HasCapability checks the declared classification AND the structural
// registry assertion, so a true result is a guarantee, not a hope.
func ({{.ReceiverName}} *{{.StructName}}) HasCapability(name capability.Name) bool {
	return {{.ReceiverName}}.Declares(name) && capability.Implements({{.ReceiverName}}, name)
}
`

// deviceTestTemplateSource is the starter test template. It deliberately
// asserts on Capabilities() (the data layer), not HasCapability() (which
// also requires structural satisfaction): a freshly generated type has no
// capability-specific accessor methods yet, so HasCapability correctly
// stays false for every declared capability until a human adds them, and
// a starter test asserting the opposite would fail out of the box,
// violating the checklist's own Release Gate.
const deviceTestTemplateSource = `package {{.Vendor}}_test

import (
	"testing"

	"github.com/SubjectVoidLLC/the-pleiades/internal/inventory/devices/{{.Vendor}}"
	"github.com/SubjectVoidLLC/the-pleiades/internal/inventory/record"
	"github.com/SubjectVoidLLC/the-pleiades/pkg/capability"
)

// Test{{.ConstructorName}}_ConstructsFromRecord is a starter test,
// generated by "pleiades forge new-device": it proves the constructor
// hydrates a real Record without error and that basic identity fields
// round-trip.
func Test{{.ConstructorName}}_ConstructsFromRecord(t *testing.T) {
	item, err := {{.Vendor}}.{{.ConstructorName}}(record.Record{ID: "t1", Name: "t1", Type: {{quote .TypeKey}}})
	if err != nil {
		t.Fatalf("{{.ConstructorName}}: %v", err)
	}
	if got := string(item.ID()); got != "t1" {
		t.Errorf("ID() = %q, want %q", got, "t1")
	}
	if got := item.Name(); got != "t1" {
		t.Errorf("Name() = %q, want %q", got, "t1")
	}
}

// Test{{.ConstructorName}}_BaselineCapabilities is a starter, table-driven
// regression proof: the vendor baseline given at generation time is
// unioned into the declared capability set. It deliberately checks
// Capabilities(), not HasCapability(): this generated type has no
// capability-specific accessor methods yet (see the TODO in
// {{.Vendor}}.go), so HasCapability correctly stays false until a human
// adds them.
func Test{{.ConstructorName}}_BaselineCapabilities(t *testing.T) {
	item, err := {{.Vendor}}.{{.ConstructorName}}(record.Record{ID: "t1", Name: "t1", Type: {{quote .TypeKey}}})
	if err != nil {
		t.Fatalf("{{.ConstructorName}}: %v", err)
	}
	declared := item.Capabilities()

	tests := []struct {
		name       string
		capability capability.Name
	}{
{{range .Capabilities}}		{name: {{quote .}}, capability: capability.Name({{quote .}})},
{{end}}	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			found := false
			for _, c := range declared {
				if c == tt.capability {
					found = true
					break
				}
			}
			if !found {
				t.Errorf("expected the vendor baseline to include declared capability %s", tt.name)
			}
		})
	}
}
`
