PRAGMA foreign_keys = off;
CREATE TABLE `credentials` (`id` integer NOT NULL PRIMARY KEY AUTOINCREMENT, `created_at` datetime NOT NULL, `updated_at` datetime NOT NULL, `name` text NOT NULL, `description` text NULL, `inputs` json NULL, `external` json NULL, `secret_binding` text NOT NULL, `credential_type_credentials` integer NOT NULL, `organization_credentials` integer NOT NULL, CONSTRAINT `credentials_credential_types_credentials` FOREIGN KEY (`credential_type_credentials`) REFERENCES `credential_types` (`id`) ON DELETE NO ACTION, CONSTRAINT `credentials_organizations_credentials` FOREIGN KEY (`organization_credentials`) REFERENCES `organizations` (`id`) ON DELETE NO ACTION);
CREATE UNIQUE INDEX `credential_name_organization_credentials` ON `credentials` (`name`, `organization_credentials`);
CREATE TABLE `credential_types` (`id` integer NOT NULL PRIMARY KEY AUTOINCREMENT, `created_at` datetime NOT NULL, `updated_at` datetime NOT NULL, `name` text NOT NULL, `description` text NULL, `kind` text NOT NULL, `namespace` text NOT NULL, `managed` bool NOT NULL DEFAULT (false), `inputs` json NULL, `injectors` json NULL, `organization_credential_types` integer NULL, CONSTRAINT `credential_types_organizations_credential_types` FOREIGN KEY (`organization_credential_types`) REFERENCES `organizations` (`id`) ON DELETE SET NULL);
CREATE UNIQUE INDEX `credentialtype_namespace` ON `credential_types` (`namespace`);
CREATE UNIQUE INDEX `credentialtype_name_organization_credential_types` ON `credential_types` (`name`, `organization_credential_types`);
CREATE INDEX `credentialtype_kind` ON `credential_types` (`kind`);
CREATE TABLE `template_credentials` (`template_id` integer NOT NULL, `credential_id` integer NOT NULL, PRIMARY KEY (`template_id`, `credential_id`), CONSTRAINT `template_credentials_template_id` FOREIGN KEY (`template_id`) REFERENCES `templates` (`id`) ON DELETE CASCADE, CONSTRAINT `template_credentials_credential_id` FOREIGN KEY (`credential_id`) REFERENCES `credentials` (`id`) ON DELETE CASCADE);
PRAGMA foreign_keys = on;
