PRAGMA foreign_keys = off;
CREATE TABLE `schedules` (`id` integer NOT NULL PRIMARY KEY AUTOINCREMENT, `created_at` datetime NOT NULL, `updated_at` datetime NOT NULL, `schedule_id` text NOT NULL, `name` text NOT NULL, `description` text NULL, `enabled` bool NOT NULL DEFAULT (true), `rrule` text NOT NULL, `exclusions` json NULL, `timezone` text NOT NULL DEFAULT ('UTC'), `dtstart` datetime NOT NULL, `dtend` datetime NULL, `next_run` datetime NULL, `last_fired` datetime NULL, `organization_schedules` integer NOT NULL, `schedule_saved_config` integer NULL, `template_schedules` integer NOT NULL, CONSTRAINT `schedules_organizations_schedules` FOREIGN KEY (`organization_schedules`) REFERENCES `organizations` (`id`) ON DELETE NO ACTION, CONSTRAINT `schedules_saved_launch_configs_saved_config` FOREIGN KEY (`schedule_saved_config`) REFERENCES `saved_launch_configs` (`id`) ON DELETE SET NULL, CONSTRAINT `schedules_templates_schedules` FOREIGN KEY (`template_schedules`) REFERENCES `templates` (`id`) ON DELETE NO ACTION);
CREATE UNIQUE INDEX `schedules_schedule_id_key` ON `schedules` (`schedule_id`);
CREATE UNIQUE INDEX `schedule_name_organization_schedules` ON `schedules` (`name`, `organization_schedules`);
CREATE INDEX `schedule_enabled_next_run_schedule_id` ON `schedules` (`enabled`, `next_run`, `schedule_id`);
CREATE TABLE `schedule_occurrences` (`id` integer NOT NULL PRIMARY KEY AUTOINCREMENT, `created_at` datetime NOT NULL, `updated_at` datetime NOT NULL, `occurrence_at` datetime NOT NULL, `outcome` text NOT NULL DEFAULT ('claimed'), `reason` text NULL, `suppressed_count` integer NOT NULL DEFAULT (0), `job_id` text NULL, `schedule_occurrences` integer NOT NULL, CONSTRAINT `schedule_occurrences_schedules_occurrences` FOREIGN KEY (`schedule_occurrences`) REFERENCES `schedules` (`id`) ON DELETE NO ACTION);
CREATE UNIQUE INDEX `scheduleoccurrence_occurrence_at_schedule_occurrences` ON `schedule_occurrences` (`occurrence_at`, `schedule_occurrences`);
CREATE INDEX `scheduleoccurrence_schedule_occurrences` ON `schedule_occurrences` (`schedule_occurrences`);
PRAGMA foreign_keys = on;
