// Code generated by ent, DO NOT EDIT.

package localcredential

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the localcredential type in the database.
	Label = "local_credential"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldPasswordHash holds the string denoting the password_hash field in the database.
	FieldPasswordHash = "password_hash"
	// FieldFailedAttempts holds the string denoting the failed_attempts field in the database.
	FieldFailedAttempts = "failed_attempts"
	// FieldLockedUntil holds the string denoting the locked_until field in the database.
	FieldLockedUntil = "locked_until"
	// FieldPasswordChangedAt holds the string denoting the password_changed_at field in the database.
	FieldPasswordChangedAt = "password_changed_at"
	// FieldMustChange holds the string denoting the must_change field in the database.
	FieldMustChange = "must_change"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the localcredential in the database.
	Table = "local_credentials"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "local_credentials"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_local_credential"
)

// Columns holds all SQL columns for localcredential fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldPasswordHash,
	FieldFailedAttempts,
	FieldLockedUntil,
	FieldPasswordChangedAt,
	FieldMustChange,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "local_credentials"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"user_local_credential",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	PasswordHashValidator func(string) error
	// DefaultFailedAttempts holds the default value on creation for the "failed_attempts" field.
	DefaultFailedAttempts int
	// FailedAttemptsValidator is a validator for the "failed_attempts" field. It is called by the builders before save.
	FailedAttemptsValidator func(int) error
	// DefaultPasswordChangedAt holds the default value on creation for the "password_changed_at" field.
	DefaultPasswordChangedAt func() time.Time
	// DefaultMustChange holds the default value on creation for the "must_change" field.
	DefaultMustChange bool
)

// OrderOption defines the ordering options for the LocalCredential queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByPasswordHash orders the results by the password_hash field.
func ByPasswordHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPasswordHash, opts...).ToFunc()
}

// ByFailedAttempts orders the results by the failed_attempts field.
func ByFailedAttempts(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFailedAttempts, opts...).ToFunc()
}

// ByLockedUntil orders the results by the locked_until field.
func ByLockedUntil(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLockedUntil, opts...).ToFunc()
}

// ByPasswordChangedAt orders the results by the password_changed_at field.
func ByPasswordChangedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPasswordChangedAt, opts...).ToFunc()
}

// ByMustChange orders the results by the must_change field.
func ByMustChange(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMustChange, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, UserTable, UserColumn),
	)
}
