FROM golang:1.26-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o runner cmd/runner/main.go

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/runner .
CMD ["./runner"]
