// Package aws implements the "aws" inventory sync plugin: PLAN.md Section
// 6a's connector for a real AWS account/region, the AWS-side answer to
// AWX_PARITY.md's own inventory-sources row (which names AWS explicitly
// alongside NetBox, Nautobot and VMware) and this codebase's analogue of
// Ansible's amazon.aws.aws_ec2 dynamic inventory plugin.
//
// Originally generated by pleiades forge new-plugin
// (internal/forge/pluginscaffold), then implemented against a real
// LocalStack container (see aws_test.go and
// internal/inventory/plugins/conformance_test.go's own "aws" backend
// entry): AWS itself has no public read-only sandbox the way Cisco's
// DevNet gives catalystcenter one, so a real (if emulated) AWS API server
// is what "representative" means for this plugin, the same reasoning
// pkg/awscloud's own tests already established this session.
//
// This plugin discovers EC2 instances and hydrates them as ordinary
// linux_server devices, not a new AWS-specific device type: once synced,
// every existing SSH-based method (net.ssh.ping, exec.command, ...)
// already works against a discovered instance with no new transport or
// method needed. It also emits a synthetic record for the account/region
// itself, classified as aws_account, mirroring
// catalystcenter/records.go's controllerRecord: a sync leaves inventory in
// a state where cloud.aws.* tasks can run without a separate manual
// add-host step.
//
// Scope is deliberately narrow, matching every other batch's restraint
// this session: EC2 instances only, never S3 (there is no S3-bucket
// "inventory" concept anywhere in this codebase — inventory means hosts).
// Both instance platforms EC2 reports classify: a Linux instance resolves
// to linux_server, a Windows one to windows_server (added once
// svc.windows.*/win.feature.* gave that device type real capability
// accessors to classify into). Any platform value EC2 could add in the
// future that this classification tree has no rule for still quarantines
// with an explicit reason rather than guessing.
package aws

import (
	"context"
	"fmt"
	"strings"

	"github.com/Subject-Void-LLC/the-pleiades/internal/classification"
	"github.com/Subject-Void-LLC/the-pleiades/internal/credential"
	inv "github.com/Subject-Void-LLC/the-pleiades/internal/inventory"
	"github.com/Subject-Void-LLC/the-pleiades/internal/inventory/record"
	"github.com/Subject-Void-LLC/the-pleiades/internal/inventory/syncplugin"
	"github.com/Subject-Void-LLC/the-pleiades/pkg/awscloud"
	"github.com/Subject-Void-LLC/the-pleiades/pkg/inventory"
)

// Name is this plugin's registration key and the value stamped into the
// SourceAuthority of every device it syncs.
const Name = "aws"

func init() {
	syncplugin.MustRegister(syncplugin.Descriptor{
		Name:        Name,
		Description: "reads EC2 instances from an AWS account/region",
		DefaultConfig: syncplugin.Config{
			Name:     Name,
			Endpoint: "",
			ReadOnly: true,
		},
		// Verified against a real LocalStack container: authenticate, page
		// EC2's real DescribeInstances, classify, and reconcile. See
		// aws_test.go and the conformance suite's "aws" backend entry.
		Status: syncplugin.StatusImplemented,
		// The region is declared rather than defaulted for the same
		// reason pkg/awscloud.New and devices/aws.Account.AWSRegion
		// refuse an empty one: a region is not a convention the way an
		// SSH port is, and guessing would read a fleet that is not the
		// one the operator meant.
		Settings: []syncplugin.SettingSpec{{
			Name:        SettingRegion,
			Description: "the AWS region to read EC2 instances from, for example us-east-1",
			Required:    true,
		}},
		RequiresCredentials: true,
		New:                 func(deps syncplugin.Deps) syncplugin.Plugin { return New(deps) },
	})
}

// SettingRegion is the Descriptor setting key naming the AWS region
// this plugin reads. It is exported so a caller assembling a Config, and
// a test asserting the wiring, name the same string the descriptor
// declares rather than two copies of a literal.
const SettingRegion = "region"

// Aws is the "aws" sync plugin. The zero value is not usable; construct
// one with New.
type Aws struct {
	cfg     syncplugin.Config
	region  string
	client  *awscloud.Client
	factory *inv.ItemFactory
	ruleSet *classification.RuleSet

	// creds resolves cfg.CredentialName at Connect time. It arrives
	// through syncplugin.Deps, so it is whatever store the composition
	// root that built this plugin uses, and syncplugin.Open has already
	// refused to build the plugin at all if that store was nil (the
	// descriptor above sets RequiresCredentials).
	creds credential.Store
}

// compile-time proof this plugin satisfies the port.
var _ syncplugin.Plugin = (*Aws)(nil)

// New creates an unconnected plugin from the dependencies the
// composition root supplies.
//
// There are deliberately no constructor Options any more. This plugin
// used to take WithRegion and WithCredentialStore, and nothing in
// production ever passed either: the registry's own argument-less
// constructor was what cmd/pleiades built, so every real
// `pleiades inventory sync --plugin aws` failed with "no region
// configured, use WithRegion" while three test suites passed. The
// credential store now arrives in deps, on the one path everything
// constructs through, and the region arrives as a declared setting on
// the Config, which is where a per-deployment value an operator types
// belongs. See internal/inventory/syncplugin/deps.go.
func New(deps syncplugin.Deps) *Aws {
	return &Aws{
		factory: inv.NewItemFactory(),
		ruleSet: classification.DefaultRuleSet(),
		creds:   deps.Credentials,
	}
}

// Connect resolves the configured credential and authenticates against
// the account/region.
//
// It authenticates eagerly rather than lazily, by asking for one page of
// instances. A Connect that only built a client would report success
// against a wrong access key or an unreachable endpoint, and the failure
// would surface later as a confusing mid-sync error.
func (p *Aws) Connect(ctx context.Context, cfg syncplugin.Config) error {
	if err := cfg.Validate(); err != nil {
		return err
	}

	// The region and the credential store are both checked again here,
	// not only in syncplugin.Open. Open is the one path any composition
	// root builds through, but Connect is a method on an exported type
	// and nothing in Go stops a caller from constructing an Aws directly
	// and calling it; the alternative to re-checking is a nil-pointer
	// panic several frames into the AWS SDK.
	region, _ := cfg.Setting(SettingRegion)
	region = strings.TrimSpace(region)
	if region == "" {
		return fmt.Errorf("sync plugin %q: no %s setting configured", Name, SettingRegion)
	}
	if p.creds == nil {
		return fmt.Errorf("sync plugin %q: no credential store configured", Name)
	}
	p.region = region

	credentialName := cfg.CredentialName
	if credentialName == "" {
		// Default to the plugin's own name so the common single-account
		// case needs no extra configuration: `pleiades add-credential aws`
		// is enough.
		credentialName = Name
	}

	cred, err := p.creds.Lookup(ctx, credentialName)
	if err != nil {
		return fmt.Errorf("sync plugin %q: resolving credential %q: %w", Name, credentialName, err)
	}

	var opts []awscloud.Option
	if cfg.Endpoint != "" {
		opts = append(opts, awscloud.WithEndpoint(cfg.Endpoint))
	}

	client, err := awscloud.New(p.region, cred.Username, cred.Password, "", opts...)
	if err != nil {
		return fmt.Errorf("sync plugin %q: %w", Name, err)
	}

	// A real, cheap authenticated call: 5 is EC2's own documented minimum
	// MaxResults, not an arbitrary choice.
	if _, _, err := client.ListInstancesPage(ctx, "", 5); err != nil {
		return fmt.Errorf("sync plugin %q: connecting to account/region %q: %w", Name, p.region, err)
	}

	p.cfg = cfg
	p.client = client
	return nil
}

// minPageSize and maxPageSize are EC2's own documented bounds for
// DescribeInstances' MaxResults. syncplugin.Config.EffectivePageSize is
// shared across every plugin and knows nothing about this one's
// upstream's specific limits, so this plugin clamps into them rather than
// forwarding a caller's PageSize straight into a real request AWS would
// reject outright (below the floor) or reinterpret via a narrowing
// int-to-int32 conversion (above int32's own range). LocalStack tolerates
// values outside this range; real AWS does not, and this plugin's
// contract does not change depending on which one is behind cfg.Endpoint.
const (
	minPageSize int32 = 5
	maxPageSize int32 = 1000
)

// clampPageSize bounds n (an int, since that is what
// syncplugin.Config.EffectivePageSize returns) into [minPageSize,
// maxPageSize] and returns it as the int32 the SDK's MaxResults expects,
// without ever converting a value outside int32's own range.
func clampPageSize(n int) int32 {
	switch {
	case n < int(minPageSize):
		return minPageSize
	case n > int(maxPageSize):
		return maxPageSize
	default:
		return int32(n)
	}
}

// Discover streams the account/region itself followed by every EC2
// instance it holds.
func (p *Aws) Discover(_ context.Context) (syncplugin.RecordIterator, error) {
	if p.client == nil {
		return nil, syncplugin.ErrNotConnected
	}
	return newInstanceIterator(p.client, p.region, p.cfg.Endpoint, clampPageSize(p.cfg.EffectivePageSize())), nil
}

// Classify maps one discovered record onto a device type and capability
// set.
//
// The account record classifies as aws_account trivially: it carries
// nothing further to derive, unlike an instance. An instance's platform
// decides everything else: a Linux instance (EC2 reports no Platform at
// all) resolves to the existing linux_server root path, and a Windows
// one ("windows", the only other value EC2's DescribeInstances defines)
// resolves to windows_server. Any other value -- which would mean AWS
// added a Platform this classification tree has no rule for -- quarantines
// with an explicit reason rather than guessing at a device type.
func (p *Aws) Classify(_ context.Context, rec record.Record) (syncplugin.Classification, error) {
	state := inventory.StateSimulateLocked
	if !p.cfg.ReadOnly {
		state = inventory.StateActive
	}

	role, _ := rec.Properties[propRole].(string)
	switch role {
	case roleAccount:
		return syncplugin.ClassifyPath(p.ruleSet, []string{"aws_account"}, state), nil
	case roleInstance:
		platform, _ := rec.Properties[propPlatform].(string)
		switch platform {
		case "":
			return syncplugin.ClassifyPath(p.ruleSet, []string{"linux_server"}, state), nil
		case "windows":
			return syncplugin.ClassifyPath(p.ruleSet, []string{"windows_server"}, state), nil
		default:
			return syncplugin.Quarantine(fmt.Sprintf("instance platform %q has no classification rule yet", platform)), nil
		}
	default:
		return syncplugin.Quarantine(fmt.Sprintf("upstream record carries no recognized %s", propRole)), nil
	}
}

// Sync reconciles every discovered record into repo through the shared
// driver.
func (p *Aws) Sync(ctx context.Context, repo inv.Repository) (syncplugin.Reconciliation, error) {
	if p.client == nil {
		return syncplugin.Reconciliation{}, syncplugin.ErrNotConnected
	}
	return syncplugin.Reconcile(ctx, p, p.cfg, repo, p.factory)
}

// Close releases the plugin's connection. pkg/awscloud.Client has no
// pooled state of its own to release (unlike pkg/catalystcenter's client,
// it holds no cached auth token), so this only clears the reference.
func (p *Aws) Close() error {
	p.client = nil
	return nil
}
