package exec

import (
	"context"
	"fmt"
	"strings"

	"github.com/Subject-Void-LLC/the-pleiades/pkg/capability"
	"github.com/Subject-Void-LLC/the-pleiades/pkg/collection"
	"github.com/Subject-Void-LLC/the-pleiades/pkg/inventory"
	"github.com/Subject-Void-LLC/the-pleiades/pkg/remoteexec"
	"github.com/Subject-Void-LLC/the-pleiades/pkg/sdk"
)

// This file implements "exec.command", generated by
// pleiades forge new-collection and then hand-completed.
//
// It is the first write-capable method in the catalog, and it is
// deliberately first: most other modules are "run a command, interpret
// the result," so what Changed means here is what the rest of the tier
// copies. See Command's own doc comment for that contract.

// paramCmd and paramArgv are the two ways a task names what to run.
// Both are Ansible's own names for the same two forms.
const (
	paramCmd  = "cmd"
	paramArgv = "argv"
)

func init() {
	collection.MustRegister(collection.Descriptor{
		Name: "exec.command",
		Manifest: collection.Manifest{
			SupportedTransports: []string{
				"ssh",
			},
			RequiredCapabilities: []capability.Name{
				capability.NameCommandExec,
			},
			ExecutionContext: collection.ExecutionContext{
				RequiresElevation: false,
			},
			PlatformTargets: nil,
			EngineVersion:   ">=1.0.0",
			Status:          collection.StatusImplemented,
			// Nothing here can be undone, and the reason is the same fact
			// that makes Changed unconditional: a command cannot be
			// inspected, so the platform cannot know what it did.
			Reversibility: collection.Reversibility{
				Reversible: false,
				Notes:      "An arbitrary command's effect is unknown to this platform, so no undo can be derived from it. Pair the task with creates or removes to make re-running it safe, which is idempotence rather than rollback.",
			},
			Doc: commandDoc(),
		},
		Invoke: Command,
	})
}

// commandDoc is this method's reference documentation, kept out of the
// registration above only because the two together would bury the
// manifest fields under a page of prose.
func commandDoc() collection.Doc {
	return collection.Doc{
		Summary:     "Runs one command directly, with no shell involved.",
		Description: "Runs a single command on the target over SSH and reports its exit status, stdout and stderr. No shell interprets the command: a semicolon, pipe or dollar sign in an argument is passed through as text, so this cannot chain commands, expand a variable or redirect output. Use exec.shell when those are what you want. A command cannot be inspected, so this reports changed every time it runs; creates and removes are how a task says what its work having already happened looks like, and a run they short-circuit reports no change.",
		Params: []collection.Param{
			{Name: paramCmd, Type: "string", Description: "The command and its arguments as one string, split the way a shell splits a command line: whitespace separates arguments, and single quotes, double quotes and backslashes group them. Mutually exclusive with argv."},
			{Name: paramArgv, Type: "list of string", Description: "The command and its arguments already split, one element each. Preferred when an argument contains characters whose quoting would be awkward to write. Mutually exclusive with cmd."},
			{Name: paramChdir, Type: "string", Description: "Change into this directory before running, and resolve a relative creates or removes against it too. The command does not run at all if the directory does not exist. Defaults to the device's own working directory, or to wherever the account lands on login."},
			{Name: paramCreates, Type: "string", Description: "A path whose existence on the target means this work is already done. When it exists, the command does not run and the task reports no change. A relative path is resolved from chdir, the same directory the command itself runs in."},
			{Name: paramRemoves, Type: "string", Description: "A path whose absence on the target means this work is already done. When it is missing, the command does not run and the task reports no change. A relative path is resolved from chdir, the same directory the command itself runs in."},
			{Name: paramStdin, Type: "string", Description: "Text piped to the command's standard input."},
			{Name: sdk.ParamInsecureSkipHostKeyVerify, Type: "bool", Default: "false", Description: "Skip SSH host key verification for this task. This removes protection against a machine in the middle answering for the device, so set it only for a target you have decided does not need it."},
		},
		Returns: []collection.ReturnField{
			{Name: statRC, Type: "int", Returned: "always", Description: "The command's exit status. Zero when it succeeded, and 0 for a run that creates or removes skipped."},
			{Name: statStdout, Type: "string", Returned: "always", Description: "Everything the command wrote to standard output, with the trailing newline removed."},
			{Name: statStderr, Type: "string", Returned: "always", Description: "Everything the command wrote to standard error, with the trailing newline removed."},
			{Name: statCmd, Type: "string", Returned: "always", Description: "The exact command line sent to the device, empty for a skipped run."},
			{Name: statSkipped, Type: "bool", Returned: "always", Description: "True when creates or removes short-circuited this task, so no command ran."},
			{Name: "msg", Type: "string", Returned: "on skip", Description: "Why the task was skipped."},
		},
		Examples: []collection.Example{
			{
				Name:        "Run a command and register its output",
				RunbookYAML: "- name: Read the kernel version\n  fqcn: exec.command\n  params:\n    cmd: uname -r\n  register: kernel\n",
			},
			{
				Name:        "Make a command idempotent with creates",
				RunbookYAML: "- name: Unpack the release once\n  fqcn: exec.command\n  params:\n    cmd: tar -xzf /tmp/release.tgz\n    chdir: /opt/app\n    creates: /opt/app/VERSION\n",
			},
			{
				Name:        "Pass an argument that a shell would mangle",
				RunbookYAML: "- name: Write a literal value\n  fqcn: exec.command\n  params:\n    argv:\n      - /usr/bin/logger\n      - \"deployed $VERSION; done\"\n",
			},
		},
		SeeAlso: []string{"exec.shell"},
	}
}

// Command implements the "exec.command" collection method: it runs one
// command on the target over SSH, with no shell interpreting it.
//
// # What Changed means here, and why every later module copies it
//
// A command cannot be inspected. Nothing can look at "systemctl restart
// nginx" and decide whether running it will alter anything, so a module
// that guessed would be lying in one direction or the other. This
// reports Changed true whenever the command actually ran, and false only
// when it did not run at all, which is exactly what Ansible's command
// module does and for exactly the same reason.
//
// That makes creates and removes load-bearing rather than convenient:
// they are the only way a task built on this method becomes idempotent,
// because they are how the author states what the work having already
// happened looks like. Run twice with creates naming a path the first
// run makes, this reports changed and then not changed. Run twice
// without them, it reports changed twice, and that is the honest answer
// rather than a defect.
//
// A non-zero exit status is an error, not a result to inspect. The
// command reached the device and reported failure, and a task whose
// command failed has failed; Ansible's command module draws the same
// line. The exit status, stdout and stderr are recorded as stats before
// the error is returned.
func Command(ctx context.Context, rc sdk.RunbookContext, device inventory.InventoryItem, params map[string]any) (collection.Result, error) {
	const fqcn = "exec.command"

	argv, err := commandArgv(params)
	if err != nil {
		return collection.Result{}, fmt.Errorf("%s: %w", fqcn, err)
	}

	conn, err := sdk.Connect(ctx, rc, device, params, fqcn)
	if err != nil {
		return collection.Result{}, err
	}
	defer func() { _ = conn.Close() }()

	// Resolved before the guard rather than after it, because the guard
	// has to look in the same place the command will run. A relative
	// creates checked from the login directory is a guard that never
	// fires, and a relative removes checked there is worse: it skips a
	// task whose file is still sitting in chdir.
	dir := workingDirectory(device, params)

	skip, err := shouldSkip(ctx, conn, dir, params)
	if err != nil {
		return collection.Result{}, fmt.Errorf("%s: %w", fqcn, err)
	}
	if skip != "" {
		if err := recordSkip(rc, skip); err != nil {
			return collection.Result{}, fmt.Errorf("%s: %w", fqcn, err)
		}
		return collection.Result{Changed: false}, nil
	}

	command := commandLine(argv, dir)

	var stdin *strings.Reader
	if text := sdk.StringParam(params, paramStdin); text != "" {
		stdin = strings.NewReader(text)
	}

	var result remoteexec.Result
	if stdin != nil {
		result, err = conn.RunWithStdin(ctx, command, stdin)
	} else {
		result, err = conn.Run(ctx, command)
	}
	if err != nil {
		return collection.Result{}, fmt.Errorf("%s: %w", fqcn, err)
	}

	if err := recordResult(rc, command, result); err != nil {
		return collection.Result{}, fmt.Errorf("%s: %w", fqcn, err)
	}

	if result.ExitCode != 0 {
		// The command ran, so it changed whatever it changed before it
		// failed. Reporting Changed here would be pointless, since the
		// executor discards the result alongside an error, but the error
		// message has to carry enough for an operator to act on: the
		// status, and whichever stream the command actually explained
		// itself on.
		return collection.Result{}, fmt.Errorf("%s: command exited %d: %s",
			fqcn, result.ExitCode, failureDetail(result))
	}

	return collection.Result{Changed: true}, nil
}

// commandArgv resolves the two mutually exclusive ways a task names what
// to run into one argument vector.
//
// Naming neither, naming both, or naming one that resolves to nothing
// are all refusals rather than defaults. There is no sensible command to
// substitute, and a module that ran something anyway would be running
// something the author did not write.
func commandArgv(params map[string]any) ([]string, error) {
	cmd := sdk.StringParam(params, paramCmd)
	argv, argvPresent, err := sdk.StringSlice(params, paramArgv)
	if err != nil {
		return nil, err
	}

	switch {
	case cmd != "" && argvPresent:
		return nil, fmt.Errorf("set either %s or %s, not both", paramCmd, paramArgv)

	case argvPresent:
		if len(argv) == 0 {
			return nil, fmt.Errorf("%s is empty: there is no command to run", paramArgv)
		}
		return argv, nil

	case cmd != "":
		words, err := remoteexec.SplitWords(cmd)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", paramCmd, err)
		}
		if len(words) == 0 {
			return nil, fmt.Errorf("%s is empty: there is no command to run", paramCmd)
		}
		return words, nil

	default:
		return nil, fmt.Errorf("set %s or %s: this method needs a command to run", paramCmd, paramArgv)
	}
}

// failureDetail picks the stream an operator should read after a
// non-zero exit: stderr when the command wrote one, stdout otherwise,
// and a plain statement when it said nothing at all.
//
// Preferring stderr matters because the alternative is an error message
// that says only "exited 1" for the large family of commands that
// explain themselves on stderr and print nothing on stdout.
func failureDetail(result remoteexec.Result) string {
	if detail := strings.TrimSpace(result.Stderr); detail != "" {
		return detail
	}
	if detail := strings.TrimSpace(result.Stdout); detail != "" {
		return detail
	}
	return "no output"
}
