package exec

import (
	"context"
	"fmt"
	"strings"

	"github.com/Subject-Void-LLC/the-pleiades/pkg/capability"
	"github.com/Subject-Void-LLC/the-pleiades/pkg/collection"
	"github.com/Subject-Void-LLC/the-pleiades/pkg/inventory"
	"github.com/Subject-Void-LLC/the-pleiades/pkg/remoteexec"
	"github.com/Subject-Void-LLC/the-pleiades/pkg/sdk"
)

// This file implements "exec.shell", generated by
// pleiades forge new-collection and then hand-completed.
//
// It is deliberately thin. Ansible has no separate shell module either:
// its shell action plugin sets _uses_shell and hands the work to the
// same command module, and the two share one argument spec. So chdir,
// creates, removes and stdin behave here exactly as they do in
// exec.command, because they are the same code, and the difference
// between the two methods is one line: whether the command reaches a
// shell.
//
// paramExecutable is the one parameter exec.command does not have, and
// it is Ansible's own name for it.
const paramExecutable = "executable"

// defaultShell is the shell used when the task names none and the device
// declares none. POSIX sh rather than bash: it is the one shell that is
// present on essentially every Unix-like target, including the busybox
// and Alpine images this repository tests against, and a module whose
// default is missing on the device is a module that fails for a reason
// the author never wrote down.
const defaultShell = "/bin/sh"

func init() {
	collection.MustRegister(collection.Descriptor{
		Name: "exec.shell",
		Manifest: collection.Manifest{
			SupportedTransports: []string{
				"ssh",
			},
			RequiredCapabilities: []capability.Name{
				capability.NameShellExec,
			},
			ExecutionContext: collection.ExecutionContext{
				RequiresElevation: false,
			},
			PlatformTargets: nil,
			EngineVersion:   ">=1.0.0",
			Status:          collection.StatusImplemented,
			// Only a call guarded by creates or removes can be checked (CheckShell).
			SupportsCheck: true,
			// Nothing here can be undone, and the reason is the same fact
			// that makes Changed unconditional: a command cannot be
			// inspected, so the platform cannot know what it did.
			Reversibility: collection.Reversibility{
				Reversible: false,
				Notes:      "A shell command's effect is unknown to this platform, and a pipeline or redirect can touch things the command line does not name, so no undo can be derived from it. Pair the task with creates or removes to make re-running it safe, which is idempotence rather than rollback.",
			},
			Doc: shellDoc(),
		},
		Invoke:    Shell,
		Check:     CheckShell,
		CheckCall: unguardedCheck,
	})
}

// shellDoc is this method's reference documentation, kept out of the
// registration above so the manifest fields stay readable.
func shellDoc() collection.Doc {
	return collection.Doc{
		Summary:     "Runs a command through the target's shell, so pipes and redirects work.",
		Description: "Runs a command line on the target through a real shell, which is what makes a pipe, a redirect, a variable expansion, a glob or a chain of commands behave the way they would if you typed them. That is also the whole risk: every one of those characters is syntax, so any runbook value interpolated into this command is code. Use exec.command when the command is a single program with arguments, which is most of the time. A command cannot be inspected, so this reports changed every time it runs; creates and removes are how a task says what its work having already happened looks like. Only a call with creates or removes can be checked: a check reads the guard's path and reports whether the line would run, running nothing. Any other call is named as unchecked, and check_mode on one is refused when the runbook is validated.",
		Params: []collection.Param{
			{Name: paramCmd, Type: "string", Required: true, Description: "The command line, passed to the shell exactly as written. Pipes, redirects, globs, variable expansions and semicolons all work, because the shell sees them."},
			{Name: paramExecutable, Type: "string", Description: "The shell to run the command with, invoked as `<executable> -c <cmd>`. Defaults to the shell the device declares, or /bin/sh."},
			{Name: paramChdir, Type: "string", Description: "Change into this directory before running, and resolve a relative creates or removes against it too. The command does not run at all if the directory does not exist. Defaults to the device's own working directory, or to wherever the account lands on login."},
			{Name: paramCreates, Type: "string", Description: "A path whose existence on the target means this work is already done. When it exists, the command does not run and the task reports no change. A relative path is resolved from chdir, the same directory the command itself runs in."},
			{Name: paramRemoves, Type: "string", Description: "A path whose absence on the target means this work is already done. When it is missing, the command does not run and the task reports no change. A relative path is resolved from chdir, the same directory the command itself runs in."},
			{Name: paramStdin, Type: "string", Description: "Text piped to the command's standard input."},
			{Name: sdk.ParamInsecureSkipHostKeyVerify, Type: "bool", Default: "false", Description: "Skip SSH host key verification for this task. This removes protection against a machine in the middle answering for the device, so set it only for a target you have decided does not need it."},
		},
		Returns: []collection.ReturnField{
			{Name: statRC, Type: "int", Returned: "always", Description: "The command's exit status, which for a pipeline is the last command's. Zero when it succeeded, and 0 for a run that creates or removes skipped."},
			{Name: statStdout, Type: "string", Returned: "always", Description: "Everything the command wrote to standard output, with the trailing newline removed."},
			{Name: statStderr, Type: "string", Returned: "always", Description: "Everything the command wrote to standard error, with the trailing newline removed."},
			{Name: statCmd, Type: "string", Returned: "always", Description: "The command line sent to the device, empty for a skipped run."},
			{Name: statSkipped, Type: "bool", Returned: "always", Description: "True when creates or removes short-circuited this task, so no command ran."},
			{Name: "msg", Type: "string", Returned: "on skip", Description: "Why the task was skipped."},
		},
		Examples: []collection.Example{
			{
				Name:        "Use a pipeline",
				RunbookYAML: "- name: Count the failed units\n  exec.shell:\n    cmd: systemctl list-units --state=failed --no-legend | wc -l\n  register: failed\n",
			},
			{
				Name:        "Redirect output to a file, once",
				RunbookYAML: "- name: Snapshot the package list\n  exec.shell:\n    cmd: dpkg -l > /var/backups/packages.txt\n    creates: /var/backups/packages.txt\n",
			},
			{
				Name:        "Choose the shell",
				RunbookYAML: "- name: Use a bash-only construct\n  exec.shell:\n    cmd: \"[[ -f /etc/os-release ]] && echo present\"\n    executable: /bin/bash\n",
			},
		},
		SeeAlso: []string{"exec.command"},
	}
}

// Shell implements the "exec.shell" collection method: it runs a command
// line on the target through a real shell.
//
// # What it shares with exec.command, and the one thing it does not
//
// Everything except the command construction is the same code, on
// purpose: the same connection, the same creates and removes guards
// resolved from the same chdir, the same stats, the same rule that a
// non-zero exit is an error, and the same Changed contract (true
// whenever the command ran, false only when a guard stopped it). See
// Command's doc comment for why Changed works that way; it is the
// contract for the whole namespace.
//
// The difference is quoting, and it is worth being precise about because
// getting it backward would silently produce either exec.command or a
// shell injection.
//
// exec.command splits the task's cmd into words locally and re-quotes
// each one, so the remote shell finds nothing to interpret. This method
// must NOT split: handing the line to a shell unsplit is the entire
// feature. What it does instead is build the three-element argument
// vector <shell> -c <line> and quote THAT, so the outer login shell that
// SSH hands the string to sees exactly three words and passes the line
// through untouched to the shell named. The author's line then reaches
// exactly one shell, the one they asked for, rather than being parsed
// once by the login shell and again by the executable.
//
// So remoteexec.QuoteCommand is reused here and remoteexec.SplitWords is
// not. A recorded plan for this method said neither could be reused,
// which was half right; the correction matters because dropping the
// quoting would let a chdir path or the line itself break out of the
// outer shell's parse.
func Shell(ctx context.Context, rc sdk.RunbookContext, device inventory.InventoryItem, params map[string]any) (collection.Result, error) {
	return shell(ctx, rc, device, params, collection.ModeExecute)
}

// CheckShell is exec.shell's check: a call guarded by creates or removes reads the guard exactly as Shell does and reports the skip the real run would make, or predicts that the command would run, without running it; an unguarded call answers that it cannot be checked, since what a command changes is not knowable without running it. This is Ansible's own check behavior for its command and shell modules.
func CheckShell(ctx context.Context, rc sdk.RunbookContext, device inventory.InventoryItem, params map[string]any) (collection.Result, error) {
	return shell(ctx, rc, device, params, collection.ModeCheck)
}

// shell is Shell's and CheckShell's one body; mode says which.
func shell(ctx context.Context, rc sdk.RunbookContext, device inventory.InventoryItem, params map[string]any, mode collection.Mode) (collection.Result, error) {
	const fqcn = "exec.shell"

	line := sdk.StringParam(params, paramCmd)
	if line == "" {
		return collection.Result{}, fmt.Errorf("%s: %s is required: there is no command to run", fqcn, paramCmd)
	}

	if mode == collection.ModeCheck {
		if err := unguardedCheck(params); err != nil {
			return collection.Result{}, err
		}
	}

	conn, err := sdk.Connect(ctx, rc, device, params, fqcn)
	if err != nil {
		return collection.Result{}, err
	}
	defer func() { _ = conn.Close() }()

	dir := workingDirectory(device, params)

	skip, err := shouldSkip(ctx, conn, dir, params)
	if err != nil {
		return collection.Result{}, fmt.Errorf("%s: %w", fqcn, err)
	}
	if skip != "" {
		if err := recordSkip(rc, skip); err != nil {
			return collection.Result{}, fmt.Errorf("%s: %w", fqcn, err)
		}
		return collection.Result{Changed: false}, nil
	}

	command := commandLine([]string{shellPath(device, params), "-c", line}, dir)
	if mode == collection.ModeCheck {
		if err := recordWouldRun(rc, command); err != nil {
			return collection.Result{}, fmt.Errorf("%s: %w", fqcn, err)
		}
		return collection.Result{Changed: true}, nil
	}

	var result remoteexec.Result
	if text := sdk.StringParam(params, paramStdin); text != "" {
		result, err = conn.RunWithStdin(ctx, command, strings.NewReader(text))
	} else {
		result, err = conn.Run(ctx, command)
	}
	if err != nil {
		return collection.Result{}, fmt.Errorf("%s: %w", fqcn, err)
	}

	if err := recordResult(rc, command, result); err != nil {
		return collection.Result{}, fmt.Errorf("%s: %w", fqcn, err)
	}

	if result.ExitCode != 0 {
		return collection.Result{}, fmt.Errorf("%s: command exited %d: %s",
			fqcn, result.ExitCode, failureDetail(result))
	}

	return collection.Result{Changed: true}, nil
}

// shellPath decides which shell runs the command: the task's own
// executable parameter when it sets one, otherwise whatever the device
// declares through capability.ShellExecCapable, otherwise /bin/sh.
//
// This is workingDirectory's shape exactly, and for the same reasons.
// Reading the device's answer is what makes the ShellExecCapable
// requirement on this manifest mean something rather than being a label,
// and the read is optional rather than a hard type assertion because
// nothing enforces a manifest's declared capabilities at run time
// (FAILURE_PATTERNS.md #151) and the Runner's own device adapter carries
// a capability list with no accessors behind it. A device that cannot
// answer gets the default, which is a perfectly good answer.
func shellPath(device inventory.InventoryItem, params map[string]any) string {
	if shell := sdk.StringParam(params, paramExecutable); shell != "" {
		return shell
	}
	if shellDev, ok := device.(capability.ShellExecCapable); ok {
		if shell := shellDev.ShellPath(); shell != "" {
			return shell
		}
	}
	return defaultShell
}
