// Certificate generation: minting one self-signed ECDSA serving
// certificate and writing the pair to disk without ever leaving a
// half-written file where a reader can see it.
package tlscert

import (
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/tls"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/pem"
	"fmt"
	"math/big"
	"net"
	"strings"
	"time"
)

// backdate is how far before "now" a generated certificate becomes valid.
//
// A container clock and the host clock that generated the certificate can
// disagree by less than a minute, and a not-yet-valid certificate fails
// exactly like an invalid one, with a message that sends an operator
// looking at the wrong thing.
const backdate = time.Minute

// Generate mints a new self-signed serving certificate into dir and
// returns the paths, the parsed leaf and the trust pool for it. Any
// existing pair in dir is replaced.
//
// The subject alternative names are the part that is easy to get wrong and
// expensive to debug. A certificate is matched against the name the client
// DIALED, so "127.0.0.1" has to be an IP SAN and "localhost" has to be a
// DNS SAN: putting the address in the Common Name, or listing 127.0.0.1 as
// a DNS name, produces a certificate that looks right in every dump and
// fails every handshake with "certificate is not valid for any names".
// Both loopback addresses are listed because a client that resolves
// "localhost" may reach either one.
//
// It is marked as a CA so that the same file works both as the server's
// leaf and as the single entry in a client's root pool. Go verifies a
// self-signed leaf found in the root pool either way, but a certificate
// that is a valid root only by that special case is one library version
// away from being a support question.
//
// Unlike Ensure, this replaces whatever is in dir without asking who wrote
// it. That is safe only because of who calls it: a developer running
// tools/devcert at a directory they named, and test helpers writing into a
// throwaway directory. The controller's start-up path never calls it, and
// must not: Ensure is the entry point that refuses to overwrite an
// operator's own material.
func Generate(dir string, opts Options) (ServingCert, error) {
	opts = opts.withDefaults()

	if err := ValidateNames(opts.ExtraNames); err != nil {
		return ServingCert{}, err
	}
	if err := ValidateNames(opts.OptionalNames); err != nil {
		return ServingCert{}, err
	}

	absDir, err := prepareDir(dir)
	if err != nil {
		return ServingCert{}, err
	}
	return generateInto(absDir, opts)
}

// minted is one freshly signed certificate and everything derived from it,
// held in memory before a single byte is written.
//
// Minting and writing are separate because two callers write the same
// material to different shapes on disk: Generate publishes the two-file
// cert.pem/key.pem layout the developer tools and an operator's own
// TLS_CERT_FILE pair use, and Ensure publishes one atomic serving bundle.
// Neither one may have its own copy of "what a certificate from this package
// looks like", because a second copy is exactly how the extended key usage or
// the IP SAN goes missing from one of them.
type minted struct {
	// leaf is parsed back out of the DER that was just signed rather than
	// kept from the template: the template is what was ASKED for, and this is
	// what was actually produced.
	leaf    *x509.Certificate
	certPEM []byte
	keyPEM  []byte
}

// mint signs one certificate and returns it with its key, touching no files.
func mint(opts Options) (minted, error) {
	key, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		return minted{}, fmt.Errorf("generating the P-256 key: %w", err)
	}

	// A random 128-bit serial, which is what a certificate authority is
	// required to use. Nothing here checks serials, but a fixed one would
	// make two certificates generated by two runs of this function
	// indistinguishable to anything that does.
	serialMax := new(big.Int).Lsh(big.NewInt(1), 128)
	serial, err := rand.Int(rand.Reader, serialMax)
	if err != nil {
		return minted{}, fmt.Errorf("generating the serial number: %w", err)
	}

	dnsNames, ipAddresses := resolveNames(opts)
	now := time.Now()
	template := x509.Certificate{
		SerialNumber: serial,
		Subject: pkix.Name{
			Organization: []string{"Pleiades"},
			CommonName:   "pleiades-local",
		},
		NotBefore:             now.Add(-backdate),
		NotAfter:              now.Add(opts.TTL),
		KeyUsage:              x509.KeyUsageDigitalSignature | x509.KeyUsageCertSign,
		ExtKeyUsage:           []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
		BasicConstraintsValid: true,
		IsCA:                  true,
		DNSNames:              dnsNames,
		IPAddresses:           ipAddresses,
	}

	der, err := x509.CreateCertificate(rand.Reader, &template, &template, &key.PublicKey, key)
	if err != nil {
		return minted{}, fmt.Errorf("signing the certificate: %w", err)
	}
	keyDER, err := x509.MarshalECPrivateKey(key)
	if err != nil {
		return minted{}, fmt.Errorf("marshalling the private key: %w", err)
	}

	parsed, err := x509.ParseCertificate(der)
	if err != nil {
		return minted{}, fmt.Errorf("parsing the certificate just signed: %w", err)
	}

	return minted{
		leaf:    parsed,
		certPEM: pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: der}),
		keyPEM:  pem.EncodeToMemory(&pem.Block{Type: "EC PRIVATE KEY", Bytes: keyDER}),
	}, nil
}

// generateInto writes a freshly minted certificate into an already resolved
// directory as the two-file cert.pem/key.pem layout, and returns what to
// serve.
//
// This is the developer and operator shape, not the one the controller
// starts from: `make dev-cert` and internal/testsupport want two paths they
// can hand to TLS_CERT_FILE and TLS_KEY_FILE. Ensure publishes a serving
// bundle instead (bundle.go), because two files cannot be replaced in one
// step and a controller sharing a directory needs them to be.
func generateInto(absDir string, opts Options) (ServingCert, error) {
	fresh, err := mint(opts)
	if err != nil {
		return ServingCert{}, err
	}

	// Provenance is recorded BEFORE either file is published, so that no
	// reader can ever see a certificate this package wrote and conclude it
	// belongs to somebody else. provisioned.go explains why that direction
	// is the safe one to be wrong in.
	if err := recordProvisioned(absDir, fresh.leaf); err != nil {
		return ServingCert{}, err
	}

	// The key lands first, and the order is deliberate rather than
	// incidental. Each rename below is atomic on its own, so no reader ever
	// sees a truncated file, but two files cannot be replaced in one step: a
	// reader arriving between the two renames sees a new key beside an old
	// certificate. Writing the key first makes that the only possible
	// mismatch, and Ensure recognises it as this package's own leftovers and
	// heals it (ownership.go's keyWasWrittenHere). A caller that needs the
	// two to be replaced together has to use Ensure, which publishes one
	// file.
	keyPath, err := writeAtomic(absDir, KeyFileName, fresh.keyPEM)
	if err != nil {
		return ServingCert{}, err
	}
	certPath, err := writeAtomic(absDir, CertFileName, fresh.certPEM)
	if err != nil {
		return ServingCert{}, err
	}

	// Built from the material in hand rather than by reading the two files
	// back, so what a caller serves is byte for byte what was just signed
	// even if another process replaces the files a microsecond later.
	pair, err := tls.X509KeyPair(fresh.certPEM, fresh.keyPEM)
	if err != nil {
		return ServingCert{}, fmt.Errorf("the certificate and key just written to %s are not a usable pair: %w", absDir, err)
	}
	pair.Leaf = fresh.leaf

	roots := x509.NewCertPool()
	roots.AddCert(fresh.leaf)

	return ServingCert{
		CertFile:        certPath,
		KeyFile:         keyPath,
		Pair:            pair,
		Leaf:            fresh.leaf,
		Roots:           roots,
		Generated:       true,
		SelfProvisioned: true,
	}, nil
}

// resolveNames is every subject alternative name a generated certificate
// carries: the loopback set, the caller's required names, and its optional
// ones.
func resolveNames(opts Options) ([]string, []net.IP) {
	all := make([]string, 0, len(opts.ExtraNames)+len(opts.OptionalNames))
	all = append(all, opts.ExtraNames...)
	all = append(all, opts.OptionalNames...)
	return namesFrom(all)
}

// requiredNames is the subset a STORED certificate must already carry to be
// reusable: the loopback set and the caller's required names, never its
// optional ones. See Options.OptionalNames for why the two differ.
func requiredNames(opts Options) ([]string, []net.IP) {
	return namesFrom(opts.ExtraNames)
}

// namesFrom turns a list of names into the two SAN fields, with the
// loopback names every certificate from this package carries already in
// place.
//
// An entry that parses as an IP address becomes an IP SAN; everything else
// becomes a DNS SAN. Duplicates and blanks are dropped so a caller can
// hand this a split environment variable directly.
func namesFrom(entries []string) ([]string, []net.IP) {
	dnsNames := []string{"localhost"}
	ipAddresses := []net.IP{net.IPv4(127, 0, 0, 1), net.IPv6loopback}

	seenDNS := map[string]bool{"localhost": true}
	seenIP := map[string]bool{
		net.IPv4(127, 0, 0, 1).String(): true,
		net.IPv6loopback.String():       true,
	}

	for _, name := range entries {
		name = strings.TrimSpace(name)
		if name == "" {
			continue
		}
		if ip := net.ParseIP(name); ip != nil {
			if seenIP[ip.String()] {
				continue
			}
			seenIP[ip.String()] = true
			ipAddresses = append(ipAddresses, ip)
			continue
		}
		// Compared case-insensitively because DNS is, so "Controller" and
		// "controller" are one name rather than two SANs that differ only
		// in a way no resolver can see.
		lowered := strings.ToLower(name)
		if seenDNS[lowered] {
			continue
		}
		seenDNS[lowered] = true
		dnsNames = append(dnsNames, lowered)
	}
	return dnsNames, ipAddresses
}
