package collectionscaffold

// collectionTemplateSource is the collection method source file template:
// a pkg/collection registration in init(), and a stub function built on
// pkg/sdk.RunbookContext. The stub always returns an explicit error, never
// success, matching the "declared is not implemented" guardrail
// docs/hephaestus.md names and Phase 34's own Release Gate depends on.
const collectionTemplateSource = `// Package {{.PackageName}} implements the "{{.Name}}" namespaced Collection
// method. Generated by pleiades forge new-collection
// (internal/forge/collectionscaffold).
//
// This package's init registers "{{.Name}}" into the shared pkg/collection
// registry via collection.MustRegister. That registry is more than
// planning-time metadata: a runbook task naming "{{.Name}}" reaches
// engine.NewCollectionActionExecutor's real dispatch path
// (cmd/pleiades/run.go), which looks this Manifest's Status up and
// refuses with its own "declared but not implemented" error before ever
// calling {{.FunctionName}} below: a declared stub is never invoked, by
// design, not because nothing reaches it. {{.FunctionName}}'s own
// "not implemented" return only ever executes if something calls it
// directly (a test does exactly this) or once a later change sets
// Invoke to it and flips Status to StatusImplemented, at which point the
// dispatcher's short-circuit no longer applies and this becomes the
// method's real body. Its signature below (context.Context,
// sdk.RunbookContext, inventory.InventoryItem, map[string]any) is not a
// placeholder: it matches collection.Method exactly, the established
// contract every real implementation must satisfy.
//
// Because this package lives under internal/, it is reachable only from
// code inside this module or a fork of it: Go's internal/ visibility rule
// blocks any other module from importing it at all. This generator is
// repo-contributor tooling, not end-user extensibility; a third-party
// Collection arriving from outside this binary needs a separate,
// not-yet-built distribution mechanism (Part X's OCI distribution work),
// not this one.
package {{.PackageName}}

import (
	"context"
	"fmt"

	"github.com/Subject-Void-LLC/the-pleiades/pkg/capability"
	"github.com/Subject-Void-LLC/the-pleiades/pkg/collection"
	"github.com/Subject-Void-LLC/the-pleiades/pkg/inventory"
	"github.com/Subject-Void-LLC/the-pleiades/pkg/sdk"
)

func init() {
	collection.MustRegister(collection.Descriptor{
		Name: {{quote .Name}},
		Manifest: collection.Manifest{
			SupportedTransports: []string{
{{range .Transports}}				{{quote .}},
{{end}}			},
			RequiredCapabilities: []capability.Name{
{{range .Capabilities}}				capability.Name({{quote .}}),
{{end}}			},
			ExecutionContext: collection.ExecutionContext{
				RequiresElevation: {{.RequiresElevation}},
			},
			// TODO(forge): PlatformTargets narrows this manifest to a
			// specific vendor, model, firmware range, or deployment
			// context (pkg/collection.PlatformTarget). Left nil: thin
			// flag parsing only, per Phase 33's own checklist. Add real
			// entries by hand once this method's platform scope is known.
			PlatformTargets: nil,
			EngineVersion:   {{quote .EngineVersion}},
			Status:          collection.StatusDeclared,
			// TODO(forge): answer this before flipping Status to
			// StatusImplemented. collection.Register REFUSES an
			// implemented method that says it is not reversible without
			// saying why, so leaving this alone turns into a panic at
			// process start rather than a question at authoring time.
			//
			// Reversible is true if a run of this method can ever emit
			// the instruction that undoes it, false if it cannot. Which
			// inverse it is belongs to the RUN and not here: a method
			// that created something undoes to a removal, and the same
			// method finding it already there undoes to whatever it
			// changed, so the concrete instruction is emitted at run time
			// with sdk.RecordInverse. Notes is required when Reversible
			// is false and should say what about this method's effect
			// the platform cannot observe or reconstruct.
			//
			// Reversibility: collection.Reversibility{Reversible: false, Notes: ""},
{{.Doc}}		},
	})
}

// {{.FunctionName}} implements the "{{.Name}}" collection method.
//
// TODO(forge): not implemented. Returns an explicit error, never success:
// a stub that reports success is worse than a method that does not
// exist, because it makes a failed runbook look like a successful one.
// A runbook task naming this FQCN never actually reaches this function
// today; see this package's own doc comment for exactly why and what
// changes that.
func {{.FunctionName}}(ctx context.Context, rc sdk.RunbookContext, device inventory.InventoryItem, params map[string]any) (collection.Result, error) {
	return collection.Result{}, fmt.Errorf("{{.Name}}: not implemented")
}
`

// collectionTestTemplateSource is the starter table-driven test template.
// It proves the init()-time registration succeeded (collection.Lookup
// finds the name, with the Manifest fields this generator was given) and
// that the stub itself returns the required explicit not-implemented
// error rather than success.
const collectionTestTemplateSource = `package {{.PackageName}}_test

import (
	"context"
	"strings"
	"testing"

	"github.com/Subject-Void-LLC/the-pleiades/internal/catalog/{{.PackagePath}}"
	"github.com/Subject-Void-LLC/the-pleiades/pkg/collection"
)

// Test{{.FunctionName}}_Registered is a starter test, generated by
// pleiades forge new-collection: it proves "{{.Name}}" registered itself
// through this package's own init(), with the manifest fields given at
// generation time.
func Test{{.FunctionName}}_Registered(t *testing.T) {
	d, ok := collection.Lookup({{quote .Name}})
	if !ok {
		t.Fatalf("collection.Lookup(%q) found nothing; did this package's init() run?", {{quote .Name}})
	}
	if d.Manifest.Status != collection.StatusDeclared {
		t.Errorf("Manifest.Status = %v, want %v", d.Manifest.Status, collection.StatusDeclared)
	}
	if d.Manifest.ExecutionContext.RequiresElevation != {{.RequiresElevation}} {
		t.Errorf("Manifest.ExecutionContext.RequiresElevation = %v, want %v",
			d.Manifest.ExecutionContext.RequiresElevation, {{.RequiresElevation}})
	}
}

// Test{{.FunctionName}}_NotImplemented is a starter, table-driven proof of
// the "declared is not implemented" guardrail: the stub must return an
// explicit error, never success. Replace this table as real parameter
// cases are added once {{.FunctionName}} is actually implemented.
func Test{{.FunctionName}}_NotImplemented(t *testing.T) {
	tests := []struct {
		name   string
		params map[string]any
	}{
		{name: "no params", params: nil},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			_, err := {{.PackageName}}.{{.FunctionName}}(context.Background(), nil, nil, tt.params)
			if err == nil {
				t.Fatal("expected an explicit not-implemented error, got nil")
			}
			if !strings.Contains(err.Error(), "not implemented") {
				t.Errorf("error = %q, want it to mention \"not implemented\"", err.Error())
			}
		})
	}
}
`
