package collectionscaffold

// collectionTemplateSource is the collection method source file template:
// a pkg/collection registration in init(), and a stub function built on
// pkg/sdk.RunbookContext. The stub always returns an explicit error, never
// success, matching the "declared is not implemented" guardrail
// docs/hephaestus.md names and Phase 34's own Release Gate depends on.
const collectionTemplateSource = `// Package {{.PackageName}} implements the "{{.Name}}" namespaced Collection
// method. Generated by pleiades forge new-collection
// (internal/forge/collectionscaffold).
//
// This package's init registers "{{.Name}}" into the shared pkg/collection
// registry via collection.MustRegister. That registry is planning-time
// metadata only: it lets a runbook task's required capability and
// platform target resolve at plan time, and it is what Phase 34's own
// validation rule checks a runbook call against. It does NOT dispatch
// calls to {{.FunctionName}} below. No dispatcher anywhere in this
// codebase yet consumes pkg/collection or pkg/sdk.RunbookContext to
// actually invoke a registered method: the only real action executor
// today, internal/engine/action.go, dispatches on a hardcoded switch over
// bare task.FQCN strings and never touches either package. {{.FunctionName}}
// is real, buildable, testable Go code, but it is not reachable from any
// execution path until a later phase builds that dispatcher. Its exact
// signature below (context.Context, sdk.RunbookContext, map[string]any) is
// this generator's own reasonable placeholder, not an established
// contract: no phase before this one defines what Go function shape a
// Collection method's real implementation must have.
//
// Because this package lives under internal/, it is reachable only from
// code inside this module or a fork of it: Go's internal/ visibility rule
// blocks any other module from importing it at all. This generator is
// repo-contributor tooling, not end-user extensibility; a third-party
// Collection arriving from outside this binary needs a separate,
// not-yet-built distribution mechanism (Part X's OCI distribution work),
// not this one.
package {{.PackageName}}

import (
	"context"
	"fmt"

	"github.com/SubjectVoidLLC/the-pleiades/pkg/capability"
	"github.com/SubjectVoidLLC/the-pleiades/pkg/collection"
	"github.com/SubjectVoidLLC/the-pleiades/pkg/inventory"
	"github.com/SubjectVoidLLC/the-pleiades/pkg/sdk"
)

func init() {
	collection.MustRegister(collection.Descriptor{
		Name: {{quote .Name}},
		Manifest: collection.Manifest{
			SupportedTransports: []string{
{{range .Transports}}				{{quote .}},
{{end}}			},
			RequiredCapabilities: []capability.Name{
{{range .Capabilities}}				capability.Name({{quote .}}),
{{end}}			},
			ExecutionContext: collection.ExecutionContext{
				RequiresElevation: {{.RequiresElevation}},
			},
			// TODO(forge): PlatformTargets narrows this manifest to a
			// specific vendor, model, firmware range, or deployment
			// context (pkg/collection.PlatformTarget). Left nil: thin
			// flag parsing only, per Phase 33's own checklist. Add real
			// entries by hand once this method's platform scope is known.
			PlatformTargets: nil,
			EngineVersion:   {{quote .EngineVersion}},
			Status:          collection.StatusDeclared,
		},
	})
}

// {{.FunctionName}} implements the "{{.Name}}" collection method.
//
// TODO(forge): not implemented. Returns an explicit error, never success:
// a stub that reports success is worse than a method that does not exist,
// because it makes a failed runbook look like a successful one. See this
// package's own doc comment for the signature's provisional status and
// the reachability gap.
func {{.FunctionName}}(ctx context.Context, rc sdk.RunbookContext, device inventory.InventoryItem, params map[string]any) (collection.Result, error) {
	return collection.Result{}, fmt.Errorf("{{.Name}}: not implemented")
}
`

// collectionTestTemplateSource is the starter table-driven test template.
// It proves the init()-time registration succeeded (collection.Lookup
// finds the name, with the Manifest fields this generator was given) and
// that the stub itself returns the required explicit not-implemented
// error rather than success.
const collectionTestTemplateSource = `package {{.PackageName}}_test

import (
	"context"
	"strings"
	"testing"

	"github.com/SubjectVoidLLC/the-pleiades/internal/catalog/{{.PackagePath}}"
	"github.com/SubjectVoidLLC/the-pleiades/pkg/collection"
)

// Test{{.FunctionName}}_Registered is a starter test, generated by
// pleiades forge new-collection: it proves "{{.Name}}" registered itself
// through this package's own init(), with the manifest fields given at
// generation time.
func Test{{.FunctionName}}_Registered(t *testing.T) {
	d, ok := collection.Lookup({{quote .Name}})
	if !ok {
		t.Fatalf("collection.Lookup(%q) found nothing; did this package's init() run?", {{quote .Name}})
	}
	if d.Manifest.Status != collection.StatusDeclared {
		t.Errorf("Manifest.Status = %v, want %v", d.Manifest.Status, collection.StatusDeclared)
	}
	if d.Manifest.ExecutionContext.RequiresElevation != {{.RequiresElevation}} {
		t.Errorf("Manifest.ExecutionContext.RequiresElevation = %v, want %v",
			d.Manifest.ExecutionContext.RequiresElevation, {{.RequiresElevation}})
	}
}

// Test{{.FunctionName}}_NotImplemented is a starter, table-driven proof of
// the "declared is not implemented" guardrail: the stub must return an
// explicit error, never success. Replace this table as real parameter
// cases are added once {{.FunctionName}} is actually implemented.
func Test{{.FunctionName}}_NotImplemented(t *testing.T) {
	tests := []struct {
		name   string
		params map[string]any
	}{
		{name: "no params", params: nil},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			_, err := {{.PackageName}}.{{.FunctionName}}(context.Background(), nil, nil, tt.params)
			if err == nil {
				t.Fatal("expected an explicit not-implemented error, got nil")
			}
			if !strings.Contains(err.Error(), "not implemented") {
				t.Errorf("error = %q, want it to mention \"not implemented\"", err.Error())
			}
		})
	}
}
`
