// Package facts implements the "facts.gather" namespaced Collection
// method. Generated by pleiades forge new-collection
// (internal/forge/collectionscaffold).
//
// This package's init registers "facts.gather" into the shared pkg/collection
// registry via collection.MustRegister. That registry is more than
// planning-time metadata: a runbook task naming "facts.gather" reaches
// engine.NewCollectionActionExecutor's real dispatch path
// (cmd/pleiades/run.go), which looks this Manifest's Status up and
// refuses with its own "declared but not implemented" error before ever
// calling Gather below: a declared stub is never invoked, by
// design, not because nothing reaches it. Gather's own
// "not implemented" return only ever executes if something calls it
// directly (a test does exactly this) or once a later change sets
// Invoke to it and flips Status to StatusImplemented, at which point the
// dispatcher's short-circuit no longer applies and this becomes the
// method's real body. Its signature below (context.Context,
// sdk.RunbookContext, inventory.InventoryItem, map[string]any) is not a
// placeholder: it matches collection.Method exactly, the established
// contract every real implementation must satisfy.
//
// Because this package lives under internal/, it is reachable only from
// code inside this module or a fork of it: Go's internal/ visibility rule
// blocks any other module from importing it at all. This generator is
// repo-contributor tooling, not end-user extensibility; a third-party
// Collection arriving from outside this binary needs a separate,
// not-yet-built distribution mechanism (Part X's OCI distribution work),
// not this one.
package facts

import (
	"context"
	"fmt"

	"github.com/SubjectVoidLLC/the-pleiades/pkg/capability"
	"github.com/SubjectVoidLLC/the-pleiades/pkg/collection"
	"github.com/SubjectVoidLLC/the-pleiades/pkg/inventory"
	"github.com/SubjectVoidLLC/the-pleiades/pkg/sdk"
)

func init() {
	collection.MustRegister(collection.Descriptor{
		Name: "facts.gather",
		Manifest: collection.Manifest{
			SupportedTransports: []string{
				"ssh",
			},
			RequiredCapabilities: []capability.Name{
				capability.Name("FactGathererCapable"),
			},
			ExecutionContext: collection.ExecutionContext{
				RequiresElevation: false,
			},
			// TODO(forge): PlatformTargets narrows this manifest to a
			// specific vendor, model, firmware range, or deployment
			// context (pkg/collection.PlatformTarget). Left nil: thin
			// flag parsing only, per Phase 33's own checklist. Add real
			// entries by hand once this method's platform scope is known.
			PlatformTargets: nil,
			EngineVersion:   ">=1.0.0",
			Status:          collection.StatusDeclared,
			Doc: collection.Doc{
				Summary: "Gathers baseline system facts from the target (OS, kernel, distribution).",
			},
		},
	})
}

// Gather implements the "facts.gather" collection method.
//
// TODO(forge): not implemented. Returns an explicit error, never success:
// a stub that reports success is worse than a method that does not
// exist, because it makes a failed runbook look like a successful one.
// A runbook task naming this FQCN never actually reaches this function
// today; see this package's own doc comment for exactly why and what
// changes that.
func Gather(ctx context.Context, rc sdk.RunbookContext, device inventory.InventoryItem, params map[string]any) (collection.Result, error) {
	return collection.Result{}, fmt.Errorf("facts.gather: not implemented")
}
