// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Subject-Void-LLC/the-pleiades/internal/ent/controllerinstance"
)

// ControllerInstanceCreate is the builder for creating a ControllerInstance entity.
type ControllerInstanceCreate struct {
	config
	mutation *ControllerInstanceMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *ControllerInstanceCreate) SetCreatedAt(v time.Time) *ControllerInstanceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ControllerInstanceCreate) SetNillableCreatedAt(v *time.Time) *ControllerInstanceCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ControllerInstanceCreate) SetUpdatedAt(v time.Time) *ControllerInstanceCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ControllerInstanceCreate) SetNillableUpdatedAt(v *time.Time) *ControllerInstanceCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetInstanceID sets the "instance_id" field.
func (_c *ControllerInstanceCreate) SetInstanceID(v string) *ControllerInstanceCreate {
	_c.mutation.SetInstanceID(v)
	return _c
}

// SetVersion sets the "version" field.
func (_c *ControllerInstanceCreate) SetVersion(v string) *ControllerInstanceCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetMigrationHead sets the "migration_head" field.
func (_c *ControllerInstanceCreate) SetMigrationHead(v string) *ControllerInstanceCreate {
	_c.mutation.SetMigrationHead(v)
	return _c
}

// SetHost sets the "host" field.
func (_c *ControllerInstanceCreate) SetHost(v string) *ControllerInstanceCreate {
	_c.mutation.SetHost(v)
	return _c
}

// SetNillableHost sets the "host" field if the given value is not nil.
func (_c *ControllerInstanceCreate) SetNillableHost(v *string) *ControllerInstanceCreate {
	if v != nil {
		_c.SetHost(*v)
	}
	return _c
}

// SetStartedUnix sets the "started_unix" field.
func (_c *ControllerInstanceCreate) SetStartedUnix(v int64) *ControllerInstanceCreate {
	_c.mutation.SetStartedUnix(v)
	return _c
}

// SetLastSeenUnix sets the "last_seen_unix" field.
func (_c *ControllerInstanceCreate) SetLastSeenUnix(v int64) *ControllerInstanceCreate {
	_c.mutation.SetLastSeenUnix(v)
	return _c
}

// Mutation returns the ControllerInstanceMutation object of the builder.
func (_c *ControllerInstanceCreate) Mutation() *ControllerInstanceMutation {
	return _c.mutation
}

// Save creates the ControllerInstance in the database.
func (_c *ControllerInstanceCreate) Save(ctx context.Context) (*ControllerInstance, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ControllerInstanceCreate) SaveX(ctx context.Context) *ControllerInstance {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ControllerInstanceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ControllerInstanceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ControllerInstanceCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := controllerinstance.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := controllerinstance.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Host(); !ok {
		v := controllerinstance.DefaultHost
		_c.mutation.SetHost(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ControllerInstanceCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ControllerInstance.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ControllerInstance.updated_at"`)}
	}
	if _, ok := _c.mutation.InstanceID(); !ok {
		return &ValidationError{Name: "instance_id", err: errors.New(`ent: missing required field "ControllerInstance.instance_id"`)}
	}
	if v, ok := _c.mutation.InstanceID(); ok {
		if err := controllerinstance.InstanceIDValidator(v); err != nil {
			return &ValidationError{Name: "instance_id", err: fmt.Errorf(`ent: validator failed for field "ControllerInstance.instance_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "ControllerInstance.version"`)}
	}
	if v, ok := _c.mutation.Version(); ok {
		if err := controllerinstance.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "ControllerInstance.version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MigrationHead(); !ok {
		return &ValidationError{Name: "migration_head", err: errors.New(`ent: missing required field "ControllerInstance.migration_head"`)}
	}
	if v, ok := _c.mutation.MigrationHead(); ok {
		if err := controllerinstance.MigrationHeadValidator(v); err != nil {
			return &ValidationError{Name: "migration_head", err: fmt.Errorf(`ent: validator failed for field "ControllerInstance.migration_head": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Host(); !ok {
		return &ValidationError{Name: "host", err: errors.New(`ent: missing required field "ControllerInstance.host"`)}
	}
	if v, ok := _c.mutation.Host(); ok {
		if err := controllerinstance.HostValidator(v); err != nil {
			return &ValidationError{Name: "host", err: fmt.Errorf(`ent: validator failed for field "ControllerInstance.host": %w`, err)}
		}
	}
	if _, ok := _c.mutation.StartedUnix(); !ok {
		return &ValidationError{Name: "started_unix", err: errors.New(`ent: missing required field "ControllerInstance.started_unix"`)}
	}
	if _, ok := _c.mutation.LastSeenUnix(); !ok {
		return &ValidationError{Name: "last_seen_unix", err: errors.New(`ent: missing required field "ControllerInstance.last_seen_unix"`)}
	}
	return nil
}

func (_c *ControllerInstanceCreate) sqlSave(ctx context.Context) (*ControllerInstance, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ControllerInstanceCreate) createSpec() (*ControllerInstance, *sqlgraph.CreateSpec) {
	var (
		_node = &ControllerInstance{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(controllerinstance.Table, sqlgraph.NewFieldSpec(controllerinstance.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(controllerinstance.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(controllerinstance.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.InstanceID(); ok {
		_spec.SetField(controllerinstance.FieldInstanceID, field.TypeString, value)
		_node.InstanceID = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(controllerinstance.FieldVersion, field.TypeString, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.MigrationHead(); ok {
		_spec.SetField(controllerinstance.FieldMigrationHead, field.TypeString, value)
		_node.MigrationHead = value
	}
	if value, ok := _c.mutation.Host(); ok {
		_spec.SetField(controllerinstance.FieldHost, field.TypeString, value)
		_node.Host = value
	}
	if value, ok := _c.mutation.StartedUnix(); ok {
		_spec.SetField(controllerinstance.FieldStartedUnix, field.TypeInt64, value)
		_node.StartedUnix = value
	}
	if value, ok := _c.mutation.LastSeenUnix(); ok {
		_spec.SetField(controllerinstance.FieldLastSeenUnix, field.TypeInt64, value)
		_node.LastSeenUnix = value
	}
	return _node, _spec
}

// ControllerInstanceCreateBulk is the builder for creating many ControllerInstance entities in bulk.
type ControllerInstanceCreateBulk struct {
	config
	err      error
	builders []*ControllerInstanceCreate
}

// Save creates the ControllerInstance entities in the database.
func (_c *ControllerInstanceCreateBulk) Save(ctx context.Context) ([]*ControllerInstance, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ControllerInstance, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ControllerInstanceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ControllerInstanceCreateBulk) SaveX(ctx context.Context) []*ControllerInstance {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ControllerInstanceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ControllerInstanceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
