// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Subject-Void-LLC/the-pleiades/internal/ent/journalentry"
)

// JournalEntry is the model entity for the JournalEntry schema.
type JournalEntry struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// JobID holds the value of the "job_id" field.
	JobID string `json:"job_id,omitempty"`
	// DeviceID holds the value of the "device_id" field.
	DeviceID string `json:"device_id,omitempty"`
	// Attempt holds the value of the "attempt" field.
	Attempt int `json:"attempt,omitempty"`
	// NodeID holds the value of the "node_id" field.
	NodeID string `json:"node_id,omitempty"`
	// RunID holds the value of the "run_id" field.
	RunID string `json:"run_id,omitempty"`
	// Sequence holds the value of the "sequence" field.
	Sequence int `json:"sequence,omitempty"`
	// DagID holds the value of the "dag_id" field.
	DagID string `json:"dag_id,omitempty"`
	// DagVersion holds the value of the "dag_version" field.
	DagVersion string `json:"dag_version,omitempty"`
	// Fqcn holds the value of the "fqcn" field.
	Fqcn string `json:"fqcn,omitempty"`
	// FqcnUnresolved holds the value of the "fqcn_unresolved" field.
	FqcnUnresolved bool `json:"fqcn_unresolved,omitempty"`
	// ProviderProgram holds the value of the "provider_program" field.
	ProviderProgram string `json:"provider_program,omitempty"`
	// ProviderDigest holds the value of the "provider_digest" field.
	ProviderDigest string `json:"provider_digest,omitempty"`
	// TaskName holds the value of the "task_name" field.
	TaskName string `json:"task_name,omitempty"`
	// Register holds the value of the "register" field.
	Register string `json:"register,omitempty"`
	// StartedAt holds the value of the "started_at" field.
	StartedAt time.Time `json:"started_at,omitempty"`
	// FinishedAt holds the value of the "finished_at" field.
	FinishedAt time.Time `json:"finished_at,omitempty"`
	// Outcome holds the value of the "outcome" field.
	Outcome journalentry.Outcome `json:"outcome,omitempty"`
	// FailureStage holds the value of the "failure_stage" field.
	FailureStage string `json:"failure_stage,omitempty"`
	// SkipKind holds the value of the "skip_kind" field.
	SkipKind string `json:"skip_kind,omitempty"`
	// SkipOrdinal holds the value of the "skip_ordinal" field.
	SkipOrdinal int `json:"skip_ordinal,omitempty"`
	// SkipTotal holds the value of the "skip_total" field.
	SkipTotal int `json:"skip_total,omitempty"`
	// StatKeys holds the value of the "stat_keys" field.
	StatKeys []string `json:"stat_keys,omitempty"`
	// UndeclaredStatCount holds the value of the "undeclared_stat_count" field.
	UndeclaredStatCount int `json:"undeclared_stat_count,omitempty"`
	// ParamKeys holds the value of the "param_keys" field.
	ParamKeys []string `json:"param_keys,omitempty"`
	// UndeclaredParamCount holds the value of the "undeclared_param_count" field.
	UndeclaredParamCount int `json:"undeclared_param_count,omitempty"`
	// InverseFqcn holds the value of the "inverse_fqcn" field.
	InverseFqcn string `json:"inverse_fqcn,omitempty"`
	// InverseFqcnUnresolved holds the value of the "inverse_fqcn_unresolved" field.
	InverseFqcnUnresolved bool `json:"inverse_fqcn_unresolved,omitempty"`
	// InverseParamKeys holds the value of the "inverse_param_keys" field.
	InverseParamKeys []string `json:"inverse_param_keys,omitempty"`
	// UndeclaredInverseParamCount holds the value of the "undeclared_inverse_param_count" field.
	UndeclaredInverseParamCount int `json:"undeclared_inverse_param_count,omitempty"`
	// DiffRecorded holds the value of the "diff_recorded" field.
	DiffRecorded bool `json:"diff_recorded,omitempty"`
	// InverseParams holds the value of the "inverse_params" field.
	InverseParams json.RawMessage `json:"inverse_params,omitempty"`
	// InverseComplete holds the value of the "inverse_complete" field.
	InverseComplete bool `json:"inverse_complete,omitempty"`
	// InversePartial holds the value of the "inverse_partial" field.
	InversePartial bool `json:"inverse_partial,omitempty"`
	// ActionChanged holds the value of the "action_changed" field.
	ActionChanged bool `json:"action_changed,omitempty"`
	// AuthoredRollback holds the value of the "authored_rollback" field.
	AuthoredRollback bool `json:"authored_rollback,omitempty"`
	// RollbackOf holds the value of the "rollback_of" field.
	RollbackOf string `json:"rollback_of,omitempty"`
	// UndoesNode holds the value of the "undoes_node" field.
	UndoesNode string `json:"undoes_node,omitempty"`
	// UndoesStep holds the value of the "undoes_step" field.
	UndoesStep   int `json:"undoes_step,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*JournalEntry) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case journalentry.FieldStatKeys, journalentry.FieldParamKeys, journalentry.FieldInverseParamKeys, journalentry.FieldInverseParams:
			values[i] = new([]byte)
		case journalentry.FieldFqcnUnresolved, journalentry.FieldInverseFqcnUnresolved, journalentry.FieldDiffRecorded, journalentry.FieldInverseComplete, journalentry.FieldInversePartial, journalentry.FieldActionChanged, journalentry.FieldAuthoredRollback:
			values[i] = new(sql.NullBool)
		case journalentry.FieldID, journalentry.FieldAttempt, journalentry.FieldSequence, journalentry.FieldSkipOrdinal, journalentry.FieldSkipTotal, journalentry.FieldUndeclaredStatCount, journalentry.FieldUndeclaredParamCount, journalentry.FieldUndeclaredInverseParamCount, journalentry.FieldUndoesStep:
			values[i] = new(sql.NullInt64)
		case journalentry.FieldJobID, journalentry.FieldDeviceID, journalentry.FieldNodeID, journalentry.FieldRunID, journalentry.FieldDagID, journalentry.FieldDagVersion, journalentry.FieldFqcn, journalentry.FieldProviderProgram, journalentry.FieldProviderDigest, journalentry.FieldTaskName, journalentry.FieldRegister, journalentry.FieldOutcome, journalentry.FieldFailureStage, journalentry.FieldSkipKind, journalentry.FieldInverseFqcn, journalentry.FieldRollbackOf, journalentry.FieldUndoesNode:
			values[i] = new(sql.NullString)
		case journalentry.FieldCreatedAt, journalentry.FieldUpdatedAt, journalentry.FieldStartedAt, journalentry.FieldFinishedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the JournalEntry fields.
func (_m *JournalEntry) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case journalentry.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case journalentry.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case journalentry.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case journalentry.FieldJobID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field job_id", values[i])
			} else if value.Valid {
				_m.JobID = value.String
			}
		case journalentry.FieldDeviceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field device_id", values[i])
			} else if value.Valid {
				_m.DeviceID = value.String
			}
		case journalentry.FieldAttempt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field attempt", values[i])
			} else if value.Valid {
				_m.Attempt = int(value.Int64)
			}
		case journalentry.FieldNodeID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field node_id", values[i])
			} else if value.Valid {
				_m.NodeID = value.String
			}
		case journalentry.FieldRunID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field run_id", values[i])
			} else if value.Valid {
				_m.RunID = value.String
			}
		case journalentry.FieldSequence:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sequence", values[i])
			} else if value.Valid {
				_m.Sequence = int(value.Int64)
			}
		case journalentry.FieldDagID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field dag_id", values[i])
			} else if value.Valid {
				_m.DagID = value.String
			}
		case journalentry.FieldDagVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field dag_version", values[i])
			} else if value.Valid {
				_m.DagVersion = value.String
			}
		case journalentry.FieldFqcn:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field fqcn", values[i])
			} else if value.Valid {
				_m.Fqcn = value.String
			}
		case journalentry.FieldFqcnUnresolved:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field fqcn_unresolved", values[i])
			} else if value.Valid {
				_m.FqcnUnresolved = value.Bool
			}
		case journalentry.FieldProviderProgram:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_program", values[i])
			} else if value.Valid {
				_m.ProviderProgram = value.String
			}
		case journalentry.FieldProviderDigest:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_digest", values[i])
			} else if value.Valid {
				_m.ProviderDigest = value.String
			}
		case journalentry.FieldTaskName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field task_name", values[i])
			} else if value.Valid {
				_m.TaskName = value.String
			}
		case journalentry.FieldRegister:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field register", values[i])
			} else if value.Valid {
				_m.Register = value.String
			}
		case journalentry.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = value.Time
			}
		case journalentry.FieldFinishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field finished_at", values[i])
			} else if value.Valid {
				_m.FinishedAt = value.Time
			}
		case journalentry.FieldOutcome:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field outcome", values[i])
			} else if value.Valid {
				_m.Outcome = journalentry.Outcome(value.String)
			}
		case journalentry.FieldFailureStage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field failure_stage", values[i])
			} else if value.Valid {
				_m.FailureStage = value.String
			}
		case journalentry.FieldSkipKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field skip_kind", values[i])
			} else if value.Valid {
				_m.SkipKind = value.String
			}
		case journalentry.FieldSkipOrdinal:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field skip_ordinal", values[i])
			} else if value.Valid {
				_m.SkipOrdinal = int(value.Int64)
			}
		case journalentry.FieldSkipTotal:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field skip_total", values[i])
			} else if value.Valid {
				_m.SkipTotal = int(value.Int64)
			}
		case journalentry.FieldStatKeys:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field stat_keys", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.StatKeys); err != nil {
					return fmt.Errorf("unmarshal field stat_keys: %w", err)
				}
			}
		case journalentry.FieldUndeclaredStatCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field undeclared_stat_count", values[i])
			} else if value.Valid {
				_m.UndeclaredStatCount = int(value.Int64)
			}
		case journalentry.FieldParamKeys:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field param_keys", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ParamKeys); err != nil {
					return fmt.Errorf("unmarshal field param_keys: %w", err)
				}
			}
		case journalentry.FieldUndeclaredParamCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field undeclared_param_count", values[i])
			} else if value.Valid {
				_m.UndeclaredParamCount = int(value.Int64)
			}
		case journalentry.FieldInverseFqcn:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field inverse_fqcn", values[i])
			} else if value.Valid {
				_m.InverseFqcn = value.String
			}
		case journalentry.FieldInverseFqcnUnresolved:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field inverse_fqcn_unresolved", values[i])
			} else if value.Valid {
				_m.InverseFqcnUnresolved = value.Bool
			}
		case journalentry.FieldInverseParamKeys:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field inverse_param_keys", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.InverseParamKeys); err != nil {
					return fmt.Errorf("unmarshal field inverse_param_keys: %w", err)
				}
			}
		case journalentry.FieldUndeclaredInverseParamCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field undeclared_inverse_param_count", values[i])
			} else if value.Valid {
				_m.UndeclaredInverseParamCount = int(value.Int64)
			}
		case journalentry.FieldDiffRecorded:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field diff_recorded", values[i])
			} else if value.Valid {
				_m.DiffRecorded = value.Bool
			}
		case journalentry.FieldInverseParams:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field inverse_params", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.InverseParams); err != nil {
					return fmt.Errorf("unmarshal field inverse_params: %w", err)
				}
			}
		case journalentry.FieldInverseComplete:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field inverse_complete", values[i])
			} else if value.Valid {
				_m.InverseComplete = value.Bool
			}
		case journalentry.FieldInversePartial:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field inverse_partial", values[i])
			} else if value.Valid {
				_m.InversePartial = value.Bool
			}
		case journalentry.FieldActionChanged:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field action_changed", values[i])
			} else if value.Valid {
				_m.ActionChanged = value.Bool
			}
		case journalentry.FieldAuthoredRollback:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field authored_rollback", values[i])
			} else if value.Valid {
				_m.AuthoredRollback = value.Bool
			}
		case journalentry.FieldRollbackOf:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field rollback_of", values[i])
			} else if value.Valid {
				_m.RollbackOf = value.String
			}
		case journalentry.FieldUndoesNode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field undoes_node", values[i])
			} else if value.Valid {
				_m.UndoesNode = value.String
			}
		case journalentry.FieldUndoesStep:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field undoes_step", values[i])
			} else if value.Valid {
				_m.UndoesStep = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the JournalEntry.
// This includes values selected through modifiers, order, etc.
func (_m *JournalEntry) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this JournalEntry.
// Note that you need to call JournalEntry.Unwrap() before calling this method if this JournalEntry
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *JournalEntry) Update() *JournalEntryUpdateOne {
	return NewJournalEntryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the JournalEntry entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *JournalEntry) Unwrap() *JournalEntry {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: JournalEntry is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *JournalEntry) String() string {
	var builder strings.Builder
	builder.WriteString("JournalEntry(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("job_id=")
	builder.WriteString(_m.JobID)
	builder.WriteString(", ")
	builder.WriteString("device_id=")
	builder.WriteString(_m.DeviceID)
	builder.WriteString(", ")
	builder.WriteString("attempt=")
	builder.WriteString(fmt.Sprintf("%v", _m.Attempt))
	builder.WriteString(", ")
	builder.WriteString("node_id=")
	builder.WriteString(_m.NodeID)
	builder.WriteString(", ")
	builder.WriteString("run_id=")
	builder.WriteString(_m.RunID)
	builder.WriteString(", ")
	builder.WriteString("sequence=")
	builder.WriteString(fmt.Sprintf("%v", _m.Sequence))
	builder.WriteString(", ")
	builder.WriteString("dag_id=")
	builder.WriteString(_m.DagID)
	builder.WriteString(", ")
	builder.WriteString("dag_version=")
	builder.WriteString(_m.DagVersion)
	builder.WriteString(", ")
	builder.WriteString("fqcn=")
	builder.WriteString(_m.Fqcn)
	builder.WriteString(", ")
	builder.WriteString("fqcn_unresolved=")
	builder.WriteString(fmt.Sprintf("%v", _m.FqcnUnresolved))
	builder.WriteString(", ")
	builder.WriteString("provider_program=")
	builder.WriteString(_m.ProviderProgram)
	builder.WriteString(", ")
	builder.WriteString("provider_digest=")
	builder.WriteString(_m.ProviderDigest)
	builder.WriteString(", ")
	builder.WriteString("task_name=")
	builder.WriteString(_m.TaskName)
	builder.WriteString(", ")
	builder.WriteString("register=")
	builder.WriteString(_m.Register)
	builder.WriteString(", ")
	builder.WriteString("started_at=")
	builder.WriteString(_m.StartedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("finished_at=")
	builder.WriteString(_m.FinishedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("outcome=")
	builder.WriteString(fmt.Sprintf("%v", _m.Outcome))
	builder.WriteString(", ")
	builder.WriteString("failure_stage=")
	builder.WriteString(_m.FailureStage)
	builder.WriteString(", ")
	builder.WriteString("skip_kind=")
	builder.WriteString(_m.SkipKind)
	builder.WriteString(", ")
	builder.WriteString("skip_ordinal=")
	builder.WriteString(fmt.Sprintf("%v", _m.SkipOrdinal))
	builder.WriteString(", ")
	builder.WriteString("skip_total=")
	builder.WriteString(fmt.Sprintf("%v", _m.SkipTotal))
	builder.WriteString(", ")
	builder.WriteString("stat_keys=")
	builder.WriteString(fmt.Sprintf("%v", _m.StatKeys))
	builder.WriteString(", ")
	builder.WriteString("undeclared_stat_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.UndeclaredStatCount))
	builder.WriteString(", ")
	builder.WriteString("param_keys=")
	builder.WriteString(fmt.Sprintf("%v", _m.ParamKeys))
	builder.WriteString(", ")
	builder.WriteString("undeclared_param_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.UndeclaredParamCount))
	builder.WriteString(", ")
	builder.WriteString("inverse_fqcn=")
	builder.WriteString(_m.InverseFqcn)
	builder.WriteString(", ")
	builder.WriteString("inverse_fqcn_unresolved=")
	builder.WriteString(fmt.Sprintf("%v", _m.InverseFqcnUnresolved))
	builder.WriteString(", ")
	builder.WriteString("inverse_param_keys=")
	builder.WriteString(fmt.Sprintf("%v", _m.InverseParamKeys))
	builder.WriteString(", ")
	builder.WriteString("undeclared_inverse_param_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.UndeclaredInverseParamCount))
	builder.WriteString(", ")
	builder.WriteString("diff_recorded=")
	builder.WriteString(fmt.Sprintf("%v", _m.DiffRecorded))
	builder.WriteString(", ")
	builder.WriteString("inverse_params=")
	builder.WriteString(fmt.Sprintf("%v", _m.InverseParams))
	builder.WriteString(", ")
	builder.WriteString("inverse_complete=")
	builder.WriteString(fmt.Sprintf("%v", _m.InverseComplete))
	builder.WriteString(", ")
	builder.WriteString("inverse_partial=")
	builder.WriteString(fmt.Sprintf("%v", _m.InversePartial))
	builder.WriteString(", ")
	builder.WriteString("action_changed=")
	builder.WriteString(fmt.Sprintf("%v", _m.ActionChanged))
	builder.WriteString(", ")
	builder.WriteString("authored_rollback=")
	builder.WriteString(fmt.Sprintf("%v", _m.AuthoredRollback))
	builder.WriteString(", ")
	builder.WriteString("rollback_of=")
	builder.WriteString(_m.RollbackOf)
	builder.WriteString(", ")
	builder.WriteString("undoes_node=")
	builder.WriteString(_m.UndoesNode)
	builder.WriteString(", ")
	builder.WriteString("undoes_step=")
	builder.WriteString(fmt.Sprintf("%v", _m.UndoesStep))
	builder.WriteByte(')')
	return builder.String()
}

// JournalEntries is a parsable slice of JournalEntry.
type JournalEntries []*JournalEntry
