// This file is hand written and is not regenerated by `go generate
// ./internal/ent`: it is the SQLite adapter behind OpenDatabase, and the only
// place SQLite's own DSN pragmas and on-disk layout are known.
package ent

import (
	"fmt"
	"net/url"
	"os"
	"path/filepath"

	"entgo.io/ent/dialect"

	// Registers the "sqlite3" database/sql driver this adapter names.
	// Every existing test reaches the SQLite path only through a _test.go
	// file that imports this driver itself, so this gap was invisible
	// until archtest's adapter-allowlist check asked "does this package
	// actually import a concrete driver" and the honest answer was no:
	// without this import the real binary would fail with "unknown driver
	// \"sqlite3\"" the first time a composition root opened one.
	_ "github.com/mattn/go-sqlite3"
)

// sqliteURLScheme is the explicit scheme selecting the SQLite adapter.
// The path follows it verbatim, so "sqlite://x.db" is the relative file
// x.db and "sqlite:///var/lib/x.db" is that absolute path.
const sqliteURLScheme = "sqlite://"

// embeddedBusyTimeoutMillis is how long a single connection waits on a
// locked database before giving up, in milliseconds. WAL mode (see
// embeddedDSN) already lets any number of readers proceed concurrently
// with the one writer, so contention is rare in an embedded
// single-process deployment; this timeout only matters for the brief
// window two writers overlap, and five seconds is generous enough to
// absorb that without a caller seeing SQLITE_BUSY.
const embeddedBusyTimeoutMillis = 5000

// resolveSQLite builds the resolved DSN for an on-disk SQLite file at
// path, including the directory creation that has to happen before the
// driver can open it.
func resolveSQLite(path string) resolvedDSN {
	return resolvedDSN{
		driver:   dialect.SQLite,
		dsn:      embeddedDSN(path),
		prepare:  func() error { return ensureSQLiteParentDir(path) },
		describe: fmt.Sprintf("%q", path),
	}
}

// ensureSQLiteParentDir creates the directory holding the database file
// if it does not already exist, since a freshly scaffolded project
// directory will not have one yet.
func ensureSQLiteParentDir(path string) error {
	// A bare filename (or the empty string) has no parent directory
	// beyond ".", which always exists, so MkdirAll is only needed, and
	// only meaningful, when Dir names something else.
	dir := filepath.Dir(path)
	if dir == "." {
		return nil
	}
	// 0o750, not 0o755: this directory holds the embedded state database
	// (device inventory, revision history), so it gets the same
	// owner-and-group-only posture as the credential store's directory in
	// internal/credential, not the world-readable default a plain
	// MkdirAll would otherwise leave it at.
	if err := os.MkdirAll(dir, 0o750); err != nil {
		return fmt.Errorf("ent: creating parent directory for embedded database %q: %w", path, err)
	}
	return nil
}

// embeddedDSN builds the mattn/go-sqlite3 data source name for a durable,
// single-process embedded database at path. Parameter names and behavior
// were verified directly against github.com/mattn/go-sqlite3 v1.14.49's
// own source (its Open method's doc comment and query-parameter handling)
// rather than assumed:
//
//   - "_fk=1" enables foreign key constraint enforcement, matching the
//     spelling this codebase already uses in client_test.go and enttest.go.
//   - "_journal_mode=WAL" puts the database in write-ahead-log mode, so
//     readers never block the writer and vice versa. This matters here
//     specifically because an embedded process may hold the client open
//     for the CLI's whole lifetime while issuing many small transactions.
//   - "_busy_timeout" (milliseconds) makes a connection wait, rather than
//     immediately fail with SQLITE_BUSY, on the rare occasion two writers
//     do overlap.
func embeddedDSN(path string) string {
	// The path is percent-escaped through url.URL's path escaping (not
	// url.PathEscape, which also escapes '/' and would place every path
	// separator into the query-string-adjacent part of the DSN). This
	// keeps '/' literal while still escaping characters such as space,
	// '?', and '#' that would otherwise be misread as the start of the
	// DSN's query string or fragment by either go-sqlite3's own DSN
	// splitting or SQLite's own URI-filename grammar. SQLite
	// percent-decodes the path component of a "file:" URI before using
	// it, so the escaped form still resolves to the exact literal path
	// passed in.
	escaped := (&url.URL{Path: path}).EscapedPath()
	return fmt.Sprintf("file:%s?_fk=1&_journal_mode=WAL&_busy_timeout=%d", escaped, embeddedBusyTimeoutMillis)
}
