// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Subject-Void-LLC/the-pleiades/internal/ent/predicate"
	"github.com/Subject-Void-LLC/the-pleiades/internal/ent/savedlaunchconfig"
	"github.com/Subject-Void-LLC/the-pleiades/internal/ent/template"
)

// SavedLaunchConfigUpdate is the builder for updating SavedLaunchConfig entities.
type SavedLaunchConfigUpdate struct {
	config
	hooks    []Hook
	mutation *SavedLaunchConfigMutation
}

// Where appends a list predicates to the SavedLaunchConfigUpdate builder.
func (_u *SavedLaunchConfigUpdate) Where(ps ...predicate.SavedLaunchConfig) *SavedLaunchConfigUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SavedLaunchConfigUpdate) SetUpdatedAt(v time.Time) *SavedLaunchConfigUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *SavedLaunchConfigUpdate) SetName(v string) *SavedLaunchConfigUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SavedLaunchConfigUpdate) SetNillableName(v *string) *SavedLaunchConfigUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *SavedLaunchConfigUpdate) ClearName() *SavedLaunchConfigUpdate {
	_u.mutation.ClearName()
	return _u
}

// SetFields sets the "fields" field.
func (_u *SavedLaunchConfigUpdate) SetFields(v map[string]interface{}) *SavedLaunchConfigUpdate {
	_u.mutation.SetFields(v)
	return _u
}

// ClearFields clears the value of the "fields" field.
func (_u *SavedLaunchConfigUpdate) ClearFields() *SavedLaunchConfigUpdate {
	_u.mutation.ClearFields()
	return _u
}

// SetAnswers sets the "answers" field.
func (_u *SavedLaunchConfigUpdate) SetAnswers(v map[string]interface{}) *SavedLaunchConfigUpdate {
	_u.mutation.SetAnswers(v)
	return _u
}

// ClearAnswers clears the value of the "answers" field.
func (_u *SavedLaunchConfigUpdate) ClearAnswers() *SavedLaunchConfigUpdate {
	_u.mutation.ClearAnswers()
	return _u
}

// SetSecretBinding sets the "secret_binding" field.
func (_u *SavedLaunchConfigUpdate) SetSecretBinding(v string) *SavedLaunchConfigUpdate {
	_u.mutation.SetSecretBinding(v)
	return _u
}

// SetNillableSecretBinding sets the "secret_binding" field if the given value is not nil.
func (_u *SavedLaunchConfigUpdate) SetNillableSecretBinding(v *string) *SavedLaunchConfigUpdate {
	if v != nil {
		_u.SetSecretBinding(*v)
	}
	return _u
}

// ClearSecretBinding clears the value of the "secret_binding" field.
func (_u *SavedLaunchConfigUpdate) ClearSecretBinding() *SavedLaunchConfigUpdate {
	_u.mutation.ClearSecretBinding()
	return _u
}

// SetTemplateID sets the "template" edge to the Template entity by ID.
func (_u *SavedLaunchConfigUpdate) SetTemplateID(id int) *SavedLaunchConfigUpdate {
	_u.mutation.SetTemplateID(id)
	return _u
}

// SetTemplate sets the "template" edge to the Template entity.
func (_u *SavedLaunchConfigUpdate) SetTemplate(v *Template) *SavedLaunchConfigUpdate {
	return _u.SetTemplateID(v.ID)
}

// Mutation returns the SavedLaunchConfigMutation object of the builder.
func (_u *SavedLaunchConfigUpdate) Mutation() *SavedLaunchConfigMutation {
	return _u.mutation
}

// ClearTemplate clears the "template" edge to the Template entity.
func (_u *SavedLaunchConfigUpdate) ClearTemplate() *SavedLaunchConfigUpdate {
	_u.mutation.ClearTemplate()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SavedLaunchConfigUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SavedLaunchConfigUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SavedLaunchConfigUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SavedLaunchConfigUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SavedLaunchConfigUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := savedlaunchconfig.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SavedLaunchConfigUpdate) check() error {
	if _u.mutation.TemplateCleared() && len(_u.mutation.TemplateIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SavedLaunchConfig.template"`)
	}
	return nil
}

func (_u *SavedLaunchConfigUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(savedlaunchconfig.Table, savedlaunchconfig.Columns, sqlgraph.NewFieldSpec(savedlaunchconfig.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(savedlaunchconfig.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(savedlaunchconfig.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(savedlaunchconfig.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.GetFields(); ok {
		_spec.SetField(savedlaunchconfig.FieldFields, field.TypeJSON, value)
	}
	if _u.mutation.FieldsCleared() {
		_spec.ClearField(savedlaunchconfig.FieldFields, field.TypeJSON)
	}
	if value, ok := _u.mutation.Answers(); ok {
		_spec.SetField(savedlaunchconfig.FieldAnswers, field.TypeJSON, value)
	}
	if _u.mutation.AnswersCleared() {
		_spec.ClearField(savedlaunchconfig.FieldAnswers, field.TypeJSON)
	}
	if value, ok := _u.mutation.SecretBinding(); ok {
		_spec.SetField(savedlaunchconfig.FieldSecretBinding, field.TypeString, value)
	}
	if _u.mutation.SecretBindingCleared() {
		_spec.ClearField(savedlaunchconfig.FieldSecretBinding, field.TypeString)
	}
	if _u.mutation.TemplateCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   savedlaunchconfig.TemplateTable,
			Columns: []string{savedlaunchconfig.TemplateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(template.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TemplateIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   savedlaunchconfig.TemplateTable,
			Columns: []string{savedlaunchconfig.TemplateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(template.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{savedlaunchconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SavedLaunchConfigUpdateOne is the builder for updating a single SavedLaunchConfig entity.
type SavedLaunchConfigUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SavedLaunchConfigMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SavedLaunchConfigUpdateOne) SetUpdatedAt(v time.Time) *SavedLaunchConfigUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *SavedLaunchConfigUpdateOne) SetName(v string) *SavedLaunchConfigUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SavedLaunchConfigUpdateOne) SetNillableName(v *string) *SavedLaunchConfigUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *SavedLaunchConfigUpdateOne) ClearName() *SavedLaunchConfigUpdateOne {
	_u.mutation.ClearName()
	return _u
}

// SetFields sets the "fields" field.
func (_u *SavedLaunchConfigUpdateOne) SetFields(v map[string]interface{}) *SavedLaunchConfigUpdateOne {
	_u.mutation.SetFields(v)
	return _u
}

// ClearFields clears the value of the "fields" field.
func (_u *SavedLaunchConfigUpdateOne) ClearFields() *SavedLaunchConfigUpdateOne {
	_u.mutation.ClearFields()
	return _u
}

// SetAnswers sets the "answers" field.
func (_u *SavedLaunchConfigUpdateOne) SetAnswers(v map[string]interface{}) *SavedLaunchConfigUpdateOne {
	_u.mutation.SetAnswers(v)
	return _u
}

// ClearAnswers clears the value of the "answers" field.
func (_u *SavedLaunchConfigUpdateOne) ClearAnswers() *SavedLaunchConfigUpdateOne {
	_u.mutation.ClearAnswers()
	return _u
}

// SetSecretBinding sets the "secret_binding" field.
func (_u *SavedLaunchConfigUpdateOne) SetSecretBinding(v string) *SavedLaunchConfigUpdateOne {
	_u.mutation.SetSecretBinding(v)
	return _u
}

// SetNillableSecretBinding sets the "secret_binding" field if the given value is not nil.
func (_u *SavedLaunchConfigUpdateOne) SetNillableSecretBinding(v *string) *SavedLaunchConfigUpdateOne {
	if v != nil {
		_u.SetSecretBinding(*v)
	}
	return _u
}

// ClearSecretBinding clears the value of the "secret_binding" field.
func (_u *SavedLaunchConfigUpdateOne) ClearSecretBinding() *SavedLaunchConfigUpdateOne {
	_u.mutation.ClearSecretBinding()
	return _u
}

// SetTemplateID sets the "template" edge to the Template entity by ID.
func (_u *SavedLaunchConfigUpdateOne) SetTemplateID(id int) *SavedLaunchConfigUpdateOne {
	_u.mutation.SetTemplateID(id)
	return _u
}

// SetTemplate sets the "template" edge to the Template entity.
func (_u *SavedLaunchConfigUpdateOne) SetTemplate(v *Template) *SavedLaunchConfigUpdateOne {
	return _u.SetTemplateID(v.ID)
}

// Mutation returns the SavedLaunchConfigMutation object of the builder.
func (_u *SavedLaunchConfigUpdateOne) Mutation() *SavedLaunchConfigMutation {
	return _u.mutation
}

// ClearTemplate clears the "template" edge to the Template entity.
func (_u *SavedLaunchConfigUpdateOne) ClearTemplate() *SavedLaunchConfigUpdateOne {
	_u.mutation.ClearTemplate()
	return _u
}

// Where appends a list predicates to the SavedLaunchConfigUpdate builder.
func (_u *SavedLaunchConfigUpdateOne) Where(ps ...predicate.SavedLaunchConfig) *SavedLaunchConfigUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SavedLaunchConfigUpdateOne) Select(field string, fields ...string) *SavedLaunchConfigUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SavedLaunchConfig entity.
func (_u *SavedLaunchConfigUpdateOne) Save(ctx context.Context) (*SavedLaunchConfig, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SavedLaunchConfigUpdateOne) SaveX(ctx context.Context) *SavedLaunchConfig {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SavedLaunchConfigUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SavedLaunchConfigUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SavedLaunchConfigUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := savedlaunchconfig.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SavedLaunchConfigUpdateOne) check() error {
	if _u.mutation.TemplateCleared() && len(_u.mutation.TemplateIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SavedLaunchConfig.template"`)
	}
	return nil
}

func (_u *SavedLaunchConfigUpdateOne) sqlSave(ctx context.Context) (_node *SavedLaunchConfig, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(savedlaunchconfig.Table, savedlaunchconfig.Columns, sqlgraph.NewFieldSpec(savedlaunchconfig.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SavedLaunchConfig.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, savedlaunchconfig.FieldID)
		for _, f := range fields {
			if !savedlaunchconfig.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != savedlaunchconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(savedlaunchconfig.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(savedlaunchconfig.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(savedlaunchconfig.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.GetFields(); ok {
		_spec.SetField(savedlaunchconfig.FieldFields, field.TypeJSON, value)
	}
	if _u.mutation.FieldsCleared() {
		_spec.ClearField(savedlaunchconfig.FieldFields, field.TypeJSON)
	}
	if value, ok := _u.mutation.Answers(); ok {
		_spec.SetField(savedlaunchconfig.FieldAnswers, field.TypeJSON, value)
	}
	if _u.mutation.AnswersCleared() {
		_spec.ClearField(savedlaunchconfig.FieldAnswers, field.TypeJSON)
	}
	if value, ok := _u.mutation.SecretBinding(); ok {
		_spec.SetField(savedlaunchconfig.FieldSecretBinding, field.TypeString, value)
	}
	if _u.mutation.SecretBindingCleared() {
		_spec.ClearField(savedlaunchconfig.FieldSecretBinding, field.TypeString)
	}
	if _u.mutation.TemplateCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   savedlaunchconfig.TemplateTable,
			Columns: []string{savedlaunchconfig.TemplateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(template.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TemplateIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   savedlaunchconfig.TemplateTable,
			Columns: []string{savedlaunchconfig.TemplateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(template.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SavedLaunchConfig{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{savedlaunchconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
