// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Subject-Void-LLC/the-pleiades/internal/ent/launchable"
	"github.com/Subject-Void-LLC/the-pleiades/internal/ent/organization"
	"github.com/Subject-Void-LLC/the-pleiades/internal/ent/savedlaunchconfig"
	"github.com/Subject-Void-LLC/the-pleiades/internal/ent/schedule"
)

// Schedule is the model entity for the Schedule schema.
type Schedule struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// ScheduleID holds the value of the "schedule_id" field.
	ScheduleID string `json:"schedule_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// Rrule holds the value of the "rrule" field.
	Rrule string `json:"rrule,omitempty"`
	// Exclusions holds the value of the "exclusions" field.
	Exclusions []string `json:"exclusions,omitempty"`
	// Timezone holds the value of the "timezone" field.
	Timezone string `json:"timezone,omitempty"`
	// Dtstart holds the value of the "dtstart" field.
	Dtstart time.Time `json:"dtstart,omitempty"`
	// Dtend holds the value of the "dtend" field.
	Dtend *time.Time `json:"dtend,omitempty"`
	// NextRun holds the value of the "next_run" field.
	NextRun *time.Time `json:"next_run,omitempty"`
	// LastFired holds the value of the "last_fired" field.
	LastFired *time.Time `json:"last_fired,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ScheduleQuery when eager-loading is set.
	Edges                  ScheduleEdges `json:"edges"`
	launchable_schedules   *int
	organization_schedules *int
	schedule_saved_config  *int
	selectValues           sql.SelectValues
}

// ScheduleEdges holds the relations/edges for other nodes in the graph.
type ScheduleEdges struct {
	// Organization holds the value of the organization edge.
	Organization *Organization `json:"organization,omitempty"`
	// Launchable holds the value of the launchable edge.
	Launchable *Launchable `json:"launchable,omitempty"`
	// SavedConfig holds the value of the saved_config edge.
	SavedConfig *SavedLaunchConfig `json:"saved_config,omitempty"`
	// Occurrences holds the value of the occurrences edge.
	Occurrences []*ScheduleOccurrence `json:"occurrences,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// OrganizationOrErr returns the Organization value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ScheduleEdges) OrganizationOrErr() (*Organization, error) {
	if e.Organization != nil {
		return e.Organization, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: organization.Label}
	}
	return nil, &NotLoadedError{edge: "organization"}
}

// LaunchableOrErr returns the Launchable value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ScheduleEdges) LaunchableOrErr() (*Launchable, error) {
	if e.Launchable != nil {
		return e.Launchable, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: launchable.Label}
	}
	return nil, &NotLoadedError{edge: "launchable"}
}

// SavedConfigOrErr returns the SavedConfig value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ScheduleEdges) SavedConfigOrErr() (*SavedLaunchConfig, error) {
	if e.SavedConfig != nil {
		return e.SavedConfig, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: savedlaunchconfig.Label}
	}
	return nil, &NotLoadedError{edge: "saved_config"}
}

// OccurrencesOrErr returns the Occurrences value or an error if the edge
// was not loaded in eager-loading.
func (e ScheduleEdges) OccurrencesOrErr() ([]*ScheduleOccurrence, error) {
	if e.loadedTypes[3] {
		return e.Occurrences, nil
	}
	return nil, &NotLoadedError{edge: "occurrences"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Schedule) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case schedule.FieldExclusions:
			values[i] = new([]byte)
		case schedule.FieldEnabled:
			values[i] = new(sql.NullBool)
		case schedule.FieldID:
			values[i] = new(sql.NullInt64)
		case schedule.FieldScheduleID, schedule.FieldName, schedule.FieldDescription, schedule.FieldRrule, schedule.FieldTimezone:
			values[i] = new(sql.NullString)
		case schedule.FieldCreatedAt, schedule.FieldUpdatedAt, schedule.FieldDtstart, schedule.FieldDtend, schedule.FieldNextRun, schedule.FieldLastFired:
			values[i] = new(sql.NullTime)
		case schedule.ForeignKeys[0]: // launchable_schedules
			values[i] = new(sql.NullInt64)
		case schedule.ForeignKeys[1]: // organization_schedules
			values[i] = new(sql.NullInt64)
		case schedule.ForeignKeys[2]: // schedule_saved_config
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Schedule fields.
func (_m *Schedule) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case schedule.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case schedule.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case schedule.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case schedule.FieldScheduleID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field schedule_id", values[i])
			} else if value.Valid {
				_m.ScheduleID = value.String
			}
		case schedule.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case schedule.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case schedule.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case schedule.FieldRrule:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field rrule", values[i])
			} else if value.Valid {
				_m.Rrule = value.String
			}
		case schedule.FieldExclusions:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field exclusions", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Exclusions); err != nil {
					return fmt.Errorf("unmarshal field exclusions: %w", err)
				}
			}
		case schedule.FieldTimezone:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field timezone", values[i])
			} else if value.Valid {
				_m.Timezone = value.String
			}
		case schedule.FieldDtstart:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field dtstart", values[i])
			} else if value.Valid {
				_m.Dtstart = value.Time
			}
		case schedule.FieldDtend:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field dtend", values[i])
			} else if value.Valid {
				_m.Dtend = new(time.Time)
				*_m.Dtend = value.Time
			}
		case schedule.FieldNextRun:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field next_run", values[i])
			} else if value.Valid {
				_m.NextRun = new(time.Time)
				*_m.NextRun = value.Time
			}
		case schedule.FieldLastFired:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_fired", values[i])
			} else if value.Valid {
				_m.LastFired = new(time.Time)
				*_m.LastFired = value.Time
			}
		case schedule.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field launchable_schedules", value)
			} else if value.Valid {
				_m.launchable_schedules = new(int)
				*_m.launchable_schedules = int(value.Int64)
			}
		case schedule.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field organization_schedules", value)
			} else if value.Valid {
				_m.organization_schedules = new(int)
				*_m.organization_schedules = int(value.Int64)
			}
		case schedule.ForeignKeys[2]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field schedule_saved_config", value)
			} else if value.Valid {
				_m.schedule_saved_config = new(int)
				*_m.schedule_saved_config = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Schedule.
// This includes values selected through modifiers, order, etc.
func (_m *Schedule) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryOrganization queries the "organization" edge of the Schedule entity.
func (_m *Schedule) QueryOrganization() *OrganizationQuery {
	return NewScheduleClient(_m.config).QueryOrganization(_m)
}

// QueryLaunchable queries the "launchable" edge of the Schedule entity.
func (_m *Schedule) QueryLaunchable() *LaunchableQuery {
	return NewScheduleClient(_m.config).QueryLaunchable(_m)
}

// QuerySavedConfig queries the "saved_config" edge of the Schedule entity.
func (_m *Schedule) QuerySavedConfig() *SavedLaunchConfigQuery {
	return NewScheduleClient(_m.config).QuerySavedConfig(_m)
}

// QueryOccurrences queries the "occurrences" edge of the Schedule entity.
func (_m *Schedule) QueryOccurrences() *ScheduleOccurrenceQuery {
	return NewScheduleClient(_m.config).QueryOccurrences(_m)
}

// Update returns a builder for updating this Schedule.
// Note that you need to call Schedule.Unwrap() before calling this method if this Schedule
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Schedule) Update() *ScheduleUpdateOne {
	return NewScheduleClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Schedule entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Schedule) Unwrap() *Schedule {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Schedule is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Schedule) String() string {
	var builder strings.Builder
	builder.WriteString("Schedule(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("schedule_id=")
	builder.WriteString(_m.ScheduleID)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("rrule=")
	builder.WriteString(_m.Rrule)
	builder.WriteString(", ")
	builder.WriteString("exclusions=")
	builder.WriteString(fmt.Sprintf("%v", _m.Exclusions))
	builder.WriteString(", ")
	builder.WriteString("timezone=")
	builder.WriteString(_m.Timezone)
	builder.WriteString(", ")
	builder.WriteString("dtstart=")
	builder.WriteString(_m.Dtstart.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.Dtend; v != nil {
		builder.WriteString("dtend=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.NextRun; v != nil {
		builder.WriteString("next_run=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LastFired; v != nil {
		builder.WriteString("last_fired=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Schedules is a parsable slice of Schedule.
type Schedules []*Schedule
