// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Subject-Void-LLC/the-pleiades/internal/ent/organization"
	"github.com/Subject-Void-LLC/the-pleiades/internal/ent/savedlaunchconfig"
	"github.com/Subject-Void-LLC/the-pleiades/internal/ent/schedule"
	"github.com/Subject-Void-LLC/the-pleiades/internal/ent/scheduleoccurrence"
	"github.com/Subject-Void-LLC/the-pleiades/internal/ent/template"
)

// ScheduleCreate is the builder for creating a Schedule entity.
type ScheduleCreate struct {
	config
	mutation *ScheduleMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *ScheduleCreate) SetCreatedAt(v time.Time) *ScheduleCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ScheduleCreate) SetNillableCreatedAt(v *time.Time) *ScheduleCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ScheduleCreate) SetUpdatedAt(v time.Time) *ScheduleCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ScheduleCreate) SetNillableUpdatedAt(v *time.Time) *ScheduleCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetScheduleID sets the "schedule_id" field.
func (_c *ScheduleCreate) SetScheduleID(v string) *ScheduleCreate {
	_c.mutation.SetScheduleID(v)
	return _c
}

// SetNillableScheduleID sets the "schedule_id" field if the given value is not nil.
func (_c *ScheduleCreate) SetNillableScheduleID(v *string) *ScheduleCreate {
	if v != nil {
		_c.SetScheduleID(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *ScheduleCreate) SetName(v string) *ScheduleCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *ScheduleCreate) SetDescription(v string) *ScheduleCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *ScheduleCreate) SetNillableDescription(v *string) *ScheduleCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *ScheduleCreate) SetEnabled(v bool) *ScheduleCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *ScheduleCreate) SetNillableEnabled(v *bool) *ScheduleCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetRrule sets the "rrule" field.
func (_c *ScheduleCreate) SetRrule(v string) *ScheduleCreate {
	_c.mutation.SetRrule(v)
	return _c
}

// SetExclusions sets the "exclusions" field.
func (_c *ScheduleCreate) SetExclusions(v []string) *ScheduleCreate {
	_c.mutation.SetExclusions(v)
	return _c
}

// SetTimezone sets the "timezone" field.
func (_c *ScheduleCreate) SetTimezone(v string) *ScheduleCreate {
	_c.mutation.SetTimezone(v)
	return _c
}

// SetNillableTimezone sets the "timezone" field if the given value is not nil.
func (_c *ScheduleCreate) SetNillableTimezone(v *string) *ScheduleCreate {
	if v != nil {
		_c.SetTimezone(*v)
	}
	return _c
}

// SetDtstart sets the "dtstart" field.
func (_c *ScheduleCreate) SetDtstart(v time.Time) *ScheduleCreate {
	_c.mutation.SetDtstart(v)
	return _c
}

// SetDtend sets the "dtend" field.
func (_c *ScheduleCreate) SetDtend(v time.Time) *ScheduleCreate {
	_c.mutation.SetDtend(v)
	return _c
}

// SetNillableDtend sets the "dtend" field if the given value is not nil.
func (_c *ScheduleCreate) SetNillableDtend(v *time.Time) *ScheduleCreate {
	if v != nil {
		_c.SetDtend(*v)
	}
	return _c
}

// SetNextRun sets the "next_run" field.
func (_c *ScheduleCreate) SetNextRun(v time.Time) *ScheduleCreate {
	_c.mutation.SetNextRun(v)
	return _c
}

// SetNillableNextRun sets the "next_run" field if the given value is not nil.
func (_c *ScheduleCreate) SetNillableNextRun(v *time.Time) *ScheduleCreate {
	if v != nil {
		_c.SetNextRun(*v)
	}
	return _c
}

// SetLastFired sets the "last_fired" field.
func (_c *ScheduleCreate) SetLastFired(v time.Time) *ScheduleCreate {
	_c.mutation.SetLastFired(v)
	return _c
}

// SetNillableLastFired sets the "last_fired" field if the given value is not nil.
func (_c *ScheduleCreate) SetNillableLastFired(v *time.Time) *ScheduleCreate {
	if v != nil {
		_c.SetLastFired(*v)
	}
	return _c
}

// SetOrganizationID sets the "organization" edge to the Organization entity by ID.
func (_c *ScheduleCreate) SetOrganizationID(id int) *ScheduleCreate {
	_c.mutation.SetOrganizationID(id)
	return _c
}

// SetOrganization sets the "organization" edge to the Organization entity.
func (_c *ScheduleCreate) SetOrganization(v *Organization) *ScheduleCreate {
	return _c.SetOrganizationID(v.ID)
}

// SetTemplateID sets the "template" edge to the Template entity by ID.
func (_c *ScheduleCreate) SetTemplateID(id int) *ScheduleCreate {
	_c.mutation.SetTemplateID(id)
	return _c
}

// SetTemplate sets the "template" edge to the Template entity.
func (_c *ScheduleCreate) SetTemplate(v *Template) *ScheduleCreate {
	return _c.SetTemplateID(v.ID)
}

// SetSavedConfigID sets the "saved_config" edge to the SavedLaunchConfig entity by ID.
func (_c *ScheduleCreate) SetSavedConfigID(id int) *ScheduleCreate {
	_c.mutation.SetSavedConfigID(id)
	return _c
}

// SetNillableSavedConfigID sets the "saved_config" edge to the SavedLaunchConfig entity by ID if the given value is not nil.
func (_c *ScheduleCreate) SetNillableSavedConfigID(id *int) *ScheduleCreate {
	if id != nil {
		_c = _c.SetSavedConfigID(*id)
	}
	return _c
}

// SetSavedConfig sets the "saved_config" edge to the SavedLaunchConfig entity.
func (_c *ScheduleCreate) SetSavedConfig(v *SavedLaunchConfig) *ScheduleCreate {
	return _c.SetSavedConfigID(v.ID)
}

// AddOccurrenceIDs adds the "occurrences" edge to the ScheduleOccurrence entity by IDs.
func (_c *ScheduleCreate) AddOccurrenceIDs(ids ...int) *ScheduleCreate {
	_c.mutation.AddOccurrenceIDs(ids...)
	return _c
}

// AddOccurrences adds the "occurrences" edges to the ScheduleOccurrence entity.
func (_c *ScheduleCreate) AddOccurrences(v ...*ScheduleOccurrence) *ScheduleCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddOccurrenceIDs(ids...)
}

// Mutation returns the ScheduleMutation object of the builder.
func (_c *ScheduleCreate) Mutation() *ScheduleMutation {
	return _c.mutation
}

// Save creates the Schedule in the database.
func (_c *ScheduleCreate) Save(ctx context.Context) (*Schedule, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ScheduleCreate) SaveX(ctx context.Context) *Schedule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ScheduleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ScheduleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ScheduleCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := schedule.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := schedule.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ScheduleID(); !ok {
		v := schedule.DefaultScheduleID()
		_c.mutation.SetScheduleID(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := schedule.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.Timezone(); !ok {
		v := schedule.DefaultTimezone
		_c.mutation.SetTimezone(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ScheduleCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Schedule.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Schedule.updated_at"`)}
	}
	if _, ok := _c.mutation.ScheduleID(); !ok {
		return &ValidationError{Name: "schedule_id", err: errors.New(`ent: missing required field "Schedule.schedule_id"`)}
	}
	if v, ok := _c.mutation.ScheduleID(); ok {
		if err := schedule.ScheduleIDValidator(v); err != nil {
			return &ValidationError{Name: "schedule_id", err: fmt.Errorf(`ent: validator failed for field "Schedule.schedule_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Schedule.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := schedule.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Schedule.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "Schedule.enabled"`)}
	}
	if _, ok := _c.mutation.Rrule(); !ok {
		return &ValidationError{Name: "rrule", err: errors.New(`ent: missing required field "Schedule.rrule"`)}
	}
	if v, ok := _c.mutation.Rrule(); ok {
		if err := schedule.RruleValidator(v); err != nil {
			return &ValidationError{Name: "rrule", err: fmt.Errorf(`ent: validator failed for field "Schedule.rrule": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Timezone(); !ok {
		return &ValidationError{Name: "timezone", err: errors.New(`ent: missing required field "Schedule.timezone"`)}
	}
	if v, ok := _c.mutation.Timezone(); ok {
		if err := schedule.TimezoneValidator(v); err != nil {
			return &ValidationError{Name: "timezone", err: fmt.Errorf(`ent: validator failed for field "Schedule.timezone": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Dtstart(); !ok {
		return &ValidationError{Name: "dtstart", err: errors.New(`ent: missing required field "Schedule.dtstart"`)}
	}
	if len(_c.mutation.OrganizationIDs()) == 0 {
		return &ValidationError{Name: "organization", err: errors.New(`ent: missing required edge "Schedule.organization"`)}
	}
	if len(_c.mutation.TemplateIDs()) == 0 {
		return &ValidationError{Name: "template", err: errors.New(`ent: missing required edge "Schedule.template"`)}
	}
	return nil
}

func (_c *ScheduleCreate) sqlSave(ctx context.Context) (*Schedule, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ScheduleCreate) createSpec() (*Schedule, *sqlgraph.CreateSpec) {
	var (
		_node = &Schedule{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(schedule.Table, sqlgraph.NewFieldSpec(schedule.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(schedule.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(schedule.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.ScheduleID(); ok {
		_spec.SetField(schedule.FieldScheduleID, field.TypeString, value)
		_node.ScheduleID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(schedule.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(schedule.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(schedule.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.Rrule(); ok {
		_spec.SetField(schedule.FieldRrule, field.TypeString, value)
		_node.Rrule = value
	}
	if value, ok := _c.mutation.Exclusions(); ok {
		_spec.SetField(schedule.FieldExclusions, field.TypeJSON, value)
		_node.Exclusions = value
	}
	if value, ok := _c.mutation.Timezone(); ok {
		_spec.SetField(schedule.FieldTimezone, field.TypeString, value)
		_node.Timezone = value
	}
	if value, ok := _c.mutation.Dtstart(); ok {
		_spec.SetField(schedule.FieldDtstart, field.TypeTime, value)
		_node.Dtstart = value
	}
	if value, ok := _c.mutation.Dtend(); ok {
		_spec.SetField(schedule.FieldDtend, field.TypeTime, value)
		_node.Dtend = &value
	}
	if value, ok := _c.mutation.NextRun(); ok {
		_spec.SetField(schedule.FieldNextRun, field.TypeTime, value)
		_node.NextRun = &value
	}
	if value, ok := _c.mutation.LastFired(); ok {
		_spec.SetField(schedule.FieldLastFired, field.TypeTime, value)
		_node.LastFired = &value
	}
	if nodes := _c.mutation.OrganizationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   schedule.OrganizationTable,
			Columns: []string{schedule.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.organization_schedules = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TemplateIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   schedule.TemplateTable,
			Columns: []string{schedule.TemplateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(template.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.template_schedules = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SavedConfigIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   schedule.SavedConfigTable,
			Columns: []string{schedule.SavedConfigColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(savedlaunchconfig.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.schedule_saved_config = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.OccurrencesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   schedule.OccurrencesTable,
			Columns: []string{schedule.OccurrencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(scheduleoccurrence.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ScheduleCreateBulk is the builder for creating many Schedule entities in bulk.
type ScheduleCreateBulk struct {
	config
	err      error
	builders []*ScheduleCreate
}

// Save creates the Schedule entities in the database.
func (_c *ScheduleCreateBulk) Save(ctx context.Context) ([]*Schedule, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Schedule, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ScheduleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ScheduleCreateBulk) SaveX(ctx context.Context) []*Schedule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ScheduleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ScheduleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
