// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Subject-Void-LLC/the-pleiades/internal/ent/predicate"
	"github.com/Subject-Void-LLC/the-pleiades/internal/ent/project"
	"github.com/Subject-Void-LLC/the-pleiades/internal/ent/syncrun"
)

// SyncRunUpdate is the builder for updating SyncRun entities.
type SyncRunUpdate struct {
	config
	hooks    []Hook
	mutation *SyncRunMutation
}

// Where appends a list predicates to the SyncRunUpdate builder.
func (_u *SyncRunUpdate) Where(ps ...predicate.SyncRun) *SyncRunUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SyncRunUpdate) SetUpdatedAt(v time.Time) *SyncRunUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *SyncRunUpdate) SetStatus(v syncrun.Status) *SyncRunUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SyncRunUpdate) SetNillableStatus(v *syncrun.Status) *SyncRunUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetActor sets the "actor" field.
func (_u *SyncRunUpdate) SetActor(v string) *SyncRunUpdate {
	_u.mutation.SetActor(v)
	return _u
}

// SetNillableActor sets the "actor" field if the given value is not nil.
func (_u *SyncRunUpdate) SetNillableActor(v *string) *SyncRunUpdate {
	if v != nil {
		_u.SetActor(*v)
	}
	return _u
}

// ClearActor clears the value of the "actor" field.
func (_u *SyncRunUpdate) ClearActor() *SyncRunUpdate {
	_u.mutation.ClearActor()
	return _u
}

// SetRevision sets the "revision" field.
func (_u *SyncRunUpdate) SetRevision(v string) *SyncRunUpdate {
	_u.mutation.SetRevision(v)
	return _u
}

// SetNillableRevision sets the "revision" field if the given value is not nil.
func (_u *SyncRunUpdate) SetNillableRevision(v *string) *SyncRunUpdate {
	if v != nil {
		_u.SetRevision(*v)
	}
	return _u
}

// SetError sets the "error" field.
func (_u *SyncRunUpdate) SetError(v string) *SyncRunUpdate {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *SyncRunUpdate) SetNillableError(v *string) *SyncRunUpdate {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *SyncRunUpdate) SetStartedAt(v time.Time) *SyncRunUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *SyncRunUpdate) SetNillableStartedAt(v *time.Time) *SyncRunUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *SyncRunUpdate) SetFinishedAt(v time.Time) *SyncRunUpdate {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *SyncRunUpdate) SetNillableFinishedAt(v *time.Time) *SyncRunUpdate {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *SyncRunUpdate) ClearFinishedAt() *SyncRunUpdate {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetOwnerInstance sets the "owner_instance" field.
func (_u *SyncRunUpdate) SetOwnerInstance(v string) *SyncRunUpdate {
	_u.mutation.SetOwnerInstance(v)
	return _u
}

// SetNillableOwnerInstance sets the "owner_instance" field if the given value is not nil.
func (_u *SyncRunUpdate) SetNillableOwnerInstance(v *string) *SyncRunUpdate {
	if v != nil {
		_u.SetOwnerInstance(*v)
	}
	return _u
}

// ClearOwnerInstance clears the value of the "owner_instance" field.
func (_u *SyncRunUpdate) ClearOwnerInstance() *SyncRunUpdate {
	_u.mutation.ClearOwnerInstance()
	return _u
}

// SetProjectID sets the "project" edge to the Project entity by ID.
func (_u *SyncRunUpdate) SetProjectID(id int) *SyncRunUpdate {
	_u.mutation.SetProjectID(id)
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *SyncRunUpdate) SetProject(v *Project) *SyncRunUpdate {
	return _u.SetProjectID(v.ID)
}

// Mutation returns the SyncRunMutation object of the builder.
func (_u *SyncRunUpdate) Mutation() *SyncRunMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *SyncRunUpdate) ClearProject() *SyncRunUpdate {
	_u.mutation.ClearProject()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SyncRunUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SyncRunUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SyncRunUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SyncRunUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SyncRunUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := syncrun.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SyncRunUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := syncrun.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SyncRun.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Actor(); ok {
		if err := syncrun.ActorValidator(v); err != nil {
			return &ValidationError{Name: "actor", err: fmt.Errorf(`ent: validator failed for field "SyncRun.actor": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Revision(); ok {
		if err := syncrun.RevisionValidator(v); err != nil {
			return &ValidationError{Name: "revision", err: fmt.Errorf(`ent: validator failed for field "SyncRun.revision": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Error(); ok {
		if err := syncrun.ErrorValidator(v); err != nil {
			return &ValidationError{Name: "error", err: fmt.Errorf(`ent: validator failed for field "SyncRun.error": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OwnerInstance(); ok {
		if err := syncrun.OwnerInstanceValidator(v); err != nil {
			return &ValidationError{Name: "owner_instance", err: fmt.Errorf(`ent: validator failed for field "SyncRun.owner_instance": %w`, err)}
		}
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SyncRun.project"`)
	}
	return nil
}

func (_u *SyncRunUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(syncrun.Table, syncrun.Columns, sqlgraph.NewFieldSpec(syncrun.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(syncrun.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(syncrun.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Actor(); ok {
		_spec.SetField(syncrun.FieldActor, field.TypeString, value)
	}
	if _u.mutation.ActorCleared() {
		_spec.ClearField(syncrun.FieldActor, field.TypeString)
	}
	if value, ok := _u.mutation.Revision(); ok {
		_spec.SetField(syncrun.FieldRevision, field.TypeString, value)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(syncrun.FieldError, field.TypeString, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(syncrun.FieldStartedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(syncrun.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(syncrun.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.OwnerInstance(); ok {
		_spec.SetField(syncrun.FieldOwnerInstance, field.TypeString, value)
	}
	if _u.mutation.OwnerInstanceCleared() {
		_spec.ClearField(syncrun.FieldOwnerInstance, field.TypeString)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   syncrun.ProjectTable,
			Columns: []string{syncrun.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   syncrun.ProjectTable,
			Columns: []string{syncrun.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{syncrun.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SyncRunUpdateOne is the builder for updating a single SyncRun entity.
type SyncRunUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SyncRunMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SyncRunUpdateOne) SetUpdatedAt(v time.Time) *SyncRunUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *SyncRunUpdateOne) SetStatus(v syncrun.Status) *SyncRunUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SyncRunUpdateOne) SetNillableStatus(v *syncrun.Status) *SyncRunUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetActor sets the "actor" field.
func (_u *SyncRunUpdateOne) SetActor(v string) *SyncRunUpdateOne {
	_u.mutation.SetActor(v)
	return _u
}

// SetNillableActor sets the "actor" field if the given value is not nil.
func (_u *SyncRunUpdateOne) SetNillableActor(v *string) *SyncRunUpdateOne {
	if v != nil {
		_u.SetActor(*v)
	}
	return _u
}

// ClearActor clears the value of the "actor" field.
func (_u *SyncRunUpdateOne) ClearActor() *SyncRunUpdateOne {
	_u.mutation.ClearActor()
	return _u
}

// SetRevision sets the "revision" field.
func (_u *SyncRunUpdateOne) SetRevision(v string) *SyncRunUpdateOne {
	_u.mutation.SetRevision(v)
	return _u
}

// SetNillableRevision sets the "revision" field if the given value is not nil.
func (_u *SyncRunUpdateOne) SetNillableRevision(v *string) *SyncRunUpdateOne {
	if v != nil {
		_u.SetRevision(*v)
	}
	return _u
}

// SetError sets the "error" field.
func (_u *SyncRunUpdateOne) SetError(v string) *SyncRunUpdateOne {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *SyncRunUpdateOne) SetNillableError(v *string) *SyncRunUpdateOne {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *SyncRunUpdateOne) SetStartedAt(v time.Time) *SyncRunUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *SyncRunUpdateOne) SetNillableStartedAt(v *time.Time) *SyncRunUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *SyncRunUpdateOne) SetFinishedAt(v time.Time) *SyncRunUpdateOne {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *SyncRunUpdateOne) SetNillableFinishedAt(v *time.Time) *SyncRunUpdateOne {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *SyncRunUpdateOne) ClearFinishedAt() *SyncRunUpdateOne {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetOwnerInstance sets the "owner_instance" field.
func (_u *SyncRunUpdateOne) SetOwnerInstance(v string) *SyncRunUpdateOne {
	_u.mutation.SetOwnerInstance(v)
	return _u
}

// SetNillableOwnerInstance sets the "owner_instance" field if the given value is not nil.
func (_u *SyncRunUpdateOne) SetNillableOwnerInstance(v *string) *SyncRunUpdateOne {
	if v != nil {
		_u.SetOwnerInstance(*v)
	}
	return _u
}

// ClearOwnerInstance clears the value of the "owner_instance" field.
func (_u *SyncRunUpdateOne) ClearOwnerInstance() *SyncRunUpdateOne {
	_u.mutation.ClearOwnerInstance()
	return _u
}

// SetProjectID sets the "project" edge to the Project entity by ID.
func (_u *SyncRunUpdateOne) SetProjectID(id int) *SyncRunUpdateOne {
	_u.mutation.SetProjectID(id)
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *SyncRunUpdateOne) SetProject(v *Project) *SyncRunUpdateOne {
	return _u.SetProjectID(v.ID)
}

// Mutation returns the SyncRunMutation object of the builder.
func (_u *SyncRunUpdateOne) Mutation() *SyncRunMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *SyncRunUpdateOne) ClearProject() *SyncRunUpdateOne {
	_u.mutation.ClearProject()
	return _u
}

// Where appends a list predicates to the SyncRunUpdate builder.
func (_u *SyncRunUpdateOne) Where(ps ...predicate.SyncRun) *SyncRunUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SyncRunUpdateOne) Select(field string, fields ...string) *SyncRunUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SyncRun entity.
func (_u *SyncRunUpdateOne) Save(ctx context.Context) (*SyncRun, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SyncRunUpdateOne) SaveX(ctx context.Context) *SyncRun {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SyncRunUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SyncRunUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SyncRunUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := syncrun.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SyncRunUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := syncrun.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SyncRun.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Actor(); ok {
		if err := syncrun.ActorValidator(v); err != nil {
			return &ValidationError{Name: "actor", err: fmt.Errorf(`ent: validator failed for field "SyncRun.actor": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Revision(); ok {
		if err := syncrun.RevisionValidator(v); err != nil {
			return &ValidationError{Name: "revision", err: fmt.Errorf(`ent: validator failed for field "SyncRun.revision": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Error(); ok {
		if err := syncrun.ErrorValidator(v); err != nil {
			return &ValidationError{Name: "error", err: fmt.Errorf(`ent: validator failed for field "SyncRun.error": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OwnerInstance(); ok {
		if err := syncrun.OwnerInstanceValidator(v); err != nil {
			return &ValidationError{Name: "owner_instance", err: fmt.Errorf(`ent: validator failed for field "SyncRun.owner_instance": %w`, err)}
		}
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SyncRun.project"`)
	}
	return nil
}

func (_u *SyncRunUpdateOne) sqlSave(ctx context.Context) (_node *SyncRun, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(syncrun.Table, syncrun.Columns, sqlgraph.NewFieldSpec(syncrun.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SyncRun.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, syncrun.FieldID)
		for _, f := range fields {
			if !syncrun.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != syncrun.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(syncrun.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(syncrun.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Actor(); ok {
		_spec.SetField(syncrun.FieldActor, field.TypeString, value)
	}
	if _u.mutation.ActorCleared() {
		_spec.ClearField(syncrun.FieldActor, field.TypeString)
	}
	if value, ok := _u.mutation.Revision(); ok {
		_spec.SetField(syncrun.FieldRevision, field.TypeString, value)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(syncrun.FieldError, field.TypeString, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(syncrun.FieldStartedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(syncrun.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(syncrun.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.OwnerInstance(); ok {
		_spec.SetField(syncrun.FieldOwnerInstance, field.TypeString, value)
	}
	if _u.mutation.OwnerInstanceCleared() {
		_spec.ClearField(syncrun.FieldOwnerInstance, field.TypeString)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   syncrun.ProjectTable,
			Columns: []string{syncrun.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   syncrun.ProjectTable,
			Columns: []string{syncrun.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SyncRun{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{syncrun.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
