// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Subject-Void-LLC/the-pleiades/internal/ent/credential"
	"github.com/Subject-Void-LLC/the-pleiades/internal/ent/inventory"
	"github.com/Subject-Void-LLC/the-pleiades/internal/ent/organization"
	"github.com/Subject-Void-LLC/the-pleiades/internal/ent/predicate"
	"github.com/Subject-Void-LLC/the-pleiades/internal/ent/savedlaunchconfig"
	"github.com/Subject-Void-LLC/the-pleiades/internal/ent/surveyquestion"
	"github.com/Subject-Void-LLC/the-pleiades/internal/ent/template"
)

// TemplateUpdate is the builder for updating Template entities.
type TemplateUpdate struct {
	config
	hooks    []Hook
	mutation *TemplateMutation
}

// Where appends a list predicates to the TemplateUpdate builder.
func (_u *TemplateUpdate) Where(ps ...predicate.Template) *TemplateUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TemplateUpdate) SetUpdatedAt(v time.Time) *TemplateUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *TemplateUpdate) SetName(v string) *TemplateUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TemplateUpdate) SetNillableName(v *string) *TemplateUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *TemplateUpdate) SetDescription(v string) *TemplateUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TemplateUpdate) SetNillableDescription(v *string) *TemplateUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *TemplateUpdate) ClearDescription() *TemplateUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetKind sets the "kind" field.
func (_u *TemplateUpdate) SetKind(v string) *TemplateUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *TemplateUpdate) SetNillableKind(v *string) *TemplateUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetDefaults sets the "defaults" field.
func (_u *TemplateUpdate) SetDefaults(v map[string]interface{}) *TemplateUpdate {
	_u.mutation.SetDefaults(v)
	return _u
}

// ClearDefaults clears the value of the "defaults" field.
func (_u *TemplateUpdate) ClearDefaults() *TemplateUpdate {
	_u.mutation.ClearDefaults()
	return _u
}

// SetPrompts sets the "prompts" field.
func (_u *TemplateUpdate) SetPrompts(v []string) *TemplateUpdate {
	_u.mutation.SetPrompts(v)
	return _u
}

// AppendPrompts appends value to the "prompts" field.
func (_u *TemplateUpdate) AppendPrompts(v []string) *TemplateUpdate {
	_u.mutation.AppendPrompts(v)
	return _u
}

// ClearPrompts clears the value of the "prompts" field.
func (_u *TemplateUpdate) ClearPrompts() *TemplateUpdate {
	_u.mutation.ClearPrompts()
	return _u
}

// SetRequiredCaps sets the "required_caps" field.
func (_u *TemplateUpdate) SetRequiredCaps(v []string) *TemplateUpdate {
	_u.mutation.SetRequiredCaps(v)
	return _u
}

// AppendRequiredCaps appends value to the "required_caps" field.
func (_u *TemplateUpdate) AppendRequiredCaps(v []string) *TemplateUpdate {
	_u.mutation.AppendRequiredCaps(v)
	return _u
}

// ClearRequiredCaps clears the value of the "required_caps" field.
func (_u *TemplateUpdate) ClearRequiredCaps() *TemplateUpdate {
	_u.mutation.ClearRequiredCaps()
	return _u
}

// SetSurveyEnabled sets the "survey_enabled" field.
func (_u *TemplateUpdate) SetSurveyEnabled(v bool) *TemplateUpdate {
	_u.mutation.SetSurveyEnabled(v)
	return _u
}

// SetNillableSurveyEnabled sets the "survey_enabled" field if the given value is not nil.
func (_u *TemplateUpdate) SetNillableSurveyEnabled(v *bool) *TemplateUpdate {
	if v != nil {
		_u.SetSurveyEnabled(*v)
	}
	return _u
}

// SetAllowSimultaneous sets the "allow_simultaneous" field.
func (_u *TemplateUpdate) SetAllowSimultaneous(v bool) *TemplateUpdate {
	_u.mutation.SetAllowSimultaneous(v)
	return _u
}

// SetNillableAllowSimultaneous sets the "allow_simultaneous" field if the given value is not nil.
func (_u *TemplateUpdate) SetNillableAllowSimultaneous(v *bool) *TemplateUpdate {
	if v != nil {
		_u.SetAllowSimultaneous(*v)
	}
	return _u
}

// SetOrganizationID sets the "organization" edge to the Organization entity by ID.
func (_u *TemplateUpdate) SetOrganizationID(id int) *TemplateUpdate {
	_u.mutation.SetOrganizationID(id)
	return _u
}

// SetOrganization sets the "organization" edge to the Organization entity.
func (_u *TemplateUpdate) SetOrganization(v *Organization) *TemplateUpdate {
	return _u.SetOrganizationID(v.ID)
}

// SetInventoryID sets the "inventory" edge to the Inventory entity by ID.
func (_u *TemplateUpdate) SetInventoryID(id int) *TemplateUpdate {
	_u.mutation.SetInventoryID(id)
	return _u
}

// SetInventory sets the "inventory" edge to the Inventory entity.
func (_u *TemplateUpdate) SetInventory(v *Inventory) *TemplateUpdate {
	return _u.SetInventoryID(v.ID)
}

// AddSurveyQuestionIDs adds the "survey_questions" edge to the SurveyQuestion entity by IDs.
func (_u *TemplateUpdate) AddSurveyQuestionIDs(ids ...int) *TemplateUpdate {
	_u.mutation.AddSurveyQuestionIDs(ids...)
	return _u
}

// AddSurveyQuestions adds the "survey_questions" edges to the SurveyQuestion entity.
func (_u *TemplateUpdate) AddSurveyQuestions(v ...*SurveyQuestion) *TemplateUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSurveyQuestionIDs(ids...)
}

// AddSavedConfigIDs adds the "saved_configs" edge to the SavedLaunchConfig entity by IDs.
func (_u *TemplateUpdate) AddSavedConfigIDs(ids ...int) *TemplateUpdate {
	_u.mutation.AddSavedConfigIDs(ids...)
	return _u
}

// AddSavedConfigs adds the "saved_configs" edges to the SavedLaunchConfig entity.
func (_u *TemplateUpdate) AddSavedConfigs(v ...*SavedLaunchConfig) *TemplateUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSavedConfigIDs(ids...)
}

// AddCredentialIDs adds the "credentials" edge to the Credential entity by IDs.
func (_u *TemplateUpdate) AddCredentialIDs(ids ...int) *TemplateUpdate {
	_u.mutation.AddCredentialIDs(ids...)
	return _u
}

// AddCredentials adds the "credentials" edges to the Credential entity.
func (_u *TemplateUpdate) AddCredentials(v ...*Credential) *TemplateUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCredentialIDs(ids...)
}

// Mutation returns the TemplateMutation object of the builder.
func (_u *TemplateUpdate) Mutation() *TemplateMutation {
	return _u.mutation
}

// ClearOrganization clears the "organization" edge to the Organization entity.
func (_u *TemplateUpdate) ClearOrganization() *TemplateUpdate {
	_u.mutation.ClearOrganization()
	return _u
}

// ClearInventory clears the "inventory" edge to the Inventory entity.
func (_u *TemplateUpdate) ClearInventory() *TemplateUpdate {
	_u.mutation.ClearInventory()
	return _u
}

// ClearSurveyQuestions clears all "survey_questions" edges to the SurveyQuestion entity.
func (_u *TemplateUpdate) ClearSurveyQuestions() *TemplateUpdate {
	_u.mutation.ClearSurveyQuestions()
	return _u
}

// RemoveSurveyQuestionIDs removes the "survey_questions" edge to SurveyQuestion entities by IDs.
func (_u *TemplateUpdate) RemoveSurveyQuestionIDs(ids ...int) *TemplateUpdate {
	_u.mutation.RemoveSurveyQuestionIDs(ids...)
	return _u
}

// RemoveSurveyQuestions removes "survey_questions" edges to SurveyQuestion entities.
func (_u *TemplateUpdate) RemoveSurveyQuestions(v ...*SurveyQuestion) *TemplateUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSurveyQuestionIDs(ids...)
}

// ClearSavedConfigs clears all "saved_configs" edges to the SavedLaunchConfig entity.
func (_u *TemplateUpdate) ClearSavedConfigs() *TemplateUpdate {
	_u.mutation.ClearSavedConfigs()
	return _u
}

// RemoveSavedConfigIDs removes the "saved_configs" edge to SavedLaunchConfig entities by IDs.
func (_u *TemplateUpdate) RemoveSavedConfigIDs(ids ...int) *TemplateUpdate {
	_u.mutation.RemoveSavedConfigIDs(ids...)
	return _u
}

// RemoveSavedConfigs removes "saved_configs" edges to SavedLaunchConfig entities.
func (_u *TemplateUpdate) RemoveSavedConfigs(v ...*SavedLaunchConfig) *TemplateUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSavedConfigIDs(ids...)
}

// ClearCredentials clears all "credentials" edges to the Credential entity.
func (_u *TemplateUpdate) ClearCredentials() *TemplateUpdate {
	_u.mutation.ClearCredentials()
	return _u
}

// RemoveCredentialIDs removes the "credentials" edge to Credential entities by IDs.
func (_u *TemplateUpdate) RemoveCredentialIDs(ids ...int) *TemplateUpdate {
	_u.mutation.RemoveCredentialIDs(ids...)
	return _u
}

// RemoveCredentials removes "credentials" edges to Credential entities.
func (_u *TemplateUpdate) RemoveCredentials(v ...*Credential) *TemplateUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCredentialIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TemplateUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TemplateUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TemplateUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TemplateUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TemplateUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := template.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TemplateUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := template.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Template.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Kind(); ok {
		if err := template.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "Template.kind": %w`, err)}
		}
	}
	if _u.mutation.OrganizationCleared() && len(_u.mutation.OrganizationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Template.organization"`)
	}
	if _u.mutation.InventoryCleared() && len(_u.mutation.InventoryIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Template.inventory"`)
	}
	return nil
}

func (_u *TemplateUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(template.Table, template.Columns, sqlgraph.NewFieldSpec(template.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(template.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(template.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(template.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(template.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(template.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Defaults(); ok {
		_spec.SetField(template.FieldDefaults, field.TypeJSON, value)
	}
	if _u.mutation.DefaultsCleared() {
		_spec.ClearField(template.FieldDefaults, field.TypeJSON)
	}
	if value, ok := _u.mutation.Prompts(); ok {
		_spec.SetField(template.FieldPrompts, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPrompts(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, template.FieldPrompts, value)
		})
	}
	if _u.mutation.PromptsCleared() {
		_spec.ClearField(template.FieldPrompts, field.TypeJSON)
	}
	if value, ok := _u.mutation.RequiredCaps(); ok {
		_spec.SetField(template.FieldRequiredCaps, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedRequiredCaps(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, template.FieldRequiredCaps, value)
		})
	}
	if _u.mutation.RequiredCapsCleared() {
		_spec.ClearField(template.FieldRequiredCaps, field.TypeJSON)
	}
	if value, ok := _u.mutation.SurveyEnabled(); ok {
		_spec.SetField(template.FieldSurveyEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AllowSimultaneous(); ok {
		_spec.SetField(template.FieldAllowSimultaneous, field.TypeBool, value)
	}
	if _u.mutation.OrganizationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   template.OrganizationTable,
			Columns: []string{template.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrganizationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   template.OrganizationTable,
			Columns: []string{template.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.InventoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   template.InventoryTable,
			Columns: []string{template.InventoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inventory.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InventoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   template.InventoryTable,
			Columns: []string{template.InventoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inventory.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SurveyQuestionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   template.SurveyQuestionsTable,
			Columns: []string{template.SurveyQuestionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(surveyquestion.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSurveyQuestionsIDs(); len(nodes) > 0 && !_u.mutation.SurveyQuestionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   template.SurveyQuestionsTable,
			Columns: []string{template.SurveyQuestionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(surveyquestion.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SurveyQuestionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   template.SurveyQuestionsTable,
			Columns: []string{template.SurveyQuestionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(surveyquestion.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SavedConfigsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   template.SavedConfigsTable,
			Columns: []string{template.SavedConfigsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(savedlaunchconfig.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSavedConfigsIDs(); len(nodes) > 0 && !_u.mutation.SavedConfigsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   template.SavedConfigsTable,
			Columns: []string{template.SavedConfigsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(savedlaunchconfig.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SavedConfigsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   template.SavedConfigsTable,
			Columns: []string{template.SavedConfigsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(savedlaunchconfig.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CredentialsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   template.CredentialsTable,
			Columns: template.CredentialsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(credential.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCredentialsIDs(); len(nodes) > 0 && !_u.mutation.CredentialsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   template.CredentialsTable,
			Columns: template.CredentialsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(credential.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CredentialsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   template.CredentialsTable,
			Columns: template.CredentialsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(credential.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{template.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TemplateUpdateOne is the builder for updating a single Template entity.
type TemplateUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TemplateMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TemplateUpdateOne) SetUpdatedAt(v time.Time) *TemplateUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *TemplateUpdateOne) SetName(v string) *TemplateUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TemplateUpdateOne) SetNillableName(v *string) *TemplateUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *TemplateUpdateOne) SetDescription(v string) *TemplateUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TemplateUpdateOne) SetNillableDescription(v *string) *TemplateUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *TemplateUpdateOne) ClearDescription() *TemplateUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetKind sets the "kind" field.
func (_u *TemplateUpdateOne) SetKind(v string) *TemplateUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *TemplateUpdateOne) SetNillableKind(v *string) *TemplateUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetDefaults sets the "defaults" field.
func (_u *TemplateUpdateOne) SetDefaults(v map[string]interface{}) *TemplateUpdateOne {
	_u.mutation.SetDefaults(v)
	return _u
}

// ClearDefaults clears the value of the "defaults" field.
func (_u *TemplateUpdateOne) ClearDefaults() *TemplateUpdateOne {
	_u.mutation.ClearDefaults()
	return _u
}

// SetPrompts sets the "prompts" field.
func (_u *TemplateUpdateOne) SetPrompts(v []string) *TemplateUpdateOne {
	_u.mutation.SetPrompts(v)
	return _u
}

// AppendPrompts appends value to the "prompts" field.
func (_u *TemplateUpdateOne) AppendPrompts(v []string) *TemplateUpdateOne {
	_u.mutation.AppendPrompts(v)
	return _u
}

// ClearPrompts clears the value of the "prompts" field.
func (_u *TemplateUpdateOne) ClearPrompts() *TemplateUpdateOne {
	_u.mutation.ClearPrompts()
	return _u
}

// SetRequiredCaps sets the "required_caps" field.
func (_u *TemplateUpdateOne) SetRequiredCaps(v []string) *TemplateUpdateOne {
	_u.mutation.SetRequiredCaps(v)
	return _u
}

// AppendRequiredCaps appends value to the "required_caps" field.
func (_u *TemplateUpdateOne) AppendRequiredCaps(v []string) *TemplateUpdateOne {
	_u.mutation.AppendRequiredCaps(v)
	return _u
}

// ClearRequiredCaps clears the value of the "required_caps" field.
func (_u *TemplateUpdateOne) ClearRequiredCaps() *TemplateUpdateOne {
	_u.mutation.ClearRequiredCaps()
	return _u
}

// SetSurveyEnabled sets the "survey_enabled" field.
func (_u *TemplateUpdateOne) SetSurveyEnabled(v bool) *TemplateUpdateOne {
	_u.mutation.SetSurveyEnabled(v)
	return _u
}

// SetNillableSurveyEnabled sets the "survey_enabled" field if the given value is not nil.
func (_u *TemplateUpdateOne) SetNillableSurveyEnabled(v *bool) *TemplateUpdateOne {
	if v != nil {
		_u.SetSurveyEnabled(*v)
	}
	return _u
}

// SetAllowSimultaneous sets the "allow_simultaneous" field.
func (_u *TemplateUpdateOne) SetAllowSimultaneous(v bool) *TemplateUpdateOne {
	_u.mutation.SetAllowSimultaneous(v)
	return _u
}

// SetNillableAllowSimultaneous sets the "allow_simultaneous" field if the given value is not nil.
func (_u *TemplateUpdateOne) SetNillableAllowSimultaneous(v *bool) *TemplateUpdateOne {
	if v != nil {
		_u.SetAllowSimultaneous(*v)
	}
	return _u
}

// SetOrganizationID sets the "organization" edge to the Organization entity by ID.
func (_u *TemplateUpdateOne) SetOrganizationID(id int) *TemplateUpdateOne {
	_u.mutation.SetOrganizationID(id)
	return _u
}

// SetOrganization sets the "organization" edge to the Organization entity.
func (_u *TemplateUpdateOne) SetOrganization(v *Organization) *TemplateUpdateOne {
	return _u.SetOrganizationID(v.ID)
}

// SetInventoryID sets the "inventory" edge to the Inventory entity by ID.
func (_u *TemplateUpdateOne) SetInventoryID(id int) *TemplateUpdateOne {
	_u.mutation.SetInventoryID(id)
	return _u
}

// SetInventory sets the "inventory" edge to the Inventory entity.
func (_u *TemplateUpdateOne) SetInventory(v *Inventory) *TemplateUpdateOne {
	return _u.SetInventoryID(v.ID)
}

// AddSurveyQuestionIDs adds the "survey_questions" edge to the SurveyQuestion entity by IDs.
func (_u *TemplateUpdateOne) AddSurveyQuestionIDs(ids ...int) *TemplateUpdateOne {
	_u.mutation.AddSurveyQuestionIDs(ids...)
	return _u
}

// AddSurveyQuestions adds the "survey_questions" edges to the SurveyQuestion entity.
func (_u *TemplateUpdateOne) AddSurveyQuestions(v ...*SurveyQuestion) *TemplateUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSurveyQuestionIDs(ids...)
}

// AddSavedConfigIDs adds the "saved_configs" edge to the SavedLaunchConfig entity by IDs.
func (_u *TemplateUpdateOne) AddSavedConfigIDs(ids ...int) *TemplateUpdateOne {
	_u.mutation.AddSavedConfigIDs(ids...)
	return _u
}

// AddSavedConfigs adds the "saved_configs" edges to the SavedLaunchConfig entity.
func (_u *TemplateUpdateOne) AddSavedConfigs(v ...*SavedLaunchConfig) *TemplateUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSavedConfigIDs(ids...)
}

// AddCredentialIDs adds the "credentials" edge to the Credential entity by IDs.
func (_u *TemplateUpdateOne) AddCredentialIDs(ids ...int) *TemplateUpdateOne {
	_u.mutation.AddCredentialIDs(ids...)
	return _u
}

// AddCredentials adds the "credentials" edges to the Credential entity.
func (_u *TemplateUpdateOne) AddCredentials(v ...*Credential) *TemplateUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCredentialIDs(ids...)
}

// Mutation returns the TemplateMutation object of the builder.
func (_u *TemplateUpdateOne) Mutation() *TemplateMutation {
	return _u.mutation
}

// ClearOrganization clears the "organization" edge to the Organization entity.
func (_u *TemplateUpdateOne) ClearOrganization() *TemplateUpdateOne {
	_u.mutation.ClearOrganization()
	return _u
}

// ClearInventory clears the "inventory" edge to the Inventory entity.
func (_u *TemplateUpdateOne) ClearInventory() *TemplateUpdateOne {
	_u.mutation.ClearInventory()
	return _u
}

// ClearSurveyQuestions clears all "survey_questions" edges to the SurveyQuestion entity.
func (_u *TemplateUpdateOne) ClearSurveyQuestions() *TemplateUpdateOne {
	_u.mutation.ClearSurveyQuestions()
	return _u
}

// RemoveSurveyQuestionIDs removes the "survey_questions" edge to SurveyQuestion entities by IDs.
func (_u *TemplateUpdateOne) RemoveSurveyQuestionIDs(ids ...int) *TemplateUpdateOne {
	_u.mutation.RemoveSurveyQuestionIDs(ids...)
	return _u
}

// RemoveSurveyQuestions removes "survey_questions" edges to SurveyQuestion entities.
func (_u *TemplateUpdateOne) RemoveSurveyQuestions(v ...*SurveyQuestion) *TemplateUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSurveyQuestionIDs(ids...)
}

// ClearSavedConfigs clears all "saved_configs" edges to the SavedLaunchConfig entity.
func (_u *TemplateUpdateOne) ClearSavedConfigs() *TemplateUpdateOne {
	_u.mutation.ClearSavedConfigs()
	return _u
}

// RemoveSavedConfigIDs removes the "saved_configs" edge to SavedLaunchConfig entities by IDs.
func (_u *TemplateUpdateOne) RemoveSavedConfigIDs(ids ...int) *TemplateUpdateOne {
	_u.mutation.RemoveSavedConfigIDs(ids...)
	return _u
}

// RemoveSavedConfigs removes "saved_configs" edges to SavedLaunchConfig entities.
func (_u *TemplateUpdateOne) RemoveSavedConfigs(v ...*SavedLaunchConfig) *TemplateUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSavedConfigIDs(ids...)
}

// ClearCredentials clears all "credentials" edges to the Credential entity.
func (_u *TemplateUpdateOne) ClearCredentials() *TemplateUpdateOne {
	_u.mutation.ClearCredentials()
	return _u
}

// RemoveCredentialIDs removes the "credentials" edge to Credential entities by IDs.
func (_u *TemplateUpdateOne) RemoveCredentialIDs(ids ...int) *TemplateUpdateOne {
	_u.mutation.RemoveCredentialIDs(ids...)
	return _u
}

// RemoveCredentials removes "credentials" edges to Credential entities.
func (_u *TemplateUpdateOne) RemoveCredentials(v ...*Credential) *TemplateUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCredentialIDs(ids...)
}

// Where appends a list predicates to the TemplateUpdate builder.
func (_u *TemplateUpdateOne) Where(ps ...predicate.Template) *TemplateUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TemplateUpdateOne) Select(field string, fields ...string) *TemplateUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Template entity.
func (_u *TemplateUpdateOne) Save(ctx context.Context) (*Template, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TemplateUpdateOne) SaveX(ctx context.Context) *Template {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TemplateUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TemplateUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TemplateUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := template.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TemplateUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := template.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Template.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Kind(); ok {
		if err := template.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "Template.kind": %w`, err)}
		}
	}
	if _u.mutation.OrganizationCleared() && len(_u.mutation.OrganizationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Template.organization"`)
	}
	if _u.mutation.InventoryCleared() && len(_u.mutation.InventoryIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Template.inventory"`)
	}
	return nil
}

func (_u *TemplateUpdateOne) sqlSave(ctx context.Context) (_node *Template, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(template.Table, template.Columns, sqlgraph.NewFieldSpec(template.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Template.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, template.FieldID)
		for _, f := range fields {
			if !template.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != template.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(template.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(template.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(template.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(template.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(template.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Defaults(); ok {
		_spec.SetField(template.FieldDefaults, field.TypeJSON, value)
	}
	if _u.mutation.DefaultsCleared() {
		_spec.ClearField(template.FieldDefaults, field.TypeJSON)
	}
	if value, ok := _u.mutation.Prompts(); ok {
		_spec.SetField(template.FieldPrompts, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPrompts(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, template.FieldPrompts, value)
		})
	}
	if _u.mutation.PromptsCleared() {
		_spec.ClearField(template.FieldPrompts, field.TypeJSON)
	}
	if value, ok := _u.mutation.RequiredCaps(); ok {
		_spec.SetField(template.FieldRequiredCaps, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedRequiredCaps(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, template.FieldRequiredCaps, value)
		})
	}
	if _u.mutation.RequiredCapsCleared() {
		_spec.ClearField(template.FieldRequiredCaps, field.TypeJSON)
	}
	if value, ok := _u.mutation.SurveyEnabled(); ok {
		_spec.SetField(template.FieldSurveyEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AllowSimultaneous(); ok {
		_spec.SetField(template.FieldAllowSimultaneous, field.TypeBool, value)
	}
	if _u.mutation.OrganizationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   template.OrganizationTable,
			Columns: []string{template.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrganizationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   template.OrganizationTable,
			Columns: []string{template.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.InventoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   template.InventoryTable,
			Columns: []string{template.InventoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inventory.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InventoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   template.InventoryTable,
			Columns: []string{template.InventoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inventory.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SurveyQuestionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   template.SurveyQuestionsTable,
			Columns: []string{template.SurveyQuestionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(surveyquestion.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSurveyQuestionsIDs(); len(nodes) > 0 && !_u.mutation.SurveyQuestionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   template.SurveyQuestionsTable,
			Columns: []string{template.SurveyQuestionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(surveyquestion.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SurveyQuestionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   template.SurveyQuestionsTable,
			Columns: []string{template.SurveyQuestionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(surveyquestion.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SavedConfigsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   template.SavedConfigsTable,
			Columns: []string{template.SavedConfigsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(savedlaunchconfig.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSavedConfigsIDs(); len(nodes) > 0 && !_u.mutation.SavedConfigsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   template.SavedConfigsTable,
			Columns: []string{template.SavedConfigsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(savedlaunchconfig.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SavedConfigsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   template.SavedConfigsTable,
			Columns: []string{template.SavedConfigsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(savedlaunchconfig.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CredentialsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   template.CredentialsTable,
			Columns: template.CredentialsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(credential.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCredentialsIDs(); len(nodes) > 0 && !_u.mutation.CredentialsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   template.CredentialsTable,
			Columns: template.CredentialsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(credential.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CredentialsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   template.CredentialsTable,
			Columns: template.CredentialsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(credential.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Template{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{template.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
