// Code generated by ent, DO NOT EDIT.

package credentialinputsource

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Subject-Void-LLC/the-pleiades/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.CredentialInputSource {
	return predicate.CredentialInputSource(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.CredentialInputSource {
	return predicate.CredentialInputSource(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.CredentialInputSource {
	return predicate.CredentialInputSource(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.CredentialInputSource {
	return predicate.CredentialInputSource(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.CredentialInputSource {
	return predicate.CredentialInputSource(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.CredentialInputSource {
	return predicate.CredentialInputSource(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.CredentialInputSource {
	return predicate.CredentialInputSource(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.CredentialInputSource {
	return predicate.CredentialInputSource(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.CredentialInputSource {
	return predicate.CredentialInputSource(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CredentialInputSource {
	return predicate.CredentialInputSource(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CredentialInputSource {
	return predicate.CredentialInputSource(sql.FieldEQ(FieldUpdatedAt, v))
}

// InputID applies equality check predicate on the "input_id" field. It's identical to InputIDEQ.
func InputID(v string) predicate.CredentialInputSource {
	return predicate.CredentialInputSource(sql.FieldEQ(FieldInputID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CredentialInputSource {
	return predicate.CredentialInputSource(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CredentialInputSource {
	return predicate.CredentialInputSource(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CredentialInputSource {
	return predicate.CredentialInputSource(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CredentialInputSource {
	return predicate.CredentialInputSource(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CredentialInputSource {
	return predicate.CredentialInputSource(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CredentialInputSource {
	return predicate.CredentialInputSource(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CredentialInputSource {
	return predicate.CredentialInputSource(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CredentialInputSource {
	return predicate.CredentialInputSource(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CredentialInputSource {
	return predicate.CredentialInputSource(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CredentialInputSource {
	return predicate.CredentialInputSource(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CredentialInputSource {
	return predicate.CredentialInputSource(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CredentialInputSource {
	return predicate.CredentialInputSource(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CredentialInputSource {
	return predicate.CredentialInputSource(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CredentialInputSource {
	return predicate.CredentialInputSource(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CredentialInputSource {
	return predicate.CredentialInputSource(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CredentialInputSource {
	return predicate.CredentialInputSource(sql.FieldLTE(FieldUpdatedAt, v))
}

// InputIDEQ applies the EQ predicate on the "input_id" field.
func InputIDEQ(v string) predicate.CredentialInputSource {
	return predicate.CredentialInputSource(sql.FieldEQ(FieldInputID, v))
}

// InputIDNEQ applies the NEQ predicate on the "input_id" field.
func InputIDNEQ(v string) predicate.CredentialInputSource {
	return predicate.CredentialInputSource(sql.FieldNEQ(FieldInputID, v))
}

// InputIDIn applies the In predicate on the "input_id" field.
func InputIDIn(vs ...string) predicate.CredentialInputSource {
	return predicate.CredentialInputSource(sql.FieldIn(FieldInputID, vs...))
}

// InputIDNotIn applies the NotIn predicate on the "input_id" field.
func InputIDNotIn(vs ...string) predicate.CredentialInputSource {
	return predicate.CredentialInputSource(sql.FieldNotIn(FieldInputID, vs...))
}

// InputIDGT applies the GT predicate on the "input_id" field.
func InputIDGT(v string) predicate.CredentialInputSource {
	return predicate.CredentialInputSource(sql.FieldGT(FieldInputID, v))
}

// InputIDGTE applies the GTE predicate on the "input_id" field.
func InputIDGTE(v string) predicate.CredentialInputSource {
	return predicate.CredentialInputSource(sql.FieldGTE(FieldInputID, v))
}

// InputIDLT applies the LT predicate on the "input_id" field.
func InputIDLT(v string) predicate.CredentialInputSource {
	return predicate.CredentialInputSource(sql.FieldLT(FieldInputID, v))
}

// InputIDLTE applies the LTE predicate on the "input_id" field.
func InputIDLTE(v string) predicate.CredentialInputSource {
	return predicate.CredentialInputSource(sql.FieldLTE(FieldInputID, v))
}

// InputIDContains applies the Contains predicate on the "input_id" field.
func InputIDContains(v string) predicate.CredentialInputSource {
	return predicate.CredentialInputSource(sql.FieldContains(FieldInputID, v))
}

// InputIDHasPrefix applies the HasPrefix predicate on the "input_id" field.
func InputIDHasPrefix(v string) predicate.CredentialInputSource {
	return predicate.CredentialInputSource(sql.FieldHasPrefix(FieldInputID, v))
}

// InputIDHasSuffix applies the HasSuffix predicate on the "input_id" field.
func InputIDHasSuffix(v string) predicate.CredentialInputSource {
	return predicate.CredentialInputSource(sql.FieldHasSuffix(FieldInputID, v))
}

// InputIDEqualFold applies the EqualFold predicate on the "input_id" field.
func InputIDEqualFold(v string) predicate.CredentialInputSource {
	return predicate.CredentialInputSource(sql.FieldEqualFold(FieldInputID, v))
}

// InputIDContainsFold applies the ContainsFold predicate on the "input_id" field.
func InputIDContainsFold(v string) predicate.CredentialInputSource {
	return predicate.CredentialInputSource(sql.FieldContainsFold(FieldInputID, v))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.CredentialInputSource {
	return predicate.CredentialInputSource(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.CredentialInputSource {
	return predicate.CredentialInputSource(sql.FieldNotNull(FieldMetadata))
}

// HasTargetCredential applies the HasEdge predicate on the "target_credential" edge.
func HasTargetCredential() predicate.CredentialInputSource {
	return predicate.CredentialInputSource(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TargetCredentialTable, TargetCredentialColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTargetCredentialWith applies the HasEdge predicate on the "target_credential" edge with a given conditions (other predicates).
func HasTargetCredentialWith(preds ...predicate.Credential) predicate.CredentialInputSource {
	return predicate.CredentialInputSource(func(s *sql.Selector) {
		step := newTargetCredentialStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSourceCredential applies the HasEdge predicate on the "source_credential" edge.
func HasSourceCredential() predicate.CredentialInputSource {
	return predicate.CredentialInputSource(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SourceCredentialTable, SourceCredentialColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSourceCredentialWith applies the HasEdge predicate on the "source_credential" edge with a given conditions (other predicates).
func HasSourceCredentialWith(preds ...predicate.Credential) predicate.CredentialInputSource {
	return predicate.CredentialInputSource(func(s *sql.Selector) {
		step := newSourceCredentialStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CredentialInputSource) predicate.CredentialInputSource {
	return predicate.CredentialInputSource(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CredentialInputSource) predicate.CredentialInputSource {
	return predicate.CredentialInputSource(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CredentialInputSource) predicate.CredentialInputSource {
	return predicate.CredentialInputSource(sql.NotPredicates(p))
}
