package file

import (
	"context"
	"fmt"

	"github.com/Subject-Void-LLC/the-pleiades/pkg/capability"
	"github.com/Subject-Void-LLC/the-pleiades/pkg/collection"
	"github.com/Subject-Void-LLC/the-pleiades/pkg/inventory"
	"github.com/Subject-Void-LLC/the-pleiades/pkg/remoteexec"
	"github.com/Subject-Void-LLC/the-pleiades/pkg/remotefile"
	"github.com/Subject-Void-LLC/the-pleiades/pkg/sdk"
)

// This file implements "file.copy", generated by
// pleiades forge new-collection and then hand-completed.
//
// It is the one method in this namespace whose subject is a file's
// CONTENT rather than the metadata around it, and that changes what
// "read before acting" has to mean. file.permissions can compare three
// short strings; this one has to decide whether two byte streams are the
// same without moving either of them, which is why the comparison is a
// SHA-256 computed on the device and compared against a SHA-256 computed
// here. Same bytes means no write is sent at all, not a write that
// happens to land identical bytes: a rewritten file has a new inode, a
// new mtime and a new moment where a reader can see it change, and a
// converged run must produce none of those.
//
// IT SUPPORTS content ONLY, never src, and the refusal is written out
// below rather than left as a missing feature.

// Parameter names, which are ansible.builtin.copy's own names. A person
// converting a playbook that writes a file with dest, content, mode,
// owner and group should be renaming nothing.
//
// The copy prefix is scaffolding, not style, and the reasoning is
// file.permissions': every method in this namespace reads a path and
// several read a mode, an owner and a group, so these belong in one
// shared file the way internal/catalog/exec/exec.go holds that
// namespace's shared names. That file does not exist yet and creating it
// from inside one method's own file would collide with the sibling
// methods being written alongside this one. Prefixed here, to be hoisted
// there, at which point the near-duplicate helpers at the bottom of this
// file and of permissions.go collapse into one copy.
const (
	copyParamDest    = "dest"
	copyParamSrc     = "src"
	copyParamContent = "content"
	copyParamMode    = "mode"
	copyParamOwner   = "owner"
	copyParamGroup   = "group"
)

// Stat keys this method returns beyond the parameter names above, both
// ansible.builtin.copy's own return names.
const (
	copyStatChecksum = "checksum"
	copyStatSize     = "size"
)

// copyCreateMode is the mode a file this method CREATES gets when the
// task names none.
//
// Ansible derives that default from the device's umask. This does not,
// deliberately. A umask-derived default is a different value on every
// device, so it cannot be written in the reference page, cannot be
// asserted in a test, and makes the after state of a create unknowable
// until the run happens. A fixed default is knowable, and 0600 is the
// direction to be wrong in: a file created too private breaks a reader
// loudly and visibly, while one created too public leaks quietly. A task
// that wants anything else says so, which is one line in the runbook.
//
// It applies to a CREATE only. An existing file keeps the mode it has
// unless the task names one; see copyEffective.
const copyCreateMode = "0600"

// FQCNs this method emits as an inverse. They are the real methods a
// rollback would dispatch, so a typo here is a rollback that cannot run.
const (
	copyInverseRemove      = "file.remove"
	copyInversePermissions = "file.permissions"
)

func init() {
	collection.MustRegister(collection.Descriptor{
		Name: "file.copy",
		Manifest: collection.Manifest{
			SupportedTransports: []string{
				"ssh",
			},
			RequiredCapabilities: []capability.Name{
				capability.NamePOSIXFileSystem,
			},
			// Writing under /etc usually needs root, and this stays false
			// anyway: elevation is a property of the individual task, since
			// writing into a directory the connecting account already owns
			// needs nothing. Declaring it unconditionally would mark every
			// copy as privileged and teach a reader to ignore the field.
			ExecutionContext: collection.ExecutionContext{
				RequiresElevation: false,
			},
			PlatformTargets: nil,
			EngineVersion:   ">=1.0.0",
			Status:          collection.StatusImplemented,
			// True, and the Notes carry the half that is NOT restored. The
			// run decides which inverse it actually emits: a created file
			// undoes to a removal, an existing one undoes to its former
			// attributes, and a converged run emits nothing at all. That is
			// exactly why the concrete instruction is emitted at run time
			// and only the yes-or-no lives here.
			Reversibility: collection.Reversibility{
				Reversible: true,
				Notes: "A run that created the file emits a file.remove that deletes it again, which is a complete undo. A run that " +
					"OVERWROTE an existing file emits a file.permissions restoring the mode, owner and group it found, and the previous " +
					"CONTENT is not restored by it: those bytes are not read before the write and are not journaled anywhere, so once " +
					"the new content lands the old content is gone. The emitted instruction says so in its own description rather than " +
					"leaving a rollback to discover it. A run that changed nothing emits nothing.",
			},
			Doc: copyDoc(),
		},
		Invoke: Copy,
	})
}

// copyDoc is this method's reference documentation, kept out of the
// registration above so the manifest fields stay readable.
//
// It is duplicated into internal/forge/catalogdata, which is the source
// the scaffolder is driven from, and internal/archtest's
// TestCatalogDataDocsMatchTheRegistry compares the two for equality so
// the copies cannot drift.
func copyDoc() collection.Doc {
	return collection.Doc{
		Summary:     "Writes inline content to a file on the target, only when the bytes there differ.",
		Description: "Writes content to a path on the device, comparing a SHA-256 of the content against a SHA-256 the device computes of what is already there, so a run that finds the same bytes sends no write at all and reports no change. A write that does happen is atomic: the bytes go to a temporary file in the destination's own directory and are renamed over it, so a reader of the path sees either the whole old file or the whole new one and never a half-written one. Only content is supported; src is refused rather than half-implemented, because src names a file beside the runbook on the controller while this method runs on the runner, which under the Walk tier is a per-task container that cannot see it. Anything at dest that is not a regular file is refused rather than replaced. An existing file keeps the mode, owner and group it had unless the task names them, matching what Ansible's own atomic move does; a file this method creates and the task gave no mode gets 0600, which is a fixed, documentable default rather than Ansible's umask-derived one.",
		Params: []collection.Param{
			{Name: copyParamDest, Type: "string", Required: true, Description: "The path to write on the device. Its parent directory must already exist: this method writes a file and never creates the directories above it, which is file.directory's job."},
			{Name: copyParamContent, Type: "string", Required: true, Description: "The bytes to write, used verbatim: nothing is appended, so a file that should end in a newline needs one in the value. An empty string is a real request and truncates the file to nothing. Quote a value YAML would otherwise read as a number or a boolean, since a non-string is refused rather than rendered."},
			{Name: copyParamSrc, Type: "string", Description: "Refused, always. In Ansible src names a file beside the playbook and the controller reads it; here a Collection method runs on the runner, which under the Walk tier is a per-task container with no access to the controller's filesystem, so honoring src would work on the Crawl tier and fail on the Walk tier. Read the file into a variable and pass it as content instead."},
			{Name: copyParamMode, Type: "string", Description: "The permission bits as one to four octal digits, quoted, for example \"0644\". Quote it: an unquoted 0644 is a number in YAML, not text. A symbolic mode such as u+x is refused, because it cannot be compared against the mode the device reports and the task would then report changed on every run. Left unset, an existing file keeps its mode and a newly created one gets 0600."},
			{Name: copyParamOwner, Type: "string", Description: "The user name to give the file. A numeric id is refused: chown reads an all-digit argument as an id while the device reports names, so the two could never compare equal and the task would report changed forever. Left unset, an existing file keeps its owner and a new one belongs to the connecting account."},
			{Name: copyParamGroup, Type: "string", Description: "The group name to give the file, refused as a numeric id for the same reason owner is."},
			{Name: sdk.ParamInsecureSkipHostKeyVerify, Type: "bool", Default: "false", Description: "Skip SSH host key verification for this task. This removes protection against a machine in the middle answering for the device, so set it only for a target you have decided does not need it."},
		},
		Returns: []collection.ReturnField{
			{Name: copyParamDest, Type: "string", Returned: "always", Description: "The path this task wrote."},
			{Name: copyStatChecksum, Type: "string", Returned: "always", Description: "The SHA-256 of the file's contents in hex, read back from the device after any write rather than computed from what was asked for. Ansible's copy reports a SHA-1 here; this reports SHA-256, which is the one hash this platform computes."},
			{Name: copyParamMode, Type: "string", Returned: "always", Description: "The permission bits the file carries now, as four octal digits."},
			{Name: copyParamOwner, Type: "string", Returned: "always", Description: "The user name owning the file now."},
			{Name: copyParamGroup, Type: "string", Returned: "always", Description: "The group owning the file now."},
			{Name: copyStatSize, Type: "int", Returned: "always", Description: "The file's size in bytes now."},
			{Name: sdk.StatDiff, Type: "dict", Returned: "always", Description: "The before and after state of the path, each holding its kind, mode, owner, group, size, modification time and the checksum of its contents. Recorded even when nothing changed, in which case the two halves are identical."},
			{Name: sdk.StatInverse, Type: "dict", Returned: "when something changed", Description: "The concrete task that undoes this run: a file.remove when this run created the file, or a file.permissions restoring the attributes it found when the file already existed. Absent from a run that changed nothing, which is how the record says undoing it means doing nothing. When the previous content was overwritten, the description says plainly that those bytes are not restored."},
		},
		Examples: []collection.Example{
			{
				Name:        "Write a configuration file",
				RunbookYAML: "- name: Install the agent configuration\n  file.copy:\n    dest: /etc/pleiades/agent.yaml\n    content: |\n      endpoint: https://controller.internal:8443\n      verify: true\n    mode: \"0644\"\n",
			},
			{
				Name:        "Write a private file",
				RunbookYAML: "- name: Drop the deploy token\n  file.copy:\n    dest: /etc/pleiades/token\n    content: \"{{ deploy_token }}\"\n    mode: \"0600\"\n    owner: pleiades\n    group: pleiades\n",
			},
			{
				Name:        "Truncate a file to nothing",
				RunbookYAML: "- name: Empty the local override file\n  file.copy:\n    dest: /etc/app/local.conf\n    content: \"\"\n",
			},
		},
		SeeAlso: []string{"file.template", "file.touch", "file.permissions", "file.remove"},
	}
}

// Copy implements the "file.copy" collection method: it makes a path hold
// exactly the content the task gives it, with the attributes it asks for.
//
// # The order of operations is the contract
//
// Everything a runbook got wrong is refused before the first packet, so a
// mistake in a task costs no round trip and names the runbook rather than
// the device. Then the path is read, then its content is compared by
// checksum, then a write is sent only if those differ, then only the
// attributes that differ are applied, and only then is anything recorded.
//
// # Why the state is read AGAIN after a write
//
// This is the part that is easy to get wrong and impossible to notice.
// remotefile.Write is atomic, which means it does not modify the file in
// place: it creates a temporary, fills it and renames it over the
// destination. The renamed file is a NEW inode carrying mktemp's
// attributes, not the destination's, so everything read before the write
// describes a file that no longer exists. An implementation that then
// compared the requested mode against that stale read would skip a chmod
// it genuinely needed and leave a 0644 configuration file at 0600, having
// reported success. So the write is followed by a fresh read, and the
// attribute pass compares against that.
//
// The same rule produces the after half of the diff: it is a real read of
// the device, never the request echoed back. A method that recorded what
// it asked for would report a converged file it had failed to change.
func Copy(ctx context.Context, rc sdk.RunbookContext, device inventory.InventoryItem, params map[string]any) (collection.Result, error) {
	const fqcn = "file.copy"

	req, err := copyParseRequest(params)
	if err != nil {
		return collection.Result{}, fmt.Errorf("%s: %w", fqcn, err)
	}

	conn, err := sdk.Connect(ctx, rc, device, params, fqcn)
	if err != nil {
		return collection.Result{}, err
	}
	defer func() { _ = conn.Close() }()

	before, err := remotefile.Stat(ctx, conn, req.dest)
	if err != nil {
		return collection.Result{}, fmt.Errorf("%s: %w", fqcn, err)
	}
	// Anything that is not a regular file is refused rather than replaced.
	// remotefile.Write renames over the destination, which would delete a
	// directory's entry, replace a symbolic link with a file instead of
	// writing through it, and destroy a socket or device node, none of
	// which this method could put back. Ansible copies INTO a directory
	// named as dest, using the source file's basename; with content and no
	// src there is no basename to use, so that behavior has no meaning
	// here and guessing a filename would be worse than refusing.
	if before.Exists() && before.Kind != remotefile.KindFile {
		return collection.Result{}, fmt.Errorf("%s: %s is a %s, not a regular file: this method would replace it rather than write through it, and could not put it back", fqcn, req.dest, before.Kind)
	}

	// The whole idempotence decision, in two hashes. The device's half is
	// computed ON the device precisely so a large file is not dragged
	// across the network to answer a question 64 characters settle.
	wanted := remotefile.ChecksumOf([]byte(req.content))
	var found string
	if before.Exists() {
		// The existence flag Checksum also returns is discarded on purpose:
		// Stat above already answered that question, and a file deleted in
		// between reads back as an empty checksum, which differs from wanted
		// and correctly turns into a write.
		if found, _, err = remotefile.Checksum(ctx, conn, req.dest); err != nil {
			return collection.Result{}, fmt.Errorf("%s: %w", fqcn, err)
		}
	}

	wrote := found != wanted
	if wrote {
		if err := remotefile.Write(ctx, conn, req.dest, []byte(req.content)); err != nil {
			return collection.Result{}, fmt.Errorf("%s: %w", fqcn, err)
		}
	}

	// Whether the TASK changed attributes is decided against what was
	// found before anything ran, not against what the write left behind.
	// The write's own attribute churn is this method's doing, not the
	// runbook's, and reporting it as a change the task made would make
	// every content update look like a permission change as well.
	attrsDiffer := copyAttributesDiffer(req.attrs, before)
	changed := wrote || attrsDiffer

	current := before
	if wrote {
		// See this function's doc comment: after an atomic write, before is
		// a description of an inode that is gone.
		if current, err = remotefile.Stat(ctx, conn, req.dest); err != nil {
			return collection.Result{}, fmt.Errorf("%s: %w: the content was written before this failed, so %s holds the new bytes with whatever attributes the write left on them", fqcn, err, req.dest)
		}
	}

	// Apply's own changed flag is deliberately discarded. It reports
	// whether a command was sent, which after a write includes putting
	// back the attributes the write disturbed, and that is not something
	// the task asked for; attrsDiffer above is the honest answer and is
	// computed from the same comparison Apply makes.
	if _, err := remotefile.Apply(ctx, conn, req.dest, copyEffective(req.attrs, before), current); err != nil {
		if wrote {
			return collection.Result{}, fmt.Errorf("%s: %w: the content was written before this failed, so %s holds the new bytes but not the attributes the task asked for", fqcn, err, req.dest)
		}
		return collection.Result{}, fmt.Errorf("%s: %w", fqcn, err)
	}

	after, afterSum := before, found
	if changed {
		if after, afterSum, err = copyReadBack(ctx, conn, req.dest); err != nil {
			return collection.Result{}, fmt.Errorf("%s: %w: the change was applied, so the device is not in the state this reports", fqcn, err)
		}
	}

	if err := sdk.RecordDiff(rc, sdk.Diff{
		Before: copyState(before, found),
		After:  copyState(after, afterSum),
	}); err != nil {
		return collection.Result{}, fmt.Errorf("%s: %w", fqcn, err)
	}
	// Only a run that really changed something emits an inverse. The
	// absence on a converged run is the record saying "undoing this means
	// doing nothing", which is a different statement from "nothing was
	// recorded" and the reason it must not be emitted unconditionally.
	if changed {
		if err := copyRecordInverse(rc, req.dest, before, wrote); err != nil {
			return collection.Result{}, fmt.Errorf("%s: %w", fqcn, err)
		}
	}
	if err := copyRecordStats(rc, req.dest, after, afterSum); err != nil {
		return collection.Result{}, fmt.Errorf("%s: %w", fqcn, err)
	}

	return collection.Result{Changed: changed}, nil
}

// copyRequest is everything this method needs out of the task's params.
type copyRequest struct {
	dest    string
	content string
	attrs   remotefile.Attributes
}

// copyParseRequest reads and checks the task's params, returning what to
// write and where.
//
// It runs before the connection is opened, on purpose. Every refusal
// below is a mistake in the runbook rather than a condition on the
// device, and one that costs a TCP connect, a key exchange and an
// authentication round before reporting itself is a slower answer to the
// same question.
func copyParseRequest(params map[string]any) (copyRequest, error) {
	var none copyRequest

	// src is answered FIRST, before the missing-content refusal it would
	// otherwise trigger. A task carrying src is a converted playbook, and
	// telling its author "content is required" would send them to add a
	// parameter when what they need is to understand why the one they
	// wrote cannot work here. Presence is enough: a task that mentions src
	// meant to use it, whatever value it gave.
	if _, present := params[copyParamSrc]; present {
		return none, fmt.Errorf("%s is not supported: it names a file beside the runbook on the controller, and a Collection method runs on the runner, which under the Walk tier is a per-task container with no access to that filesystem. Honoring it would work on the Crawl tier and fail on the Walk tier, so it is refused on both. Read the file into a variable and pass it as %s instead",
			copyParamSrc, copyParamContent)
	}

	// Read all five through one loop rather than five near-identical
	// blocks: the type refusal is the same sentence for each of them, and
	// five copies of it is five places for one of them to drift.
	values := make(map[string]string, 5)
	for _, key := range []string{copyParamDest, copyParamContent, copyParamMode, copyParamOwner, copyParamGroup} {
		value, err := textParam(params, key)
		if err != nil {
			return none, err
		}
		values[key] = value
	}

	dest := values[copyParamDest]
	if dest == "" {
		return none, fmt.Errorf("%s is required", copyParamDest)
	}

	// Content is checked for PRESENCE, not for emptiness, and the two are
	// different requests. An empty string is a real instruction to
	// truncate the file to nothing, which a runbook does deliberately, so
	// treating it as absent would refuse the one task that needs it most
	// clearly.
	if raw, present := params[copyParamContent]; !present || raw == nil {
		return none, fmt.Errorf("%s is required: it is the only source this method accepts, since %s cannot be read from where a method runs", copyParamContent, copyParamSrc)
	}

	req := copyRequest{
		dest:    dest,
		content: values[copyParamContent],
		attrs: remotefile.Attributes{
			Mode:  values[copyParamMode],
			Owner: values[copyParamOwner],
			Group: values[copyParamGroup],
		},
	}

	if err := checkMode(copyParamMode, req.attrs.Mode); err != nil {
		return none, err
	}
	if err := checkName(copyParamOwner, req.attrs.Owner); err != nil {
		return none, err
	}
	if err := checkName(copyParamGroup, req.attrs.Group); err != nil {
		return none, err
	}

	return req, nil
}

// copyEffective is the attribute set the device must end up with, which
// is what the task asked for filled in from what was already there.
//
// The filling in is the important half and it mirrors what Ansible's own
// atomic move does. An atomic write replaces the destination with a fresh
// inode carrying mktemp's 0600 and the connecting account's ownership, so
// a method that applied only the attributes the task named would silently
// re-permission every file it updated: a 0644 configuration file that
// changed content would come back 0600 and the service reading it would
// stop, with the task reporting success. Naming nothing must mean
// "leave it as it was", so an existing file's own values are what get
// re-applied.
//
// A file being CREATED has no former values to keep, so an unnamed mode
// becomes copyCreateMode; see that constant for why it is fixed rather
// than derived from the device's umask. Owner and group are left empty
// there, which leaves the file belonging to the connecting account, the
// same account the temporary was created as.
func copyEffective(want remotefile.Attributes, before remotefile.Info) remotefile.Attributes {
	effective := want
	if !before.Exists() {
		if effective.Mode == "" {
			effective.Mode = copyCreateMode
		}
		return effective
	}
	if effective.Mode == "" {
		effective.Mode = before.Mode
	}
	if effective.Owner == "" {
		effective.Owner = before.Owner
	}
	if effective.Group == "" {
		effective.Group = before.Group
	}
	return effective
}

// copyAttributesDiffer reports whether an attribute the task NAMED
// differs from what the device already had.
//
// Only named attributes count. The ones copyEffective fills in from
// before are, by construction, equal to before, and counting them would
// make a converged run report a change.
func copyAttributesDiffer(want remotefile.Attributes, before remotefile.Info) bool {
	switch {
	case want.Mode != "" && remotefile.NormalizeMode(want.Mode) != before.Mode:
		return true
	case want.Owner != "" && want.Owner != before.Owner:
		return true
	case want.Group != "" && want.Group != before.Group:
		return true
	}
	return false
}

// copyReadBack reads the path's state and the checksum of its contents
// from the device, which together are the after half of the diff.
//
// Two round trips rather than one because stat has no checksum field and
// nothing computes both at once. They are worth it: the after state is
// the one thing a method must never assert, and a run that reported the
// content it intended to write while the device held something else is
// exactly the defect this pair of reads exists to make impossible.
//
// It deliberately does not verify that the path still exists. If another
// actor removed it between the write and this read, an absent after state
// is the truth about the device, and reporting the truth is better than
// inventing a failure for a race this method did not lose.
func copyReadBack(ctx context.Context, conn *remoteexec.Conn, filePath string) (remotefile.Info, string, error) {
	info, err := remotefile.Stat(ctx, conn, filePath)
	if err != nil {
		return remotefile.Info{}, "", err
	}
	sum, _, err := remotefile.Checksum(ctx, conn, filePath)
	if err != nil {
		return remotefile.Info{}, "", err
	}
	return info, sum, nil
}

// copyState renders one half of the diff: what remotefile.Info records
// about the path, plus the checksum of its contents.
//
// The checksum is what makes this method's diff mean anything. Every
// other key here is metadata, and two files with the same mode, owner,
// group and even the same size can hold completely different bytes, so a
// diff without it could show a content rewrite as no difference at all.
func copyState(info remotefile.Info, sum string) map[string]any {
	state := info.Map()
	if info.Exists() {
		state[copyStatChecksum] = sum
	}
	return state
}

// copyRecordInverse emits the concrete task that undoes this run.
//
// # Two runs, two different inverses, which is the whole reason this is
// emitted rather than declared
//
// A run that CREATED the file undoes to a removal: nothing was at the
// path, so deleting it destroys nothing the run did not make.
//
// A run that found a file already there undoes to its former attributes,
// and NEVER to a removal. Removing it would destroy a file the run did
// not create, which is the worst thing a rollback can do and is exactly
// what a static "the inverse of copy is remove" declaration would have
// told it to do.
//
// The second case is emitted even when the run only changed content and
// left the attributes alone, and that is deliberate. There is nothing
// that can restore the old bytes, so the honest record is an instruction
// that restores what it can plus a description saying what it cannot;
// emitting nothing would say "undoing this means doing nothing", which is
// a different and false statement. Running it costs nothing when the
// attributes never moved, because file.permissions is itself convergent
// and sends no command for a value that already matches.
//
// One known limit, recorded rather than hidden: stat prints a numeric uid
// or gid as the owner or group name when the device has no passwd or
// group entry for it, and file.permissions refuses an all-digit name. An
// inverse captured from such a device names the account this platform
// cannot compare, and would be refused if it were ever dispatched.
func copyRecordInverse(rc sdk.RunbookContext, dest string, before remotefile.Info, wrote bool) error {
	if !before.Exists() {
		return sdk.RecordInverse(rc, sdk.Inverse{
			FQCN:        copyInverseRemove,
			Params:      map[string]any{"path": dest},
			Description: "Removes " + dest + ", which this run created. Nothing was at that path beforehand, so this destroys nothing the run did not make.",
		})
	}

	description := "Restores the mode, owner and group " + dest + " had before this run."
	if wrote {
		description += " It does NOT restore the previous content: those bytes were overwritten and were never read, so nothing on this platform holds them. The file keeps this run's content."
	}
	return sdk.RecordInverse(rc, sdk.Inverse{
		FQCN: copyInversePermissions,
		Params: map[string]any{
			"path":  dest,
			"mode":  before.Mode,
			"owner": before.Owner,
			"group": before.Group,
		},
		Description: description,
	})
}

// copyRecordStats writes the stats this method returns, which are
// ansible.builtin.copy's own return names so a converted playbook's later
// tasks read what they already read.
//
// They report the state the file is in NOW, read back from the device,
// not what the task was asked for. That is the same thing on a successful
// run and is the distinction that matters when a task named no mode:
// the mode, owner and group still come back, describing the file rather
// than the request.
func copyRecordStats(rc sdk.RunbookContext, dest string, after remotefile.Info, sum string) error {
	for key, value := range map[string]any{
		copyParamDest:    dest,
		copyStatChecksum: sum,
		copyParamMode:    after.Mode,
		copyParamOwner:   after.Owner,
		copyParamGroup:   after.Group,
		copyStatSize:     after.Size,
	} {
		if err := rc.SetStat(key, value); err != nil {
			return err
		}
	}
	return nil
}
