package file

import (
	"context"
	"fmt"
	"path"

	"github.com/Subject-Void-LLC/the-pleiades/pkg/capability"
	"github.com/Subject-Void-LLC/the-pleiades/pkg/collection"
	"github.com/Subject-Void-LLC/the-pleiades/pkg/inventory"
	"github.com/Subject-Void-LLC/the-pleiades/pkg/remoteexec"
	"github.com/Subject-Void-LLC/the-pleiades/pkg/remotefile"
	"github.com/Subject-Void-LLC/the-pleiades/pkg/sdk"
)

// This file implements "file.directory", generated by
// pleiades forge new-collection and then hand-completed.
//
// It is ansible.builtin.file with state=directory and nothing else.
// Removing a directory is file.remove, and changing the attributes of
// something that already exists without caring what it is is
// file.permissions, so this method's whole job is the one sentence its
// Summary gives it: the directory exists, and it has the mode, owner and
// group the task asked for.
//
// # Why the identifiers here carry the method's name
//
// Six methods live in this one package, each in its own file, and Go has
// no file-level scope: an unprefixed paramPath declared here would
// collide with the identical constant the next method needs. So every
// identifier below is prefixed with the method it belongs to. The natural
// cleanup once the namespace is finished is a shared file.go holding the
// parameter names the whole namespace agrees on, exactly as exec.go does
// for the exec namespace, and these move there rather than staying
// prefixed forever.

// Parameter names this method reads. They are ansible.builtin.file's own
// spellings, because this platform is a superset of Ansible rather than a
// new vocabulary: a person converting a playbook should be renaming
// nothing.
//
// Ansible's file module also takes state, recurse, follow and force. state
// is not read here because the FQCN already says it: a task naming
// file.directory has said state=directory. The other three are out of
// scope for this method rather than silently ignored; see Directory's own
// doc comment for what that means for a symlink.
const (
	dirParamPath  = "path"
	dirParamMode  = "mode"
	dirParamOwner = "owner"
	dirParamGroup = "group"
)

// dirStatPath is the stat this method emits naming the directory it acted
// on, matching what ansible.builtin.file returns so a converted playbook's
// later tasks read the same name.
const dirStatPath = "path"

func init() {
	collection.MustRegister(collection.Descriptor{
		Name: "file.directory",
		Manifest: collection.Manifest{
			SupportedTransports: []string{
				"ssh",
			},
			RequiredCapabilities: []capability.Name{
				capability.NamePOSIXFileSystem,
			},
			ExecutionContext: collection.ExecutionContext{
				// Creating a directory under a path the connecting account
				// already owns needs nothing extra, and that is the common
				// case. Setting owner or group almost always does need root,
				// but that is a property of those two parameters rather than
				// of the method, and declaring the whole method elevated
				// would demand privilege from every task that only creates a
				// directory in its own home.
				RequiresElevation: false,
			},
			PlatformTargets: nil,
			EngineVersion:   ">=0.2.0",
			Status:          collection.StatusImplemented,
			// True means this method can ever emit an inverse, not that
			// every run does. Which inverse it is cannot be declared here,
			// because it depends on what the run FOUND: creating the
			// directory undoes to a removal, and finding it already there
			// undoes to the attributes it had. See directoryRecordInverse,
			// and permRecordInverse for the reasoning in full.
			Reversibility: collection.Reversibility{
				Reversible: true,
				Notes: "A run that created the directory emits a file.remove naming it. That removal is deliberately not " +
					"recursive, so it refuses rather than destroying anything put inside the directory after this task ran. " +
					"A run that found the directory already there and only changed its mode, owner or group emits a " +
					"file.permissions carrying the old ones, which puts the attributes back and never removes the directory. " +
					"A converged run emits nothing at all. Parents a run created on the way to the directory are not removed by that undo.",
				Inverses: []sdk.InverseSpec{
					{FQCN: "file.remove", Record: []string{"path"}},
					{FQCN: "file.permissions", Record: []string{"path", "mode", "owner", "group"}},
				},
			},
			// A check reads the path, compares, and reports whether a real
			// run would create the directory or change its attributes,
			// sending nothing. See CheckDirectory.
			SupportsCheck: true,
			Doc:           directoryDoc(),
		},
		Invoke: Directory,
		Check:  CheckDirectory,
	})
}

// directoryDoc is this method's reference documentation, kept out of the
// registration above so the manifest fields stay readable rather than
// being buried under a page of prose.
func directoryDoc() collection.Doc {
	return collection.Doc{
		Summary:     "Makes sure a directory exists on the target, with the mode, owner and group the task asks for.",
		Description: "Ensures a directory exists at a path, creating any missing parents along the way exactly as mkdir -p does, and gives the directory, and every parent it creates, the mode, owner and group the task names, as Ansible does; a parent that already existed is never changed. This is ansible.builtin.file with state=directory; use file.remove to delete a directory and file.permissions to change attributes without creating anything. State is read before anything is written, so a run that finds the directory already correct reports no change, and only the attributes that actually differ are applied. If something that is not a directory already exists at the path, the task fails rather than replacing it: turning a file into a directory would destroy the file.",
		Params: []collection.Param{
			{Name: dirParamPath, Type: "string", Required: true, Description: "The directory to ensure exists. Missing parent directories are created too, the way mkdir -p does. Ansible creates parents implicitly and has no parameter for it, so neither does this."},
			{Name: dirParamMode, Type: "string", Description: "The permission bits in octal, written as a quoted string such as \"0755\". Quote it: an unquoted 0755 is read as a number by YAML and its leading zero is lost, so an unquoted value is refused rather than applied. A symbolic mode such as u+rwx is refused too, since it cannot be compared against the mode the device reports. Left unset, a new directory gets whatever the device's umask gives it and an existing one keeps the mode it has. Applies to the directory this task names and to every parent it creates on the way there, as ansible.builtin.file does, so a private tree is private all the way down; a parent that already existed keeps its mode."},
			{Name: dirParamOwner, Type: "string", Description: "The user name that should own the directory. A name rather than a numeric id, because a name is what the device reports back and therefore the only form this method can compare against. Given to every parent this task creates too, as mode is. Left unset, ownership is not touched."},
			{Name: dirParamGroup, Type: "string", Description: "The group name that should own the directory, under the same rule as owner: a name, not a numeric id, and given to every parent this task creates. Left unset, the group is not touched."},
			{Name: sdk.ParamInsecureSkipHostKeyVerify, Type: "bool", Default: "false", Description: "Skip SSH host key verification for this task. This removes protection against a machine in the middle answering for the device, so set it only for a target you have decided does not need it."},
		},
		Returns: []collection.ReturnField{
			{Name: dirStatPath, Type: "string", Returned: "always", Description: "The directory this task acted on."},
			{Name: sdk.StatDiff, Type: "dict", Returned: "always", Description: "What the path looked like before this task and what it looks like after, each holding exists, kind, mode, owner and group. Recorded even on a run that changed nothing, because \"it was already like this\" is what tells a later rollback to do nothing."},
		},
		Examples: []collection.Example{
			{
				Name:        "Create a directory tree",
				RunbookYAML: "- name: Make sure the release directory is there\n  file.directory:\n    path: /opt/app/releases/current\n",
			},
			{
				Name:        "Create it with a mode",
				RunbookYAML: "- name: Make a private directory\n  file.directory:\n    path: /var/lib/app/secrets\n    mode: \"0700\"\n",
			},
			{
				Name:        "Hand it to a service account",
				RunbookYAML: "- name: Own the data directory\n  file.directory:\n    path: /var/lib/app/data\n    owner: app\n    group: app\n    mode: \"0750\"\n",
			},
		},
		SeeAlso: []string{"file.remove", "file.permissions"},
	}
}

// Directory implements the "file.directory" collection method: it makes
// sure a directory exists at a path, with the attributes the task asked
// for.
//
// # What Changed means here
//
// exec.command established the contract for a method whose effect cannot
// be inspected, and this is the other half of it: this method CAN inspect
// what it is about to do, so it must. The path is read first, the wanted
// state is compared against what was found, and only the parts that
// differ are written. A second run over a converged device therefore
// reports Changed false, and that is the single property most worth
// protecting here, because a module that reports a change forever is
// indistinguishable from one that is genuinely fixing something every
// time.
//
// The comparison is what makes that work, so it is worth naming the two
// places it is easy to lose. A mode is compared normalized, since stat
// prints 755 and a runbook writes 0755 (remotefile.NormalizeMode). And
// owner and group are compared by NAME, which is why a numeric id is
// refused below rather than accepted: a uid can never equal the name stat
// reports, so accepting one would quietly produce a task that chowns on
// every run.
//
// # Why a non-directory is refused instead of replaced
//
// If something that is not a directory is already at the path, this fails
// and says what is there. The alternative is removing it first, which for
// a regular file means destroying data the runbook never mentioned, and
// for a symlink means destroying a link whose target is very likely the
// thing the author actually cared about. Ansible's file module will
// replace a file with a directory when force is set, and this method
// deliberately does not implement force yet: the refusal is the safe
// default, and a parameter that turns a safe default into a destructive
// one should arrive with its own tests rather than as a side effect of
// this one.
//
// A symlink is refused even when it points AT a directory, which is the
// case a naive implementation gets wrong: `test -d` follows the link and
// answers yes, so a module built on it would happily chmod and chown the
// link's target, a path the runbook never named. Ansible's follow
// parameter is what chooses that behavior there, and it is out of scope
// here, so this reports the link and stops.
//
// # What a partial failure leaves behind
//
// Creating the directory and setting its attributes are separate
// operations against a real device, so the second can fail after the
// first succeeded. When that happens the error says the directory was
// created, because an operator reading "chown failed" needs to know the
// device changed anyway. Re-running the task converges it: the directory
// now exists, so only the attributes are attempted the second time.
func Directory(ctx context.Context, rc sdk.RunbookContext, device inventory.InventoryItem, params map[string]any) (collection.Result, error) {
	return directory(ctx, rc, device, params, collection.ModeExecute)
}

// CheckDirectory is "file.directory" in check mode: it reads the path and
// reports whether Directory would create it or change its attributes, and
// changes nothing.
//
// It runs the same body as Directory (directory, below), so it parses the
// same params, refuses the same modes and names, reads the same path and
// refuses the same file or symlink standing where the directory should
// be. It differs in three places: it sends no mkdir, chmod or chown; its
// diff's after half is remotefile's prediction of what a real run would
// leave rather than a read-back; and it records no inverse, since nothing
// was done that could be undone.
func CheckDirectory(ctx context.Context, rc sdk.RunbookContext, device inventory.InventoryItem, params map[string]any) (collection.Result, error) {
	return directory(ctx, rc, device, params, collection.ModeCheck)
}

// directory is the one body Directory and CheckDirectory share. mode
// decides only whether anything is written; every read and every refusal
// happens in both.
func directory(ctx context.Context, rc sdk.RunbookContext, device inventory.InventoryItem, params map[string]any, mode collection.Mode) (collection.Result, error) {
	const fqcn = "file.directory"

	// Both reads happen before the connection is opened, so a runbook
	// mistake costs no round trip and the error names the runbook rather
	// than the device.
	dirPath, err := sdk.RequiredStringParam(params, dirParamPath)
	if err != nil {
		return collection.Result{}, fmt.Errorf("%s: %w", fqcn, err)
	}

	want, err := directoryAttributes(params)
	if err != nil {
		return collection.Result{}, fmt.Errorf("%s: %w", fqcn, err)
	}

	conn, err := sdk.Connect(ctx, rc, device, params, fqcn)
	if err != nil {
		return collection.Result{}, err
	}
	defer func() { _ = conn.Close() }()

	// The read that the whole contract rests on. It answers three
	// questions at once: whether anything is there, whether what is there
	// is a directory, and what its current attributes are, which is both
	// the "before" half of the diff and the thing the wanted attributes
	// are compared against.
	before, err := remotefile.Stat(ctx, conn, dirPath)
	if err != nil {
		return collection.Result{}, fmt.Errorf("%s: %w", fqcn, err)
	}

	switch before.Kind {
	case remotefile.KindAbsent, remotefile.KindDirectory:
		// The two states this method can converge.
	default:
		return collection.Result{}, fmt.Errorf("%s: %s is %s, not a directory: refusing to replace it, since removing what is there would destroy it",
			fqcn, dirPath, describeDirectoryKind(before))
	}

	if mode == collection.ModeCheck {
		return checkDirectory(rc, dirPath, want, before)
	}

	created := false
	var parents []string
	if !before.Exists() {
		// The parents mkdir -p is about to create, found first so each can
		// be given the task's attributes, as ansible.builtin.file gives
		// them: a private directory under a new parent is otherwise
		// reachable through a parent the umask left open. Only looked for
		// when there are attributes to give.
		if !want.Empty() {
			if parents, err = missingParents(ctx, conn, dirPath); err != nil {
				return collection.Result{}, fmt.Errorf("%s: %w", fqcn, err)
			}
		}
		// Parents included, because that is what ansible.builtin.file does
		// and what mkdir -p means. Nothing checks afterward whether the
		// directory appeared: mkdir reports its own failure, and a second
		// stat purely to confirm success would cost a round trip to learn
		// what a non-zero exit status already said.
		if err := remotefile.MakeDirectory(ctx, conn, dirPath, true); err != nil {
			return collection.Result{}, fmt.Errorf("%s: %w", fqcn, err)
		}
		created = true
	}

	// before is the freshly-absent Info on the create path, whose Mode,
	// Owner and Group are empty, so every named attribute differs from it
	// and every named attribute gets applied. That is correct rather than
	// accidental: a directory that has just been created has whatever the
	// umask gave it, which is never what the task asked for.
	attributesChanged, err := remotefile.Apply(ctx, conn, dirPath, want, before)
	if err != nil {
		if created {
			return collection.Result{}, fmt.Errorf("%s: created %s but could not set its attributes: %w", fqcn, dirPath, err)
		}
		return collection.Result{}, fmt.Errorf("%s: %w", fqcn, err)
	}
	// The created parents, deepest first, so a parent's new mode can never
	// stop the chmod of the directory below it.
	for i := len(parents) - 1; i >= 0; i-- {
		if _, err := remotefile.Apply(ctx, conn, parents[i], want, remotefile.Info{Kind: remotefile.KindAbsent}); err != nil {
			return collection.Result{}, fmt.Errorf("%s: created %s but could not set the attributes of %s, a parent it created: %w", fqcn, dirPath, parents[i], err)
		}
	}

	changed := created || attributesChanged

	// The "after" half is read back from the device rather than assembled
	// from what was asked for, so the diff records what IS rather than
	// what was intended. They differ more often than they should: a mode
	// applied to a directory on a filesystem mounted with restrictive
	// options, or a chown that a policy layer partially honored, both
	// report success and leave something other than the request.
	//
	// A converged run skips the read entirely, since nothing was written
	// and a second stat could only return what the first one already did.
	after := before
	if changed {
		if after, err = remotefile.Stat(ctx, conn, dirPath); err != nil {
			return collection.Result{}, fmt.Errorf("%s: %w", fqcn, err)
		}
	}

	if err := rc.SetStat(dirStatPath, dirPath); err != nil {
		return collection.Result{}, fmt.Errorf("%s: %w", fqcn, err)
	}
	if err := sdk.RecordDiff(rc, sdk.Diff{Before: before.Map(), After: after.Map()}); err != nil {
		return collection.Result{}, fmt.Errorf("%s: %w", fqcn, err)
	}
	if err := directoryRecordInverse(rc, dirPath, created, attributesChanged, before); err != nil {
		return collection.Result{}, fmt.Errorf("%s: %w", fqcn, err)
	}

	return collection.Result{Changed: changed}, nil
}

// checkDirectory finishes a check once directory has read the path and
// found it absent or a directory: it works out what Directory would do and
// records that, writing nothing.
//
// The two decisions are the ones Directory acts on. A missing path would
// be created; an existing one would have its attributes changed exactly
// when remotefile.Differs says so, which is the comparison remotefile.Apply
// itself makes. A new directory needs no Differs call: every attribute the
// task names gets applied to it, as Directory's own comment on the create
// path explains.
//
// The after half is remotefile's Prediction, which leaves out what only
// the device can decide (a new directory's umask-given mode, its owner
// when the task names none) rather than filling those in with a guess.
func checkDirectory(rc sdk.RunbookContext, path string, want remotefile.Attributes, before remotefile.Info) (collection.Result, error) {
	const fqcn = "file.directory"

	after := before.Map()
	changed := false
	switch {
	case !before.Exists():
		after = remotefile.PredictCreate(remotefile.KindDirectory, want).Map()
		changed = true
	case remotefile.Differs(want, before):
		after = remotefile.PredictApply(want, before).Map()
		changed = true
	}

	if err := rc.SetStat(dirStatPath, path); err != nil {
		return collection.Result{}, fmt.Errorf("%s: %w", fqcn, err)
	}
	if err := sdk.RecordDiff(rc, sdk.Diff{Before: before.Map(), After: after}); err != nil {
		return collection.Result{}, fmt.Errorf("%s: %w", fqcn, err)
	}
	return collection.Result{Changed: changed}, nil
}

// directoryRecordInverse writes the instruction that undoes this run,
// which is a different instruction depending on what the run found.
//
// # The distinction this makes is the dangerous one
//
// Getting it wrong deletes a directory the run never created. A task
// pointed at /var/lib/app that finds it already there and only tightens
// its mode has changed one number; an undo that removed the path would
// take the application's data with it, which is not the opposite of what
// the run did but a far larger act the run never performed.
//
// So the branch is on what was FOUND, never on what the method is:
//
//   - Created it: the inverse is file.remove. The run made the path, so
//     removing it restores the device to a state where it does not exist.
//   - Found it and changed its attributes: the inverse is file.permissions
//     with the mode, owner and group it had. The path outlives the undo.
//   - Found it already correct: NOTHING is emitted. See permRecordInverse
//     for why that silence is the honest record rather than a gap in one.
//
// Created wins over the attribute case when both are true, and that is
// right rather than a shortcut: this run created the directory AND set its
// mode, so removing the directory undoes both at once.
//
// # Why the emitted removal is not recursive
//
// file.remove refuses a non-empty directory unless a task sets recurse,
// and this deliberately leaves it unset. What this run created was an
// EMPTY directory, so removing an empty directory is its exact inverse. If
// something has since put content inside, that content is not this run's
// to destroy, and a refusal an operator has to read is a far better answer
// than a silent recursive delete.
func directoryRecordInverse(rc sdk.RunbookContext, path string, created, attributesChanged bool, before remotefile.Info) error {
	switch {
	case created:
		// The parameter names below are file.remove's own, which is why they
		// are written out rather than reusing this file's constants: they
		// belong to the method being invoked, not to this one.
		return sdk.RecordInverse(rc, sdk.Inverse{
			FQCN:   "file.remove",
			Params: map[string]any{"path": path},
			Description: fmt.Sprintf("Remove the directory %s, which this task created. It refuses if anything has been "+
				"put inside since, because that content is not this task's to delete.", path),
		})
	case attributesChanged:
		// file.permissions' parameter names, for the same reason.
		return sdk.RecordInverse(rc, sdk.Inverse{
			FQCN: "file.permissions",
			Params: map[string]any{
				"path":  path,
				"mode":  before.Mode,
				"owner": before.Owner,
				"group": before.Group,
			},
			Description: fmt.Sprintf("Set the directory %s back to mode %s, owned by %s:%s, which is what it was before "+
				"this task ran. The directory itself is left alone, since this task did not create it.",
				path, before.Mode, before.Owner, before.Group),
		})
	default:
		return nil
	}
}

// missingParents returns the directories above dir that do not exist yet,
// topmost first: the ones mkdir -p creates on the way to it. It stops at
// the first one that exists, whatever it is, since mkdir -p creates
// nothing above that.
func missingParents(ctx context.Context, conn *remoteexec.Conn, dir string) ([]string, error) {
	var missing []string
	for p := path.Dir(path.Clean(dir)); p != "/" && p != "."; p = path.Dir(p) {
		info, err := remotefile.Stat(ctx, conn, p)
		if err != nil {
			return nil, err
		}
		if info.Exists() {
			break
		}
		missing = append([]string{p}, missing...)
	}
	return missing, nil
}

// directoryAttributes reads the mode, owner and group a task asked for.
//
// An empty field means "leave this alone", which is what lets a task set
// a mode without also having an opinion about ownership.
func directoryAttributes(params map[string]any) (remotefile.Attributes, error) {
	mode, err := directoryMode(params)
	if err != nil {
		return remotefile.Attributes{}, err
	}
	owner, err := directoryName(params, dirParamOwner)
	if err != nil {
		return remotefile.Attributes{}, err
	}
	group, err := directoryName(params, dirParamGroup)
	if err != nil {
		return remotefile.Attributes{}, err
	}
	return remotefile.Attributes{Mode: mode, Owner: owner, Group: group}, nil
}

// directoryMode reads the mode parameter, refusing the two forms that
// would compile fine and then make this method report a change forever.
//
// The first is a mode that is not a string at all. `mode: 0755` in a
// runbook is a NUMBER to a YAML parser, and the leading zero is gone by
// the time it reaches here, so the value that arrives is 493 rather than
// the bits the author wrote. Reading it with the ordinary string reader
// would treat it as absent and silently apply no mode at all, which is
// the worst of the three available outcomes; Ansible has the same trap
// and answers it the same way, by telling the author to quote it.
//
// The second is a symbolic mode such as u+rwx. chmod accepts it happily,
// but this method has to compare the mode it wants against the mode stat
// reports, which is octal, and there is no comparison between the two
// short of reimplementing symbolic mode algebra against the current bits.
// Applying one unconditionally would work and would report changed on
// every single run. Refusing is the honest answer until that algebra is
// worth writing.
func directoryMode(params map[string]any) (string, error) {
	raw, present := params[dirParamMode]
	if !present || raw == nil {
		return "", nil
	}

	mode, ok := raw.(string)
	if !ok {
		return "", fmt.Errorf("%s must be a quoted string: write %s: \"0755\", since YAML reads an unquoted 0755 as the number %v and loses the leading zero", dirParamMode, dirParamMode, raw)
	}
	if !isOctalMode(mode) {
		return "", fmt.Errorf("%s %q is not an octal mode: write it as three or four octal digits such as \"0755\", since a symbolic mode cannot be compared against the mode the device reports", dirParamMode, mode)
	}
	return mode, nil
}

// isOctalMode reports whether mode is three or four octal digits, which
// is every mode chmod takes numerically: three for the permission bits
// and an optional fourth leading digit for setuid, setgid and the sticky
// bit.
func isOctalMode(mode string) bool {
	if len(mode) < 3 || len(mode) > 4 {
		return false
	}
	for _, c := range mode {
		if c < '0' || c > '7' {
			return false
		}
	}
	return true
}

// directoryName reads an owner or group parameter, refusing anything that
// is not a string.
//
// The refusal is the same idempotence argument the mode one makes.
// Ansible accepts a numeric uid for owner, and this does not, because
// remotefile.Stat reports ownership by NAME: a numeric id can never
// compare equal to the name that comes back, so accepting one would build
// a task that runs chown on every single run and reports changed forever.
// A name is also the portable form, since the same uid means different
// people on different devices.
func directoryName(params map[string]any, key string) (string, error) {
	raw, present := params[key]
	if !present || raw == nil {
		return "", nil
	}

	name, ok := raw.(string)
	if !ok {
		return "", fmt.Errorf("%s must be a name, not %v: this method compares ownership by name, which is what the device reports back", key, raw)
	}
	return name, nil
}

// describeDirectoryKind says what is at a path, in words that belong in
// the middle of a refusal sentence.
//
// A symlink names its target, because "there is a symlink there" and
// "there is a symlink there pointing at the directory you meant" send an
// operator to two completely different fixes.
func describeDirectoryKind(info remotefile.Info) string {
	switch info.Kind {
	case remotefile.KindFile:
		return "a file"
	case remotefile.KindSymlink:
		return fmt.Sprintf("a symlink to %q", info.Target)
	default:
		// remotefile.KindOther: a socket, a device node or a fifo. Listed
		// as what it is not, since the stat format this reads carries the
		// type bits but nothing that separates those three from each other.
		return "not a regular file, a directory or a symlink"
	}
}
