package file

import (
	"context"
	"fmt"

	"github.com/Subject-Void-LLC/the-pleiades/pkg/capability"
	"github.com/Subject-Void-LLC/the-pleiades/pkg/collection"
	"github.com/Subject-Void-LLC/the-pleiades/pkg/inventory"
	"github.com/Subject-Void-LLC/the-pleiades/pkg/remotefile"
	"github.com/Subject-Void-LLC/the-pleiades/pkg/sdk"
)

// This file implements "file.permissions", generated by
// pleiades forge new-collection and then hand-completed.
//
// It is the smallest converging method in this namespace, which makes it
// the clearest place to see the rules the rest of them follow: read what
// is there before touching anything, change only what differs, report
// changed only when something really moved, and record the prior state so
// an inverse has something to restore.
//
// IT CREATES NOTHING, and that is a decision rather than an omission.
// "Make sure this file is 0644" and "make this file exist" are different
// intentions, and a method that quietly did both would create an empty
// file wherever a runbook had a typo in a path, then report success.
// file.touch and file.directory are the two methods that create.

// Parameter names, which are ansible.builtin.file's own names. This
// platform is a superset of Ansible rather than a new vocabulary, so a
// person converting a playbook that sets mode, owner and group on a path
// should be renaming nothing.
//
// The perm prefix is scaffolding, not style. Every method in this
// namespace reads a path and several read a mode, an owner and a group,
// so these four belong in one file shared by the whole package the way
// internal/catalog/exec/exec.go holds that namespace's shared names. That
// shared file does not exist yet, and creating it from inside one
// method's own file would collide with the sibling methods being written
// alongside this one. Prefixed here, to be hoisted there.
//
// The same four words are also the stat keys this method returns under,
// deliberately: ansible.builtin.file returns path, mode, owner and group
// too, so one vocabulary covers what a task is asked for, what it reports
// and what its diff records.
const (
	permParamPath  = "path"
	permParamMode  = "mode"
	permParamOwner = "owner"
	permParamGroup = "group"
)

// permMaxModeDigits is how many octal digits a mode may carry.
//
// Four covers the widest real mode, the setuid, setgid and sticky bits
// plus the three permission triads (for example 4755). A fifth digit is
// not a mode anyone meant, so refusing it catches a typo at the runbook
// rather than passing it to chmod on the device.
const permMaxModeDigits = 4

func init() {
	collection.MustRegister(collection.Descriptor{
		Name: "file.permissions",
		Manifest: collection.Manifest{
			SupportedTransports: []string{
				"ssh",
			},
			RequiredCapabilities: []capability.Name{
				capability.NamePOSIXFileSystem,
			},
			// Left false even though setting an owner usually needs root.
			// Elevation here is a property of the individual task (chmod on
			// a path the account already owns needs nothing), so declaring
			// it unconditionally would mark every mode change as privileged
			// and teach a reader to ignore the field.
			ExecutionContext: collection.ExecutionContext{
				RequiresElevation: false,
			},
			PlatformTargets: nil,
			EngineVersion:   ">=1.0.0",
			Status:          collection.StatusImplemented,
			// The cleanest reversible method in the catalog: its whole
			// effect is a triple of values on one path, so re-applying the
			// triple it found undoes it exactly.
			//
			// This field says only WHETHER, which is all a manifest can
			// honestly say. WHICH mode, owner and group to put back is a
			// property of the run rather than of the method, so the run is
			// what emits it; see permRecordInverse.
			Reversibility: collection.Reversibility{
				Reversible: true,
				Notes: "A run that changed something emits a file.permissions carrying the mode, owner and group the path had " +
					"before, which restores it exactly. A converged run emits nothing, because undoing a change that was never " +
					"made means doing nothing. A run that fails partway emits nothing either, so whatever it applied before " +
					"failing stays applied and has to be re-run rather than undone.",
			},
			Doc: permissionsDoc(),
		},
		Invoke: Permissions,
	})
}

// permissionsDoc is this method's reference documentation, kept out of
// the registration above so the manifest fields stay readable.
//
// It is duplicated into internal/forge/catalogdata, which is the source
// the scaffolder is driven from, and internal/archtest's
// TestCatalogDataDocsMatchTheRegistry compares the two for equality so
// the copies cannot drift.
func permissionsDoc() collection.Doc {
	return collection.Doc{
		Summary:     "Sets a file's owner, group, and mode on the target.",
		Description: "Sets the mode, owner and group of a path that already exists, changing only the ones that differ from what the device reports. A path that is absent is a refusal rather than a create, since making a file exist is file.touch's job and making a directory exist is file.directory's; that keeps a typo in a path from silently producing an empty file. A symbolic link is refused too, because chmod and chown follow a link while a stat of the link reports the link itself, so such a task would change one path while comparing against another and could never report converged. At least one of mode, owner and group must be given: a task that asks for nothing is a runbook mistake, not a no-op.",
		Params: []collection.Param{
			{Name: permParamPath, Type: "string", Required: true, Description: "The path to change. It must already exist: this method changes a path rather than creating one."},
			{Name: permParamMode, Type: "string", Description: "The permission bits as one to four octal digits, quoted, for example \"0644\". Quote it: an unquoted 0644 is a number in YAML, not text. A symbolic mode such as u+x is refused, because it cannot be compared against the mode the device reports and the task would then report changed on every run."},
			{Name: permParamOwner, Type: "string", Description: "The user name to give the path. A numeric id is refused: chown reads an all-digit argument as an id while the device reports names, so the two could never compare equal and the task would report changed forever."},
			{Name: permParamGroup, Type: "string", Description: "The group name to give the path, refused as a numeric id for the same reason owner is."},
			{Name: sdk.ParamInsecureSkipHostKeyVerify, Type: "bool", Default: "false", Description: "Skip SSH host key verification for this task. This removes protection against a machine in the middle answering for the device, so set it only for a target you have decided does not need it."},
		},
		Returns: []collection.ReturnField{
			{Name: permParamPath, Type: "string", Returned: "always", Description: "The path this task acted on."},
			{Name: permParamMode, Type: "string", Returned: "always", Description: "The permission bits the path carries now, as four octal digits."},
			{Name: permParamOwner, Type: "string", Returned: "always", Description: "The user name owning the path now."},
			{Name: permParamGroup, Type: "string", Returned: "always", Description: "The group owning the path now."},
			{Name: sdk.StatDiff, Type: "dict", Returned: "always", Description: "The before and after state of the path, each holding its kind, mode, owner, group, size and modification time. Recorded even when nothing changed, in which case the two halves are identical."},
		},
		Examples: []collection.Example{
			{
				Name:        "Lock down a key file",
				RunbookYAML: "- name: Keep the deploy key private\n  fqcn: file.permissions\n  params:\n    path: /etc/pleiades/deploy.key\n    mode: \"0600\"\n    owner: pleiades\n    group: pleiades\n",
			},
			{
				Name:        "Make a script executable",
				RunbookYAML: "- name: Allow the rotation script to run\n  fqcn: file.permissions\n  params:\n    path: /usr/local/bin/rotate-logs\n    mode: \"0755\"\n",
			},
			{
				Name:        "Hand a directory to a service account",
				RunbookYAML: "- name: Give the cache directory to the service\n  fqcn: file.permissions\n  params:\n    path: /var/cache/pleiades\n    owner: pleiades\n",
			},
		},
		SeeAlso: []string{"file.touch", "file.directory", "file.copy"},
	}
}

// Permissions implements the "file.permissions" collection method: it
// sets the mode, owner and group of a path that already exists.
//
// # The order of operations is the contract
//
// Everything a runbook got wrong is refused before the first packet, so
// a mistake in a task costs no round trip and names the runbook rather
// than the device. Then the path is read, then only the attributes that
// differ are applied, and only then is anything recorded.
//
// Reading first is what makes Changed mean something. chmod and chown
// both succeed happily when they change nothing, so a method that applied
// unconditionally would be invisible on the device and very visible in a
// report that says changed on every run forever. A converged run
// reporting false is the single property this method exists to hold.
//
// The read is also the only chance to capture the prior state: once chmod
// has run, what was there before is gone, and those are exactly the values
// the emitted inverse carries. See permRecordInverse.
func Permissions(ctx context.Context, rc sdk.RunbookContext, device inventory.InventoryItem, params map[string]any) (collection.Result, error) {
	const fqcn = "file.permissions"

	path, want, err := permRequest(params)
	if err != nil {
		return collection.Result{}, fmt.Errorf("%s: %w", fqcn, err)
	}

	conn, err := sdk.Connect(ctx, rc, device, params, fqcn)
	if err != nil {
		return collection.Result{}, err
	}
	defer func() { _ = conn.Close() }()

	before, err := remotefile.Stat(ctx, conn, path)
	if err != nil {
		return collection.Result{}, fmt.Errorf("%s: %w", fqcn, err)
	}
	if !before.Exists() {
		return collection.Result{}, fmt.Errorf("%s: %s does not exist: this method changes a path rather than creating one, and file.touch or file.directory is what creates", fqcn, path)
	}
	// A link is refused rather than followed. remotefile.Stat reports the
	// link itself while chmod and chown resolve it, so following would mean
	// changing the target while comparing against the link, and a link's own
	// mode is a constant 0777 on Linux. The task would report changed on
	// every run and the operator would be reading the wrong path's state.
	if before.Kind == remotefile.KindSymlink {
		return collection.Result{}, fmt.Errorf("%s: %s is a symbolic link to %s: point the task at the target, since chmod and chown follow a link while its own mode never changes", fqcn, path, before.Target)
	}

	changed, err := remotefile.Apply(ctx, conn, path, want, before)
	if err != nil {
		// Apply stops at the first failure, so a mode that landed before a
		// chown failed is already on the device. Saying so in the error is
		// the only place it can be said: the engine discards a Result that
		// arrives with an error, and recording a diff here would claim an
		// after state that the failed half never reached.
		if changed {
			return collection.Result{}, fmt.Errorf("%s: %w: part of the change was applied before this failed, so re-run the task once the cause is fixed", fqcn, err)
		}
		return collection.Result{}, fmt.Errorf("%s: %w", fqcn, err)
	}

	after := permApplied(before, want)
	if err := sdk.RecordDiff(rc, sdk.Diff{Before: before.Map(), After: after.Map()}); err != nil {
		return collection.Result{}, fmt.Errorf("%s: %w", fqcn, err)
	}
	// Only a run that really moved something has anything to undo. The
	// converged run deliberately emits NOTHING, and that absence is the
	// record saying "undoing this task means doing nothing"; an inverse
	// emitted here anyway would make a rollback chmod a path this run left
	// exactly as it found it.
	if changed {
		if err := permRecordInverse(rc, fqcn, path, before); err != nil {
			return collection.Result{}, fmt.Errorf("%s: %w", fqcn, err)
		}
	}
	if err := permRecordStats(rc, path, after); err != nil {
		return collection.Result{}, fmt.Errorf("%s: %w", fqcn, err)
	}

	return collection.Result{Changed: changed}, nil
}

// permRequest reads and checks everything this method needs from the
// task's params, returning the path and the attributes to converge on.
//
// It runs before the connection is opened, on purpose. Every refusal
// below is a mistake in the runbook rather than a condition on the
// device, and one that costs a TCP connect, a key exchange and an
// authentication round before reporting itself is a slower answer to the
// same question.
func permRequest(params map[string]any) (string, remotefile.Attributes, error) {
	var none remotefile.Attributes

	// Read all four through one loop rather than four near-identical
	// blocks: the type refusal is the same sentence for each of them, and
	// four copies of it is four places for one of them to drift.
	values := make(map[string]string, 4)
	for _, key := range []string{permParamPath, permParamMode, permParamOwner, permParamGroup} {
		value, err := permTextParam(params, key)
		if err != nil {
			return "", none, err
		}
		values[key] = value
	}

	path := values[permParamPath]
	if path == "" {
		return "", none, fmt.Errorf("%s is required", permParamPath)
	}

	want := remotefile.Attributes{
		Mode:  values[permParamMode],
		Owner: values[permParamOwner],
		Group: values[permParamGroup],
	}
	// A task naming a path and nothing else is refused rather than treated
	// as a no-op. Silently succeeding would hide the real mistake, which is
	// almost always a mode that YAML swallowed or a parameter spelled
	// wrongly, behind a green task that changed nothing.
	if want.Empty() {
		return "", none, fmt.Errorf("at least one of %s, %s or %s is required: a task that asks for nothing to change is a runbook mistake rather than a no-op",
			permParamMode, permParamOwner, permParamGroup)
	}

	if err := permCheckMode(want.Mode); err != nil {
		return "", none, err
	}
	if err := permCheckName(permParamOwner, want.Owner); err != nil {
		return "", none, err
	}
	if err := permCheckName(permParamGroup, want.Group); err != nil {
		return "", none, err
	}

	return path, want, nil
}

// permTextParam reads one string parameter, refusing a value that arrived
// as something other than text.
//
// sdk.StringParam is the usual reader and it treats a non-string as
// absent, which is the wrong answer for exactly this method. `mode: 0644`
// without quotes is the most common mistake anyone makes with Ansible's
// file module: YAML reads the leading zero as octal and hands over the
// number 420, so a reader that shrugged at a non-string would report
// "at least one of mode, owner or group is required" and send the author
// hunting for a parameter they did in fact write.
func permTextParam(params map[string]any, key string) (string, error) {
	raw, present := params[key]
	if !present || raw == nil {
		return "", nil
	}
	text, ok := raw.(string)
	if !ok {
		return "", fmt.Errorf("%s is %T, not text: quote it in the runbook, since an unquoted mode such as 0644 is read as a number rather than as the digits you wrote", key, raw)
	}
	return text, nil
}

// permCheckMode refuses a mode this method cannot compare, which is any
// mode that is not plain octal digits.
//
// A symbolic mode (u+x, go-w) is what this rejects, and rejecting it is
// the honest option rather than the limited one. Deciding whether u+x is
// already applied means resolving it against the current bits, and the
// alternative that needs no resolution, applying it every time, is a
// method that reports changed forever. remotefile.NormalizeMode compares
// "0644" against stat's "644" by padding; there is nothing it can pad
// "u+x" into.
func permCheckMode(mode string) error {
	if mode == "" || permIsOctal(mode) {
		return nil
	}
	return fmt.Errorf("%s %q must be one to four octal digits such as \"0644\": a symbolic mode cannot be compared against what the device reports, so the task would report changed on every run",
		permParamMode, mode)
}

// permCheckName refuses a numeric owner or group.
//
// chown itself is the reason. An all-digit argument is read by chown as a
// numeric id, never as a name, while the device reports names back
// through stat, so "1000" and "alice" would compare unequal on every
// single run even when they are the same account. Resolving one to the
// other would need a passwd lookup on the device that this namespace has
// no primitive for, so the refusal says what to write instead.
func permCheckName(key, name string) error {
	if name == "" || !permIsDigits(name) {
		return nil
	}
	return fmt.Errorf("%s %q is a numeric id: name the account instead, since the device reports names and a numeric id would compare unequal on every run", key, name)
}

// permIsOctal reports whether text is one to permMaxModeDigits octal
// digits, which is the only mode form this method accepts.
func permIsOctal(text string) bool {
	return len(text) <= permMaxModeDigits && permDigitsOnly(text, '7')
}

// permIsDigits reports whether text is entirely decimal digits, which is
// how an owner or group given as a numeric id is recognized.
func permIsDigits(text string) bool {
	return permDigitsOnly(text, '9')
}

// permDigitsOnly reports whether text is non-empty and made only of
// digits from '0' up to and including highest.
//
// One helper for both checks rather than two loops that differ by one
// byte, and it works on bytes rather than runes deliberately: a multi-byte
// rune's bytes are all above '9', so a mode or a name containing one is
// refused rather than being silently truncated by a byte comparison.
func permDigitsOnly(text string, highest byte) bool {
	for i := 0; i < len(text); i++ {
		if text[i] < '0' || text[i] > highest {
			return false
		}
	}
	return len(text) > 0
}

// permApplied returns the state the path is in once want has been applied
// to before.
//
// It derives the after state rather than reading it back with a second
// stat. That is a real trade and worth naming: a re-read would observe
// the truth instead of asserting it, but it costs another round trip on
// every single run, and every value it could report is already pinned.
// The mode is whatever remotefile.NormalizeMode makes of the requested
// one, and the owner and group are names this method already refused to
// accept as ids, so nothing can come back in a different spelling than it
// went out in.
//
// On a converged run the derived after equals before exactly, field for
// field, which is what sdk.Unchanged expresses for methods that need a
// separate path for it. This one needs no separate path, and one path is
// easier to keep correct than two.
func permApplied(before remotefile.Info, want remotefile.Attributes) remotefile.Info {
	after := before
	if want.Mode != "" {
		after.Mode = remotefile.NormalizeMode(want.Mode)
	}
	if want.Owner != "" {
		after.Owner = want.Owner
	}
	if want.Group != "" {
		after.Group = want.Group
	}
	return after
}

// permRecordInverse writes the instruction that undoes this run: the same
// method, pointed at the same path, carrying the three values the path
// carried before it was touched.
//
// # Why the run emits this instead of the manifest declaring it
//
// This is the worked example for the whole namespace, so the reasoning
// lives here and the sibling methods point at it.
//
// The manifest can only say whether a method can EVER be undone. It
// cannot say what the undo is, because that is never a property of the
// method: the same file.permissions task, with the same params, against
// two devices, undoes to two different modes, whichever each device
// happened to have. A declaration would have to name a capture key and
// leave a rollback engine to rebuild the instruction from it, which puts
// knowledge of every method in the catalog inside that engine. Emitting
// it here keeps that knowledge in the one place that has it, and what
// lands in the record is already a runnable task rather than a template.
//
// # Why all three values, when the task may have asked for one
//
// A task that set only the mode still emits the owner and group it found.
// The rule is that the inverse restores what was THERE, and what was
// there is the whole triple; re-asserting an owner this run did not move
// is a no-op on any device nobody else has touched since. The cost is
// real and worth naming: if something else changed the owner between this
// run and a rollback, the rollback puts back the owner this run observed
// rather than leaving that later change alone. Restoring an observed
// state is the honest thing a record of an observation can promise, and
// narrowing it to only the fields that moved would need the per-field
// answer that remotefile.Apply does not report.
//
// # What it does NOT do
//
// It never removes the path. This method creates nothing, so there is
// never anything for an undo to delete, which is the distinction
// file.directory and file.symlink have to make at run time and this one
// does not.
func permRecordInverse(rc sdk.RunbookContext, fqcn, path string, before remotefile.Info) error {
	return sdk.RecordInverse(rc, sdk.Inverse{
		FQCN: fqcn,
		Params: map[string]any{
			permParamPath:  path,
			permParamMode:  before.Mode,
			permParamOwner: before.Owner,
			permParamGroup: before.Group,
		},
		Description: fmt.Sprintf("Set %s back to mode %s, owned by %s:%s, which is what it was before this task ran.",
			path, before.Mode, before.Owner, before.Group),
	})
}

// permRecordStats writes the stats this method returns, which are
// ansible.builtin.file's own return names so a converted playbook's later
// tasks read what they already read.
//
// They report the state the path is in NOW, not what the task was asked
// for, which is the same thing on a successful run and is the distinction
// that matters when a task set only the mode: owner and group still come
// back, read from the device rather than left empty.
func permRecordStats(rc sdk.RunbookContext, path string, after remotefile.Info) error {
	for key, value := range map[string]any{
		permParamPath:  path,
		permParamMode:  after.Mode,
		permParamOwner: after.Owner,
		permParamGroup: after.Group,
	} {
		if err := rc.SetStat(key, value); err != nil {
			return err
		}
	}
	return nil
}
