package file

import (
	"context"
	"fmt"
	"strings"

	"github.com/Subject-Void-LLC/the-pleiades/pkg/capability"
	"github.com/Subject-Void-LLC/the-pleiades/pkg/collection"
	"github.com/Subject-Void-LLC/the-pleiades/pkg/inventory"
	"github.com/Subject-Void-LLC/the-pleiades/pkg/remoteexec"
	"github.com/Subject-Void-LLC/the-pleiades/pkg/remotefile"
	"github.com/Subject-Void-LLC/the-pleiades/pkg/sdk"
)

// This file implements "file.remove", generated by
// pleiades forge new-collection and then hand-completed.
//
// It is this namespace's ansible.builtin.file with state=absent, and it
// is the only method here whose work cannot be taken back. Everything it
// does is therefore arranged around one idea: find out what is there
// BEFORE touching it, act only on what is really there, and refuse the
// one case where a small typo deletes a large tree.
//
// The parameter identifiers below are prefixed with the method name only
// because the seven methods of this package are being written in
// parallel and a shared `paramPath` would collide at merge time. The
// STRING is the contract, not the identifier, so hoisting these into one
// shared block later changes nothing a runbook can see, and should be
// done once every method in the package exists.
const (
	// removeParamPath is ansible.builtin.file's own name for the thing
	// being operated on. Ansible also accepts dest and name as aliases;
	// they are not accepted here, because a second spelling is a second
	// thing to document, to validate and to get wrong, and every
	// ansible.builtin.file example in the wild writes path.
	removeParamPath = "path"

	// removeParamRecurse gates deleting a directory that is not empty.
	//
	// The spelling is Ansible's, from the same module's argument spec,
	// and the meaning is not: there, recurse applies attributes down a
	// tree and state=absent recurses whether or not anybody asked. Here
	// it is the switch that permits a recursive delete at all. Reusing
	// the word is deliberate under this platform's superset rule (a
	// converted playbook should be renaming nothing), and the difference
	// is stated in this method's Doc rather than left for somebody to
	// discover.
	removeParamRecurse = "recurse"
)

func init() {
	collection.MustRegister(collection.Descriptor{
		Name: "file.remove",
		Manifest: collection.Manifest{
			SupportedTransports: []string{
				"ssh",
			},
			RequiredCapabilities: []capability.Name{
				capability.NamePOSIXFileSystem,
			},
			ExecutionContext: collection.ExecutionContext{
				RequiresElevation: false,
			},
			PlatformTargets: nil,
			EngineVersion:   ">=1.0.0",
			Status:          collection.StatusImplemented,
			// Deletion is the one operation in this namespace that can
			// never emit an inverse, so this is the one manifest here that
			// answers false. Registration refuses a false with no Notes,
			// which is the right place to be strict: "this cannot be
			// undone" is the answer an operator most needs a reason for.
			// See Remove's own doc comment for why the prior state is
			// still read, and recorded, when nothing can use it to restore.
			Reversibility: collection.Reversibility{
				Reversible: false,
				Notes: "What this removes is gone. The content is not journaled anywhere, not the bytes of a file, not the " +
					"tree under a directory, not what a symbolic link pointed at, so nothing on this platform can put it " +
					"back and no run of this method emits an inverse. The recorded diff still describes what was there, so " +
					"a rollback can report precisely what it cannot restore, which is the honest answer. Emitting an " +
					"inverse that recreated the path would be worse than emitting none: it would leave an empty file where " +
					"a full one had been and call that a restore.",
			},
			Doc: removeDoc(),
		},
		Invoke: Remove,
	})
}

// removeDoc is this method's reference documentation, kept out of the
// registration above so the manifest fields stay readable.
//
// It is duplicated by hand into internal/forge/catalogdata, which an
// architecture test compares against this value for equality, so an edit
// here without the matching edit there fails the build rather than
// quietly shipping two different documents.
func removeDoc() collection.Doc {
	return collection.Doc{
		Summary:     "Removes a file or directory from the target.",
		Description: "Ensures nothing exists at a path, which is ansible.builtin.file with state=absent. It reads the path first, so a path that is already gone reports no change and sends no removal command at all, and a symbolic link is removed as the link rather than followed to whatever it points at. It diverges from Ansible in exactly one place, deliberately: Ansible deletes a non-empty directory without being asked, and this refuses unless the task sets recurse, because a recursive delete is the most destructive thing in this namespace and should be readable in the runbook that asks for it. Nothing this method removes can be restored by this platform.",
		Params: []collection.Param{
			{Name: removeParamPath, Type: "string", Required: true, Description: "The path that must not exist when this task finishes. A symbolic link is removed as the link, so whatever it points at is left alone."},
			{Name: removeParamRecurse, Type: "bool", Default: "false", Description: "Permit removing a directory that is not empty, and everything inside it. Without it, a non-empty directory is refused rather than emptied. Ansible's state=absent recurses without asking; this does not."},
			{Name: sdk.ParamInsecureSkipHostKeyVerify, Type: "bool", Default: "false", Description: "Skip SSH host key verification for this task. This removes protection against a machine in the middle answering for the device, so set it only for a target you have decided does not need it."},
		},
		Returns: []collection.ReturnField{
			{Name: sdk.StatDiff, Type: "object", Returned: "always", Description: "What was at the path before this task and what is there after, under before and after. The before half carries exists, kind, mode, owner, group and size, which is everything a rollback can report about what it cannot restore. On a path that was already absent the two halves are identical, which is how a reader tells \"nothing to do\" from \"never ran\"."},
		},
		Examples: []collection.Example{
			{
				Name:        "Remove a file",
				RunbookYAML: "- name: Drop the leftover lock file\n  fqcn: file.remove\n  params:\n    path: /var/run/deploy.lock\n",
			},
			{
				Name:        "Remove an empty directory",
				RunbookYAML: "- name: Drop the empty spool directory\n  fqcn: file.remove\n  params:\n    path: /var/spool/old-queue\n",
			},
			{
				Name:        "Remove a directory and everything in it",
				RunbookYAML: "- name: Drop the previous release\n  fqcn: file.remove\n  params:\n    path: /opt/app/releases/2024-11-02\n    recurse: true\n",
			},
		},
		SeeAlso: []string{"file.directory", "file.touch"},
	}
}

// Remove implements the "file.remove" collection method: it ensures
// nothing exists at a path.
//
// # What Changed means here
//
// Unlike exec.command, this method CAN inspect what it is about to do, so
// it must. It stats the path first and reports Changed only when
// something was really there and is not any more. A path that is already
// gone reports Changed false and sends no removal command at all, not
// even a "rm -f" that would succeed harmlessly, because "the second run
// was quiet" is the property this whole tier is judged on and the cheapest
// way to be sure of it is to have nothing to be quiet about.
//
// # Why it records state it cannot use
//
// The manifest declares this not reversible, and it means it: the bytes
// are not journaled anywhere, so no rollback can put them back and this
// method emits no inverse on any path through it. The read before the
// delete still records what was there, under the "diff" stat, because a
// rollback that has to stop at this task should be able to say exactly
// what it is refusing to restore ("a 4 KiB file, mode 0640, owned by
// postgres") rather than "something was deleted here." Only the forward
// run is ever in a position to know that.
//
// # The one divergence from Ansible
//
// ansible.builtin.file with state=absent deletes a directory and
// everything under it without being asked. This refuses, unless the task
// sets recurse: true. The reason is that the difference between removing
// /opt/app/current and removing /opt/app is one keystroke, and the second
// one is unrecoverable; making the runbook say the word is the only point
// at which a human reviewing a diff can see it coming. An empty directory
// still goes without recurse, since there is nothing under it to lose.
func Remove(ctx context.Context, rc sdk.RunbookContext, device inventory.InventoryItem, params map[string]any) (collection.Result, error) {
	const fqcn = "file.remove"

	// Both parameter reads happen before the connection. A refusal that
	// costs a TCP connect, a key exchange and an authentication round to
	// deliver is a refusal that took a second to say what the runbook
	// itself could have been told immediately.
	path, err := sdk.RequiredStringParam(params, removeParamPath)
	if err != nil {
		return collection.Result{}, fmt.Errorf("%s: %w: there is nothing to remove", fqcn, err)
	}

	// BoolParamOr rather than BoolParam, so a value that is neither true
	// nor false is refused instead of read as false. Reading a misspelled
	// "yes" as false would turn an author's explicit permission into a
	// refusal, which is the safe direction, but reading any non-boolean as
	// a value at all is how the opposite mistake gets made later.
	recurse, err := sdk.BoolParamOr(params, removeParamRecurse, false)
	if err != nil {
		return collection.Result{}, fmt.Errorf("%s: %w", fqcn, err)
	}

	conn, err := sdk.Connect(ctx, rc, device, params, fqcn)
	if err != nil {
		return collection.Result{}, err
	}
	defer func() { _ = conn.Close() }()

	// Read before acting. Everything after this point depends on knowing
	// what is really there: whether to act at all, whether the recurse
	// refusal applies, and what the diff records.
	before, err := remotefile.Stat(ctx, conn, path)
	if err != nil {
		return collection.Result{}, fmt.Errorf("%s: %w", fqcn, err)
	}

	if !before.Exists() {
		// Recorded even though nothing happened. An absent diff and a diff
		// whose halves match are different statements: the first says this
		// task was never reached, the second says it was reached and had
		// nothing to do, and only the second is safe for a rollback to skip
		// over.
		if err := sdk.RecordDiff(rc, sdk.Unchanged(before.Map())); err != nil {
			return collection.Result{}, fmt.Errorf("%s: %w", fqcn, err)
		}
		return collection.Result{Changed: false}, nil
	}

	if err := removeTarget(ctx, conn, path, before.Kind, recurse); err != nil {
		return collection.Result{}, fmt.Errorf("%s: %w", fqcn, err)
	}

	// Built rather than re-read. The removal succeeded, so the state is
	// known exactly, and a second stat would spend a round trip to be told
	// what the first one already implies.
	after := remotefile.Info{Kind: remotefile.KindAbsent}
	if err := sdk.RecordDiff(rc, sdk.Diff{Before: before.Map(), After: after.Map()}); err != nil {
		return collection.Result{}, fmt.Errorf("%s: %w", fqcn, err)
	}

	return collection.Result{Changed: true}, nil
}

// removeTarget deletes what Stat found, choosing the form of deletion
// from what is really at the path rather than from what the runbook
// guessed was there.
//
// The recursive flag handed to remotefile.Remove is deliberately NOT the
// task's recurse parameter. By the time control reaches that line the
// path is either not a directory, or it is one the task explicitly
// permitted recursion on, so "rm -rf" is never pointed at a plain file
// because somebody set recurse: true for a directory elsewhere in a loop.
// The flag follows the device's answer, which is the only one that is
// true.
func removeTarget(ctx context.Context, conn *remoteexec.Conn, path string, kind remotefile.Kind, recurse bool) error {
	if kind == remotefile.KindDirectory && !recurse {
		return removeEmptyDirectory(ctx, conn, path)
	}
	return remotefile.Remove(ctx, conn, path, kind == remotefile.KindDirectory)
}

// removeEmptyDirectory removes a directory only if it is empty, and
// refuses in a way that names the parameter that would have allowed it.
//
// # Why this sends rmdir rather than reusing remotefile.Remove
//
// remotefile.Remove offers "rm -f" and "rm -rf", and neither is right
// here. "rm -f" cannot remove a directory at all. "rm -rf" can, and the
// obvious shape (list the directory, and if the listing was empty send
// "rm -rf") was rejected: the listing and the removal are two commands
// with a gap between them, so a file written into the directory during
// that gap is deleted by a task whose runbook said recurse: false. That
// is a small window, and it is a window on the single operation this
// method exists to make explicit.
//
// rmdir has no such gap. The kernel refuses a non-empty directory
// atomically, so the promise the runbook read ("this will not delete
// anything inside") is enforced where it cannot be raced instead of being
// checked a moment earlier and hoped for. The cost is one command this
// package sends itself rather than through the shared primitive, which is
// acceptable precisely because pkg/remotefile has no rmdir to call: this
// is a missing primitive, not a second opinion about an existing one. If
// a second method ever needs it, it belongs there, not copied.
//
// A failure is reported as one thing rather than two. rmdir exits
// non-zero for a directory that is not empty and for one this account
// cannot remove, and telling those apart would need a second probe whose
// answer could itself be stale. The message says both, and carries what
// the device said, so the operator reads the real reason rather than this
// method's guess at it.
//
// The "--" terminates rmdir's options. Quoting stops the shell from
// splitting or expanding a path, and does nothing at all about a path
// that begins with a dash being read as a flag.
func removeEmptyDirectory(ctx context.Context, conn *remoteexec.Conn, path string) error {
	result, err := conn.Run(ctx, "rmdir -- "+remoteexec.QuoteArg(path))
	if err != nil {
		return fmt.Errorf("remove directory %s: %w", path, err)
	}
	if result.ExitCode != 0 {
		return fmt.Errorf("refusing to remove directory %s: %s: it is not empty, or this account cannot remove it. "+
			"Set %s: true to remove a directory and everything inside it",
			path, strings.TrimSpace(result.Stderr), removeParamRecurse)
	}
	return nil
}
