package file

import (
	"context"
	"fmt"

	"github.com/Subject-Void-LLC/the-pleiades/pkg/capability"
	"github.com/Subject-Void-LLC/the-pleiades/pkg/collection"
	"github.com/Subject-Void-LLC/the-pleiades/pkg/inventory"
	"github.com/Subject-Void-LLC/the-pleiades/pkg/remotefile"
	"github.com/Subject-Void-LLC/the-pleiades/pkg/sdk"
)

// This file implements "file.touch", generated by
// pleiades forge new-collection and then hand-completed.
//
// It is ansible.builtin.file with state: touch, and nothing more. The
// scope is deliberately that narrow: the same Ansible module also creates
// directories, removes paths and makes links, and this catalog splits
// those into file.directory, file.remove and file.symlink instead of one
// method with a state parameter that changes what every other parameter
// means.

// Parameter names this method reads.
//
// They are ansible.builtin.file's own names for the same four things,
// because this platform is a superset of Ansible rather than a second
// vocabulary: a person converting a task that sets state: touch should be
// renaming nothing. Ansible also accepts dest and name as aliases for
// path; they are deliberately not accepted here, since three spellings of
// one key is three things a reader has to know and the canonical one is
// what its own documentation uses.
//
// The touch prefix on each name is bookkeeping, not meaning. Every method
// in this package was written on its own and each declared the copy it
// needed, so the prefix is what keeps four identical constants from
// colliding. They belong in a shared file for this namespace, unprefixed,
// the moment one exists, because path, mode, owner and group mean exactly
// the same thing in all of them.
const (
	touchParamPath  = "path"
	touchParamMode  = "mode"
	touchParamOwner = "owner"
	touchParamGroup = "group"
)

// Stat keys this method emits, beyond the shared "diff" record that
// sdk.RecordDiff writes.
//
// dest rather than path is Ansible's own spelling in the file module's
// return block for state: touch, so a converted playbook's later task
// reading it finds the value where it already looked. created has no
// Ansible equivalent, and is an addition rather than a rename: it answers
// the one question this method's caller most often has a "when" clause
// about, which is whether the file was made or merely re-stamped.
const (
	touchStatDest    = "dest"
	touchStatCreated = "created"
)

func init() {
	collection.MustRegister(collection.Descriptor{
		Name: "file.touch",
		Manifest: collection.Manifest{
			SupportedTransports: []string{
				"ssh",
			},
			RequiredCapabilities: []capability.Name{
				capability.NamePOSIXFileSystem,
			},
			ExecutionContext: collection.ExecutionContext{
				RequiresElevation: false,
			},
			PlatformTargets: nil,
			EngineVersion:   ">=0.2.0",
			Status:          collection.StatusImplemented,
			// It reads the path before it writes, so a check can predict
			// through the same code (CheckTouch).
			SupportsCheck: true,
			// True, but only in part, which is the honest answer here and
			// the reason Notes says what it says. One thing this method
			// changes on every single run, the modification time, cannot
			// be restored by anything in this catalog. See
			// touchRecordInverse, and permRecordInverse for the reasoning
			// behind emitting rather than declaring.
			Reversibility: collection.Reversibility{
				Reversible: true,
				Notes: "A run that created the file emits a file.remove naming it. A run that found the file already there and " +
					"also changed its mode, owner or group emits a file.permissions carrying the old ones, which is a partial " +
					"undo: the modification time this method moves on every run is NOT restored, because no method in this " +
					"catalog can set one. A run that found the file already there and only re-stamped it emits nothing at all, " +
					"since the modification time is then the single thing that moved and nothing here can put it back.",
			},
			Doc: touchDoc(),
		},
		Invoke: Touch,
		Check:  CheckTouch,
	})
}

// touchDoc is this method's reference documentation, kept out of the
// registration above so the manifest fields stay readable rather than
// being buried under a page of prose.
func touchDoc() collection.Doc {
	return collection.Doc{
		Summary:     "Creates an empty file on the target, or updates its modification time.",
		Description: "Makes sure a regular file exists at a path, creating it empty when nothing is there and updating its modification time when it already is. This is ansible.builtin.file with state: touch, and it reports changed on every run for the same reason that module does: moving a modification time is a real change to the device, so a run that claimed otherwise would be wrong rather than tidy. The two kinds of change are told apart in the recorded diff, where a created file reads exists false then true and a re-stamped one reads true then true. Anything at the path that is not a regular file is refused rather than replaced.",
		Params: []collection.Param{
			{Name: touchParamPath, Type: "string", Required: true, Description: "The full path to the file. It is created empty when nothing is there, and left alone apart from its modification time when a regular file already is. A directory, a symbolic link or anything else at the path is refused."},
			{Name: touchParamMode, Type: "string", Description: "The permission bits as one to four octal digits, quoted, for example \"0644\". Quote it: an unquoted 0644 is a number in YAML, not text, and is refused rather than silently ignored. A symbolic mode such as u+x is refused too, because it cannot be compared against the mode the device reports. Sent to the device only when it differs from what is already there, so a converged file is not re-chmodded. Left alone when not set."},
			{Name: touchParamOwner, Type: "string", Description: "The user that should own the file, by name. A numeric id is refused: chown reads an all-digit argument as an id while the device reports names back, so the two would compare unequal on every run. Sent only when it differs. Left alone when not set."},
			{Name: touchParamGroup, Type: "string", Description: "The group that should own the file, by name. A numeric id is refused, for the same reason it is on owner. Sent only when it differs, and in one chown alongside owner when both are set. Left alone when not set."},
			{Name: sdk.ParamInsecureSkipHostKeyVerify, Type: "bool", Default: "false", Description: "Skip SSH host key verification for this task. This removes protection against a machine in the middle answering for the device, so set it only for a target you have decided does not need it."},
		},
		Returns: []collection.ReturnField{
			{Name: touchStatDest, Type: "string", Returned: "always", Description: "The path this touched, exactly as the task named it."},
			{Name: touchStatCreated, Type: "bool", Returned: "always", Description: "True when nothing was at the path and an empty file was made. False when a file was already there and only its modification time moved."},
			{Name: sdk.StatDiff, Type: "dict", Returned: "always", Description: "The before and after state of the path, each holding exists, kind, and for a path that is there its mode, owner, group, size and mtime. This is the record a rollback reads, so it is written even though this method always reports changed."},
		},
		Examples: []collection.Example{
			{
				Name:        "Create a marker file",
				RunbookYAML: "- name: Mark the host as provisioned\n  file.touch:\n    path: /var/lib/pleiades/provisioned\n",
			},
			{
				Name:        "Create a log file with an owner and a mode",
				RunbookYAML: "- name: Make the log file the service will append to\n  file.touch:\n    path: /var/log/app/app.log\n    owner: app\n    group: app\n    mode: \"0640\"\n",
			},
			{
				Name:        "Act only when the file had to be created",
				RunbookYAML: "- name: Create the seed file\n  file.touch:\n    path: /opt/app/seed\n  register: seed\n\n- name: Seed the database the first time only\n  exec.command:\n    cmd: /opt/app/bin/seed\n  when_cel: seed.created\n",
			},
		},
		SeeAlso: []string{"file.remove", "file.permissions", "file.copy"},
	}
}

// Touch implements the "file.touch" collection method: it makes sure a
// regular file exists at a path, and moves its modification time.
//
// # Why this one always reports changed
//
// Every other converging method in this namespace reports changed only
// when the state it found differs from the state it wants, and a second
// run of it reports nothing. This one reports changed every time, and
// that is not an exception to the rule but the rule applied honestly.
// The state this method's caller asked for includes the modification
// time being now, and now is different on every run, so the device really
// does move each time. Ansible's own file module answers the same way for
// the same reason. A version that compared the mtime it found against
// "now" and called them equal would be reporting no change to a device it
// had just written to, which is the failure that makes a run report
// untrustworthy in the direction that matters.
//
// # Why the state is still read first
//
// Reading before acting is not what decides changed here, since that
// answer is already known. It is doing two other jobs.
//
// It is the guard. Something that is not a regular file at the path is
// refused, because touch on a directory fails on the device anyway and
// touch through a symbolic link would silently stamp a DIFFERENT path
// than the task named, and then record a diff describing the wrong one.
// Following the link is what Ansible's follow: yes default does, and it
// is rejected here: this method's whole output is a statement about one
// path, and quietly retargeting it makes both the statement and the
// rollback record false.
//
// It is also the only chance to see the prior state. Once the file is
// touched the previous modification time is gone, and the forward run is
// the only thing that was ever in a position to look. That read is what
// makes the inverse decidable: a path that was absent undoes to a removal,
// and a path that was already there undoes to its old attributes or to
// nothing at all. An inverse that removed the file in both cases would
// delete something the run never created. See touchRecordInverse.
func Touch(ctx context.Context, rc sdk.RunbookContext, device inventory.InventoryItem, params map[string]any) (collection.Result, error) {
	return touch(ctx, rc, device, params, collection.ModeExecute)
}

// CheckTouch is file.touch's check: the same reads and the same refusals
// as Touch, through the one body both share, then a prediction instead of
// the write. A touch always changes the file (it moves the modification
// time even when nothing else differs), so a check always predicts a
// change, and its diff's After half is remotefile.PredictTouch: a new
// empty file, or the existing one with the requested attributes and a
// modification time only the device can decide.
func CheckTouch(ctx context.Context, rc sdk.RunbookContext, device inventory.InventoryItem, params map[string]any) (collection.Result, error) {
	return touch(ctx, rc, device, params, collection.ModeCheck)
}

// touch is Touch's and CheckTouch's one body; mode says which.
func touch(ctx context.Context, rc sdk.RunbookContext, device inventory.InventoryItem, params map[string]any, mode collection.Mode) (collection.Result, error) {
	const fqcn = "file.touch"

	// Refused before connecting, so a runbook typo costs no round trip and
	// the error names the runbook's mistake rather than the device's.
	path, err := sdk.RequiredStringParam(params, touchParamPath)
	if err != nil {
		return collection.Result{}, fmt.Errorf("%s: %w", fqcn, err)
	}

	// Validated here, before connecting, for the same reason path is: a
	// runbook mistake should cost no round trip and should be reported
	// against the runbook.
	//
	// This used to read the three attributes with sdk.StringParam, which
	// reports a non-string as absent. `mode: 0600` written without quotes
	// is a number by the time YAML is done with it, so it arrived as
	// absent, and the task touched the file, left the mode alone and
	// reported success. See attributes.go.
	want, err := attributeParams(params, touchParamMode, touchParamOwner, touchParamGroup)
	if err != nil {
		return collection.Result{}, fmt.Errorf("%s: %w", fqcn, err)
	}

	conn, err := sdk.Connect(ctx, rc, device, params, fqcn)
	if err != nil {
		return collection.Result{}, err
	}
	defer func() { _ = conn.Close() }()

	before, err := remotefile.Stat(ctx, conn, path)
	if err != nil {
		return collection.Result{}, fmt.Errorf("%s: %w", fqcn, err)
	}
	if before.Exists() && before.Kind != remotefile.KindFile {
		return collection.Result{}, fmt.Errorf(
			"%s: %s exists and is not a regular file (%s): refusing to touch it, since replacing whatever is there is not what this method does",
			fqcn, path, before.Kind)
	}

	if mode == collection.ModeCheck {
		// Everything a real run records except the undo instruction, which
		// a check never records: nothing was done.
		if err := sdk.RecordDiff(rc, sdk.Diff{Before: before.Map(), After: remotefile.PredictTouch(want, before).Map()}); err != nil {
			return collection.Result{}, fmt.Errorf("%s: %w", fqcn, err)
		}
		if err := recordTouch(rc, path, !before.Exists()); err != nil {
			return collection.Result{}, fmt.Errorf("%s: %w", fqcn, err)
		}
		return collection.Result{Changed: true}, nil
	}

	if err := remotefile.Touch(ctx, conn, path); err != nil {
		return collection.Result{}, fmt.Errorf("%s: %w", fqcn, err)
	}

	// Apply's report of whether it moved anything feeds no Changed
	// decision, which this method has already made unconditionally. It is
	// kept for the one question it is the only answer to: whether this run
	// changed anything an undo could actually put back. A run that merely
	// re-stamped a file moved a modification time and nothing else, and
	// nothing in this catalog can restore one.
	attributesChanged, err := remotefile.Apply(ctx, conn, path, want, before)
	if err != nil {
		return collection.Result{}, fmt.Errorf("%s: %w", fqcn, err)
	}

	// Read back rather than assume. Predicting the after state from what
	// was asked for would record a guess: a mode can be altered by a
	// setgid parent, a chown can be a no-op for an account that could not
	// perform it, and the new modification time is only knowable from the
	// device. A rollback record built from intentions rather than facts is
	// worse than none, because it looks authoritative.
	after, err := remotefile.Stat(ctx, conn, path)
	if err != nil {
		return collection.Result{}, fmt.Errorf("%s: %w", fqcn, err)
	}

	if err := sdk.RecordDiff(rc, sdk.Diff{Before: before.Map(), After: after.Map()}); err != nil {
		return collection.Result{}, fmt.Errorf("%s: %w", fqcn, err)
	}
	if err := touchRecordInverse(rc, path, before, attributesChanged); err != nil {
		return collection.Result{}, fmt.Errorf("%s: %w", fqcn, err)
	}
	if err := recordTouch(rc, path, !before.Exists()); err != nil {
		return collection.Result{}, fmt.Errorf("%s: %w", fqcn, err)
	}

	return collection.Result{Changed: true}, nil
}

// touchRecordInverse writes the instruction that undoes this run, and is
// the one place in this namespace where a run that really changed
// something can still have nothing to emit.
//
// # The three cases
//
//   - The file was absent: this run created it, so the inverse is a
//     file.remove. Removing it restores the device exactly.
//   - The file was there and this run also moved its mode, owner or
//     group: the inverse is a file.permissions carrying the old ones. It
//     restores what it can and says in its own Description what it
//     cannot, which is the modification time.
//   - The file was there and nothing but the modification time moved:
//     NOTHING is emitted.
//
// # Why the last case emits nothing rather than something
//
// This method always reports Changed, because moving a modification time
// is a real change to the device. But no method in this catalog can set a
// modification time, so there is no instruction that would put it back. The
// choices were to emit an inverse that does not undo what happened, or to
// emit none and say why in the manifest's Notes. Emitting a file.remove
// here was the tempting wrong answer and would be the worst outcome
// available: the file existed before this task, so a rollback that deleted
// it would destroy something the run never created, in exchange for
// undoing a timestamp.
//
// An inverse that is honestly absent is readable. One that quietly does
// the wrong thing is not, and it only becomes visible the first time
// somebody actually rolls back.
func touchRecordInverse(rc sdk.RunbookContext, path string, before remotefile.Info, attributesChanged bool) error {
	switch {
	case !before.Exists():
		// file.remove's own parameter name, which is why it is written out
		// rather than reusing this file's constants.
		return sdk.RecordInverse(rc, sdk.Inverse{
			FQCN:        "file.remove",
			Params:      map[string]any{"path": path},
			Description: fmt.Sprintf("Remove the file %s, which this task created empty.", path),
		})
	case attributesChanged:
		// file.permissions' parameter names, for the same reason.
		return sdk.RecordInverse(rc, sdk.Inverse{
			FQCN: "file.permissions",
			Params: map[string]any{
				"path":  path,
				"mode":  before.Mode,
				"owner": before.Owner,
				"group": before.Group,
			},
			Description: fmt.Sprintf("Set %s back to mode %s, owned by %s:%s, which is what it was before this task ran. "+
				"The file is NOT removed, since this task did not create it, and its previous modification time of %d is "+
				"not restored, because no method in this catalog can set one.",
				path, before.Mode, before.Owner, before.Group, before.Mtime),
		})
	default:
		return nil
	}
}

// recordTouch writes the two stats this method reports beyond the shared
// diff record.
//
// The stats are written in a fixed order rather than by ranging a map, so
// a failure part way through is reproducible: a map range would make
// which key was reached depend on Go's randomized iteration, and a test
// covering the failure path could then pass or fail by luck.
func recordTouch(rc sdk.RunbookContext, path string, created bool) error {
	for _, stat := range []struct {
		key   string
		value any
	}{
		{key: touchStatDest, value: path},
		{key: touchStatCreated, value: created},
	} {
		if err := rc.SetStat(stat.key, stat.value); err != nil {
			return err
		}
	}
	return nil
}
