package windows_test

import (
	"testing"

	"github.com/Subject-Void-LLC/the-pleiades/internal/inventory/devices/windows"
	"github.com/Subject-Void-LLC/the-pleiades/internal/inventory/record"
	"github.com/Subject-Void-LLC/the-pleiades/pkg/capability"
)

// TestNewServer_ConstructsFromRecord is a starter test,
// generated by "pleiades forge new-device": it proves the constructor
// hydrates a real Record without error and that basic identity fields
// round-trip.
func TestNewServer_ConstructsFromRecord(t *testing.T) {
	item, err := windows.NewServer(record.Record{ID: "t1", Name: "t1", Type: "windows_server"})
	if err != nil {
		t.Fatalf("NewServer: %v", err)
	}
	if got := string(item.ID()); got != "t1" {
		t.Errorf("ID() = %q, want %q", got, "t1")
	}
	if got := item.Name(); got != "t1" {
		t.Errorf("Name() = %q, want %q", got, "t1")
	}
}

// TestNewServer_BaselineCapabilities is a starter, table-driven
// regression proof: the vendor baseline given at generation time is
// unioned into the declared capability set. It deliberately checks
// Capabilities(), not HasCapability(): this generated type has no
// capability-specific accessor methods yet (see the TODO in
// windows.go), so HasCapability correctly stays false until a human
// adds them.
func TestNewServer_BaselineCapabilities(t *testing.T) {
	item, err := windows.NewServer(record.Record{ID: "t1", Name: "t1", Type: "windows_server"})
	if err != nil {
		t.Fatalf("NewServer: %v", err)
	}
	declared := item.Capabilities()

	tests := []struct {
		name       string
		capability capability.Name
	}{
		{name: "WindowsCapable", capability: capability.Name("WindowsCapable")},
		{name: "WinRMCapable", capability: capability.Name("WinRMCapable")},
		{name: "WindowsServiceCapable", capability: capability.Name("WindowsServiceCapable")},
		{name: "WindowsFeatureCapable", capability: capability.Name("WindowsFeatureCapable")},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			found := false
			for _, c := range declared {
				if c == tt.capability {
					found = true
					break
				}
			}
			if !found {
				t.Errorf("expected the vendor baseline to include declared capability %s", tt.name)
			}
		})
	}
}
