// Package externalscaffold: the templates for a generated program's Go source.
package externalscaffold

// mainTemplateSource is the program's entry point: the package doc
// comment, and a main that is one call to external.Main. Everything the
// program does lives in the method file, so an author adding a second
// method changes this file by one argument.
const mainTemplateSource = `// Package main is an external Collection for The Pleiades that provides one
// method, {{quote .Name}}. Generated by pleiades forge new-external.
//
// The Pleiades runs this program itself, as a child process on the machine
// running pleiades run or on a Runner, never on a managed device. It runs
// the program with one argument: "describe" to learn which methods it
// provides and what each one needs, or "invoke" to run one method once,
// reading the request on stdin and writing the one response to file
// descriptor 3. The method reaches its target device over SSH with the
// single credential The Pleiades hands it for that task. The program is not
// meant to be run by hand.
//
// See README.md for how to build it and where to install it.
package main

import "github.com/Subject-Void-LLC/the-pleiades/pkg/external"

// main serves this program's methods. external.Main registers each one
// through collection.Register, the same validation every built-in method
// passes, answers the one command The Pleiades ran the program with, and
// exits with its status. It never returns.
//
// To provide a second method, write its descriptor in a file of its own
// and pass it here as another argument.
func main() {
	external.Main({{.FunctionName}}Descriptor())
}
`

// methodTemplateSource is the method file: the descriptor, its reference
// documentation, and a body that genuinely runs. The body only reads, and
// the comments on SupportsCheck and Reversibility say why both answers
// are true of that body and what to change when the body writes.
const methodTemplateSource = `// This file implements one Collection method, {{quote .Name}},
// generated by pleiades forge new-external as a working starting point.
// As generated, it connects to the target over SSH, runs one read-only
// command, and records what the command printed. Replace the method's
// body with its real work, and read the comments on SupportsCheck and
// Reversibility in the descriptor before you do: both answers are only
// true of the read-only body they were written for.

package main

import (
	"context"
	"fmt"
	"strings"

	"github.com/Subject-Void-LLC/the-pleiades/pkg/capability"
	"github.com/Subject-Void-LLC/the-pleiades/pkg/collection"
	"github.com/Subject-Void-LLC/the-pleiades/pkg/inventory"
	"github.com/Subject-Void-LLC/the-pleiades/pkg/sdk"
)

// {{.Prefix}}FQCN is this method's fully-qualified name. It is the name a
// runbook task uses, and it prefixes every error the method returns so an
// operator reading a failure knows which task produced it.
const {{.Prefix}}FQCN = {{quote .Name}}

// {{.Prefix}}Command is the one command the method runs on the target.
// It only reads, which is what makes the method's check mode and
// reversibility answers true. Change it and both answers need a second
// look.
const {{.Prefix}}Command = "uname -a"

// {{.Prefix}}StatUname is the stat the method records the command's
// output under. A runbook reads it through the task's register variable.
const {{.Prefix}}StatUname = "uname"

// {{.FunctionName}}Descriptor returns the registry entry for this method:
// its name, its declared contract, and the functions that run it. main
// hands it to external.Main, which validates it with collection.Register
// before answering anything, exactly as a built-in method is validated.
func {{.FunctionName}}Descriptor() collection.Descriptor {
	return collection.Descriptor{
		Name: {{.Prefix}}FQCN,
		Manifest: collection.Manifest{
			SupportedTransports: []string{"ssh"},
			// SSHTransportCapable means "reachable over SSH", which is all
			// sdk.Connect needs. The Pleiades checks it against the target
			// before it runs this program, so a device without it is
			// refused by name instead of failing partway through a dial.
			RequiredCapabilities: []capability.Name{capability.NameSSHTransport},
{{- if .EngineConstraint}}
			// The oldest Pleiades this program runs on: the release that
			// generated it. A release refuses to load a method stating a
			// newer one; raise it when the program starts using something
			// only a later release has.
			EngineVersion: {{quote .EngineConstraint}},
{{- end}}
			Status:               collection.StatusImplemented,
			// Not reversible, because there is nothing to reverse: the
			// body only reads. collection.Register requires Notes whenever
			// Reversible is false. When the body starts changing the
			// device, answer this again, and if a run's change can be
			// undone, record the concrete undo with sdk.RecordInverse
			// from the real run.
			Reversibility: collection.Reversibility{
				Reversible: false,
				Notes:      "Read-only: it runs uname -a and changes nothing on the device, so a run leaves nothing to undo.",
			},
			// SupportsCheck is true, and Check below is the same function
			// as Invoke. That is honest ONLY because the body writes
			// nothing. A check run must change nothing and report whether
			// a real run would change anything. A body that only reads
			// does exactly that, and reports Changed false both ways.
			//
			// The moment the body writes anything, using it as the check
			// would make a dry run change the device. Before that change
			// ships, do one of two things. Either write a separate Check
			// function that reads the current state, compares it with
			// what the task asked for, returns Result.Changed as "a real
			// run would change something", changes nothing, and never
			// calls sdk.RecordInverse. Or set SupportsCheck to false,
			// remove Check, and set NoCheckReason to why, and a check run
			// will then report this method as unchecked, by name, giving
			// that reason.
			SupportsCheck: true,
			Doc:           {{.Prefix}}Doc(),
		},
		Invoke: {{.FunctionName}},
		Check:  {{.FunctionName}},
	}
}

// {{.Prefix}}Doc is this method's reference documentation, the text
// pleiades doc prints for it. Rewrite it when you replace the body.
func {{.Prefix}}Doc() collection.Doc {
	return collection.Doc{
		Summary:     "Reads the target's kernel and host details with uname -a.",
		Description: "A generated starting point. It connects to the target over SSH with the task's credential, runs uname -a, and records what it printed. It changes nothing, so it reports no change on every run and runs the same way in check mode.",
		Params: []collection.Param{
			{Name: sdk.ParamInsecureSkipHostKeyVerify, Type: "bool", Default: "false", Description: "Skip SSH host key verification for this task. This removes protection against a machine in the middle answering for the device, so set it only for a target you have decided does not need it."},
		},
		Returns: []collection.ReturnField{
			{Name: {{.Prefix}}StatUname, Type: "string", Returned: "on success", Description: "What uname -a printed, without its trailing newline."},
		},
		Examples: []collection.Example{
			{Name: "Read a device's kernel details", RunbookYAML: "- name: Read the kernel details\n  " + {{.Prefix}}FQCN + ":\n  register: details\n"},
		},
	}
}

// {{.FunctionName}} is the method's body, run for both Invoke and Check.
// It opens one SSH connection to the target with the credential The Pleiades
// handed this program for the task, runs the read-only command, and
// records the command's output as a stat.
//
// It reports Changed false on every run, because reading is not changing.
// A non-zero exit status is an error rather than a result: the command
// reached the device and failed there, so the task has failed, and the
// error carries the status and whatever the device said on stderr. A
// device with no POSIX shell (a network switch reached over SSH, for
// example) fails this way, since uname is a POSIX command.
func {{.FunctionName}}(ctx context.Context, rc sdk.RunbookContext, device inventory.InventoryItem, params map[string]any) (collection.Result, error) {
	// sdk.Connect dials the device's SSH address and authenticates with
	// the credential in rc, never one from params: params come from the
	// runbook file, and a runbook file is committed to version control.
	// It verifies the host key unless the task explicitly set
	// insecure_skip_host_key_verify.
	conn, err := sdk.Connect(ctx, rc, device, params, {{.Prefix}}FQCN)
	if err != nil {
		return collection.Result{}, err
	}
	defer func() { _ = conn.Close() }()

	result, err := conn.Run(ctx, {{.Prefix}}Command)
	if err != nil {
		// An error here means the command's outcome on the device is
		// unknown (the connection dropped, say), which is different
		// from the command running and failing.
		return collection.Result{}, fmt.Errorf("%s: %w", {{.Prefix}}FQCN, err)
	}
	if result.ExitCode != 0 {
		return collection.Result{}, fmt.Errorf("%s: %q exited %d: %s",
			{{.Prefix}}FQCN, {{.Prefix}}Command, result.ExitCode, strings.TrimSpace(result.Stderr))
	}

	if err := rc.SetStat({{.Prefix}}StatUname, strings.TrimSpace(result.Stdout)); err != nil {
		return collection.Result{}, fmt.Errorf("%s: %w", {{.Prefix}}FQCN, err)
	}
	return collection.Result{Changed: false}, nil
}
`
