// Package catalog exists purely to trigger every generated Collection
// package's own init() registration into the shared pkg/collection
// registry: see internal/forge/catalogdata for the source of truth these
// packages were generated from, tools/gencatalog for what writes this
// file, and internal/inventory/builtins.go for the identical pattern
// applied to device types. Regenerated by tools/gencatalog every run:
// never hand-edited, never hand-added-to.
package catalog

import (
	_ "github.com/Subject-Void-LLC/the-pleiades/internal/catalog/archive"
	_ "github.com/Subject-Void-LLC/the-pleiades/internal/catalog/cloud/aws/ec2"
	_ "github.com/Subject-Void-LLC/the-pleiades/internal/catalog/cloud/aws/s3"
	_ "github.com/Subject-Void-LLC/the-pleiades/internal/catalog/container/docker"
	_ "github.com/Subject-Void-LLC/the-pleiades/internal/catalog/exec"
	_ "github.com/Subject-Void-LLC/the-pleiades/internal/catalog/facts"
	_ "github.com/Subject-Void-LLC/the-pleiades/internal/catalog/file"
	_ "github.com/Subject-Void-LLC/the-pleiades/internal/catalog/file/block"
	_ "github.com/Subject-Void-LLC/the-pleiades/internal/catalog/file/line"
	_ "github.com/Subject-Void-LLC/the-pleiades/internal/catalog/fs"
	_ "github.com/Subject-Void-LLC/the-pleiades/internal/catalog/fw/firewalld"
	_ "github.com/Subject-Void-LLC/the-pleiades/internal/catalog/http"
	_ "github.com/Subject-Void-LLC/the-pleiades/internal/catalog/identity/group"
	_ "github.com/Subject-Void-LLC/the-pleiades/internal/catalog/identity/user"
	_ "github.com/Subject-Void-LLC/the-pleiades/internal/catalog/net/catalyst"
	_ "github.com/Subject-Void-LLC/the-pleiades/internal/catalog/net/cli"
	_ "github.com/Subject-Void-LLC/the-pleiades/internal/catalog/net/eos"
	_ "github.com/Subject-Void-LLC/the-pleiades/internal/catalog/net/ios"
	_ "github.com/Subject-Void-LLC/the-pleiades/internal/catalog/net/junos"
	_ "github.com/Subject-Void-LLC/the-pleiades/internal/catalog/net/netconf"
	_ "github.com/Subject-Void-LLC/the-pleiades/internal/catalog/net/ssh"
	_ "github.com/Subject-Void-LLC/the-pleiades/internal/catalog/pkg"
	_ "github.com/Subject-Void-LLC/the-pleiades/internal/catalog/pkg/apt"
	_ "github.com/Subject-Void-LLC/the-pleiades/internal/catalog/pkg/dnf"
	_ "github.com/Subject-Void-LLC/the-pleiades/internal/catalog/pleiades/builtin/wait"
	_ "github.com/Subject-Void-LLC/the-pleiades/internal/catalog/svc"
	_ "github.com/Subject-Void-LLC/the-pleiades/internal/catalog/svc/systemd"
	_ "github.com/Subject-Void-LLC/the-pleiades/internal/catalog/svc/windows"
	_ "github.com/Subject-Void-LLC/the-pleiades/internal/catalog/wait"
	_ "github.com/Subject-Void-LLC/the-pleiades/internal/catalog/win/feature"
)
