package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"cel.dev/cel-go/cel"
	"cel.dev/cel-go/common"

	"github.com/Subject-Void-LLC/the-pleiades/internal/engine"
)

// filterStage names one cel.EnvOption engine.CELLibraryOptions() returns,
// in the exact order that function returns them, so generateFilters can
// attribute each newly discovered function or macro to a human-readable
// section. This is presentation grouping only: the functions, signatures
// and examples rendered under each stage all come from the live
// engine.CELVariableOptions/CELLibraryOptions, never hand-typed here. If
// engine.CELLibraryOptions ever reorders or adds an entry without a
// matching update to filterStageLabels below, generateFilters's own
// length check fails the build rather than silently mislabeling a
// section.
type filterStage struct {
	title string
	intro string
}

// generateFilters emits outDir/filters/index.md: every function and macro
// callable from a when/when_or/when_cel expression beyond CEL's own
// built-in operators, whether pkg/filters registers it or a cel-go
// standard extension does. Nothing here is a second, hand-maintained copy
// of a function's name or signature: this builds the exact baseline
// environment engine.NewCELEvaluator would build with no libraries, then
// extends it one engine.CELLibraryOptions() entry at a time, diffing
// cel.Env.Functions() and cel.Env.Macros() after each step by overload ID
// (not by function name: ext.Network adds new overloads to the
// standard library's own pre-existing "string" conversion function, which
// a name-level diff would miss entirely) to discover exactly what each
// step adds. A page produced this way cannot claim a function exists, or
// a signature reads a certain way, that the real, shipped engine
// disagrees with.
func generateFilters(outDir string) error {
	filtersDir := filepath.Join(outDir, "filters")
	if err := os.MkdirAll(filtersDir, 0o755); err != nil { // #nosec G301 -- generated docs, not secret material
		return fmt.Errorf("creating %s: %w", filtersDir, err)
	}

	baseline, err := cel.NewEnv(engine.CELVariableOptions()...)
	if err != nil {
		return fmt.Errorf("gendocs: building baseline CEL env: %w", err)
	}

	libOpts := engine.CELLibraryOptions()
	stages := filterStageLabels()
	if len(stages) != len(libOpts) {
		return fmt.Errorf("gendocs: filterStageLabels() has %d entries but engine.CELLibraryOptions() returns %d; "+
			"update tools/gendocs/filters.go's stage table to match", len(stages), len(libOpts))
	}

	var b strings.Builder
	b.WriteString(frontMatter("beta"))
	b.WriteString("# Filter reference\n\n")
	b.WriteString("Every function and macro callable from a `when`, `when_or` or `when_cel` expression, " +
		"beyond CEL's own built-in operators (`==`, `&&`, `in`, and so on; see the " +
		"[CEL language definition](https://github.com/google/cel-spec/blob/master/doc/langdef.md) for " +
		"those). A filter is not a Collection method: it is a pure, deterministic function of its " +
		"arguments, with no device, no capability and no execution context. " +
		"This page is generated by diffing the real CEL environment `engine.NewCELEvaluator` builds " +
		"against a bare baseline with no libraries added, so a function or signature listed here is " +
		"proven callable, not merely intended.\n\n")
	b.WriteString("A signature written `filters.safeInt(dyn, int) -> int` means the first argument accepts " +
		"any CEL type (converted to a string before parsing); a signature's own fallback argument, where " +
		"one exists, keeps its exact declared type, so a value the wrong literal type there fails to " +
		"compile rather than being silently coerced.\n\n")

	cur := baseline
	for i, opt := range libOpts {
		next, err := cur.Extend(opt)
		if err != nil {
			return fmt.Errorf("gendocs: extending CEL env with stage %q: %w", stages[i].title, err)
		}

		funcs := newFunctions(cur, next)
		macros := newMacros(cur, next)
		if len(funcs) > 0 || len(macros) > 0 {
			fmt.Fprintf(&b, "## %s\n\n", stages[i].title)
			b.WriteString(stages[i].intro + "\n\n")
			for _, fd := range funcs {
				renderFunctionDoc(&b, fd)
			}
			for _, md := range macros {
				renderMacroDoc(&b, md)
			}
		}

		cur = next
	}

	return os.WriteFile(filepath.Join(filtersDir, "index.md"), []byte(b.String()), 0o644) // #nosec G306 -- generated docs, not secret material
}

// filterStageLabels is the presentation-only label table paired
// positionally against engine.CELLibraryOptions()'s own returned slice
// (ext.Network(), ext.Encoders(), cel.OptionalTypes(), filtersLib(), in
// that order). Only the title and intro sentence are hand-written; every
// function name, signature and example rendered under a stage comes from
// the live env diff in generateFilters.
func filterStageLabels() []filterStage {
	return []filterStage{
		{
			title: "Network & addressing (`ext.Network`)",
			intro: "cel-go's own `ext.Network()`, built on Go's `net/netip`. `ip` and `net.CIDR` values are " +
				"opaque types with a custom type adapter; a `net/netip.Addr` or `netip.Prefix` from Go code " +
				"converts into this environment directly. Parsing is strict: an IPv4-mapped IPv6 address or " +
				"a zone suffix is rejected, not silently accepted.",
		},
		{
			title: "Encoding (`ext.Encoders`)",
			intro: "cel-go's own `ext.Encoders()`. `base64.encode` takes `bytes` and returns `string`; " +
				"`base64.decode` takes `string` and returns `bytes`, the reverse of what the names alone " +
				"suggest. Reach for `base64.encode(bytes(x))` and `string(base64.decode(x))` when the value " +
				"in hand is a CEL string rather than bytes.",
		},
		{
			title: "Optional values (`cel.OptionalTypes`)",
			intro: "cel-go's own `cel.OptionalTypes()`. This is the environment's answer to Ansible's " +
				"`default` filter: `stat.?retries.orValue(0)` reads as \"the value at `retries` if present, " +
				"otherwise `0`\", and covers a field that may be **absent** entirely. It is a different " +
				"problem from a field that is **present but malformed**, which the `filters.safe*` family " +
				"above answers instead; the two are not interchangeable.",
		},
		{
			title: "First-party filters (`filters.*`)",
			intro: "`pkg/filters`, registered under the flat `filters.` prefix, a namespace independent " +
				"of a Collection's `<namespace>.<method>` FQCN (the two never cross-reference each other, " +
				"so no collision is possible even in principle). Every function here is independently " +
				"unit-tested as plain Go, with no dependency on CEL; `internal/engine/cel_filters.go` is " +
				"the only translation between the two.",
		},
	}
}

// functionDoc pairs one function's live documentation with only the
// overloads a given stage newly introduced, so a function the standard
// library already declared (such as "string") renders solely the
// overload(s) that stage's own library actually added to it.
type functionDoc struct {
	name        string
	description string
	overloads   []overloadDoc
}

type overloadDoc struct {
	signature string
	examples  []string
}

// newFunctions returns every function overload present in next but not in
// prev, grouped by function name and ordered for stable, diff-friendly
// output (regeneration must be byte-for-byte idempotent; see
// TestRun_Idempotent).
func newFunctions(prev, next *cel.Env) []functionDoc {
	prevFns := prev.Functions()
	nextFns := next.Functions()

	names := make([]string, 0, len(nextFns))
	for name := range nextFns {
		names = append(names, name)
	}
	sort.Strings(names)

	var out []functionDoc
	for _, name := range names {
		nextFn := nextFns[name]
		prevIDs := map[string]bool{}
		if prevFn := prevFns[name]; prevFn != nil {
			for _, o := range prevFn.OverloadDecls() {
				prevIDs[o.ID()] = true
			}
		}

		overloadDecls := nextFn.OverloadDecls()
		fullDoc := nextFn.Documentation()

		var overloads []overloadDoc
		for i, od := range overloadDecls {
			if prevIDs[od.ID()] {
				continue
			}
			if i >= len(fullDoc.Children) {
				continue
			}
			child := fullDoc.Children[i]
			var examples []string
			for _, ex := range child.Children {
				examples = append(examples, ex.Description)
			}
			overloads = append(overloads, overloadDoc{signature: child.Signature, examples: examples})
		}
		if len(overloads) == 0 {
			continue
		}
		// ParseDescription (not the raw Description()) trims trailing
		// whitespace per line and drops blank lines, the same
		// normalization FunctionDecl.Documentation() itself applies
		// internally; using it here rather than the raw joined string
		// keeps this renderer correct for any doc string, not only the
		// ones this package happens to write with clean line endings.
		out = append(out, functionDoc{name: name, description: common.ParseDescription(nextFn.Description()), overloads: overloads})
	}
	return out
}

// macroDoc mirrors functionDoc for a macro (an AST-rewriting construct
// like optMap, distinct from an ordinary function call).
type macroDoc struct {
	name        string
	description string
	examples    []string
}

// newMacros returns every macro present in next but not in prev, keyed by
// MacroKey (which encodes name, arity and receiver style, so two macros
// sharing a bare name but differing in arity are not conflated), sorted
// for stable output.
func newMacros(prev, next *cel.Env) []macroDoc {
	prevKeys := map[string]bool{}
	for _, m := range prev.Macros() {
		prevKeys[m.MacroKey()] = true
	}

	var fresh []cel.Macro
	for _, m := range next.Macros() {
		if !prevKeys[m.MacroKey()] {
			fresh = append(fresh, m)
		}
	}
	sort.Slice(fresh, func(i, j int) bool { return fresh[i].MacroKey() < fresh[j].MacroKey() })

	out := make([]macroDoc, 0, len(fresh))
	for _, m := range fresh {
		// cel.Macro's own interface does not declare Documentation(); only
		// the concrete type every real macro (including every macro
		// cel.OptionalTypes registers) is built from implements it, via
		// the separate common.Documentor interface. A macro that does not
		// implement it is skipped rather than causing a panic: better to
		// document a macro with no name than to fail generation entirely
		// over a cel-go internal type this package does not control.
		documented, ok := m.(common.Documentor)
		if !ok {
			continue
		}
		doc := documented.Documentation()
		var examples []string
		for _, ex := range doc.Children {
			examples = append(examples, ex.Description)
		}
		out = append(out, macroDoc{name: doc.Name, description: doc.Description, examples: examples})
	}
	return out
}

func renderFunctionDoc(b *strings.Builder, fd functionDoc) {
	fmt.Fprintf(b, "### `%s`\n\n", fd.name)
	if fd.description != "" {
		fmt.Fprintf(b, "%s\n\n", fd.description)
	}
	for _, od := range fd.overloads {
		fmt.Fprintf(b, "- `%s`\n", od.signature)
		for _, ex := range od.examples {
			for _, line := range strings.Split(ex, "\n") {
				fmt.Fprintf(b, "  - `%s`\n", line)
			}
		}
	}
	b.WriteString("\n")
}

func renderMacroDoc(b *strings.Builder, md macroDoc) {
	fmt.Fprintf(b, "### `%s` (macro)\n\n", md.name)
	if md.description != "" {
		fmt.Fprintf(b, "%s\n\n", md.description)
	}
	for _, ex := range md.examples {
		for _, line := range strings.Split(ex, "\n") {
			fmt.Fprintf(b, "- `%s`\n", line)
		}
	}
	b.WriteString("\n")
}
