// Code generated by ent, DO NOT EDIT.

package journalentry

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Subject-Void-LLC/the-pleiades/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldEQ(FieldUpdatedAt, v))
}

// JobID applies equality check predicate on the "job_id" field. It's identical to JobIDEQ.
func JobID(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldEQ(FieldJobID, v))
}

// DeviceID applies equality check predicate on the "device_id" field. It's identical to DeviceIDEQ.
func DeviceID(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldEQ(FieldDeviceID, v))
}

// Attempt applies equality check predicate on the "attempt" field. It's identical to AttemptEQ.
func Attempt(v int) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldEQ(FieldAttempt, v))
}

// NodeID applies equality check predicate on the "node_id" field. It's identical to NodeIDEQ.
func NodeID(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldEQ(FieldNodeID, v))
}

// RunID applies equality check predicate on the "run_id" field. It's identical to RunIDEQ.
func RunID(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldEQ(FieldRunID, v))
}

// Sequence applies equality check predicate on the "sequence" field. It's identical to SequenceEQ.
func Sequence(v int) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldEQ(FieldSequence, v))
}

// DagID applies equality check predicate on the "dag_id" field. It's identical to DagIDEQ.
func DagID(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldEQ(FieldDagID, v))
}

// DagVersion applies equality check predicate on the "dag_version" field. It's identical to DagVersionEQ.
func DagVersion(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldEQ(FieldDagVersion, v))
}

// Fqcn applies equality check predicate on the "fqcn" field. It's identical to FqcnEQ.
func Fqcn(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldEQ(FieldFqcn, v))
}

// FqcnUnresolved applies equality check predicate on the "fqcn_unresolved" field. It's identical to FqcnUnresolvedEQ.
func FqcnUnresolved(v bool) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldEQ(FieldFqcnUnresolved, v))
}

// ProviderProgram applies equality check predicate on the "provider_program" field. It's identical to ProviderProgramEQ.
func ProviderProgram(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldEQ(FieldProviderProgram, v))
}

// ProviderDigest applies equality check predicate on the "provider_digest" field. It's identical to ProviderDigestEQ.
func ProviderDigest(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldEQ(FieldProviderDigest, v))
}

// TaskName applies equality check predicate on the "task_name" field. It's identical to TaskNameEQ.
func TaskName(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldEQ(FieldTaskName, v))
}

// Register applies equality check predicate on the "register" field. It's identical to RegisterEQ.
func Register(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldEQ(FieldRegister, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldEQ(FieldStartedAt, v))
}

// FinishedAt applies equality check predicate on the "finished_at" field. It's identical to FinishedAtEQ.
func FinishedAt(v time.Time) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldEQ(FieldFinishedAt, v))
}

// FailureStage applies equality check predicate on the "failure_stage" field. It's identical to FailureStageEQ.
func FailureStage(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldEQ(FieldFailureStage, v))
}

// SkipKind applies equality check predicate on the "skip_kind" field. It's identical to SkipKindEQ.
func SkipKind(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldEQ(FieldSkipKind, v))
}

// SkipOrdinal applies equality check predicate on the "skip_ordinal" field. It's identical to SkipOrdinalEQ.
func SkipOrdinal(v int) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldEQ(FieldSkipOrdinal, v))
}

// SkipTotal applies equality check predicate on the "skip_total" field. It's identical to SkipTotalEQ.
func SkipTotal(v int) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldEQ(FieldSkipTotal, v))
}

// UndeclaredStatCount applies equality check predicate on the "undeclared_stat_count" field. It's identical to UndeclaredStatCountEQ.
func UndeclaredStatCount(v int) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldEQ(FieldUndeclaredStatCount, v))
}

// UndeclaredParamCount applies equality check predicate on the "undeclared_param_count" field. It's identical to UndeclaredParamCountEQ.
func UndeclaredParamCount(v int) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldEQ(FieldUndeclaredParamCount, v))
}

// InverseFqcn applies equality check predicate on the "inverse_fqcn" field. It's identical to InverseFqcnEQ.
func InverseFqcn(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldEQ(FieldInverseFqcn, v))
}

// InverseFqcnUnresolved applies equality check predicate on the "inverse_fqcn_unresolved" field. It's identical to InverseFqcnUnresolvedEQ.
func InverseFqcnUnresolved(v bool) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldEQ(FieldInverseFqcnUnresolved, v))
}

// UndeclaredInverseParamCount applies equality check predicate on the "undeclared_inverse_param_count" field. It's identical to UndeclaredInverseParamCountEQ.
func UndeclaredInverseParamCount(v int) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldEQ(FieldUndeclaredInverseParamCount, v))
}

// DiffRecorded applies equality check predicate on the "diff_recorded" field. It's identical to DiffRecordedEQ.
func DiffRecorded(v bool) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldEQ(FieldDiffRecorded, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldLTE(FieldUpdatedAt, v))
}

// JobIDEQ applies the EQ predicate on the "job_id" field.
func JobIDEQ(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldEQ(FieldJobID, v))
}

// JobIDNEQ applies the NEQ predicate on the "job_id" field.
func JobIDNEQ(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldNEQ(FieldJobID, v))
}

// JobIDIn applies the In predicate on the "job_id" field.
func JobIDIn(vs ...string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldIn(FieldJobID, vs...))
}

// JobIDNotIn applies the NotIn predicate on the "job_id" field.
func JobIDNotIn(vs ...string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldNotIn(FieldJobID, vs...))
}

// JobIDGT applies the GT predicate on the "job_id" field.
func JobIDGT(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldGT(FieldJobID, v))
}

// JobIDGTE applies the GTE predicate on the "job_id" field.
func JobIDGTE(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldGTE(FieldJobID, v))
}

// JobIDLT applies the LT predicate on the "job_id" field.
func JobIDLT(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldLT(FieldJobID, v))
}

// JobIDLTE applies the LTE predicate on the "job_id" field.
func JobIDLTE(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldLTE(FieldJobID, v))
}

// JobIDContains applies the Contains predicate on the "job_id" field.
func JobIDContains(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldContains(FieldJobID, v))
}

// JobIDHasPrefix applies the HasPrefix predicate on the "job_id" field.
func JobIDHasPrefix(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldHasPrefix(FieldJobID, v))
}

// JobIDHasSuffix applies the HasSuffix predicate on the "job_id" field.
func JobIDHasSuffix(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldHasSuffix(FieldJobID, v))
}

// JobIDEqualFold applies the EqualFold predicate on the "job_id" field.
func JobIDEqualFold(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldEqualFold(FieldJobID, v))
}

// JobIDContainsFold applies the ContainsFold predicate on the "job_id" field.
func JobIDContainsFold(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldContainsFold(FieldJobID, v))
}

// DeviceIDEQ applies the EQ predicate on the "device_id" field.
func DeviceIDEQ(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldEQ(FieldDeviceID, v))
}

// DeviceIDNEQ applies the NEQ predicate on the "device_id" field.
func DeviceIDNEQ(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldNEQ(FieldDeviceID, v))
}

// DeviceIDIn applies the In predicate on the "device_id" field.
func DeviceIDIn(vs ...string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldIn(FieldDeviceID, vs...))
}

// DeviceIDNotIn applies the NotIn predicate on the "device_id" field.
func DeviceIDNotIn(vs ...string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldNotIn(FieldDeviceID, vs...))
}

// DeviceIDGT applies the GT predicate on the "device_id" field.
func DeviceIDGT(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldGT(FieldDeviceID, v))
}

// DeviceIDGTE applies the GTE predicate on the "device_id" field.
func DeviceIDGTE(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldGTE(FieldDeviceID, v))
}

// DeviceIDLT applies the LT predicate on the "device_id" field.
func DeviceIDLT(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldLT(FieldDeviceID, v))
}

// DeviceIDLTE applies the LTE predicate on the "device_id" field.
func DeviceIDLTE(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldLTE(FieldDeviceID, v))
}

// DeviceIDContains applies the Contains predicate on the "device_id" field.
func DeviceIDContains(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldContains(FieldDeviceID, v))
}

// DeviceIDHasPrefix applies the HasPrefix predicate on the "device_id" field.
func DeviceIDHasPrefix(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldHasPrefix(FieldDeviceID, v))
}

// DeviceIDHasSuffix applies the HasSuffix predicate on the "device_id" field.
func DeviceIDHasSuffix(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldHasSuffix(FieldDeviceID, v))
}

// DeviceIDIsNil applies the IsNil predicate on the "device_id" field.
func DeviceIDIsNil() predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldIsNull(FieldDeviceID))
}

// DeviceIDNotNil applies the NotNil predicate on the "device_id" field.
func DeviceIDNotNil() predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldNotNull(FieldDeviceID))
}

// DeviceIDEqualFold applies the EqualFold predicate on the "device_id" field.
func DeviceIDEqualFold(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldEqualFold(FieldDeviceID, v))
}

// DeviceIDContainsFold applies the ContainsFold predicate on the "device_id" field.
func DeviceIDContainsFold(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldContainsFold(FieldDeviceID, v))
}

// AttemptEQ applies the EQ predicate on the "attempt" field.
func AttemptEQ(v int) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldEQ(FieldAttempt, v))
}

// AttemptNEQ applies the NEQ predicate on the "attempt" field.
func AttemptNEQ(v int) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldNEQ(FieldAttempt, v))
}

// AttemptIn applies the In predicate on the "attempt" field.
func AttemptIn(vs ...int) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldIn(FieldAttempt, vs...))
}

// AttemptNotIn applies the NotIn predicate on the "attempt" field.
func AttemptNotIn(vs ...int) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldNotIn(FieldAttempt, vs...))
}

// AttemptGT applies the GT predicate on the "attempt" field.
func AttemptGT(v int) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldGT(FieldAttempt, v))
}

// AttemptGTE applies the GTE predicate on the "attempt" field.
func AttemptGTE(v int) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldGTE(FieldAttempt, v))
}

// AttemptLT applies the LT predicate on the "attempt" field.
func AttemptLT(v int) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldLT(FieldAttempt, v))
}

// AttemptLTE applies the LTE predicate on the "attempt" field.
func AttemptLTE(v int) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldLTE(FieldAttempt, v))
}

// NodeIDEQ applies the EQ predicate on the "node_id" field.
func NodeIDEQ(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldEQ(FieldNodeID, v))
}

// NodeIDNEQ applies the NEQ predicate on the "node_id" field.
func NodeIDNEQ(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldNEQ(FieldNodeID, v))
}

// NodeIDIn applies the In predicate on the "node_id" field.
func NodeIDIn(vs ...string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldIn(FieldNodeID, vs...))
}

// NodeIDNotIn applies the NotIn predicate on the "node_id" field.
func NodeIDNotIn(vs ...string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldNotIn(FieldNodeID, vs...))
}

// NodeIDGT applies the GT predicate on the "node_id" field.
func NodeIDGT(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldGT(FieldNodeID, v))
}

// NodeIDGTE applies the GTE predicate on the "node_id" field.
func NodeIDGTE(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldGTE(FieldNodeID, v))
}

// NodeIDLT applies the LT predicate on the "node_id" field.
func NodeIDLT(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldLT(FieldNodeID, v))
}

// NodeIDLTE applies the LTE predicate on the "node_id" field.
func NodeIDLTE(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldLTE(FieldNodeID, v))
}

// NodeIDContains applies the Contains predicate on the "node_id" field.
func NodeIDContains(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldContains(FieldNodeID, v))
}

// NodeIDHasPrefix applies the HasPrefix predicate on the "node_id" field.
func NodeIDHasPrefix(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldHasPrefix(FieldNodeID, v))
}

// NodeIDHasSuffix applies the HasSuffix predicate on the "node_id" field.
func NodeIDHasSuffix(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldHasSuffix(FieldNodeID, v))
}

// NodeIDEqualFold applies the EqualFold predicate on the "node_id" field.
func NodeIDEqualFold(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldEqualFold(FieldNodeID, v))
}

// NodeIDContainsFold applies the ContainsFold predicate on the "node_id" field.
func NodeIDContainsFold(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldContainsFold(FieldNodeID, v))
}

// RunIDEQ applies the EQ predicate on the "run_id" field.
func RunIDEQ(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldEQ(FieldRunID, v))
}

// RunIDNEQ applies the NEQ predicate on the "run_id" field.
func RunIDNEQ(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldNEQ(FieldRunID, v))
}

// RunIDIn applies the In predicate on the "run_id" field.
func RunIDIn(vs ...string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldIn(FieldRunID, vs...))
}

// RunIDNotIn applies the NotIn predicate on the "run_id" field.
func RunIDNotIn(vs ...string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldNotIn(FieldRunID, vs...))
}

// RunIDGT applies the GT predicate on the "run_id" field.
func RunIDGT(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldGT(FieldRunID, v))
}

// RunIDGTE applies the GTE predicate on the "run_id" field.
func RunIDGTE(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldGTE(FieldRunID, v))
}

// RunIDLT applies the LT predicate on the "run_id" field.
func RunIDLT(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldLT(FieldRunID, v))
}

// RunIDLTE applies the LTE predicate on the "run_id" field.
func RunIDLTE(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldLTE(FieldRunID, v))
}

// RunIDContains applies the Contains predicate on the "run_id" field.
func RunIDContains(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldContains(FieldRunID, v))
}

// RunIDHasPrefix applies the HasPrefix predicate on the "run_id" field.
func RunIDHasPrefix(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldHasPrefix(FieldRunID, v))
}

// RunIDHasSuffix applies the HasSuffix predicate on the "run_id" field.
func RunIDHasSuffix(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldHasSuffix(FieldRunID, v))
}

// RunIDEqualFold applies the EqualFold predicate on the "run_id" field.
func RunIDEqualFold(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldEqualFold(FieldRunID, v))
}

// RunIDContainsFold applies the ContainsFold predicate on the "run_id" field.
func RunIDContainsFold(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldContainsFold(FieldRunID, v))
}

// SequenceEQ applies the EQ predicate on the "sequence" field.
func SequenceEQ(v int) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldEQ(FieldSequence, v))
}

// SequenceNEQ applies the NEQ predicate on the "sequence" field.
func SequenceNEQ(v int) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldNEQ(FieldSequence, v))
}

// SequenceIn applies the In predicate on the "sequence" field.
func SequenceIn(vs ...int) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldIn(FieldSequence, vs...))
}

// SequenceNotIn applies the NotIn predicate on the "sequence" field.
func SequenceNotIn(vs ...int) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldNotIn(FieldSequence, vs...))
}

// SequenceGT applies the GT predicate on the "sequence" field.
func SequenceGT(v int) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldGT(FieldSequence, v))
}

// SequenceGTE applies the GTE predicate on the "sequence" field.
func SequenceGTE(v int) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldGTE(FieldSequence, v))
}

// SequenceLT applies the LT predicate on the "sequence" field.
func SequenceLT(v int) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldLT(FieldSequence, v))
}

// SequenceLTE applies the LTE predicate on the "sequence" field.
func SequenceLTE(v int) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldLTE(FieldSequence, v))
}

// DagIDEQ applies the EQ predicate on the "dag_id" field.
func DagIDEQ(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldEQ(FieldDagID, v))
}

// DagIDNEQ applies the NEQ predicate on the "dag_id" field.
func DagIDNEQ(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldNEQ(FieldDagID, v))
}

// DagIDIn applies the In predicate on the "dag_id" field.
func DagIDIn(vs ...string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldIn(FieldDagID, vs...))
}

// DagIDNotIn applies the NotIn predicate on the "dag_id" field.
func DagIDNotIn(vs ...string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldNotIn(FieldDagID, vs...))
}

// DagIDGT applies the GT predicate on the "dag_id" field.
func DagIDGT(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldGT(FieldDagID, v))
}

// DagIDGTE applies the GTE predicate on the "dag_id" field.
func DagIDGTE(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldGTE(FieldDagID, v))
}

// DagIDLT applies the LT predicate on the "dag_id" field.
func DagIDLT(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldLT(FieldDagID, v))
}

// DagIDLTE applies the LTE predicate on the "dag_id" field.
func DagIDLTE(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldLTE(FieldDagID, v))
}

// DagIDContains applies the Contains predicate on the "dag_id" field.
func DagIDContains(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldContains(FieldDagID, v))
}

// DagIDHasPrefix applies the HasPrefix predicate on the "dag_id" field.
func DagIDHasPrefix(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldHasPrefix(FieldDagID, v))
}

// DagIDHasSuffix applies the HasSuffix predicate on the "dag_id" field.
func DagIDHasSuffix(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldHasSuffix(FieldDagID, v))
}

// DagIDIsNil applies the IsNil predicate on the "dag_id" field.
func DagIDIsNil() predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldIsNull(FieldDagID))
}

// DagIDNotNil applies the NotNil predicate on the "dag_id" field.
func DagIDNotNil() predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldNotNull(FieldDagID))
}

// DagIDEqualFold applies the EqualFold predicate on the "dag_id" field.
func DagIDEqualFold(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldEqualFold(FieldDagID, v))
}

// DagIDContainsFold applies the ContainsFold predicate on the "dag_id" field.
func DagIDContainsFold(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldContainsFold(FieldDagID, v))
}

// DagVersionEQ applies the EQ predicate on the "dag_version" field.
func DagVersionEQ(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldEQ(FieldDagVersion, v))
}

// DagVersionNEQ applies the NEQ predicate on the "dag_version" field.
func DagVersionNEQ(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldNEQ(FieldDagVersion, v))
}

// DagVersionIn applies the In predicate on the "dag_version" field.
func DagVersionIn(vs ...string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldIn(FieldDagVersion, vs...))
}

// DagVersionNotIn applies the NotIn predicate on the "dag_version" field.
func DagVersionNotIn(vs ...string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldNotIn(FieldDagVersion, vs...))
}

// DagVersionGT applies the GT predicate on the "dag_version" field.
func DagVersionGT(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldGT(FieldDagVersion, v))
}

// DagVersionGTE applies the GTE predicate on the "dag_version" field.
func DagVersionGTE(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldGTE(FieldDagVersion, v))
}

// DagVersionLT applies the LT predicate on the "dag_version" field.
func DagVersionLT(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldLT(FieldDagVersion, v))
}

// DagVersionLTE applies the LTE predicate on the "dag_version" field.
func DagVersionLTE(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldLTE(FieldDagVersion, v))
}

// DagVersionContains applies the Contains predicate on the "dag_version" field.
func DagVersionContains(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldContains(FieldDagVersion, v))
}

// DagVersionHasPrefix applies the HasPrefix predicate on the "dag_version" field.
func DagVersionHasPrefix(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldHasPrefix(FieldDagVersion, v))
}

// DagVersionHasSuffix applies the HasSuffix predicate on the "dag_version" field.
func DagVersionHasSuffix(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldHasSuffix(FieldDagVersion, v))
}

// DagVersionIsNil applies the IsNil predicate on the "dag_version" field.
func DagVersionIsNil() predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldIsNull(FieldDagVersion))
}

// DagVersionNotNil applies the NotNil predicate on the "dag_version" field.
func DagVersionNotNil() predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldNotNull(FieldDagVersion))
}

// DagVersionEqualFold applies the EqualFold predicate on the "dag_version" field.
func DagVersionEqualFold(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldEqualFold(FieldDagVersion, v))
}

// DagVersionContainsFold applies the ContainsFold predicate on the "dag_version" field.
func DagVersionContainsFold(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldContainsFold(FieldDagVersion, v))
}

// FqcnEQ applies the EQ predicate on the "fqcn" field.
func FqcnEQ(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldEQ(FieldFqcn, v))
}

// FqcnNEQ applies the NEQ predicate on the "fqcn" field.
func FqcnNEQ(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldNEQ(FieldFqcn, v))
}

// FqcnIn applies the In predicate on the "fqcn" field.
func FqcnIn(vs ...string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldIn(FieldFqcn, vs...))
}

// FqcnNotIn applies the NotIn predicate on the "fqcn" field.
func FqcnNotIn(vs ...string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldNotIn(FieldFqcn, vs...))
}

// FqcnGT applies the GT predicate on the "fqcn" field.
func FqcnGT(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldGT(FieldFqcn, v))
}

// FqcnGTE applies the GTE predicate on the "fqcn" field.
func FqcnGTE(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldGTE(FieldFqcn, v))
}

// FqcnLT applies the LT predicate on the "fqcn" field.
func FqcnLT(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldLT(FieldFqcn, v))
}

// FqcnLTE applies the LTE predicate on the "fqcn" field.
func FqcnLTE(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldLTE(FieldFqcn, v))
}

// FqcnContains applies the Contains predicate on the "fqcn" field.
func FqcnContains(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldContains(FieldFqcn, v))
}

// FqcnHasPrefix applies the HasPrefix predicate on the "fqcn" field.
func FqcnHasPrefix(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldHasPrefix(FieldFqcn, v))
}

// FqcnHasSuffix applies the HasSuffix predicate on the "fqcn" field.
func FqcnHasSuffix(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldHasSuffix(FieldFqcn, v))
}

// FqcnIsNil applies the IsNil predicate on the "fqcn" field.
func FqcnIsNil() predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldIsNull(FieldFqcn))
}

// FqcnNotNil applies the NotNil predicate on the "fqcn" field.
func FqcnNotNil() predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldNotNull(FieldFqcn))
}

// FqcnEqualFold applies the EqualFold predicate on the "fqcn" field.
func FqcnEqualFold(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldEqualFold(FieldFqcn, v))
}

// FqcnContainsFold applies the ContainsFold predicate on the "fqcn" field.
func FqcnContainsFold(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldContainsFold(FieldFqcn, v))
}

// FqcnUnresolvedEQ applies the EQ predicate on the "fqcn_unresolved" field.
func FqcnUnresolvedEQ(v bool) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldEQ(FieldFqcnUnresolved, v))
}

// FqcnUnresolvedNEQ applies the NEQ predicate on the "fqcn_unresolved" field.
func FqcnUnresolvedNEQ(v bool) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldNEQ(FieldFqcnUnresolved, v))
}

// ProviderProgramEQ applies the EQ predicate on the "provider_program" field.
func ProviderProgramEQ(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldEQ(FieldProviderProgram, v))
}

// ProviderProgramNEQ applies the NEQ predicate on the "provider_program" field.
func ProviderProgramNEQ(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldNEQ(FieldProviderProgram, v))
}

// ProviderProgramIn applies the In predicate on the "provider_program" field.
func ProviderProgramIn(vs ...string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldIn(FieldProviderProgram, vs...))
}

// ProviderProgramNotIn applies the NotIn predicate on the "provider_program" field.
func ProviderProgramNotIn(vs ...string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldNotIn(FieldProviderProgram, vs...))
}

// ProviderProgramGT applies the GT predicate on the "provider_program" field.
func ProviderProgramGT(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldGT(FieldProviderProgram, v))
}

// ProviderProgramGTE applies the GTE predicate on the "provider_program" field.
func ProviderProgramGTE(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldGTE(FieldProviderProgram, v))
}

// ProviderProgramLT applies the LT predicate on the "provider_program" field.
func ProviderProgramLT(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldLT(FieldProviderProgram, v))
}

// ProviderProgramLTE applies the LTE predicate on the "provider_program" field.
func ProviderProgramLTE(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldLTE(FieldProviderProgram, v))
}

// ProviderProgramContains applies the Contains predicate on the "provider_program" field.
func ProviderProgramContains(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldContains(FieldProviderProgram, v))
}

// ProviderProgramHasPrefix applies the HasPrefix predicate on the "provider_program" field.
func ProviderProgramHasPrefix(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldHasPrefix(FieldProviderProgram, v))
}

// ProviderProgramHasSuffix applies the HasSuffix predicate on the "provider_program" field.
func ProviderProgramHasSuffix(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldHasSuffix(FieldProviderProgram, v))
}

// ProviderProgramIsNil applies the IsNil predicate on the "provider_program" field.
func ProviderProgramIsNil() predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldIsNull(FieldProviderProgram))
}

// ProviderProgramNotNil applies the NotNil predicate on the "provider_program" field.
func ProviderProgramNotNil() predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldNotNull(FieldProviderProgram))
}

// ProviderProgramEqualFold applies the EqualFold predicate on the "provider_program" field.
func ProviderProgramEqualFold(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldEqualFold(FieldProviderProgram, v))
}

// ProviderProgramContainsFold applies the ContainsFold predicate on the "provider_program" field.
func ProviderProgramContainsFold(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldContainsFold(FieldProviderProgram, v))
}

// ProviderDigestEQ applies the EQ predicate on the "provider_digest" field.
func ProviderDigestEQ(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldEQ(FieldProviderDigest, v))
}

// ProviderDigestNEQ applies the NEQ predicate on the "provider_digest" field.
func ProviderDigestNEQ(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldNEQ(FieldProviderDigest, v))
}

// ProviderDigestIn applies the In predicate on the "provider_digest" field.
func ProviderDigestIn(vs ...string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldIn(FieldProviderDigest, vs...))
}

// ProviderDigestNotIn applies the NotIn predicate on the "provider_digest" field.
func ProviderDigestNotIn(vs ...string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldNotIn(FieldProviderDigest, vs...))
}

// ProviderDigestGT applies the GT predicate on the "provider_digest" field.
func ProviderDigestGT(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldGT(FieldProviderDigest, v))
}

// ProviderDigestGTE applies the GTE predicate on the "provider_digest" field.
func ProviderDigestGTE(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldGTE(FieldProviderDigest, v))
}

// ProviderDigestLT applies the LT predicate on the "provider_digest" field.
func ProviderDigestLT(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldLT(FieldProviderDigest, v))
}

// ProviderDigestLTE applies the LTE predicate on the "provider_digest" field.
func ProviderDigestLTE(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldLTE(FieldProviderDigest, v))
}

// ProviderDigestContains applies the Contains predicate on the "provider_digest" field.
func ProviderDigestContains(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldContains(FieldProviderDigest, v))
}

// ProviderDigestHasPrefix applies the HasPrefix predicate on the "provider_digest" field.
func ProviderDigestHasPrefix(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldHasPrefix(FieldProviderDigest, v))
}

// ProviderDigestHasSuffix applies the HasSuffix predicate on the "provider_digest" field.
func ProviderDigestHasSuffix(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldHasSuffix(FieldProviderDigest, v))
}

// ProviderDigestIsNil applies the IsNil predicate on the "provider_digest" field.
func ProviderDigestIsNil() predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldIsNull(FieldProviderDigest))
}

// ProviderDigestNotNil applies the NotNil predicate on the "provider_digest" field.
func ProviderDigestNotNil() predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldNotNull(FieldProviderDigest))
}

// ProviderDigestEqualFold applies the EqualFold predicate on the "provider_digest" field.
func ProviderDigestEqualFold(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldEqualFold(FieldProviderDigest, v))
}

// ProviderDigestContainsFold applies the ContainsFold predicate on the "provider_digest" field.
func ProviderDigestContainsFold(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldContainsFold(FieldProviderDigest, v))
}

// TaskNameEQ applies the EQ predicate on the "task_name" field.
func TaskNameEQ(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldEQ(FieldTaskName, v))
}

// TaskNameNEQ applies the NEQ predicate on the "task_name" field.
func TaskNameNEQ(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldNEQ(FieldTaskName, v))
}

// TaskNameIn applies the In predicate on the "task_name" field.
func TaskNameIn(vs ...string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldIn(FieldTaskName, vs...))
}

// TaskNameNotIn applies the NotIn predicate on the "task_name" field.
func TaskNameNotIn(vs ...string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldNotIn(FieldTaskName, vs...))
}

// TaskNameGT applies the GT predicate on the "task_name" field.
func TaskNameGT(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldGT(FieldTaskName, v))
}

// TaskNameGTE applies the GTE predicate on the "task_name" field.
func TaskNameGTE(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldGTE(FieldTaskName, v))
}

// TaskNameLT applies the LT predicate on the "task_name" field.
func TaskNameLT(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldLT(FieldTaskName, v))
}

// TaskNameLTE applies the LTE predicate on the "task_name" field.
func TaskNameLTE(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldLTE(FieldTaskName, v))
}

// TaskNameContains applies the Contains predicate on the "task_name" field.
func TaskNameContains(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldContains(FieldTaskName, v))
}

// TaskNameHasPrefix applies the HasPrefix predicate on the "task_name" field.
func TaskNameHasPrefix(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldHasPrefix(FieldTaskName, v))
}

// TaskNameHasSuffix applies the HasSuffix predicate on the "task_name" field.
func TaskNameHasSuffix(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldHasSuffix(FieldTaskName, v))
}

// TaskNameIsNil applies the IsNil predicate on the "task_name" field.
func TaskNameIsNil() predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldIsNull(FieldTaskName))
}

// TaskNameNotNil applies the NotNil predicate on the "task_name" field.
func TaskNameNotNil() predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldNotNull(FieldTaskName))
}

// TaskNameEqualFold applies the EqualFold predicate on the "task_name" field.
func TaskNameEqualFold(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldEqualFold(FieldTaskName, v))
}

// TaskNameContainsFold applies the ContainsFold predicate on the "task_name" field.
func TaskNameContainsFold(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldContainsFold(FieldTaskName, v))
}

// RegisterEQ applies the EQ predicate on the "register" field.
func RegisterEQ(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldEQ(FieldRegister, v))
}

// RegisterNEQ applies the NEQ predicate on the "register" field.
func RegisterNEQ(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldNEQ(FieldRegister, v))
}

// RegisterIn applies the In predicate on the "register" field.
func RegisterIn(vs ...string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldIn(FieldRegister, vs...))
}

// RegisterNotIn applies the NotIn predicate on the "register" field.
func RegisterNotIn(vs ...string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldNotIn(FieldRegister, vs...))
}

// RegisterGT applies the GT predicate on the "register" field.
func RegisterGT(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldGT(FieldRegister, v))
}

// RegisterGTE applies the GTE predicate on the "register" field.
func RegisterGTE(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldGTE(FieldRegister, v))
}

// RegisterLT applies the LT predicate on the "register" field.
func RegisterLT(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldLT(FieldRegister, v))
}

// RegisterLTE applies the LTE predicate on the "register" field.
func RegisterLTE(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldLTE(FieldRegister, v))
}

// RegisterContains applies the Contains predicate on the "register" field.
func RegisterContains(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldContains(FieldRegister, v))
}

// RegisterHasPrefix applies the HasPrefix predicate on the "register" field.
func RegisterHasPrefix(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldHasPrefix(FieldRegister, v))
}

// RegisterHasSuffix applies the HasSuffix predicate on the "register" field.
func RegisterHasSuffix(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldHasSuffix(FieldRegister, v))
}

// RegisterIsNil applies the IsNil predicate on the "register" field.
func RegisterIsNil() predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldIsNull(FieldRegister))
}

// RegisterNotNil applies the NotNil predicate on the "register" field.
func RegisterNotNil() predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldNotNull(FieldRegister))
}

// RegisterEqualFold applies the EqualFold predicate on the "register" field.
func RegisterEqualFold(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldEqualFold(FieldRegister, v))
}

// RegisterContainsFold applies the ContainsFold predicate on the "register" field.
func RegisterContainsFold(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldContainsFold(FieldRegister, v))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldLTE(FieldStartedAt, v))
}

// StartedAtIsNil applies the IsNil predicate on the "started_at" field.
func StartedAtIsNil() predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldIsNull(FieldStartedAt))
}

// StartedAtNotNil applies the NotNil predicate on the "started_at" field.
func StartedAtNotNil() predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldNotNull(FieldStartedAt))
}

// FinishedAtEQ applies the EQ predicate on the "finished_at" field.
func FinishedAtEQ(v time.Time) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldEQ(FieldFinishedAt, v))
}

// FinishedAtNEQ applies the NEQ predicate on the "finished_at" field.
func FinishedAtNEQ(v time.Time) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldNEQ(FieldFinishedAt, v))
}

// FinishedAtIn applies the In predicate on the "finished_at" field.
func FinishedAtIn(vs ...time.Time) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldIn(FieldFinishedAt, vs...))
}

// FinishedAtNotIn applies the NotIn predicate on the "finished_at" field.
func FinishedAtNotIn(vs ...time.Time) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldNotIn(FieldFinishedAt, vs...))
}

// FinishedAtGT applies the GT predicate on the "finished_at" field.
func FinishedAtGT(v time.Time) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldGT(FieldFinishedAt, v))
}

// FinishedAtGTE applies the GTE predicate on the "finished_at" field.
func FinishedAtGTE(v time.Time) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldGTE(FieldFinishedAt, v))
}

// FinishedAtLT applies the LT predicate on the "finished_at" field.
func FinishedAtLT(v time.Time) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldLT(FieldFinishedAt, v))
}

// FinishedAtLTE applies the LTE predicate on the "finished_at" field.
func FinishedAtLTE(v time.Time) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldLTE(FieldFinishedAt, v))
}

// FinishedAtIsNil applies the IsNil predicate on the "finished_at" field.
func FinishedAtIsNil() predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldIsNull(FieldFinishedAt))
}

// FinishedAtNotNil applies the NotNil predicate on the "finished_at" field.
func FinishedAtNotNil() predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldNotNull(FieldFinishedAt))
}

// OutcomeEQ applies the EQ predicate on the "outcome" field.
func OutcomeEQ(v Outcome) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldEQ(FieldOutcome, v))
}

// OutcomeNEQ applies the NEQ predicate on the "outcome" field.
func OutcomeNEQ(v Outcome) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldNEQ(FieldOutcome, v))
}

// OutcomeIn applies the In predicate on the "outcome" field.
func OutcomeIn(vs ...Outcome) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldIn(FieldOutcome, vs...))
}

// OutcomeNotIn applies the NotIn predicate on the "outcome" field.
func OutcomeNotIn(vs ...Outcome) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldNotIn(FieldOutcome, vs...))
}

// FailureStageEQ applies the EQ predicate on the "failure_stage" field.
func FailureStageEQ(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldEQ(FieldFailureStage, v))
}

// FailureStageNEQ applies the NEQ predicate on the "failure_stage" field.
func FailureStageNEQ(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldNEQ(FieldFailureStage, v))
}

// FailureStageIn applies the In predicate on the "failure_stage" field.
func FailureStageIn(vs ...string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldIn(FieldFailureStage, vs...))
}

// FailureStageNotIn applies the NotIn predicate on the "failure_stage" field.
func FailureStageNotIn(vs ...string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldNotIn(FieldFailureStage, vs...))
}

// FailureStageGT applies the GT predicate on the "failure_stage" field.
func FailureStageGT(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldGT(FieldFailureStage, v))
}

// FailureStageGTE applies the GTE predicate on the "failure_stage" field.
func FailureStageGTE(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldGTE(FieldFailureStage, v))
}

// FailureStageLT applies the LT predicate on the "failure_stage" field.
func FailureStageLT(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldLT(FieldFailureStage, v))
}

// FailureStageLTE applies the LTE predicate on the "failure_stage" field.
func FailureStageLTE(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldLTE(FieldFailureStage, v))
}

// FailureStageContains applies the Contains predicate on the "failure_stage" field.
func FailureStageContains(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldContains(FieldFailureStage, v))
}

// FailureStageHasPrefix applies the HasPrefix predicate on the "failure_stage" field.
func FailureStageHasPrefix(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldHasPrefix(FieldFailureStage, v))
}

// FailureStageHasSuffix applies the HasSuffix predicate on the "failure_stage" field.
func FailureStageHasSuffix(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldHasSuffix(FieldFailureStage, v))
}

// FailureStageIsNil applies the IsNil predicate on the "failure_stage" field.
func FailureStageIsNil() predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldIsNull(FieldFailureStage))
}

// FailureStageNotNil applies the NotNil predicate on the "failure_stage" field.
func FailureStageNotNil() predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldNotNull(FieldFailureStage))
}

// FailureStageEqualFold applies the EqualFold predicate on the "failure_stage" field.
func FailureStageEqualFold(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldEqualFold(FieldFailureStage, v))
}

// FailureStageContainsFold applies the ContainsFold predicate on the "failure_stage" field.
func FailureStageContainsFold(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldContainsFold(FieldFailureStage, v))
}

// SkipKindEQ applies the EQ predicate on the "skip_kind" field.
func SkipKindEQ(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldEQ(FieldSkipKind, v))
}

// SkipKindNEQ applies the NEQ predicate on the "skip_kind" field.
func SkipKindNEQ(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldNEQ(FieldSkipKind, v))
}

// SkipKindIn applies the In predicate on the "skip_kind" field.
func SkipKindIn(vs ...string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldIn(FieldSkipKind, vs...))
}

// SkipKindNotIn applies the NotIn predicate on the "skip_kind" field.
func SkipKindNotIn(vs ...string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldNotIn(FieldSkipKind, vs...))
}

// SkipKindGT applies the GT predicate on the "skip_kind" field.
func SkipKindGT(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldGT(FieldSkipKind, v))
}

// SkipKindGTE applies the GTE predicate on the "skip_kind" field.
func SkipKindGTE(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldGTE(FieldSkipKind, v))
}

// SkipKindLT applies the LT predicate on the "skip_kind" field.
func SkipKindLT(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldLT(FieldSkipKind, v))
}

// SkipKindLTE applies the LTE predicate on the "skip_kind" field.
func SkipKindLTE(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldLTE(FieldSkipKind, v))
}

// SkipKindContains applies the Contains predicate on the "skip_kind" field.
func SkipKindContains(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldContains(FieldSkipKind, v))
}

// SkipKindHasPrefix applies the HasPrefix predicate on the "skip_kind" field.
func SkipKindHasPrefix(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldHasPrefix(FieldSkipKind, v))
}

// SkipKindHasSuffix applies the HasSuffix predicate on the "skip_kind" field.
func SkipKindHasSuffix(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldHasSuffix(FieldSkipKind, v))
}

// SkipKindIsNil applies the IsNil predicate on the "skip_kind" field.
func SkipKindIsNil() predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldIsNull(FieldSkipKind))
}

// SkipKindNotNil applies the NotNil predicate on the "skip_kind" field.
func SkipKindNotNil() predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldNotNull(FieldSkipKind))
}

// SkipKindEqualFold applies the EqualFold predicate on the "skip_kind" field.
func SkipKindEqualFold(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldEqualFold(FieldSkipKind, v))
}

// SkipKindContainsFold applies the ContainsFold predicate on the "skip_kind" field.
func SkipKindContainsFold(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldContainsFold(FieldSkipKind, v))
}

// SkipOrdinalEQ applies the EQ predicate on the "skip_ordinal" field.
func SkipOrdinalEQ(v int) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldEQ(FieldSkipOrdinal, v))
}

// SkipOrdinalNEQ applies the NEQ predicate on the "skip_ordinal" field.
func SkipOrdinalNEQ(v int) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldNEQ(FieldSkipOrdinal, v))
}

// SkipOrdinalIn applies the In predicate on the "skip_ordinal" field.
func SkipOrdinalIn(vs ...int) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldIn(FieldSkipOrdinal, vs...))
}

// SkipOrdinalNotIn applies the NotIn predicate on the "skip_ordinal" field.
func SkipOrdinalNotIn(vs ...int) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldNotIn(FieldSkipOrdinal, vs...))
}

// SkipOrdinalGT applies the GT predicate on the "skip_ordinal" field.
func SkipOrdinalGT(v int) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldGT(FieldSkipOrdinal, v))
}

// SkipOrdinalGTE applies the GTE predicate on the "skip_ordinal" field.
func SkipOrdinalGTE(v int) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldGTE(FieldSkipOrdinal, v))
}

// SkipOrdinalLT applies the LT predicate on the "skip_ordinal" field.
func SkipOrdinalLT(v int) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldLT(FieldSkipOrdinal, v))
}

// SkipOrdinalLTE applies the LTE predicate on the "skip_ordinal" field.
func SkipOrdinalLTE(v int) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldLTE(FieldSkipOrdinal, v))
}

// SkipTotalEQ applies the EQ predicate on the "skip_total" field.
func SkipTotalEQ(v int) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldEQ(FieldSkipTotal, v))
}

// SkipTotalNEQ applies the NEQ predicate on the "skip_total" field.
func SkipTotalNEQ(v int) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldNEQ(FieldSkipTotal, v))
}

// SkipTotalIn applies the In predicate on the "skip_total" field.
func SkipTotalIn(vs ...int) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldIn(FieldSkipTotal, vs...))
}

// SkipTotalNotIn applies the NotIn predicate on the "skip_total" field.
func SkipTotalNotIn(vs ...int) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldNotIn(FieldSkipTotal, vs...))
}

// SkipTotalGT applies the GT predicate on the "skip_total" field.
func SkipTotalGT(v int) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldGT(FieldSkipTotal, v))
}

// SkipTotalGTE applies the GTE predicate on the "skip_total" field.
func SkipTotalGTE(v int) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldGTE(FieldSkipTotal, v))
}

// SkipTotalLT applies the LT predicate on the "skip_total" field.
func SkipTotalLT(v int) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldLT(FieldSkipTotal, v))
}

// SkipTotalLTE applies the LTE predicate on the "skip_total" field.
func SkipTotalLTE(v int) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldLTE(FieldSkipTotal, v))
}

// StatKeysIsNil applies the IsNil predicate on the "stat_keys" field.
func StatKeysIsNil() predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldIsNull(FieldStatKeys))
}

// StatKeysNotNil applies the NotNil predicate on the "stat_keys" field.
func StatKeysNotNil() predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldNotNull(FieldStatKeys))
}

// UndeclaredStatCountEQ applies the EQ predicate on the "undeclared_stat_count" field.
func UndeclaredStatCountEQ(v int) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldEQ(FieldUndeclaredStatCount, v))
}

// UndeclaredStatCountNEQ applies the NEQ predicate on the "undeclared_stat_count" field.
func UndeclaredStatCountNEQ(v int) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldNEQ(FieldUndeclaredStatCount, v))
}

// UndeclaredStatCountIn applies the In predicate on the "undeclared_stat_count" field.
func UndeclaredStatCountIn(vs ...int) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldIn(FieldUndeclaredStatCount, vs...))
}

// UndeclaredStatCountNotIn applies the NotIn predicate on the "undeclared_stat_count" field.
func UndeclaredStatCountNotIn(vs ...int) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldNotIn(FieldUndeclaredStatCount, vs...))
}

// UndeclaredStatCountGT applies the GT predicate on the "undeclared_stat_count" field.
func UndeclaredStatCountGT(v int) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldGT(FieldUndeclaredStatCount, v))
}

// UndeclaredStatCountGTE applies the GTE predicate on the "undeclared_stat_count" field.
func UndeclaredStatCountGTE(v int) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldGTE(FieldUndeclaredStatCount, v))
}

// UndeclaredStatCountLT applies the LT predicate on the "undeclared_stat_count" field.
func UndeclaredStatCountLT(v int) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldLT(FieldUndeclaredStatCount, v))
}

// UndeclaredStatCountLTE applies the LTE predicate on the "undeclared_stat_count" field.
func UndeclaredStatCountLTE(v int) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldLTE(FieldUndeclaredStatCount, v))
}

// ParamKeysIsNil applies the IsNil predicate on the "param_keys" field.
func ParamKeysIsNil() predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldIsNull(FieldParamKeys))
}

// ParamKeysNotNil applies the NotNil predicate on the "param_keys" field.
func ParamKeysNotNil() predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldNotNull(FieldParamKeys))
}

// UndeclaredParamCountEQ applies the EQ predicate on the "undeclared_param_count" field.
func UndeclaredParamCountEQ(v int) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldEQ(FieldUndeclaredParamCount, v))
}

// UndeclaredParamCountNEQ applies the NEQ predicate on the "undeclared_param_count" field.
func UndeclaredParamCountNEQ(v int) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldNEQ(FieldUndeclaredParamCount, v))
}

// UndeclaredParamCountIn applies the In predicate on the "undeclared_param_count" field.
func UndeclaredParamCountIn(vs ...int) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldIn(FieldUndeclaredParamCount, vs...))
}

// UndeclaredParamCountNotIn applies the NotIn predicate on the "undeclared_param_count" field.
func UndeclaredParamCountNotIn(vs ...int) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldNotIn(FieldUndeclaredParamCount, vs...))
}

// UndeclaredParamCountGT applies the GT predicate on the "undeclared_param_count" field.
func UndeclaredParamCountGT(v int) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldGT(FieldUndeclaredParamCount, v))
}

// UndeclaredParamCountGTE applies the GTE predicate on the "undeclared_param_count" field.
func UndeclaredParamCountGTE(v int) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldGTE(FieldUndeclaredParamCount, v))
}

// UndeclaredParamCountLT applies the LT predicate on the "undeclared_param_count" field.
func UndeclaredParamCountLT(v int) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldLT(FieldUndeclaredParamCount, v))
}

// UndeclaredParamCountLTE applies the LTE predicate on the "undeclared_param_count" field.
func UndeclaredParamCountLTE(v int) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldLTE(FieldUndeclaredParamCount, v))
}

// InverseFqcnEQ applies the EQ predicate on the "inverse_fqcn" field.
func InverseFqcnEQ(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldEQ(FieldInverseFqcn, v))
}

// InverseFqcnNEQ applies the NEQ predicate on the "inverse_fqcn" field.
func InverseFqcnNEQ(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldNEQ(FieldInverseFqcn, v))
}

// InverseFqcnIn applies the In predicate on the "inverse_fqcn" field.
func InverseFqcnIn(vs ...string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldIn(FieldInverseFqcn, vs...))
}

// InverseFqcnNotIn applies the NotIn predicate on the "inverse_fqcn" field.
func InverseFqcnNotIn(vs ...string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldNotIn(FieldInverseFqcn, vs...))
}

// InverseFqcnGT applies the GT predicate on the "inverse_fqcn" field.
func InverseFqcnGT(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldGT(FieldInverseFqcn, v))
}

// InverseFqcnGTE applies the GTE predicate on the "inverse_fqcn" field.
func InverseFqcnGTE(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldGTE(FieldInverseFqcn, v))
}

// InverseFqcnLT applies the LT predicate on the "inverse_fqcn" field.
func InverseFqcnLT(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldLT(FieldInverseFqcn, v))
}

// InverseFqcnLTE applies the LTE predicate on the "inverse_fqcn" field.
func InverseFqcnLTE(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldLTE(FieldInverseFqcn, v))
}

// InverseFqcnContains applies the Contains predicate on the "inverse_fqcn" field.
func InverseFqcnContains(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldContains(FieldInverseFqcn, v))
}

// InverseFqcnHasPrefix applies the HasPrefix predicate on the "inverse_fqcn" field.
func InverseFqcnHasPrefix(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldHasPrefix(FieldInverseFqcn, v))
}

// InverseFqcnHasSuffix applies the HasSuffix predicate on the "inverse_fqcn" field.
func InverseFqcnHasSuffix(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldHasSuffix(FieldInverseFqcn, v))
}

// InverseFqcnIsNil applies the IsNil predicate on the "inverse_fqcn" field.
func InverseFqcnIsNil() predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldIsNull(FieldInverseFqcn))
}

// InverseFqcnNotNil applies the NotNil predicate on the "inverse_fqcn" field.
func InverseFqcnNotNil() predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldNotNull(FieldInverseFqcn))
}

// InverseFqcnEqualFold applies the EqualFold predicate on the "inverse_fqcn" field.
func InverseFqcnEqualFold(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldEqualFold(FieldInverseFqcn, v))
}

// InverseFqcnContainsFold applies the ContainsFold predicate on the "inverse_fqcn" field.
func InverseFqcnContainsFold(v string) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldContainsFold(FieldInverseFqcn, v))
}

// InverseFqcnUnresolvedEQ applies the EQ predicate on the "inverse_fqcn_unresolved" field.
func InverseFqcnUnresolvedEQ(v bool) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldEQ(FieldInverseFqcnUnresolved, v))
}

// InverseFqcnUnresolvedNEQ applies the NEQ predicate on the "inverse_fqcn_unresolved" field.
func InverseFqcnUnresolvedNEQ(v bool) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldNEQ(FieldInverseFqcnUnresolved, v))
}

// InverseParamKeysIsNil applies the IsNil predicate on the "inverse_param_keys" field.
func InverseParamKeysIsNil() predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldIsNull(FieldInverseParamKeys))
}

// InverseParamKeysNotNil applies the NotNil predicate on the "inverse_param_keys" field.
func InverseParamKeysNotNil() predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldNotNull(FieldInverseParamKeys))
}

// UndeclaredInverseParamCountEQ applies the EQ predicate on the "undeclared_inverse_param_count" field.
func UndeclaredInverseParamCountEQ(v int) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldEQ(FieldUndeclaredInverseParamCount, v))
}

// UndeclaredInverseParamCountNEQ applies the NEQ predicate on the "undeclared_inverse_param_count" field.
func UndeclaredInverseParamCountNEQ(v int) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldNEQ(FieldUndeclaredInverseParamCount, v))
}

// UndeclaredInverseParamCountIn applies the In predicate on the "undeclared_inverse_param_count" field.
func UndeclaredInverseParamCountIn(vs ...int) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldIn(FieldUndeclaredInverseParamCount, vs...))
}

// UndeclaredInverseParamCountNotIn applies the NotIn predicate on the "undeclared_inverse_param_count" field.
func UndeclaredInverseParamCountNotIn(vs ...int) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldNotIn(FieldUndeclaredInverseParamCount, vs...))
}

// UndeclaredInverseParamCountGT applies the GT predicate on the "undeclared_inverse_param_count" field.
func UndeclaredInverseParamCountGT(v int) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldGT(FieldUndeclaredInverseParamCount, v))
}

// UndeclaredInverseParamCountGTE applies the GTE predicate on the "undeclared_inverse_param_count" field.
func UndeclaredInverseParamCountGTE(v int) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldGTE(FieldUndeclaredInverseParamCount, v))
}

// UndeclaredInverseParamCountLT applies the LT predicate on the "undeclared_inverse_param_count" field.
func UndeclaredInverseParamCountLT(v int) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldLT(FieldUndeclaredInverseParamCount, v))
}

// UndeclaredInverseParamCountLTE applies the LTE predicate on the "undeclared_inverse_param_count" field.
func UndeclaredInverseParamCountLTE(v int) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldLTE(FieldUndeclaredInverseParamCount, v))
}

// DiffRecordedEQ applies the EQ predicate on the "diff_recorded" field.
func DiffRecordedEQ(v bool) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldEQ(FieldDiffRecorded, v))
}

// DiffRecordedNEQ applies the NEQ predicate on the "diff_recorded" field.
func DiffRecordedNEQ(v bool) predicate.JournalEntry {
	return predicate.JournalEntry(sql.FieldNEQ(FieldDiffRecorded, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.JournalEntry) predicate.JournalEntry {
	return predicate.JournalEntry(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.JournalEntry) predicate.JournalEntry {
	return predicate.JournalEntry(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.JournalEntry) predicate.JournalEntry {
	return predicate.JournalEntry(sql.NotPredicates(p))
}
