package wait

import (
	"context"
	"fmt"

	"github.com/Subject-Void-LLC/the-pleiades/pkg/capability"
	"github.com/Subject-Void-LLC/the-pleiades/pkg/collection"
	"github.com/Subject-Void-LLC/the-pleiades/pkg/inventory"
	"github.com/Subject-Void-LLC/the-pleiades/pkg/remotefile"
	"github.com/Subject-Void-LLC/the-pleiades/pkg/sdk"
)

// This file implements "wait.path", generated by
// pleiades forge new-collection and then hand-completed.
//
// It is ansible.builtin.wait_for aimed at a path, with search_regex left
// to the sibling method: "is it there yet" and "does it say the right
// thing yet" are different questions with different failure messages, and
// one method answering both would have to explain in every error which of
// the two it had been asked.
//
// It creates nothing and deletes nothing. That is worth saying because
// state: absent reads like an instruction to remove the path, and it is
// not: it means "wait until something else removes it". file.remove is
// what removes.

func init() {
	collection.MustRegister(collection.Descriptor{
		Name: "wait.path",
		Manifest: collection.Manifest{
			SupportedTransports: []string{
				"ssh",
			},
			// POSIXFileSystemCapable rather than the NetworkAddressable
			// this method was scaffolded with. Being addressable is what
			// gets a connection open; what this method actually needs is a
			// device whose filesystem answers a stat, which is the same
			// requirement the file namespace declares and the same
			// primitive (pkg/remotefile) it reads through.
			RequiredCapabilities: []capability.Name{
				capability.NamePOSIXFileSystem,
			},
			// Reading a path needs no privilege the account does not
			// already have for the directory it sits in, and a task that
			// cannot traverse there fails with a real error rather than a
			// wrong answer, so declaring elevation here would mark every
			// wait as privileged and teach a reader to ignore the field.
			ExecutionContext: collection.ExecutionContext{
				RequiresElevation: false,
			},
			PlatformTargets: nil,
			EngineVersion:   ">=1.0.0",
			Status:          collection.StatusImplemented,
			// Reversible: false is the honest answer rather than an
			// unfinished one. This method observes and never acts, so a
			// rollback of it has nothing to move back, and it never emits
			// an inverse at run time either.
			Reversibility: collection.Reversibility{
				Reversible: false,
				Notes: "This method watches a path and changes nothing on the device, so there is nothing to undo. That is the same fact " +
					"that makes it report changed: false. It still records a diff whose two halves are identical, so a journal can tell " +
					"an observation from a task that was never recorded.",
			},
			Doc: pathDoc(),
		},
		Invoke: Path,
	})
}

// pathDoc is this method's reference documentation, kept out of the
// registration above so the manifest fields stay readable.
//
// It is duplicated into internal/forge/catalogdata, which is the source
// the scaffolder is driven from, and internal/archtest's
// TestCatalogDataDocsMatchTheRegistry compares the two for equality so
// the copies cannot drift.
func pathDoc() collection.Doc {
	return collection.Doc{
		Summary:     "Waits for a file path on the target to exist (or stop existing).",
		Description: "Polls a path on the device until it exists, or until it is gone when state is absent, and fails when the timeout runs out first. It changes nothing: state: absent waits for something else to remove the path, it does not remove it. Anything at the path counts as existing, including a directory and a symbolic link whose target is missing, since the link itself is a thing that is there; that differs from wait_for, which follows a link and calls a broken one absent. The delay is spent out of the timeout rather than added to it, matching wait_for, so delay must be shorter than timeout. A run that gives up returns an error, because a task that waited for something that never happened has failed.",
		Params: []collection.Param{
			{Name: waitParamPath, Type: "string", Required: true, Description: "The path on the device to watch."},
			{Name: waitParamState, Type: "string", Default: "present", Choices: []string{"present", "absent", "started", "stopped"}, Description: "Whether to wait for the path to exist (present) or to stop existing (absent). started and stopped are accepted as wait_for's own spellings of the same two, so a converted playbook needs no edit. drained is refused, since it asks about a socket's send queue and means nothing for a file."},
			{Name: waitParamTimeout, Type: "int", Default: "300", Description: "How many seconds to wait in total before giving up, counted from the start of the task, so the delay comes out of it. Must be more than 0."},
			{Name: waitParamDelay, Type: "int", Default: "0", Description: "How many seconds to wait before looking the first time. Must be shorter than the timeout, which it is spent out of."},
			{Name: waitParamSleep, Type: "int", Default: "1", Description: "How many seconds to wait between looks. Must be more than 0: a sleep of zero would probe the device as fast as it can answer."},
			{Name: sdk.ParamInsecureSkipHostKeyVerify, Type: "bool", Default: "false", Description: "Skip SSH host key verification for this task. This removes protection against a machine in the middle answering for the device, so set it only for a target you have decided does not need it."},
		},
		Returns: []collection.ReturnField{
			{Name: waitParamPath, Type: "string", Returned: "always", Description: "The path this task watched."},
			{Name: waitStatElapsed, Type: "int", Returned: "always", Description: "How many whole seconds the task waited, including the delay."},
			{Name: sdk.StatDiff, Type: "dict", Returned: "always", Description: "The state of the path when the wait ended, holding its path, kind, mode, owner, group, size and modification time. Both halves are identical, since a wait changes nothing."},
		},
		Examples: []collection.Example{
			{
				Name:        "Wait for a service to write its socket",
				RunbookYAML: "- name: Wait for the socket to appear\n  wait.path:\n    path: /run/pleiades/api.sock\n    timeout: 60\n",
			},
			{
				Name:        "Wait for a lock file to be released",
				RunbookYAML: "- name: Wait for the package manager to finish\n  wait.path:\n    path: /var/lib/dpkg/lock-frontend\n    state: absent\n    timeout: 300\n    sleep: 5\n",
			},
			{
				Name:        "Give a slow starter a head start",
				RunbookYAML: "- name: Wait for the pid file, but not immediately\n  wait.path:\n    path: /run/app.pid\n    delay: 10\n    timeout: 120\n",
			},
		},
		SeeAlso: []string{"wait.search", "pleiades.builtin.wait.port"},
	}
}

// Path implements the "wait.path" collection method: it watches a path
// on the device until it exists, or until it is gone.
//
// # Why this reports Changed false unconditionally
//
// It never sends a command that alters anything. The only commands it
// sends are the stat probes, so there is no run of it that could
// honestly report a change, and one that did would make every report
// claim work that never happened.
//
// # What the diff is for, given nothing changed
//
// The recorded diff holds the state the path was in when the wait ended,
// in both halves. It is what lets a journal say this task looked and
// found a directory of this mode owned by this account, rather than
// leaving a reader unable to tell an observation from a task that never
// ran. The inverse of that observation is nothing at all, which is why
// this method emits none.
func Path(ctx context.Context, rc sdk.RunbookContext, device inventory.InventoryItem, params map[string]any) (collection.Result, error) {
	const fqcn = "wait.path"

	req, err := waitReadRequest(params)
	if err != nil {
		return collection.Result{}, fmt.Errorf("%s: %w", fqcn, err)
	}

	conn, err := sdk.Connect(ctx, rc, device, params, fqcn)
	if err != nil {
		return collection.Result{}, err
	}
	defer func() { _ = conn.Close() }()

	// The last thing the probe saw, kept out here because it is what the
	// diff records: on the run that succeeded it is the state that made
	// the condition true, which is the only observation worth keeping.
	var observed remotefile.Info

	elapsed, err := waitPoll(ctx, req, pathCondition(req), func(ctx context.Context) (bool, error) {
		// Stat reports a missing path as an answer rather than as an
		// error, which is exactly what this method needs: absence is the
		// condition half the time, and a reader that raised on it could
		// never wait for anything to appear.
		info, err := remotefile.Stat(ctx, conn, req.Path)
		if err != nil {
			return false, err
		}
		observed = info
		return info.Exists() == req.Present, nil
	})
	if err != nil {
		return collection.Result{}, fmt.Errorf("%s: %w", fqcn, err)
	}

	// Map() renders a fresh map every call, so adding the path to it
	// cannot disturb anything the probe still holds.
	state := observed.Map()
	state[waitParamPath] = req.Path
	if err := waitRecord(rc, req, state, elapsed); err != nil {
		return collection.Result{}, fmt.Errorf("%s: %w", fqcn, err)
	}

	return collection.Result{Changed: false}, nil
}

// pathCondition describes what this task is waiting for, in the words
// the timeout and cancellation messages read best with.
//
// It exists so the sentence is written once for both states. "timed out
// after 30s waiting for /run/app.pid to exist" tells an operator what to
// go and look at; the alternative, one message with the state parameter
// printed inside it, makes them work out what present meant for a path.
func pathCondition(req waitRequest) string {
	if req.Present {
		return "for " + req.Path + " to exist"
	}
	return "for " + req.Path + " to stop existing"
}
