package wait

import (
	"context"
	"fmt"
	"regexp"

	"github.com/Subject-Void-LLC/the-pleiades/pkg/capability"
	"github.com/Subject-Void-LLC/the-pleiades/pkg/collection"
	"github.com/Subject-Void-LLC/the-pleiades/pkg/inventory"
	"github.com/Subject-Void-LLC/the-pleiades/pkg/remotefile"
	"github.com/Subject-Void-LLC/the-pleiades/pkg/sdk"
)

// This file implements "wait.search", generated by
// pleiades forge new-collection and then hand-completed.
//
// It is ansible.builtin.wait_for's search_regex half: the path has to
// exist AND its contents have to say something. The usual shape is a
// service that writes a line to its log when it has finished starting,
// which is the only readable signal a lot of daemons give.

// Stat names this method returns beyond the shared ones, which are
// wait_for's own names for the same two things.
const (
	searchStatMatchGroups    = "match_groups"
	searchStatMatchGroupdict = "match_groupdict"
)

// Keys this method records inside the diff, beyond the path.
//
// They are separate from the file namespace's stat keys on purpose: what
// this method observed is not a file's mode and owner, it is whether the
// file was readable and whether its contents matched.
const (
	searchKeyExists  = "exists"
	searchKeyMatched = "matched"
)

// searchMultiline is prepended to every pattern, because wait_for
// compiles search_regex with Python's re.MULTILINE.
//
// Without it "^Started" would only ever match at the very start of a
// file, and a log file's interesting line is never the first one. This
// is the difference between a converted playbook working and it waiting
// out its whole timeout against a file that plainly contains the text.
const searchMultiline = "(?m)"

func init() {
	collection.MustRegister(collection.Descriptor{
		Name: "wait.search",
		Manifest: collection.Manifest{
			SupportedTransports: []string{
				"ssh",
			},
			// POSIXFileSystemCapable rather than the NetworkAddressable
			// this method was scaffolded with, for the same reason
			// wait.path changed it: being addressable opens a connection,
			// and what this needs is a device whose filesystem will hand
			// back a file's contents.
			RequiredCapabilities: []capability.Name{
				capability.NamePOSIXFileSystem,
			},
			ExecutionContext: collection.ExecutionContext{
				RequiresElevation: false,
			},
			PlatformTargets: nil,
			EngineVersion:   ">=1.0.0",
			Status:          collection.StatusImplemented,
			// Reversible: false is the honest answer rather than an
			// unfinished one: reading a file changes nothing that a
			// rollback could put back, and this method emits no inverse at
			// run time either.
			Reversibility: collection.Reversibility{
				Reversible: false,
				Notes: "This method reads a file and changes nothing on the device, so there is nothing to undo. That is the same fact that " +
					"makes it report changed: false. It still records a diff whose two halves are identical, so a journal can tell an " +
					"observation from a task that was never recorded.",
			},
			// Only reads, and still not checkable: see NoCheckReason.
			NoCheckReason: "what a wait waits for is usually an earlier task's change, which a check never makes, so a check would wait out " +
				"its timeout and fail where the real run succeeds",
			Doc: searchDoc(),
		},
		Invoke: Search,
	})
}

// searchDoc is this method's reference documentation, kept out of the
// registration above so the manifest fields stay readable.
//
// It is duplicated into internal/forge/catalogdata, which is the source
// the scaffolder is driven from, and internal/archtest's
// TestCatalogDataDocsMatchTheRegistry compares the two for equality so
// the copies cannot drift.
func searchDoc() collection.Doc {
	return collection.Doc{
		Summary:     "Waits for a pattern to appear in a file's contents on the target.",
		Description: "Reads a file on the device on an interval until search_regex matches it, or until it stops matching when state is absent, and fails when the timeout runs out first. It changes nothing. The whole file is read on every look, so this suits a service's startup log rather than a file that grows without limit. The pattern is matched in multiline mode, as wait_for matches it, so ^ and $ mean the start and end of a line; it is a Go RE2 pattern, so a backreference or a lookahead is refused when the task is read rather than silently never matching. Only a regular file is read: a path that is missing, or that is a directory, counts as not matching, which satisfies state: absent at once and never satisfies state: present.",
		Params: []collection.Param{
			{Name: waitParamPath, Type: "string", Required: true, Description: "The file on the device to read."},
			{Name: waitParamSearchRegex, Type: "string", Required: true, Description: "The pattern to look for, matched in multiline mode against the whole file. Use wait.path when only the file's existence matters."},
			{Name: waitParamState, Type: "string", Default: "present", Choices: []string{"present", "absent", "started", "stopped"}, Description: "Whether to wait for the pattern to match (present) or to stop matching (absent). started and stopped are accepted as wait_for's own spellings of the same two. drained is refused, since it asks about a socket's send queue and means nothing for a file."},
			{Name: waitParamTimeout, Type: "int", Default: "300", Description: "How many seconds to wait in total before giving up, counted from the start of the task, so the delay comes out of it. Must be more than 0."},
			{Name: waitParamDelay, Type: "int", Default: "0", Description: "How many seconds to wait before reading the first time. Useful when the file still holds the previous run's matching line. Must be shorter than the timeout, which it is spent out of."},
			{Name: waitParamSleep, Type: "int", Default: "1", Description: "How many seconds to wait between reads. Must be more than 0: a sleep of zero would read the file as fast as the device can send it."},
			{Name: sdk.ParamInsecureSkipHostKeyVerify, Type: "bool", Default: "false", Description: "Skip SSH host key verification for this task. This removes protection against a machine in the middle answering for the device, so set it only for a target you have decided does not need it."},
		},
		Returns: []collection.ReturnField{
			{Name: waitParamPath, Type: "string", Returned: "always", Description: "The file this task read."},
			{Name: waitParamSearchRegex, Type: "string", Returned: "always", Description: "The pattern this task looked for, exactly as the task wrote it."},
			{Name: waitStatElapsed, Type: "int", Returned: "always", Description: "How many whole seconds the task waited, including the delay."},
			{Name: searchStatMatchGroups, Type: "list of string", Returned: "when the pattern matched", Description: "The capture groups of the match, in order, without the whole match itself."},
			{Name: searchStatMatchGroupdict, Type: "dict", Returned: "when the pattern matched", Description: "The named capture groups of the match, keyed by name. Empty when the pattern names none."},
			{Name: sdk.StatDiff, Type: "dict", Returned: "always", Description: "What the last read found: the path, whether it was a readable file, the pattern, and whether it matched. Both halves are identical, since a wait changes nothing."},
		},
		Examples: []collection.Example{
			{
				Name:        "Wait for a service to log that it started",
				RunbookYAML: "- name: Wait for the API to finish starting\n  wait.search:\n    path: /var/log/pleiades/api.log\n    search_regex: \"^Listening on \"\n    timeout: 120\n",
			},
			{
				Name:        "Capture the port a service chose",
				RunbookYAML: "- name: Read the port out of the log\n  wait.search:\n    path: /var/log/app.log\n    search_regex: \"listening on port (?P<port>[0-9]+)\"\n  register: startup\n",
			},
			{
				Name:        "Wait for an error line to be rotated away",
				RunbookYAML: "- name: Wait for the log to stop showing the failure\n  wait.search:\n    path: /var/log/app.log\n    search_regex: \"FATAL\"\n    state: absent\n    timeout: 60\n    sleep: 5\n",
			},
		},
		SeeAlso: []string{"wait.path", "pleiades.builtin.wait.port"},
	}
}

// Search implements the "wait.search" collection method: it reads a file
// on the device until its contents match a pattern, or stop matching it.
//
// # Why the whole file is read every time
//
// There is no remote primitive here for "the part I have not read yet".
// The transport is an SSH exec channel and pkg/remotefile.Read is a cat,
// so each look sends the whole file back. That is fine for the case this
// method exists for, a service's startup log, and it is the reason the
// documentation says so rather than leaving somebody to point it at a
// file that grows without limit and wonder where the bandwidth went.
//
// # A missing file is not an error
//
// It is an answer: a file that is not there contains no match. So a task
// waiting for a pattern keeps waiting, which is what someone watching a
// log that has not been created yet wants, and a task waiting for a
// pattern to disappear is satisfied at once, which is correct because a
// deleted log cannot still say the thing.
func Search(ctx context.Context, rc sdk.RunbookContext, device inventory.InventoryItem, params map[string]any) (collection.Result, error) {
	const fqcn = "wait.search"

	req, err := waitReadRequest(params)
	if err != nil {
		return collection.Result{}, fmt.Errorf("%s: %w", fqcn, err)
	}

	pattern, err := waitTextParam(params, waitParamSearchRegex)
	if err != nil {
		return collection.Result{}, fmt.Errorf("%s: %w", fqcn, err)
	}
	if pattern == "" {
		return collection.Result{}, fmt.Errorf("%s: %s is required: use wait.path when only the file's existence matters", fqcn, waitParamSearchRegex)
	}
	// Compiled before connecting, so a pattern RE2 cannot express is
	// reported as the runbook mistake it is. Left to run time it would
	// look like a wait that never matched and then timed out, which sends
	// the reader to the device instead of to the pattern.
	search, err := regexp.Compile(searchMultiline + pattern)
	if err != nil {
		return collection.Result{}, fmt.Errorf("%s: %s %q cannot be compiled: %w: this is a Go RE2 pattern, which has no backreferences and no lookahead",
			fqcn, waitParamSearchRegex, pattern, err)
	}

	conn, err := sdk.Connect(ctx, rc, device, params, fqcn)
	if err != nil {
		return collection.Result{}, err
	}
	defer func() { _ = conn.Close() }()

	// What the last read found, kept out here because it is what gets
	// recorded once the wait ends.
	var (
		readable bool
		match    []string
	)

	elapsed, err := waitPoll(ctx, req, searchCondition(req, pattern), func(ctx context.Context) (bool, error) {
		content, exists, err := remotefile.Read(ctx, conn, req.Path)
		if err != nil {
			return false, err
		}
		readable = exists
		// Reset every time, so a file that matched on one look and was
		// then truncated does not leave the earlier match behind to be
		// reported as if it were still there.
		match = nil
		if exists {
			match = search.FindStringSubmatch(content)
		}
		return (match != nil) == req.Present, nil
	})
	if err != nil {
		return collection.Result{}, fmt.Errorf("%s: %w", fqcn, err)
	}

	state := map[string]any{
		waitParamPath:        req.Path,
		searchKeyExists:      readable,
		waitParamSearchRegex: pattern,
		searchKeyMatched:     match != nil,
	}
	if err := waitRecord(rc, req, state, elapsed); err != nil {
		return collection.Result{}, fmt.Errorf("%s: %w", fqcn, err)
	}
	if err := searchRecord(rc, pattern, search, match); err != nil {
		return collection.Result{}, fmt.Errorf("%s: %w", fqcn, err)
	}

	return collection.Result{Changed: false}, nil
}

// searchRecord writes the stats this method returns beyond the shared
// ones: the pattern, and the capture groups of the match.
//
// The groups are recorded only when there was a match, which is
// wait_for's own behavior and the honest one: a task waiting for a
// pattern to disappear ended with nothing matching, and reporting empty
// groups there would look like a match that captured nothing.
func searchRecord(rc sdk.RunbookContext, pattern string, search *regexp.Regexp, match []string) error {
	if err := rc.SetStat(waitParamSearchRegex, pattern); err != nil {
		return err
	}
	if match == nil {
		return nil
	}

	groups, named := searchGroups(search, match)
	if err := rc.SetStat(searchStatMatchGroups, groups); err != nil {
		return err
	}
	return rc.SetStat(searchStatMatchGroupdict, named)
}

// searchGroups splits a match into wait_for's two return shapes: every
// capture group in order, and the named ones keyed by name.
//
// The whole match is deliberately left out of both. FindStringSubmatch
// puts it at index 0 while Python's MatchObject.groups() starts at the
// first real group, and a converted playbook reading match_groups[0]
// expects the first captured value rather than the entire line.
func searchGroups(search *regexp.Regexp, match []string) ([]string, map[string]string) {
	names := search.SubexpNames()
	groups := make([]string, 0, len(names))
	named := make(map[string]string, len(names))

	for i, name := range names {
		if i == 0 {
			continue
		}
		groups = append(groups, match[i])
		// An unnamed group has an empty name here, and adding it under ""
		// would put a value in the dictionary that no playbook could ask
		// for by name.
		if name != "" {
			named[name] = match[i]
		}
	}
	return groups, named
}

// searchCondition describes what this task is waiting for, in the words
// the timeout and cancellation messages read best with.
//
// It names the pattern as well as the file, because the two mistakes
// behind a timeout here are a file nobody is writing and a pattern that
// does not say what its author thought, and an operator cannot tell them
// apart from a message that mentions only one.
func searchCondition(req waitRequest, pattern string) string {
	if req.Present {
		return fmt.Sprintf("for %q to match %s", pattern, req.Path)
	}
	return fmt.Sprintf("for %q to stop matching %s", pattern, req.Path)
}
