// Command sweep removes stale build output from this working tree.
//
// A full `make ci` run leaves real weight behind. Every composition root
// under cmd/ links a static binary, and tools/gendocs links another, so a
// developer who has built everything is carrying roughly 300 MB of
// executables at the repository root that no test reads and no commit
// tracks. They are regenerated by `make build` in under a minute. On a WSL
// installation the cost is worse than the number suggests, because the
// virtual disk Windows backs the filesystem with grows to fit the high
// water mark and never shrinks on its own, so a file deleted today still
// occupies the same space on the Windows volume tomorrow.
//
// The safety rule this tool follows is that git decides, not a name list.
// Nothing is removed unless `git check-ignore` confirms the path is
// ignored, which makes it impossible for a typo in a pattern here to
// delete a tracked source file. Two further limits keep it narrow:
//
//   - Only regular files are ever considered. Directories are skipped
//     outright, which is what keeps the gitignored internal document trees
//     (.AGENTS/, .DESIGN/, .IGNORE/, .SPECIFICATION/) safe. Those are
//     ignored by .gitignore's `.[A-Z]*` pattern exactly like a stale
//     binary is, and they are irreplaceable, so the distinction cannot
//     rest on anyone remembering to exclude them.
//   - Only files older than -max-age are removed. A binary built in the
//     last few days is probably the one being used right now.
//
// The Go build cache is deliberately left alone by default. It is shared
// by every Go module on the machine rather than owned by this repository,
// and cmd/go already trims entries it has not used in five days. Measured
// on this checkout the cache held 18 GB with nothing in it older than two
// weeks, so an age-based sweep would have freed nothing. The -cache-budget
// flag exists for the case where the cache is genuinely too large to keep,
// and it says plainly that the price is a slow first rebuild.
package main

import (
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

// sweepableSuffixes lists the file endings that mark a path as build
// output rather than something a person wrote. An extensionless file is
// handled separately by the executable-bit check in classify, because that
// is the shape every Go binary at the repository root takes.
var sweepableSuffixes = []string{".test", ".out", ".log", ".exe", ".prof", ".cover"}

// protectedNames lists ignored files that are inputs rather than output,
// so they are never swept no matter how old they get. The credential files
// are the important entries: they are ignored because they hold secrets,
// not because they are disposable, and regenerating one is not possible.
var protectedNames = []string{".env", "credentials.json", "master.key"}

// candidate is one file the sweep has decided it may remove, carried with
// the two facts the report needs.
type candidate struct {
	path string // absolute path on disk
	size int64  // bytes the file occupies
	age  time.Duration
}

func main() {
	maxAge := flag.Duration("max-age", 7*24*time.Hour, "leave build output newer than this alone, since it is probably in use")
	dryRun := flag.Bool("dry-run", false, "report what would be removed and remove nothing")
	cacheBudget := flag.Int64("cache-budget", 0, "if non-zero, clear the whole shared Go build cache when it exceeds this many GB (costs a slow rebuild)")
	installTimerFlag := flag.Bool("install-timer", false, "install a systemd user timer that runs this sweep weekly")
	removeTimerFlag := flag.Bool("remove-timer", false, "stop and remove the weekly systemd user timer")
	flag.Parse()

	root, err := repoRoot()
	if err != nil {
		fmt.Fprintf(os.Stderr, "sweep: %v\n", err)
		os.Exit(1)
	}

	// The timer flags manage the schedule rather than performing a sweep,
	// so each returns instead of falling through to the sweep itself.
	if *removeTimerFlag {
		if err := removeTimer(); err != nil {
			fmt.Fprintf(os.Stderr, "sweep: %v\n", err)
			os.Exit(1)
		}
		return
	}
	if *installTimerFlag {
		if err := installTimer(root, maxAge.String()); err != nil {
			fmt.Fprintf(os.Stderr, "sweep: %v\n", err)
			os.Exit(1)
		}
		return
	}

	found, err := collect(root, *maxAge)
	if err != nil {
		fmt.Fprintf(os.Stderr, "sweep: %v\n", err)
		os.Exit(1)
	}

	var freed int64
	for _, c := range found {
		rel, _ := filepath.Rel(root, c.path)
		if *dryRun {
			fmt.Printf("  would remove %-24s %7s  (%d days old)\n", rel, humanBytes(c.size), int(c.age.Hours()/24))
			freed += c.size
			continue
		}
		if err := os.Remove(c.path); err != nil {
			fmt.Fprintf(os.Stderr, "  failed to remove %s: %v\n", rel, err)
			continue
		}
		fmt.Printf("  removed %-24s %7s  (%d days old)\n", rel, humanBytes(c.size), int(c.age.Hours()/24))
		freed += c.size
	}

	verb := "freed"
	if *dryRun {
		verb = "would free"
	}
	if len(found) == 0 {
		fmt.Printf("sweep: nothing to remove (no ignored build output older than %s)\n", *maxAge)
	} else {
		fmt.Printf("sweep: %s %s across %d file(s)\n", verb, humanBytes(freed), len(found))
	}

	if *cacheBudget > 0 {
		if err := sweepCache(*cacheBudget, *dryRun); err != nil {
			fmt.Fprintf(os.Stderr, "sweep: %v\n", err)
			os.Exit(1)
		}
	}
}

// repoRoot returns the absolute path of the repository this tool was run
// from. It asks git rather than walking up looking for a .git directory so
// that running the tool from a worktree resolves to that worktree.
func repoRoot() (string, error) {
	out, err := exec.Command("git", "rev-parse", "--show-toplevel").Output()
	if err != nil {
		return "", fmt.Errorf("not inside a git repository: %w", err)
	}
	return strings.TrimSpace(string(out)), nil
}

// collect walks the repository root and returns every file the sweep is
// allowed to remove, sorted largest first so the report leads with the
// entries that matter. It deliberately does not recurse: build output that
// matters lives at the root, and a recursive sweep would have to reason
// about testdata directories full of deliberately odd files.
func collect(root string, maxAge time.Duration) ([]candidate, error) {
	entries, err := os.ReadDir(root)
	if err != nil {
		return nil, fmt.Errorf("reading %s: %w", root, err)
	}

	var found []candidate
	for _, e := range entries {
		c, ok := classify(root, e, maxAge)
		if ok {
			found = append(found, c)
		}
	}
	sort.Slice(found, func(i, j int) bool { return found[i].size > found[j].size })
	return found, nil
}

// classify decides whether one directory entry is sweepable build output.
// It returns false for anything it is not certain about, which is why each
// check is a reason to reject rather than a reason to accept.
func classify(root string, e os.DirEntry, maxAge time.Duration) (candidate, bool) {
	// A directory is never swept. This is what protects .AGENTS/,
	// .DESIGN/, .IGNORE/ and .SPECIFICATION/, which are ignored by the
	// same .gitignore pattern a stale binary is but hold the only copy of
	// the project's internal documents.
	if e.IsDir() {
		return candidate{}, false
	}

	name := e.Name()
	for _, p := range protectedNames {
		if name == p {
			return candidate{}, false
		}
	}

	info, err := e.Info()
	if err != nil {
		return candidate{}, false
	}

	// The entry has to look like build output: either a known artifact
	// suffix, or an extensionless file carrying the executable bit, which
	// is the shape of every Go binary `go build` drops at the root.
	looksBuilt := false
	for _, s := range sweepableSuffixes {
		if strings.HasSuffix(name, s) {
			looksBuilt = true
			break
		}
	}
	if !looksBuilt && filepath.Ext(name) == "" && info.Mode().Perm()&0o111 != 0 {
		looksBuilt = true
	}
	if !looksBuilt {
		return candidate{}, false
	}

	age := time.Since(info.ModTime())
	if age < maxAge {
		return candidate{}, false
	}

	// The last word belongs to git. If the file is tracked, or is not
	// ignored, it is somebody's work and the sweep does not touch it.
	full := filepath.Join(root, name)
	if !gitIgnored(root, full) {
		return candidate{}, false
	}

	return candidate{path: full, size: info.Size(), age: age}, true
}

// gitIgnored reports whether git considers path ignored. A non-zero exit
// from check-ignore means "not ignored", which is the safe answer, so any
// error at all is reported as not ignored.
//
// The "--" separator is defensive rather than load-bearing. Every caller
// today passes an absolute path, which git cannot mistake for an option.
// It is written anyway because this one answer is the entire safety rule
// of the sweep, and a later caller passing a bare name should not be able
// to turn a file called "-q" into a second flag.
func gitIgnored(root, path string) bool {
	cmd := exec.Command("git", "check-ignore", "-q", "--", path)
	cmd.Dir = root
	return cmd.Run() == nil
}

// sweepCache clears the shared Go build cache when it exceeds budgetGB.
// This is opt-in because the cache is not this repository's property: it
// is keyed by content and shared with every other Go module on the
// machine, and cmd/go already evicts entries it has not used in five days.
func sweepCache(budgetGB int64, dryRun bool) error {
	out, err := exec.Command("go", "env", "GOCACHE").Output()
	if err != nil {
		return fmt.Errorf("asking go for GOCACHE: %w", err)
	}
	dir := strings.TrimSpace(string(out))

	var total int64
	err = filepath.Walk(dir, func(_ string, info os.FileInfo, err error) error {
		if err != nil {
			return nil // an unreadable entry is not worth failing the sweep over
		}
		if !info.IsDir() {
			total += info.Size()
		}
		return nil
	})
	if err != nil {
		return fmt.Errorf("measuring %s: %w", dir, err)
	}

	budget := budgetGB * 1024 * 1024 * 1024
	if total <= budget {
		fmt.Printf("sweep: go build cache is %s, under the %d GB budget, leaving it alone\n", humanBytes(total), budgetGB)
		return nil
	}
	if dryRun {
		fmt.Printf("sweep: go build cache is %s, over the %d GB budget, would clear it (next build will be slow)\n", humanBytes(total), budgetGB)
		return nil
	}
	if err := exec.Command("go", "clean", "-cache").Run(); err != nil {
		return fmt.Errorf("clearing the go build cache: %w", err)
	}
	fmt.Printf("sweep: go build cache was %s, over the %d GB budget, cleared it (next build will be slow)\n", humanBytes(total), budgetGB)
	return nil
}

// humanBytes renders a byte count the way a person reads one.
func humanBytes(n int64) string {
	const unit = 1024
	if n < unit {
		return fmt.Sprintf("%d B", n)
	}
	div, exp := int64(unit), 0
	for m := n / unit; m >= unit; m /= unit {
		div *= unit
		exp++
	}
	return fmt.Sprintf("%.1f %cB", float64(n)/float64(div), "KMGT"[exp])
}
