// Code generated by ent, DO NOT EDIT.

package schedule

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Subject-Void-LLC/the-pleiades/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Schedule {
	return predicate.Schedule(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Schedule {
	return predicate.Schedule(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Schedule {
	return predicate.Schedule(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Schedule {
	return predicate.Schedule(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Schedule {
	return predicate.Schedule(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Schedule {
	return predicate.Schedule(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Schedule {
	return predicate.Schedule(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Schedule {
	return predicate.Schedule(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Schedule {
	return predicate.Schedule(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldEQ(FieldUpdatedAt, v))
}

// ScheduleID applies equality check predicate on the "schedule_id" field. It's identical to ScheduleIDEQ.
func ScheduleID(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldEQ(FieldScheduleID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldEQ(FieldDescription, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.Schedule {
	return predicate.Schedule(sql.FieldEQ(FieldEnabled, v))
}

// Rrule applies equality check predicate on the "rrule" field. It's identical to RruleEQ.
func Rrule(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldEQ(FieldRrule, v))
}

// Timezone applies equality check predicate on the "timezone" field. It's identical to TimezoneEQ.
func Timezone(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldEQ(FieldTimezone, v))
}

// Dtstart applies equality check predicate on the "dtstart" field. It's identical to DtstartEQ.
func Dtstart(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldEQ(FieldDtstart, v))
}

// Dtend applies equality check predicate on the "dtend" field. It's identical to DtendEQ.
func Dtend(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldEQ(FieldDtend, v))
}

// NextRun applies equality check predicate on the "next_run" field. It's identical to NextRunEQ.
func NextRun(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldEQ(FieldNextRun, v))
}

// LastFired applies equality check predicate on the "last_fired" field. It's identical to LastFiredEQ.
func LastFired(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldEQ(FieldLastFired, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldLTE(FieldUpdatedAt, v))
}

// ScheduleIDEQ applies the EQ predicate on the "schedule_id" field.
func ScheduleIDEQ(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldEQ(FieldScheduleID, v))
}

// ScheduleIDNEQ applies the NEQ predicate on the "schedule_id" field.
func ScheduleIDNEQ(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldNEQ(FieldScheduleID, v))
}

// ScheduleIDIn applies the In predicate on the "schedule_id" field.
func ScheduleIDIn(vs ...string) predicate.Schedule {
	return predicate.Schedule(sql.FieldIn(FieldScheduleID, vs...))
}

// ScheduleIDNotIn applies the NotIn predicate on the "schedule_id" field.
func ScheduleIDNotIn(vs ...string) predicate.Schedule {
	return predicate.Schedule(sql.FieldNotIn(FieldScheduleID, vs...))
}

// ScheduleIDGT applies the GT predicate on the "schedule_id" field.
func ScheduleIDGT(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldGT(FieldScheduleID, v))
}

// ScheduleIDGTE applies the GTE predicate on the "schedule_id" field.
func ScheduleIDGTE(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldGTE(FieldScheduleID, v))
}

// ScheduleIDLT applies the LT predicate on the "schedule_id" field.
func ScheduleIDLT(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldLT(FieldScheduleID, v))
}

// ScheduleIDLTE applies the LTE predicate on the "schedule_id" field.
func ScheduleIDLTE(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldLTE(FieldScheduleID, v))
}

// ScheduleIDContains applies the Contains predicate on the "schedule_id" field.
func ScheduleIDContains(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldContains(FieldScheduleID, v))
}

// ScheduleIDHasPrefix applies the HasPrefix predicate on the "schedule_id" field.
func ScheduleIDHasPrefix(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldHasPrefix(FieldScheduleID, v))
}

// ScheduleIDHasSuffix applies the HasSuffix predicate on the "schedule_id" field.
func ScheduleIDHasSuffix(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldHasSuffix(FieldScheduleID, v))
}

// ScheduleIDEqualFold applies the EqualFold predicate on the "schedule_id" field.
func ScheduleIDEqualFold(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldEqualFold(FieldScheduleID, v))
}

// ScheduleIDContainsFold applies the ContainsFold predicate on the "schedule_id" field.
func ScheduleIDContainsFold(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldContainsFold(FieldScheduleID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Schedule {
	return predicate.Schedule(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Schedule {
	return predicate.Schedule(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Schedule {
	return predicate.Schedule(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Schedule {
	return predicate.Schedule(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.Schedule {
	return predicate.Schedule(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.Schedule {
	return predicate.Schedule(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldContainsFold(FieldDescription, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.Schedule {
	return predicate.Schedule(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.Schedule {
	return predicate.Schedule(sql.FieldNEQ(FieldEnabled, v))
}

// RruleEQ applies the EQ predicate on the "rrule" field.
func RruleEQ(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldEQ(FieldRrule, v))
}

// RruleNEQ applies the NEQ predicate on the "rrule" field.
func RruleNEQ(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldNEQ(FieldRrule, v))
}

// RruleIn applies the In predicate on the "rrule" field.
func RruleIn(vs ...string) predicate.Schedule {
	return predicate.Schedule(sql.FieldIn(FieldRrule, vs...))
}

// RruleNotIn applies the NotIn predicate on the "rrule" field.
func RruleNotIn(vs ...string) predicate.Schedule {
	return predicate.Schedule(sql.FieldNotIn(FieldRrule, vs...))
}

// RruleGT applies the GT predicate on the "rrule" field.
func RruleGT(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldGT(FieldRrule, v))
}

// RruleGTE applies the GTE predicate on the "rrule" field.
func RruleGTE(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldGTE(FieldRrule, v))
}

// RruleLT applies the LT predicate on the "rrule" field.
func RruleLT(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldLT(FieldRrule, v))
}

// RruleLTE applies the LTE predicate on the "rrule" field.
func RruleLTE(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldLTE(FieldRrule, v))
}

// RruleContains applies the Contains predicate on the "rrule" field.
func RruleContains(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldContains(FieldRrule, v))
}

// RruleHasPrefix applies the HasPrefix predicate on the "rrule" field.
func RruleHasPrefix(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldHasPrefix(FieldRrule, v))
}

// RruleHasSuffix applies the HasSuffix predicate on the "rrule" field.
func RruleHasSuffix(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldHasSuffix(FieldRrule, v))
}

// RruleEqualFold applies the EqualFold predicate on the "rrule" field.
func RruleEqualFold(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldEqualFold(FieldRrule, v))
}

// RruleContainsFold applies the ContainsFold predicate on the "rrule" field.
func RruleContainsFold(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldContainsFold(FieldRrule, v))
}

// ExclusionsIsNil applies the IsNil predicate on the "exclusions" field.
func ExclusionsIsNil() predicate.Schedule {
	return predicate.Schedule(sql.FieldIsNull(FieldExclusions))
}

// ExclusionsNotNil applies the NotNil predicate on the "exclusions" field.
func ExclusionsNotNil() predicate.Schedule {
	return predicate.Schedule(sql.FieldNotNull(FieldExclusions))
}

// TimezoneEQ applies the EQ predicate on the "timezone" field.
func TimezoneEQ(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldEQ(FieldTimezone, v))
}

// TimezoneNEQ applies the NEQ predicate on the "timezone" field.
func TimezoneNEQ(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldNEQ(FieldTimezone, v))
}

// TimezoneIn applies the In predicate on the "timezone" field.
func TimezoneIn(vs ...string) predicate.Schedule {
	return predicate.Schedule(sql.FieldIn(FieldTimezone, vs...))
}

// TimezoneNotIn applies the NotIn predicate on the "timezone" field.
func TimezoneNotIn(vs ...string) predicate.Schedule {
	return predicate.Schedule(sql.FieldNotIn(FieldTimezone, vs...))
}

// TimezoneGT applies the GT predicate on the "timezone" field.
func TimezoneGT(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldGT(FieldTimezone, v))
}

// TimezoneGTE applies the GTE predicate on the "timezone" field.
func TimezoneGTE(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldGTE(FieldTimezone, v))
}

// TimezoneLT applies the LT predicate on the "timezone" field.
func TimezoneLT(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldLT(FieldTimezone, v))
}

// TimezoneLTE applies the LTE predicate on the "timezone" field.
func TimezoneLTE(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldLTE(FieldTimezone, v))
}

// TimezoneContains applies the Contains predicate on the "timezone" field.
func TimezoneContains(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldContains(FieldTimezone, v))
}

// TimezoneHasPrefix applies the HasPrefix predicate on the "timezone" field.
func TimezoneHasPrefix(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldHasPrefix(FieldTimezone, v))
}

// TimezoneHasSuffix applies the HasSuffix predicate on the "timezone" field.
func TimezoneHasSuffix(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldHasSuffix(FieldTimezone, v))
}

// TimezoneEqualFold applies the EqualFold predicate on the "timezone" field.
func TimezoneEqualFold(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldEqualFold(FieldTimezone, v))
}

// TimezoneContainsFold applies the ContainsFold predicate on the "timezone" field.
func TimezoneContainsFold(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldContainsFold(FieldTimezone, v))
}

// DtstartEQ applies the EQ predicate on the "dtstart" field.
func DtstartEQ(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldEQ(FieldDtstart, v))
}

// DtstartNEQ applies the NEQ predicate on the "dtstart" field.
func DtstartNEQ(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldNEQ(FieldDtstart, v))
}

// DtstartIn applies the In predicate on the "dtstart" field.
func DtstartIn(vs ...time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldIn(FieldDtstart, vs...))
}

// DtstartNotIn applies the NotIn predicate on the "dtstart" field.
func DtstartNotIn(vs ...time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldNotIn(FieldDtstart, vs...))
}

// DtstartGT applies the GT predicate on the "dtstart" field.
func DtstartGT(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldGT(FieldDtstart, v))
}

// DtstartGTE applies the GTE predicate on the "dtstart" field.
func DtstartGTE(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldGTE(FieldDtstart, v))
}

// DtstartLT applies the LT predicate on the "dtstart" field.
func DtstartLT(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldLT(FieldDtstart, v))
}

// DtstartLTE applies the LTE predicate on the "dtstart" field.
func DtstartLTE(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldLTE(FieldDtstart, v))
}

// DtendEQ applies the EQ predicate on the "dtend" field.
func DtendEQ(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldEQ(FieldDtend, v))
}

// DtendNEQ applies the NEQ predicate on the "dtend" field.
func DtendNEQ(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldNEQ(FieldDtend, v))
}

// DtendIn applies the In predicate on the "dtend" field.
func DtendIn(vs ...time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldIn(FieldDtend, vs...))
}

// DtendNotIn applies the NotIn predicate on the "dtend" field.
func DtendNotIn(vs ...time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldNotIn(FieldDtend, vs...))
}

// DtendGT applies the GT predicate on the "dtend" field.
func DtendGT(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldGT(FieldDtend, v))
}

// DtendGTE applies the GTE predicate on the "dtend" field.
func DtendGTE(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldGTE(FieldDtend, v))
}

// DtendLT applies the LT predicate on the "dtend" field.
func DtendLT(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldLT(FieldDtend, v))
}

// DtendLTE applies the LTE predicate on the "dtend" field.
func DtendLTE(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldLTE(FieldDtend, v))
}

// DtendIsNil applies the IsNil predicate on the "dtend" field.
func DtendIsNil() predicate.Schedule {
	return predicate.Schedule(sql.FieldIsNull(FieldDtend))
}

// DtendNotNil applies the NotNil predicate on the "dtend" field.
func DtendNotNil() predicate.Schedule {
	return predicate.Schedule(sql.FieldNotNull(FieldDtend))
}

// NextRunEQ applies the EQ predicate on the "next_run" field.
func NextRunEQ(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldEQ(FieldNextRun, v))
}

// NextRunNEQ applies the NEQ predicate on the "next_run" field.
func NextRunNEQ(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldNEQ(FieldNextRun, v))
}

// NextRunIn applies the In predicate on the "next_run" field.
func NextRunIn(vs ...time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldIn(FieldNextRun, vs...))
}

// NextRunNotIn applies the NotIn predicate on the "next_run" field.
func NextRunNotIn(vs ...time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldNotIn(FieldNextRun, vs...))
}

// NextRunGT applies the GT predicate on the "next_run" field.
func NextRunGT(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldGT(FieldNextRun, v))
}

// NextRunGTE applies the GTE predicate on the "next_run" field.
func NextRunGTE(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldGTE(FieldNextRun, v))
}

// NextRunLT applies the LT predicate on the "next_run" field.
func NextRunLT(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldLT(FieldNextRun, v))
}

// NextRunLTE applies the LTE predicate on the "next_run" field.
func NextRunLTE(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldLTE(FieldNextRun, v))
}

// NextRunIsNil applies the IsNil predicate on the "next_run" field.
func NextRunIsNil() predicate.Schedule {
	return predicate.Schedule(sql.FieldIsNull(FieldNextRun))
}

// NextRunNotNil applies the NotNil predicate on the "next_run" field.
func NextRunNotNil() predicate.Schedule {
	return predicate.Schedule(sql.FieldNotNull(FieldNextRun))
}

// LastFiredEQ applies the EQ predicate on the "last_fired" field.
func LastFiredEQ(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldEQ(FieldLastFired, v))
}

// LastFiredNEQ applies the NEQ predicate on the "last_fired" field.
func LastFiredNEQ(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldNEQ(FieldLastFired, v))
}

// LastFiredIn applies the In predicate on the "last_fired" field.
func LastFiredIn(vs ...time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldIn(FieldLastFired, vs...))
}

// LastFiredNotIn applies the NotIn predicate on the "last_fired" field.
func LastFiredNotIn(vs ...time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldNotIn(FieldLastFired, vs...))
}

// LastFiredGT applies the GT predicate on the "last_fired" field.
func LastFiredGT(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldGT(FieldLastFired, v))
}

// LastFiredGTE applies the GTE predicate on the "last_fired" field.
func LastFiredGTE(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldGTE(FieldLastFired, v))
}

// LastFiredLT applies the LT predicate on the "last_fired" field.
func LastFiredLT(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldLT(FieldLastFired, v))
}

// LastFiredLTE applies the LTE predicate on the "last_fired" field.
func LastFiredLTE(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldLTE(FieldLastFired, v))
}

// LastFiredIsNil applies the IsNil predicate on the "last_fired" field.
func LastFiredIsNil() predicate.Schedule {
	return predicate.Schedule(sql.FieldIsNull(FieldLastFired))
}

// LastFiredNotNil applies the NotNil predicate on the "last_fired" field.
func LastFiredNotNil() predicate.Schedule {
	return predicate.Schedule(sql.FieldNotNull(FieldLastFired))
}

// HasOrganization applies the HasEdge predicate on the "organization" edge.
func HasOrganization() predicate.Schedule {
	return predicate.Schedule(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OrganizationTable, OrganizationColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOrganizationWith applies the HasEdge predicate on the "organization" edge with a given conditions (other predicates).
func HasOrganizationWith(preds ...predicate.Organization) predicate.Schedule {
	return predicate.Schedule(func(s *sql.Selector) {
		step := newOrganizationStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTemplate applies the HasEdge predicate on the "template" edge.
func HasTemplate() predicate.Schedule {
	return predicate.Schedule(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TemplateTable, TemplateColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTemplateWith applies the HasEdge predicate on the "template" edge with a given conditions (other predicates).
func HasTemplateWith(preds ...predicate.Template) predicate.Schedule {
	return predicate.Schedule(func(s *sql.Selector) {
		step := newTemplateStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSavedConfig applies the HasEdge predicate on the "saved_config" edge.
func HasSavedConfig() predicate.Schedule {
	return predicate.Schedule(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, SavedConfigTable, SavedConfigColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSavedConfigWith applies the HasEdge predicate on the "saved_config" edge with a given conditions (other predicates).
func HasSavedConfigWith(preds ...predicate.SavedLaunchConfig) predicate.Schedule {
	return predicate.Schedule(func(s *sql.Selector) {
		step := newSavedConfigStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasOccurrences applies the HasEdge predicate on the "occurrences" edge.
func HasOccurrences() predicate.Schedule {
	return predicate.Schedule(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, OccurrencesTable, OccurrencesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOccurrencesWith applies the HasEdge predicate on the "occurrences" edge with a given conditions (other predicates).
func HasOccurrencesWith(preds ...predicate.ScheduleOccurrence) predicate.Schedule {
	return predicate.Schedule(func(s *sql.Selector) {
		step := newOccurrencesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Schedule) predicate.Schedule {
	return predicate.Schedule(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Schedule) predicate.Schedule {
	return predicate.Schedule(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Schedule) predicate.Schedule {
	return predicate.Schedule(sql.NotPredicates(p))
}
